### ISSUE TITLE
Bug: typo in mimir-distributed chart of graphite querier config

### ISSUE THREAD

**Issue by Cimbel** [grafana/mimir#10275]
### What is the bug?

Typo in values of mimir-distributed helm chart.
`graphite.querier.storageSchemas.schemasConfiguration`
The following line must be `retentions = 10s:8d,10m:1y` insted of `retentions = 10s:8d,10min:1y` in configuration of Graphite.

### How to reproduce it?

1. Add graphite datasource
2. Send couple of metrics
3. Wait 9 days and try to query data

### What did you think would happen?

Graphite Querier won't be able to return data older than 7-8 days

### What was your environment?

Infrastructure: Kubernetes
Tool: helm

### Any additional context to share?

Here is link to line that requires fix - https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml#L4168

**Comment by ywwg** [comment]
for the record, the querier config was not invalid as far as mimir's parsing is concerned, but the carbon relay that sends graphite data doesn't support more than one character for unit names
