### ISSUE TITLE
Docs: Decide what to replace `basic` with in the configuration parameter categories

### ISSUE THREAD

**Issue by jdbaldry** [grafana/mimir#1034]
Breaking https://github.com/grafana/mimir/pull/938#discussion_r794864661 out into its own top-level discussion:

Basic, advanced, and experimental overload two orthogonal dimensions into one:
1. "How advanced does the user need to be to use/configure this"
2. "How stable is the feature"

If we're talking user progression, basic, advanced, and expert are the common terms. Though I agree that basic can have negative connotations, in the context of "this is a basic setup" it makes more sense than "this is a core setup".

On stability, stable and experimental are the common terms.

One could argue that two categorizations are too complex for what we need, which would lead us to basic, advanced, expert, and experimental.

All that being said, while I believe that basic is more correct than core, I do not feel very strongly.

What I do feel strongly about is that whatever system we end up using here need to match what Grafana, Loki, and Tempo are using or will be using.

_Originally posted by @RichiH in https://github.com/grafana/mimir/issues/938#issuecomment-1025571891_

**Comment by osg-grafana** [comment]
Going on memory here that this issue has been resolved. Please reopen if there is still anything in question.
