### ISSUE TITLE
Write frontmatter’s `description:` per page

### ISSUE THREAD

**Issue by jdbaldry** [grafana/mimir#1306]
In markdown documents there is frontmatter that includes a "description" member.

For example:
```yaml
---
title: "Title"
description: ""
weight: 10
---
```

This "description" becomes the snippet used in the search engine results page.

- Is it better to have a bad description or no description at all?
- Does the empty string result in no description?
- What does a search engine do if there is no description?
- What happens if a description is too long?
- What happens if a description is too short?

**Comment by osg-grafana** [comment]
@GrafanaWriter, given what we have learned since this issue was opened, what is the current advise?

**Comment by osg-grafana** [comment]
> @GrafanaWriter, given what we have learned since this issue was opened, what is the current advise?

> @GrafanaWriter, given what we have learned since this issue was opened, what is the current advise?

@AnneB-SEO2, what is your advice for this issue?

**Comment by GrafanaWriter** [comment]
We should incorporate frontmatter, as our guidelines suggest. Closing as this appears to be present in Mimir docs.
