### ISSUE TITLE
Document Mimir jsonnet

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1369]
We should add "Deploy Grafana Mimir with jsonnet" documentation, covering:

- [ ] What's currently covered by `operations/mimir/README.md`
- [ ] Document how to enable and migrate ingesters to multi-zone
- [ ] Document how to enable and migrate store-gateways to multi-zone

**Comment by GrafanaWriter** [comment]
Fixed with https://github.com/grafana/mimir/pull/2127
