### ISSUE TITLE
Add limits on query and rule length

### ISSUE THREAD

**Issue by bboreham** [grafana/mimir#1383]
#### Is your feature request related to a problem? Please describe.

Very large queries can cause crashes, e.g. the recent Go regexp issue with a 2MB regexp.

#### Describe the solution you'd like

Limits so that queries over some length, e.g. 4KB, would be rejected.
Queries can come in to the query-frontend, or be specified in alert and recording rules.
Perhaps the limit could be overridable per-tenant for special people.

#### Describe alternatives you've considered

The alternative is to be vulnerable to DOS attacks, mostly unknown at this time.

**Comment by dimitarvdimitrov** [comment]
this looks related to #4602

**Comment by pracucci** [comment]
Closed by https://github.com/grafana/mimir/pull/4606
