### ISSUE TITLE
Docs: Vet use of "can" and "you" in the configuration section

### ISSUE THREAD

**Issue by KMiller-Grafana** [grafana/mimir#1390]
Outstanding issues in the configuration sections of the docs

![Screen Shot 2022-03-04 at 10 03 29 AM](https://user-images.githubusercontent.com/84039272/156817546-f7f60bf6-8bb6-4002-bc59-b4906da10e89.png)

**Comment by osg-grafana** [comment]
See https://grafana.com/docs/mimir/latest/operators-guide/configuring/about-runtime-configuration/#runtime-configuration-of-per-tenant-limits.
