### ISSUE TITLE
Docs: Component types have hash rings

### ISSUE THREAD

**Issue by KMiller-Grafana** [grafana/mimir#1429]
In architecture/hash-ring/_index.md, the discussion on hash rings is misleading.  Throughout the page, prose refers to **the** hash ring.  That implies that there is one hash ring.  There are many hash rings.  Each component type (that uses a hash ring for info) has its own independent ring. 

Revise the page to not imply a single hash ring.

For example, instead of  the"How the hash ring works in Grafana Mimir" , it should be "How hash rings work in Grafana Mimir". And, instead of the start of the section that reads "The hash ring in Grafana Mimir is used to share work across . . ." it should  be "Hash rings in Grafana Mimir share work across. . ."

**Comment by osg-grafana** [comment]
Fixed by #4042
