### ISSUE TITLE
Add aliases to each topic

### ISSUE THREAD

**Issue by chri2547** [grafana/mimir#1450]
This work can happen post-launch

**Comment by GrafanaWriter** [comment]
Aliases need only be added if the content is moved. Suggest we retitle this to "Add description and keywords", which are the two forms of metadata that help users find what they need from both social (Twitter) and search engines.

**Comment by osg-grafana** [comment]
> Aliases need only be added if the content is moved. Suggest we retitle this to "Add description and keywords", which are the two forms of metadata that help users find what they need from both social (Twitter) and search engines.

This issue sounds like a NOP, so closing to document the decision. Will open two subsequent issues to address 1) descriptions and 2) keywords, so they can potentially be handled differently or by different people.
