### ISSUE TITLE
Docs: Refactor docs/sources/operators-guide/configuring/about-versioning.md file

### ISSUE THREAD

**Issue by chri2547** [grafana/mimir#1480]
Copy some of the most relevant information located in https://github.com/grafana/mimir/blob/main/docs/sources/operators-guide/configuring/about-versioning.md to the release notes, and keep the versioning.md file intact (which duplicates some of the content, but that's ok for now).

[Edit by @osg-grafana]: See @KMiller-Grafana’s comment, which holds most relevancy for this issue given current file content.

**Comment by osg-grafana** [comment]
This file indeed needs to be refactored because its contents do not reflect the file title.

**Comment by osg-grafana** [comment]
> Copy some of the most relevant information located in https://github.com/grafana/mimir/blob/main/docs/sources/operators-guide/configuring/about-versioning.md to the release notes, and keep the versioning.md file intact (which duplicates some of the content, but that's ok for now).

See @KMiller-Grafana’s comment, which holds most relevancy for this issue given current file content.

**Comment by GrafanaWriter** [comment]
This work is complete - see https://grafana.com/docs/mimir/latest/
