### ISSUE TITLE
/ready message after /shutdown should be clearer

### ISSUE THREAD

**Issue by bboreham** [grafana/mimir#149]
After calling `/shutdown`, an ingester removes itself from the ring and returns 503 to `/ready`.
However the body returned via http is not very helpful if you didn't know what happened:
```
Some services are not Running:
Running: 4
Terminated: 1
```

It would be better to say something like "ingester has been shut down", or at least list the service which has been terminated.

**Comment by bubu11e** [comment]
Hi, i assume this issue has been fixed by commit 0e9a085f0a.

**Comment by pracucci** [comment]
> Hi, i assume this issue has been fixed by commit [0e9a085](https://github.com/grafana/mimir/commit/0e9a085f0a4e118b33a1302667a2d2cda42d5e78).

Agree `/ready` has been addressed by that commit.
