### ISSUE TITLE
Need a helm chart to deploy in kubernetes cluster

### ISSUE THREAD

**Issue by SMYALTAMASH** [grafana/mimir#1576]
#### Is your feature request related to a problem? Please describe.

I've gone through the repo and saw there is a docker-compose way of deploying the mimir to test it locally. But to deploy it in kubernetes with hpa and default minio it would be better to have a helm chart so that it is easy to test it out. 

#### Describe the solution you'd like

Helm chart for deploying mimir in kubernetes cluster. 

#### Describe alternatives you've considered

N/A

#### Additional context

N/A

**Comment by oneacl** [comment]
Hi,

There is one: https://github.com/grafana/helm-charts/tree/main/charts/mimir-distributed

**Comment by SMYALTAMASH** [comment]
Awesome, can you add this as part of readme so that it'll help others as well.

**Comment by 09jvilla** [comment]
@SMYALTAMASH -- the Helm chart is mentioned in the Grafana Mimir documentation:
https://grafana.com/docs/mimir/latest/operators-guide/deploying-grafana-mimir/

I'm going to close this for now.
