### ISSUE TITLE
instructions on how to build an arm64 container image

### ISSUE THREAD

**Issue by oneacl** [grafana/mimir#1577]
Hi,

The images on dockerhub are amd64 only and I need to run in an arm64 k8s environment - would you happen to have some instructions on how to build the container images? 

I can't seem to figure out from the Makefile how to build it (and there's no Dockerfile in the root).

Thank you.

**Comment by pstibrany** [comment]
Hi. You can use `GOARCH=arm64 make ./cmd/mimir/.uptodate` to build image for `linux/arm64`.

**Comment by oneacl** [comment]
Hi,
Thanks for taking the time to reply. 
I checkout tags/mimir-2.2.0 and tried to build it for amd64 first - however, it seems to try to pull an image that doesn't exist on dockerhub

# GOARCH=amd64 make ./cmd/mimir/.uptodate
docker pull grafana/mimir-build-image:update-go-1.17.8-8a996bb57
Error response from daemon: pull access denied for grafana/mimir-build-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:114: fetch-build-image] Error 1
# 

Looking at Makefile.local.example
[..]
BUILD_IMAGE ?= grafana/mimir-build-image
[..]

and Makefile does a:
[..]
Makefile:       docker pull $(BUILD_IMAGE):$(LATEST_BUILD_IMAGE_TAG)
[..]

so what I did was build that image locally via mimir-build-image/Dockerfile, tagged it as expected, commented out the pull and reran.

# GOARCH=amd64 make ./cmd/mimir/.uptodate                                                                                                                                                                           
#docker pull grafana/mimir-build-image:update-go-1.17.8-8a996bb57                                                                                                                                                                           
docker tag grafana/mimir-build-image:update-go-1.17.8-8a996bb57 grafana/mimir-build-image:latest                                                                                                                                            
touch mimir-build-image/.uptodate                                                                                                                                                                                                           
                                                                                                                                                                                                                                            
>>>> Entering build container: protos                                                                                                                                                                                                       
time docker run --rm --tty -i -v ~/.ssh/:/root/.ssh:delegated,z -v /mimir/.cache:/go/cache:delegated,z -v /mimir/.pkg:/go/pkg:delegated,z -v /mimir:/go/src/github.com/grafana/mimir:delegated,z grafana/mimir-build-image GOOS=linux GOARCH
=amd64 BINARY_SUFFIX="" protos;                                                                                                                                                                                                             
make: Entering directory '/go/src/github.com/grafana/mimir'                                                                                                                                                                                 
make: *** No rule to make target 'protos'.  Stop.                                                                                                                                                                                           
make: Leaving directory '/go/src/github.com/grafana/mimir'                                                                                                                                                                                  
                                                                                                                                                                                                                                            
real    0m1.978s                                                                                                                                                                                                                            
user    0m0.089s                                                                                                                                                                                                                            
sys     0m0.074s                                                                                                                                                                                                                            
make: *** [Makefile:215: protos] Error 2        
# 

I'll have to dig through the Makefile next - sorry, I know this is not a support forum and appreciate your input.

**Comment by pstibrany** [comment]
```
docker pull grafana/mimir-build-image:update-go-1.17.8-8a996bb57
Error response from daemon: pull access denied for grafana/mimir-build-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Thank you, let me see if we can fix that. Can you try running `GOARCH=arm64 BUILD_IN_CONTAINER=false make ./cmd/mimir/.uptodate` in the meantime? (It will still try to pull that build image first, but it won't be used.)

**Comment by oneacl** [comment]
Confirmed I can pull the build image now.

setting the flag to false doesn't seem to do anything different:

-# GOARCH=amd64 BUILD_IN_CONTAINER=false make ./cmd/mimir/.uptodate
docker pull grafana/mimir-build-image:update-go-1.17.8-8a996bb57
update-go-1.17.8-8a996bb57: Pulling from grafana/mimir-build-image
Digest: sha256:af614acb9070b2ebd41730eb8ab4c60eeacbd05403e452273564f3a7e108d5e6
Status: Image is up to date for grafana/mimir-build-image:update-go-1.17.8-8a996bb57
docker tag grafana/mimir-build-image:update-go-1.17.8-8a996bb57 grafana/mimir-build-image:latest
touch mimir-build-image/.uptodate

>>>> Entering build container: protos
time docker run --rm --tty -i -v ~/.ssh/:/root/.ssh:delegated,z -v /mimir/.cache:/go/cache:delegated,z -v /mimir/.pkg:/go/pkg:delegated,z -v /mimir:/go/src/github.com/grafana/mimir:delegated,z grafana/mimir-build-image GOOS=linux GOARCH=amd64 BINARY_SUFFIX="" protos;
make: Entering directory '/go/src/github.com/grafana/mimir'
make: *** No rule to make target 'protos'.  Stop.
make: Leaving directory '/go/src/github.com/grafana/mimir'

real    0m1.783s
user    0m0.082s
sys     0m0.051s
make: *** [Makefile:215: protos] Error 2
-# 

This shouldn't be an issue I'd think but thought to mention it just the same. I don't have go on the host I'm working on so I'm doing the work in docker (nested seems to work just fine from what I gather) and this is how I ran it on the host:

-# docker run --rm -it -v /root/mimir:/mimir -v /var/run/docker.sock:/var/run/docker.sock golang:1.17.8-buster

**Comment by pstibrany** [comment]
I think I got the variables wrong: `GOARCH=amd64 make  BUILD_IN_CONTAINER=false ./cmd/mimir/.uptodate` actually doesn't use container on my machine (but requires Go locally).

Does `GOARCH=amd64 make ./cmd/mimir/.uptodate` work for you now, after making build-image public?

**Comment by oneacl** [comment]
Making progress (and yes, the public build image works as expected):

-# GOARCH=amd64 make BUILD_IN_CONTAINER=false ./cmd/mimir/.uptodate
protoc -I /go/src:./vendor/github.com/thanos-io/thanos/pkg:./vendor/github.com/gogo/protobuf:./vendor:./pkg/ruler/rulespb --gogoslick_out=plugins=grpc,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,:./pkg/ruler/rulespb ./pkg/ruler/rulespb/rules.proto
github.com/grafana/mimir/pkg/mimirpb/mimir.proto: File not found.
rules.proto: Import "github.com/grafana/mimir/pkg/mimirpb/mimir.proto" was not found or had errors.
rules.proto:44:12: "cortexpb.LabelPair" is not defined.
rules.proto:48:12: "cortexpb.LabelPair" is not defined.
make: *** [Makefile:229: pkg/ruler/rulespb/rules.pb.go] Error 1
-# 

Technically I have everything go related since I run this in "golang:1.17.8-buster" image but as you can tell, I'm not overly familiar with go.

**Comment by pstibrany** [comment]
With build image, I was hoping you could just use `GOARCH=amd64 make./cmd/mimir/.uptodate` to use it.

Problem you're getting seems to be related to protobuf. When running outside of build-image, you may need to install `protoc` with Go extension.

If you want, I can push Mimir-2.0.0 arm64 image into docker repository for you.

**Comment by oneacl** [comment]
of course, if you could push mimir-2.0.0 arm64 to dockerhub that would be ideal - thank you very much for that.

I installed protoc from the debian repos and probably doesn't have the go-extension - I'll also check that.

Thank you again.

**Comment by pstibrany** [comment]
I've pushed [`grafana/mimir:2.0.0-arm64` image](https://hub.docker.com/layers/200534401/grafana/mimir/2.0.0-arm64/images/sha256-67a127fe26dc8ad3267d32b37e471bf064246704f6484e23f1a3efa493a9e108?context=repo). It's built from exact same tag as `grafana/mimir:2.0.0` but with `GOARCH=arm64`, as discussed above. (It's a separate image, to avoid breaking our "golden" 2.0.0).

We would like to start publishing multiarch images in the future, there is PR in progress for that: https://github.com/grafana/mimir/pull/1124.

**Comment by oneacl** [comment]
This is greatly appreciated, the arm64 image works perfectly - thank you again for your prompt support on this.

I'll keep an eye on PR1124.
