### ISSUE TITLE
Docs feedback: /operators-guide/architecture/components/_index.md

### ISSUE THREAD

**Issue by antimack** [grafana/mimir#1582]
components page missing distributor

**Comment by pracucci** [comment]
Thanks for reporting it! We're looking into it.

**Comment by osg-grafana** [comment]
This is building fine in `next`. Will check `latest` now...

**Comment by osg-grafana** [comment]
The issue was a line in a `.gitignore` file: `dist*` that was doing what it was supposed to do. Correction was to change that line to `dist/*`.

**Comment by osg-grafana** [comment]
@grafana/docs-squad fyi in case you have any `dist`*-named files anywhere.
