### ISSUE TITLE
document ruler edit API

### ISSUE THREAD

**Issue by flokli** [grafana/mimir#1585]
#### Is your feature request related to a problem? Please describe.

I'd like to programmatically update alerting rules in Mimir. It seems it's [possible to do somehow from Grafana](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/create-cortex-loki-managed-recording-rule/#add-a-cortex-or-loki-managed-recording-rule), but the [Mimir docs](https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/) don't list any documentation for the `PUT`/`POST` part of it.

#### Describe the solution you'd like

The API to be documented.

#### Describe alternatives you've considered

N/A

#### Additional context

https://github.com/grafana/agent/issues/1544

**Comment by pracucci** [comment]
Hi @flokli thanks for opening this issue. Does this API answer your question?
https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#set-rule-group

**Comment by flokli** [comment]
Yes, this is fine. Thanks!

**Comment by osg-grafana** [comment]
Change from `Done` to `Closed` to signal that this is a NOP for the Docs Squad.
