### ISSUE TITLE
Docs: Clarify pros and cons of using CL configuration for Mimir, to improve UX

### ISSUE THREAD

**Issue by c0ffeec0der** [grafana/mimir#1644]
#### Is your feature request related to a problem? Please describe.

This is more to a question.. rather than a feature request..

The documentation says: It is best to specify your configuration via the configuration file rather than CLI

But I see that it is specified in CLI in github.com/grafana/mimir/operations/mimir

Question, is there a specific reason why currently the config is in CLI? What is the plan for going forward? Will the config still in CLI or in a config file? Loki configuration is in single configmap, so I am wondering why mimir is taking different approach for defining the config file. It looks like the structure of the config is the same. Thanks

**Comment by 56quarters** [comment]
Hello!

They're functionally equivalent and are both valid ways of configuring Mimir. There are some tradeoffs in terms of working with them that probably come down to personal preference.

Config file:
* Easier to stick a single configuration file in version control and _know_ all the settings applied to each component
* You can hit the `/config` endpoint on any component and get the full config for the entire cluster

CLI flags:
* Easier to build dynamically in jsonnet, just add key-value pairs to an array. No need to worry about nesting blocks in a config file

Hope this helps!

**Comment by c0ffeec0der** [comment]
Hello @56quarters , 

Ah i see now, adding key-value pair is much more flexible than nesting config. Thank you for sharing

**Comment by pstibrany** [comment]
> Config file:
> 
> * Easier to stick a single configuration file in version control and _know_ all the settings applied to each component
> * You can hit the `/config` endpoint on any component and get the full config for the entire cluster
> 
> CLI flags:
> 
> * Easier to build dynamically in jsonnet, just add key-value pairs to an array. No need to worry about nesting blocks in a config file

Few notes:
- `/config` endpoint also works when using CLI flags. It however always shows YAML config.
- Btw: `/config?mode=diff` is useful for seeing non-default values only.
- One nice benefit of CLI flags is that when deploying into kubernetes, all used flags are clearly visible via `kubectl describe pod`. With config file, one needs to find the right configmap, and even then it's not clear if component is using that version or some previous version. (`/config` always shows config used by given component)
- When changing config file, automation needs to restart all components. When changing CLI flags, kubernetes knows to restart only pods with updated CLI flags.

**Comment by c0ffeec0der** [comment]
Thanks @pstibrany , after reading your points I think the approach with config in CLI makes it easier for debugging, I like the point where we do `kubectl describe pod` shows the whole config for the pod instead of figuring out in the configmap. Redeploying pod individually to reflect updated config is also a big plus! with configmap if deploying the impacted pod, the other pod will have previous version of config. with CLI config, it is always updated

Just taking this a little further, considering the good points discussed here, wouldn't it be a good idea to reflect in this [documentation](https://github.com/grafana/mimir/blob/main/docs/sources/operators-guide/configuring/about-configurations.md)? So that it is inline with the approach taken using tanka deployment. This might need a little more discussion internally to agree as a better approach across products (Ioki, tempo, mimir).

From outside prespective, I was accustomed using single file config style from loki; tempo also use the same method; so when I came across mimir it was a surprise. However, the debugging and restarting pod is a big plus - potentially removing runtime configuration (even statefulset could use cli config and redeploy pod as long pvc in retain mode)

Unless there is a factor where cli configuration is not favorable, this should be the default style for deployment (helm and tanka). You can simplify the go code by removing runtime configuration, easier debugging and much flexible deployment. But this needs to be discussed across products and agree on the approach

**Comment by pstibrany** [comment]
That's a good point. Having the same recommendations between our projects makes sense, although teams not always agree on what is the best approach :)

**Comment by c0ffeec0der** [comment]
The advantage of microservice is that each process could scale horizontally (independently)

If the case is that a component depends on other component config, it looks like the config structure is still a monolith..

for example if ruler require `-querier.*` config then there should be a mechanism where querier component pass the config to ruler during startup communication, or the design is made that each component is independent removing the need to see other config.

In current condition if one modify `-querier.*` config then querier and ruler need to be restarted at minimum. It looks like the config structure could potentially cause break across service unless all pods config are updated - which the advantage of microservice is not being fully utilized

One file approach is good for learning. However, it shouldn't be a safer approach in microservice setup.. it's actually unsafe.. and holds back the power being microservice..

Just a thought..

**Comment by pracucci** [comment]
> The advantage of microservice is that each process could scale horizontally (independently)

I think in your comment we're mixing scaling with rollouts. If you deploy Mimir in microservices mode with a shared config, services are still horizontally scaling independently. For example, if you experience an high load on query path, you could scale up queriers only.

However, if you need to change the config (excluding the runtime config) or rollout a new version, then the change will be applied to all components which will be restarted.

**Comment by c0ffeec0der** [comment]
You are correct, it should be rollout.. sorry. The rollout of new version would cause a restart on all components due to having the same file for configuration and interdependency in the component config.

I am already clear of the initial question on why the CLI approach for mimir so i can close this issue. I do like the idea, its visibilty, granularity of the method for debugging and operational flexibility are useful and powerful. It was disturbing at first but after some explanation and thoughts, its beautiful. Hopefully tanka deployment for loki and tempo could follow this approach as tanka is for advance user and that config interdependency could be reduced.

@pracucci, Would you want to use this issue number as perhaps a base for future actions? If not, I am happy to close this one. Thanks

**Comment by osg-grafana** [comment]
> @pracucci, Would you want to use this issue number as perhaps a base for future actions? If not, I am happy to close this one. Thanks

I renamed this issue so we can get some of this exchange into the technical documentation.

**Comment by osg-grafana** [comment]
Closing due to lack of concrete action item for technical documentation.
