### ISSUE TITLE
memcached dns+ addresses resolve from CNAME

### ISSUE THREAD

**Issue by oneacl** [grafana/mimir#1654]
#### Describe the bug
With cortex I could use the memcached addresses dns+memcached.example.com configuration (although the documentation was clearly saying that it has to resolve to A/AAAA so maybe it was an unknown bug?)

This no longer works with mimir.

#### To Reproduce
Configure mimir with:
bucket_store:
  metadata_cache:
    backend: memcached
    memcached:
      addresses: dns+memcached.example.com

where memcached.example.com is a CNAME to someserver.example.com and someserver.example.com IN A 192.0.2.1

The mimir output will return:
name=metadata-cacche msg="failed to resolve addresses for memcached" addresses=dns+memcached.example.com err="2 errors: lookup IP address - invalid A or AAA response record [..] IN CNAME somserver.example.com

#### Additional Context

Unfortunately due to my infrastructure is deployed I can only have a CNAME for the memcached servers (and no SRV records either).

Would there be a workaround here for me to try?

Thank you.

**Comment by pracucci** [comment]
Thanks for your report!

I did a brief investigation and I've been able to reproduce it. The change has been introduced in https://github.com/grafana/mimir/pull/142 where memcached client DNS resolver moved from golang one to `miekgdns`.

To better understand your use case and properly fix it, could you show me the output of `dig memcached.example.com` (replacing `memcached.example.com ` with the the actual host and then redacting any sensitive data), please?

**Comment by oneacl** [comment]
Thank you too for the prompt fix, really appreciate it.
