### ISSUE TITLE
Docs: Change task topic titles from gerunds to imperatives

### ISSUE THREAD

**Issue by chri2547** [grafana/mimir#1663]
Change all task topics to (imperative) verb + object instead of using gerunds.

General approach:
1. Add an alias that is self-referencing to all files.
2. Commit the changes.
3. Run `doc-validator` locally; leave global link checking for later.
4. Commit the changes.
5. Move a directory of files from -ing ending to imperative.
6. Rerun `doc-validator` locally on that directory; leave global link checking for later.
7. Fix any broken links with `mv-manager`.
8. Rerun `doc-validator` from `.../doc/sources` in the `mimir` repo.
9. Repeat as needed.
10. Commit the changes.

**Comment by osg-grafana** [comment]
This involves link checking and alias changes.

**Comment by osg-grafana** [comment]
Moving to 2.3 per conversation with @dimitarvdimitrov, because these changes are forward-facing changes and it reduces the need to cherry pick for 2.2.

**Comment by osg-grafana** [comment]
Per @pracucci, the paths that are now absolute need to be relative.

**Comment by osg-grafana** [comment]
Increasing estimate of complexity of this issue.

**Comment by pracucci** [comment]
> Increasing estimate of complexity of this issue.

No. It's not a requirement. Aliases can both be absolute or relative (both are supported). There are pros and cons of both. The reason why I opened https://github.com/grafana/mimir/pull/2396 is because in https://github.com/grafana/mimir/pull/2351 the relative paths were rewritten adding a `/` in front of them (so making them absolute, but without changing them to be real absolute paths).

**Comment by osg-grafana** [comment]
@KMiller-Grafana, here is an issue that might cause problems with links breaking. @gguillotte-grafana is investigating how we can get visibility about which links are broken where. cc @knylander-grafana and @Eve832

**Comment by Eve832** [comment]
@pracucci is correct. The relrefs will still work either way, but it's not a good habit. I think if we're linking across repos, we can either use `ref` instead of `relref` or absolute URLs.

**Comment by osg-grafana** [comment]
@colega, added you as assignee because you volunteered. :)

**Comment by GrafanaWriter** [comment]
Closing as this is quite stale and our relref shortcode has been built out.
