### ISSUE TITLE
Service Account and RBAC for tanka deployment

### ISSUE THREAD

**Issue by c0ffeec0der** [grafana/mimir#1670]
#### Is your feature request related to a problem? Please describe.

I notice that there is no RBAC implementation (service account and roles) for tanka deployment. Please add as it is quite a standard security requirement

#### Describe the solution you'd like

Add RBAC implementation for tanka deployment

**Comment by c0ffeec0der** [comment]
Hello

That should be ok then. I was comparing with loki jsonnet too and noticed that service account is created for all components, but no roles was bound; except for promtail (which is equivalent to grafana agent; and grafana agent has rbac implemented) 

Question: Are the components in loki (i.e ingester in loki with ingester in mimir) have different behavior related to accessing k8s api that the service account is created to accomodate future use? If not, then I am thinking of creating an issue there to clean it up?

**Comment by pracucci** [comment]
> Question: Are the components in loki (i.e ingester in loki with ingester in mimir) have different behavior related to accessing k8s api that the service account is created to accomodate future use? If not, then I am thinking of creating an issue there to clean it up?

I don't know. I would ask it in https://github.com/grafana/loki

**Comment by c0ffeec0der** [comment]
Okay, let me try there. Thank you
