### ISSUE TITLE
Publish rpm and deb packages

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1687]
We removed support for rpm and deb packages in https://github.com/grafana/mimir/pull/1138 but there's some people in the community that finds them useful and we should re-introduce them.

Thoughts:
- Previously, they were configured with `/etc/cortex/single-process-config.yaml` by default. I would suggest to not bind them to any specific config. By default, Mimir should run with the default configuration. It should be easy to specify a config file path tho.
- We need to discuss at Grafana Labs where these packages should be published.

**Comment by wilfriedroset** [comment]
My plan is git revert, hack, hack hack until I have a working Makefile.

**Comment by ymartin-ovh** [comment]
> > should we include only mimir binary or should we add the other as well? (we can start small and improve after)
> 
> I would package only Mimir binary.
> 
> > should we build and package inside a container?
> 
> Yes, possibly. However, I wouldn't start from scratch again but revive what we dropped in #1138.

Is it possible to provide a dedicated mimir-utils package with mimirtool for example ?

Regards
