### ISSUE TITLE
Document how to configure storage retention

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1700]
The Mimir documentation doesn't explain how to configure storage retention.

We should document:
- How `-compactor.blocks-retention-period` works: explain by default is 0 that means retention is disabled (blocks are never deleted), explain it can be overridden on a per-tenant basis.
- Per-series deletion (including [this Prometheus API](https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series)) is currently not supported

Notes:
- We should create a dedicated page about the retention and link it from the compactor (the compactor page mentions "Deleting blocks that are no longer within a configurable retention period" but doesn't say anything else about it)
- We should make sure a search of "retention" in https://grafana.com/docs/mimir/latest finds the new retention doc page

**Comment by 56quarters** [comment]
Probably worth mentioning that in the absence of any compactor settings, it's possible (or could be configured such) that old data will still be cleaned by bucket retention policies.

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by pracucci** [comment]
_I'm picking up this issue._
