### ISSUE TITLE
Docs feedback: /operators-guide/securing/authentication-and-authorization.md

### ISSUE THREAD

**Issue by fanis** [grafana/mimir#1707]
Minor type in "information" below:

>Note: Not all tenant IDs are valid. For more **inforamtion** about tenant ID restrictions, refer to [About tenant IDs](https://grafana.com/docs/mimir/latest/operators-guide/configuring/about-tenant-ids/).

**Comment by pracucci** [comment]
Thanks @fanis! Want to open a PR to fix it?
