### ISSUE TITLE
Unneeded mutex in `blocksStoreQueryable.selectSorted`

### ISSUE THREAD

**Issue by colega** [grafana/mimir#1716]
#### Describe the ~bug~ issue

There's a mutex called `resultMtx` in `blocksStoreQueryable.selectSorted`:

https://github.com/grafana/mimir/blob/ba2e9a0ef577c9c6e77885609297a35f000c71e7/pkg/querier/blocks_store_queryable.go#L458-L477

However, `queryFunc` doesn't seem to be executed concurrently, so the mutex is not really needed.

#### Expected behavior

Either:
- Remove the mutex as it is not needed
- If the mutex is needed, then `leftChunksLimit` is being read without holding the mutex, which is an issue.

**Comment by pracucci** [comment]
I agree the `resultMtx` is not needed and can be removed.

**Comment by hi-rustin** [comment]
I am working on this.
