### ISSUE TITLE
Add PromQL negative offset support to Mimir

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1744]
Prometheus enabled negative offset support in [2.33.0](https://github.com/prometheus/prometheus/releases/tag/v2.33.0). Mimir currently doesn't support it so it's keeping it disabled.

We should add negative offset support to Mimir. When doing it, we should pay attention to:
- Query-frontend results cache
- Query sharding

_An easy option to begin with, may be detecting if a query is using negative offsets and just disable results cache and query sharding for them._

**Comment by pstibrany** [comment]
I am curious why do we need to disable query sharding when using negative offsets?

**Comment by pracucci** [comment]
> I am curious why do we need to disable query sharding when using negative offsets?

Unfortunately I don't remember all details and I can't find notes about it right now. Ok, let's say we should test query sharding with negative offsets and decide based on tests results.

**Comment by v-zhuravlev** [comment]
Looking forward to this feature, waiting for it to create some useful dashboards in Cloud integrations.

**Comment by RichiH** [comment]
Consensus is to have a first iteration as per @pracucci 's suggestion in https://github.com/grafana/mimir/issues/1744#issue-1212049465

* Disable caching for now
* Test if query sharding is possible, disable if it's not

It might make sense to introduce a counter so we know how many queries use negative offsets.

**Comment by pracucci** [comment]
> It might make sense to introduce a counter so we know how many queries use negative offsets.

I like this idea, but I would further extend it. We could have a metric to track the number of non cachable requests, and have a `reason` label to keep track of "why":
https://github.com/grafana/mimir/blob/321e66db90cf39e8eb1067aada9064d15cac4ba9/pkg/frontend/querymiddleware/results_cache.go#L176-L194

**Comment by RichiH** [comment]
This sounds good, I like it.

I am wondering if having metrics around amount of series / execution time would make sense as well. My gut is that this is currently not needed, but I thought I'd raise it.
