### ISSUE TITLE
Increase verbosity around readiness

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#1780]
#### Is your feature request related to a problem? Please describe.

When components aren't ready (i.e. return HTTP 503 on `GET /ready`) there is no obvious way to understand why the component isn't ready.

#### Describe the solution you'd like

There are logs explaining what service/target is blocking the start.

#### Describe alternatives you've considered

Port-forward to the pod and hit the `/ready` endpoint manually. This may not be an obvious course of action for users not familiar with our helm chart. We also have no docs to explain how to use the endpoint. Finally, the endpoint does not expose _which_ services are 

#### Proposal

Add info logs every time the `/ready` endpoint is hit and returns a non-200 response. The logs should contain more granular information such as the state of each service or the names of services in each state (right now we only return the number of services per state on the HTTP endpoint)

**Comment by pracucci** [comment]
The `/services` endpoint should give details about non-ready services.

**Comment by dimitarvdimitrov** [comment]
Using `/services` isn't much different from having to hit `/ready`. It does give more information, but is still a more complex process compared to searching for logs.

I will draft a small PR with a proposal

**Comment by dimitarvdimitrov** [comment]
kinda forgot about this. opened a PR with a proposal
