### ISSUE TITLE
Do not validate alertmanager configuration when alertmanager module is not needed

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#1784]
#### Describe the bug

Alertmanager configuration parameters and flags are validated even when alertmanager is not started and therefore no `instance_availability_zone` is set for the target.

It would be better if parameters are only validated in general when the relevant component / dependency is loaded and used by the target.

#### To Reproduce

Add 
```yaml
alertmanager:
  sharding_ring:
        zone_awareness_enabled: true
```
To your config file. Start a querier with `-target=querier -config.file=mimir.yaml`

Querier fails to start with:
```
error validating config: invalid alertmanager config: the configured alertmanager has zone awareness enabled but zone is not set
```

#### Expected behavior

Expected: querier starts up.

#### Environment

- Infrastructure: k8s
- Deployment tool: helm

#### Additional Context

Found during working on multi zone support for mimir helm chart: https://github.com/grafana/helm-charts/pull/1205
According to documentation this should have worked:
https://grafana.com/docs/mimir/latest/operators-guide/configuring/about-configurations/
"Operational considerations

Use a single configuration file, and either pass it to all replicas of Grafana Mimir (when running multiple single-process Mimir replicas) or to all components of Grafana Mimir (when running Grafana Mimir as microservices). When running Grafana Mimir on Kubernetes, you can achieve this by storing the configuration file in a [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) and mounting it in each Grafana Mimir container."

**Comment by ch33hau** [comment]
Hi @krajorama, can I try on fixing this?
