### ISSUE TITLE
Grafana dashboards have same UIDs as cortex ones

### ISSUE THREAD

**Issue by fculpo** [grafana/mimir#1789]
Hi,

We are using the mixins in a kube-prometheus environnmenent.
We have a mimir and a cortex cluster for different uses.

The mimir-mixin dashboards have the same UIDs as cortex-mixin ones and grafana refuses to load them.

Would it be possible to generate new UIDs ?
 
Thanks

**Comment by fculpo** [comment]
Awesome ! That would be much appreciated :)

**Comment by pracucci** [comment]
This is the code used by Grafana to auto-generate dashboard UIDs. We could just run it to generate new random ones:
https://github.com/grafana/grafana/blob/main/pkg/util/shortid_generator.go
