### ISSUE TITLE
Drop incoming TCP connections when limit is reached

### ISSUE THREAD

**Issue by ortuman** [grafana/mimir#1813]
#### Is your feature request related to a problem? Please describe.

Current TCP connection limiting works by blocking and enqueuing all new request until the total number is under the limit. This may lead to situations where a component rapidly exhausts all of its resources when incoming requests start to enqueue. 

#### Describe the solution you'd like

Once the connection limit has been reached, start dropping connections by returning a `http.StatusTooManyRequests` or `codes.ResourceExhausted` status code, for HTTP and gRPC respectively. 

#### Describe alternatives you've considered

We now resort to `netutil.LimitListener` to limit TCP connections for [HTTP](https://github.com/weaveworks/common/blob/master/server/server.go#L202) and [gRPC](https://github.com/weaveworks/common/blob/master/server/server.go#L217). We may ignore this values (set them to 0 = unlimited), and resort to specific middlewares to implement dropping logic. As part of this, additional config flags may be added to avoid conflicting with current `-server.http-conn-limit` and `-server.grpc-conn-limit`.

**Comment by pracucci** [comment]
> Once the connection limit has been reached, start dropping connections by returning a http.StatusTooManyRequests or codes.ResourceExhausted status code, for HTTP and gRPC respectively.

I think the key point here is that we still have to "consume" the HTTP request body to be able to send the response, but we should ensure the HTTP request body is not fully loaded in memory but just "discarded".

**Comment by pstibrany** [comment]
> I think the key point here is that we still have to "consume" the HTTP request body to be able to send the response, but we should ensure the HTTP request body is not fully loaded in memory but just "discarded".

We don't need to read full request to send a reply, unless we want to keep the connection open and be able to read more requests from it. In this situation, that doesn't seem like desirable property.

**Comment by pstibrany** [comment]
> We don't need to read full request to send a reply, unless we want to keep the connection open and be able to read more requests from it. In this situation, that doesn't seem like desirable property.

Except when using httpgrpc, where we don't have such control, and full request is received before it is even passed to the handler.

**Comment by pracucci** [comment]
_I've the feeling the issue is not super clear, trying to rephrase what I think we want to do._

Distributors have a per-instance limit on max inflight requests. This limit is enforced after we read the full request body in memory (it could be received either via HTTP or httpgrpc, depending on whether there's a proxy in between). Reading the full request body in memory, even if we already hit the max inflight requests, could still cause distributors to go OOM, which is what we experienced in some circumnstances. 

Proposal: we could check the limit before reading the request body, and discard it if limit has been reached.

**Comment by pstibrany** [comment]
> Distributors have a per-instance limit on max inflight requests. This limit is enforced after we read the full request body in memory (it could be received either via HTTP or httpgrpc, depending on whether there's a proxy in between). Reading the full request body in memory, even if we already hit the max inflight requests, could still cause distributors to go OOM, which is what we experienced in some circumnstances.

Thanks for clarification. You're suggesting to move the inflight requests limit into the `push.Handler`, before reading and parsing the request. (Unfortunately request will still be fully read into memory by httpgrpc, if gRPC based proxying is used, but at least push request will not decoded into `mimirpb.WriteRequest`). That makes sense.

**Comment by pracucci** [comment]
> Unfortunately request will still be fully read into memory by httpgrpc, if gRPC based proxying is used

I would do a step forward and investigate how we can avoid it. Maybe via a gRPC interceptor checking if max inflight requests limit is hit?

**Comment by krajorama** [comment]
Am I right to assume that dropping the connections would fix the issue of also reaching linux conntrack limit?

**Comment by pracucci** [comment]
> Am I right to assume that dropping the connections would fix the issue of also reaching linux conntrack limit?

I don't think so. The clients will re-connect anyway. On the opposite, I think we shouldn't close the TCP connection to leverage on HTTP keep alive and keep getting TCP connections reused.

**Comment by ortuman** [comment]
After discussing internally, we agreed on adding this drop connection logic exclusively in the cortex-gw/cloud-backend-gateway, as to date this problem has only manifested on this component.

Plus, this would simplify the solution by leaving aside gRPC/httpgrpc.  

Closing, and moving this issue to our enterprise repo. 👍
