### ISSUE TITLE
Docs: add ruler "remote" mode diagram to ruler component documentation

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1831]
The PR https://github.com/grafana/mimir/pull/1714 updated ruler documentation to mention the "remote" operational mode too, and the ruler diagram has been moved under "internal" section:
https://grafana.com/docs/mimir/next/operators-guide/architecture/components/ruler/ruler.svg

We should draw a similar diagram but showing the "remote" operational mode.

Differently than the "internal" mode diagram, the "external" mode diagram should have:
- No arrows from ruler to ingester and store-gateway
- An arrow from ruler to query-frontend
- An arrow from query-frontend to querier
- Arrows from querier to ingester and store-gateway
- Remove "Metadata cache" because it's not used by the ruler, but the "querier"

**Comment by 09jvilla** [comment]
@pracucci @ortuman -- take a look at 
https://docs.google.com/presentation/d/1LemaTVqa4Lf_tpql060vVoDGXrthp-Pie_SQL7qwHjc/edit#slide=id.g11c3d9a6d38_0_39

does this look right? I omitted the caches for simplicity.

**Comment by 09jvilla** [comment]
PR to fix
https://github.com/grafana/mimir/pull/1861
