### ISSUE TITLE
Proposal: deprecate -distributor.extend-writes and keep it always disabled

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1854]
`-distributor.extend-writes` (defaults `true`) is a setting used by distributors and rulers to find the set of ingesters a series should be written to. The doc says:

> Try writing to an additional ingester in the presence of an ingester not in the ACTIVE state. It is useful to disable this along with -ingester.ring.unregister-on-shutdown=false in order to not spread samples to extra ingesters during rolling restarts with consistent naming.

In Mimir jsonnet we currently disable `extend-writes` when ingesters are configured to not unregister on shutdown. For that use case, we already know it's safe to disable it.

Question: is it safe to also disable it for the case ingesters **do** unregister on shutdown (default)? To answer this question, we need to understand what are the cases when an ingester is not ACTIVE and if there could be more than 1 non-ACTIVE ingester in 1 replication set under normal conditions. If there's no more than 1 non-ACTIVE ingester in 1 replication set under normal conditions, then it's safe to keep it always disabled.

> in 1 replication set

I'm mentioning it, because the `extend-writes` setting affect only the [`ring.Get()` called by distributor Push()](https://github.com/grafana/mimir/blob/93dbb1fc6197e381e3265f72d9c1b399afe570e3/pkg/distributor/distributor.go#L798-L807), which is used to build the replication set for 1 series. With a RF=3 and quorum=2, we can tolerate up to 1 non-ACTIVE ingester in each replication set when we write series from distributors to ingesters.

> we need to understand what are the cases when an ingester is not ACTIVE and if there could be more than 1 non-ACTIVE ingester in 1 replication set under normal conditions

Cases coming to my mind:
- Rolling update: 1 ingester at a time (when multi-zone is disabled) or multiple ingesters in the same zone (when multi-zone is enabled). In both cases, there should be only up to 1 non-ACTIVE ingester per replication set. We're safe.
- Scale up: multiple ingesters in PENDING or JOINING state, in different zones, at the same time. This could happen, but it's no different than the current behaviour with Mimir deployed with Jsonnet. I think it's not a big deal for Mimir, because a new ingester stays in PENDING/JOINING state for a very short time.
- Scale down: in order to guarantee query results correctness, we need to scale down 1 ingester at a time or, at most, 1 zone at a time (when multi-zone is enabled). We should be safe.

## Proposal

I propose to deprecate it and keep it always disabled.

**Comment by 09jvilla** [comment]
@pracucci I'll excuse myself from commenting on the correctness of the proposal since I'm a bit out of my depth, but roughly the logic makes sense to me. 

As you're considering both the `-ingester.unregister-on-shutdown=false` and `-ingester.unregister-on-shutdown=true` cases, am I right to assume that you want to keep `-ingester.unregister-on-shutdown=true` as the default for the unregister flag? 

If so, do you have opposition to overriding this default in the Helm chart (meaning, having `-ingester.unregister-on-shutdown=false` in the Helm chart) since we can make assumptions about our Helm users deploying the ingesters as StatefulSets? See @Logiraptor 's issue here in the chart repo: https://github.com/grafana/helm-charts/issues/1313

**Comment by pracucci** [comment]
> As you're considering both the -ingester.unregister-on-shutdown=false and -ingester.unregister-on-shutdown=true cases, am I right to assume that you want to keep -ingester.unregister-on-shutdown=true as the default for the unregister flag?

I would start a separation discussion about it (unrelated from this issue). The main problem changing default to `-ingester.unregister-on-shutdown=false` is that rolling updates wouldn't work if the instance ID (in the ring) is not preserved between restarts.

**Comment by bboreham** [comment]
I have never understood what this feature was supposed to achieve. I believe it causes issues such as https://github.com/cortexproject/cortex/issues/1290. Happy to see it removed, although it would be even better to understand it first.
