### ISSUE TITLE
Metrics: cluster_namespace_deployment_reason:required_replicas:count{reason: memory_usage} rule fails

### ISSUE THREAD

**Issue by pdf** [grafana/mimir#1860]
#### Describe the bug
Prometheus produces the following error when attempting to execute the rule `cluster_namespace_deployment_reason:required_replicas:count` (for `reason: memory_usage`):

```
vector cannot contain metrics with the same labelset
```

This is undesirable as it causes alerts to be emitted for failing rules.

#### To Reproduce

1. Deploy mimir (helm: mimir-distributed)
2. Deploy Prometheus (helm: kube-prometheus-stack)
3. Deploy the monitoring mixin from `operations/mimir-mixin/` in this repository.

#### Expected behavior

Rules should execute without error.

#### Environment

- Infrastructure: Kubernetes v1.23
- Deployment tool: helm (deployment), jsonnet (metrics)

#### Additional Context

The error is produced because the `container_memory_usage_bytes` metric used in `cluster_namespace_deployment:container_memory_usage_bytes:sum` contains series that do not contain any of the labels `cluster`, `namespace`, or `deployment`. The almost identical `cluster_namespace_deployment:container_cpu_usage_seconds_total:sum_rate` relies on `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate`, which is pre-filtered like so:

```promql
sum by(cluster, namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!="",job="kubelet",metrics_path="/metrics/cadvisor"}[5m])) * on(cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=""}))
```

So, `container_memory_usage_bytes` needs to be filtered to produce metrics that include at least one of the required labels, either as an additional rule, or by embedding the filtering into `cluster_namespace_deployment:container_memory_usage_bytes:sum`.

**Comment by pdf** [comment]
I think the following change is probably adequate (making this change won't fix previously recorded series, but allow the subsequent rule to succeed once its `[1d]` window rolls out):

```diff
diff --git a/operations/mimir-mixin/recording_rules.libsonnet b/operations/mimir-mixin/recording_rules.libsonnet
index c76be953d..9278e9ff1 100644
--- a/operations/mimir-mixin/recording_rules.libsonnet
+++ b/operations/mimir-mixin/recording_rules.libsonnet
@@ -335,7 +335,7 @@ local utils = import 'mixin-utils/utils.libsonnet';
               sum by (%(alert_aggregation_labels)s, deployment) (
                 label_replace(
                   label_replace(
-                    container_memory_usage_bytes,
+                    container_memory_usage_bytes{image!="",job="kubelet",metrics_path="/metrics/cadvisor"},
                     "deployment", "$1", "%(per_instance_label)s", "(.*)-(?:([0-9]+)|([a-z0-9]+)-([a-z0-9]+))"
                   ),
                   # The question mark in "(.*?)" is used to make it non-greedy, otherwise it
```

**Comment by pracucci** [comment]
Thanks for opening this issue.

> I think the following change is probably adequate (making this change won't fix previously recorded series, but will allow the subsequent rule to succeed once its [1d] window rolls out, for existing users - for new users it should work immediately):

That would be a breaking change. It implies `container_memory_usage_bytes` is exported by `job="kubelet",metrics_path="/metrics/cadvisor"}` but that's not necessarily the case (e.g. it would break at Grafana Labs infrastructure).

> vector cannot contain metrics with the same labelset

The recording rule currently expects the `pod` label on `container_memory_usage_bytes` (the `pod` label can be customised via the `per_instance_label` config field, when building the mixin yourself).

Does your `container_memory_usage_bytes` has the `pod` label? If not, could you try to customise the `per_instance_label` and rebuild the mixin running `make build-mixin`? 

_I'm asking because if your container metrics don't have the `pod` label, then I would expect there will be other things breaking in dashboards and rules._

**Comment by pdf** [comment]
> That would be a breaking change. It implies `container_memory_usage_bytes` is exported by `job="kubelet",metrics_path="/metrics/cadvisor"}` but that's not necessarily the case (e.g. it would break at Grafana Labs infrastructure).

Actually, I believe that just `container_memory_usage_bytes{image!=""}` would be sufficient, would that work for your env?

> Does your `container_memory_usage_bytes` has the `pod` label? If not, could you try to customise the `per_instance_label` and rebuild the mixin running `make build-mixin`?

It contains a mix of series with and without `pod`, for example:

```
container_memory_usage_bytes{endpoint="https-metrics", id="/", instance="172.22.0.2:10250", job="kubelet", metrics_path="/metrics/cadvisor", node="nodename", service="prometheus-stack-kubelet"}
```

The problem is that with such a series, the current `cluster_namespace_deployment:container_memory_usage_bytes:sum` rule will produce a new series with no labels at all, which causes `quantile_over_time` to fail in `cluster_namespace_deployment_reason:required_replicas:count` because it can't compute common labels.

**Comment by pracucci** [comment]
> Actually, I believe that just container_memory_usage_bytes{image!=""} would be sufficient, would that work for your env?

It looks good to me! I'm seeing other recording rules (e.g. from K8S mixin) doing the same. Fancy to open a PR to fix it, please?
