### ISSUE TITLE
Query frontend: parser panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by RobertSalong** [grafana/mimir#1866]
#### Describe the bug

mimir query frontend runs into a parser panic: `runtime error: index out of range [0] with length 0` every time regex-matching labels that include  $* in the beginning or end of label value are queried through a grafana panel.

#### To Reproduce

1. Mimir 2.0.0
3. Grafana 8.4.4
4. Query from mimir datasource any regex match or not-regex match with a label value that includes a `$*` specifically in the beginning or end of the value. 

Examples found so far:

```
metric_name{label_name=~"$*label_value"}
metric_name{label_name!~"$*label_value"}
metric_name{label_name=~"label_value$*"}
metric_name{label_name!~"label_value$*"}
metric_name{label_name=~"$*"}
metric_name{label_name!~"$*"}
anything{anything=~"$*anything"}
```

Note: label_value can be any string or missing altogether. Looks like the query has to include a combination of `=~` and `$*` or `!~ `and `$*` in the labels. Metrics, label names and label values do not need to be valid(actually exist) for this to occur.
 
#### Expected behaviour

query frontend not to run into a panic

**Comment by 56quarters** [comment]
Thank you for this bug report! I can reproduce this in grafana/mimir-prometheus but *not* prometheus/prometheus: https://github.com/grafana/mimir-prometheus/compare/56quarters/mimir-issue-1866

**Comment by pracucci** [comment]
> Thank you for this bug report! I can reproduce this in grafana/mimir-prometheus but _not_ prometheus/prometheus: https://github.com/grafana/mimir-prometheus/compare/56quarters/mimir-issue-1866

First thing that comes to my mind are the regex optimizations we have in `mimir-prometheus`.

**Comment by colega** [comment]
Thank you for reporting, we've fixed this in https://github.com/grafana/mimir-prometheus/pull/234 and brought the fix to Mimir in https://github.com/grafana/mimir/pull/1883
