### ISSUE TITLE
Compactor block index size limited to 64GiB

### ISSUE THREAD

**Issue by mattmendick** [grafana/mimir#19]
**Describe the bug**
During compaction, if the block index to be output by the compactor will be larger than 64GiB, the process will fail.

**To Reproduce**
1. Run Mimir with a lot of metrics in a single tenant, like 1B
2. Configure compaction to be `2h0m0s,12h0m0s,24h0m0s`
3. When the compaction eventually tries to compact a large file, compactor will output `exceeding max size of 64GiB`

**Expected behavior**
The file would be allowed to be written larger than 64GiB

**Environment:**
 - Infrastructure: k8s
 - Deployment tool: jsonnet

**Comment by colega** [comment]
This issue is solved by split-and-merge compactor, right?

**Comment by pstibrany** [comment]
That's right!

**Comment by colega** [comment]
Closing then. A link to our compactor docs for people who may reach this issue from the internet:

https://grafana.com/docs/mimir/next/operators-guide/architecture/components/compactor/?plcmt=footer#grafana-mimir-compactor

@pstibrany consider adding a link here to any other information you're planning to publish about the compactor.

**Comment by pstibrany** [comment]
This blog post explains how new compactor in Mimir works, and avoids the issue with TSDB index size:

https://grafana.com/blog/2022/04/19/how-grafana-mimirs-split-and-merge-compactor-enables-scaling-metrics-to-1-billion-active-series/
