### ISSUE TITLE
Stop saying "out of bounds"

### ISSUE THREAD

**Issue by bboreham** [grafana/mimir#1908]
#### Is your feature request related to a problem? Please describe.

Users get messages like this and it means nothing to them.
```
time="2022-05-20T15:05:31Z" level=error msg="Request failed: 400 user=1234: err: out of bounds. timestamp=2022-05-20T13:22:47.101Z, series={__name__=\"process_max_fds\", app=\"promtail\" ..."
```

#### Describe the solution you'd like

Say something like "timestamp too old".

#### Describe alternatives you've considered

If we could just accept older data, maybe related to #1757, then this error would not occur.

#### Additional context

The error comes from inside TSDB; I guess we'd have to check in the ingester before sending it to TSDB.
Or we could try changing the message upstream in Prometheus.

**Comment by gmintoco** [comment]
This would benefit us as well. We have some edge devices that push back metrics when they can (usually only down for a few hours but potentially could be days at a time) being able to ingest this data back into Mimir when they come online would be very useful

**Comment by pracucci** [comment]
> This would benefit us as well. We have some edge devices that push back metrics when they can (usually only down for a few hours but potentially could be days at a time) being able to ingest this data back into Mimir when they come online would be very useful

This issue is about rephrasing the error message, while what you need is the ability to ingest samples with any timestamp: it's something we're already working on (not tracked by this issue), but will take some time to get it production grade.

**Comment by daper** [comment]
Is there any place where I could follow the progress of this feature?

**Comment by pracucci** [comment]
> Is there any place where I could follow the progress of this feature?

@codesome @jesusvazquez What's the best way to follow out-of-order samples ingestion for OSS community?

**Comment by osg-grafana** [comment]
@grafana/docs-squad, any objection to flag this phrase in the linter?

**Comment by jesusvazquez** [comment]
In the following weeks we'll merge a PR that brings out of order support where the out of bounds errors have been replaced for sample too old. Maybe we could consider enabling the linter after that?

**Comment by codesome** [comment]
With #2187, we say "too old" only if the out of order ingestion is enabled. If there is any place where "out of bounds" is used, that still stays with #2187 with out of order disabled.

**Comment by pracucci** [comment]
We remapped the "out of bounds" error into a more understandable error in https://github.com/grafana/mimir/pull/2066, so I think we can close this issue.

_Feel free to reopen it anytime if think otherwise._
