### ISSUE TITLE
Consider removing `__org_id__` label from the block

### ISSUE THREAD

**Issue by pstibrany** [grafana/mimir#1923]
Mimir uses some block labels internally, one of them being `__org_id__` . In ingester.go, there is this comment:

https://github.com/grafana/mimir/blob/221caaae03790aebce68eff887be82006952d183/pkg/ingester/ingester.go#L1513-L1515

What do you think about removing `__org_id__` label from the blocks? Shipper is already happy with `__ingester_id__` set by ingester,  and doesn’t need `__org_id__` too. Plus we don’t really use `__org_id__`  label for anything in the code, so if block doesn’t have it, it’s not a problem. But it makes upload of blocks more difficult – see `metaconvert` and many other places which add the label for to make Mimir happy (but Mimir doesn’t care.)

Not requiring any special label would simplify manual upload of the blocks from Prometheus, and some code where we currently set the label.

(I don't suggest that we update existing blocks to remove the label, just that we don't set the label for new blocks.)

**Comment by pracucci** [comment]
I agree removing it.

> Shipper is already happy with __ingester_id__ set by ingester

We could also consider changing shipper logic to not force us setting any external label at all.

**Comment by pstibrany** [comment]
I started to work on this (incl. changing shipper logic.)

**Comment by yeya24** [comment]
Do we want to maintain shipper code in mimir? Is it better to modify this logic on Thanos directly?

**Comment by pstibrany** [comment]
Ingester no longer adds any extra labels, and compactor will ignore existing `__org_id__` labels in order to be able to compact blocks with and without this label together. This is now fixed (via #1972).
