### ISSUE TITLE
Classify -querier.query-ingesters-within and -querier.query-store-after as advanced

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1924]
Currently `-querier.query-ingesters-within` and `-querier.query-store-after` are classified as basic. In the past few days, we worked to change related defaults https://github.com/grafana/mimir/pull/1909 and I would expect ordinary Mimir users to not touch them anymore.

What's the sentiment if we classify them as advanced?

**Comment by stevesg** [comment]
Given that tuning them needs quite a deep understanding of how querying works, I agree they should not be basic.
