### ISSUE TITLE
Docs: Add the guide Getting started with Grafana Mimir using the Helm chart

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#1945]
#### Is your documentation request related to a feature? If so, which one?

Use-case: as a new user of the mimir-distributed helm chart I want to get from zero to running Mimir with the chart in a test environment. I want to know how to test that the installation worked. I want to be able to use the mimir dashboards to check metrics of my installation.

#### Describe the solution that you’d like or the expected outcome

Add a getting started with mimir-distributed helm chart. It should have these information:
- pre-requisites (kubernetes, software requirements)
- instructions on how to install the chart in a custom namespace
- instructions on how to set up remote write
- instructions on how to query data with curl
- instructions on how to set up Grafana and do query
- instructions on how to set up ServiceMonitoring 
  - additional pre-requisites (prometheus operator)
  - how to set up ServiceMonitoring
  - how to check the data
  - how to install mimir dashboards

Out of scope: non-minio bucket store, GEM, production env. Stick to getting started as quickly as possible to support adoption and getting familiar with mimir and chart concepts.

**Comment by pstibrany** [comment]
Note that configuration at https://github.com/grafana/mimir/tree/main/docs/configurations/grafanacon-2022 achieves something similar: it's basic step-by-step setup of Mimir helm chart. It differs from your goal:

- it doesn't use separate namespace (to simplify the demo)
- no curl example
- setup of Grafana is covered in the demo itself, but not in index.md instructions
- ServiceMonitors are briefly mentioned in the demo, but not explained thoroughly (with more time, ideally there would be a slide covering this concept)

Note that Mimir dashboards require scrape interval to be lower than default 60s.

**Comment by krajorama** [comment]
We need to call attention to the fact that the default values.yaml allows some shortcuts that should not be relied on in production:
- unsafe minio
- automtatically injected X-Scope-OrdID=anonymous (if not specified)
- non redundant (?)

**Comment by osg-grafana** [comment]
Pardon the noise, we are working with a new workflow to manage doc tickets and I moved a subtask mistakenly, which moved this issue.
