### ISSUE TITLE
Accept JSON in the remote write API

### ISSUE THREAD

**Issue by colega** [grafana/mimir#1950]
#### Is your feature request related to a problem? Please describe.

I am using Mimir as the timeseries DB for my weather station, which is running on an [ESP32 board](https://www.espressif.com/en/products/socs/esp32). 

I tried pushing data using [prometheus-arduino](https://github.com/grafana/prometheus-arduino) library, however I wasn't able to make it work properly (90% caused by my lack of C++ knowledge) so I surrended and switched to running Micropython code on it.

However, there's no full support for Protocol Buffers in Micropython yet, and trying to use it's just too complicated.

#### Describe the solution you'd like

I'd like to be able to send JSON-encoded `prompb.RemoteWrite` request (same protobuf, but json-encoded) to the `/api/v1/push` endpoint. That would require considering the `content-type` header in `push.Handler`:
https://github.com/grafana/mimir/blob/a21356223b79d9041c66b9049540f09768adab27/pkg/util/push/push.go#L53-L61

We should use a more efficient JSON parser than the stdlib's one, and we should provide benchmarks measuring the performance impact on using JSON. 

#### Describe alternatives you've considered

As a temporary solution, I just [wrote a simple proxy](https://github.com/colega/prometheus-json-remote-write-proxy) that unmarshals `prompb.RemoteWrite` from JSON, marshals it back as protobuf and forwards the request.

#### Additional context

IMO, this is something that would make it easier to use Mimir (and Grafana Cloud) from third-party and ad-hoc tools, as building a JSON payload is something that virtually any tool can do.

This is something that [was requested for Prometheus](https://groups.google.com/g/prometheus-users/c/odqr6EInLhs) in the past and something that [alternative solutions already support](https://github.com/timescale/promscale/blob/9eaf677/docs/writing_to_promscale.md#json-streaming-format).

**Comment by pstibrany** [comment]
This would be very useful!

> IMO, this is something that would make it easier to use Mimir (and Grafana Cloud) from third-party and ad-hoc tools, as building a JSON payload is something that virtually any tool can do.

I was wondering if int64 timestamps could be a problem, but it seems that Number.MAX_SAFE_INTEGER is `2^53 - 1`, which is large enough to hold unix timestamps in milliseconds (which are between 2^40 and 2^41).

**Comment by gouthamve** [comment]
I would instead try to ingest the Influx Line Protocol. It is simpler than JSON at would make it much easier to push from Arduino and similar systems than JSON. Not to mention the number of client libraries already available and maintained.

If we do have to ingest JSON, there is a deprecated Prometheus format: https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY/edit

I wonder if OpenMetrics has ever thought about a JSON format. Poking @RichiH

**Comment by pstibrany** [comment]
> It is simpler than JSON at would make it much easier to push from Arduino and similar systems than JSON.

Influx Line Protocol would be nice too, but the point here was accepting the same protobuf message just in json form.

**Comment by colega** [comment]
Exactly: ingesting same model but json-marshaled is less cost (both implementing and maintaining) than ingesting the deprecated Prometheus format.

Regarding the influx line: I agree that it would be simplier to send than JSON format, but it's a parallel conversation happening in a different forum right now (being decided where to put different proxies we have, and whether they have to be proxies).

**Comment by RichiH** [comment]
I am not certain if I have a strong opinion in this specific case, but as I was tagged let me share my gut around what I would do:

While Prometheus does not support this, OpenMetrics is explicitly designed to allow push, and has well-defined properties around it. It is even simpler to `printf` than to create JSON, so maybe that's a trade-off you might be interested in; also see https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#supporting-target-metadata-in-both-push-based-and-pull-based-systems

**Comment by colega** [comment]
I'll close this issue since JSON will be supported as part of OLTP ingestion in https://github.com/grafana/mimir/pull/695

There's no need to add yet another standard here.

https://www.youtube.com/watch?v=yqgJLRhM-MI
