### ISSUE TITLE
Inner evaluation span missing from query traces

### ISSUE THREAD

**Issue by aknuds1** [grafana/mimir#1954]
#### Describe the bug
[This](https://github.com/prometheus/prometheus/blob/57f4aab27d53872b109c8513846765df6b51eb57/promql/engine.go#L1229-L1232) particular inner evaluation span is missing from query traces, according to @pracucci.

#### To Reproduce
Not sure.

#### Expected behavior
To see the aforementioned [span](https://github.com/prometheus/prometheus/blob/57f4aab27d53872b109c8513846765df6b51eb57/promql/engine.go#L1229-L1232) in Mimir query traces.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: Jsonnet

**Comment by pracucci** [comment]
I think it has been broken by this change: https://github.com/prometheus/prometheus/pull/9724. I'm investigating it.
