### ISSUE TITLE
Play with Grafana Mimir tutorial not working on `main`

### ISSUE THREAD

**Issue by pstibrany** [grafana/mimir#1979]
#### Describe the bug

Running `docker-compose up` from `mimir/tutorials/play-with-grafana-mimir` directory on latest `main` (fc83295de305b5167a89b67fca5a30800682f5ff) fails with error:

```
play-with-grafana-mimir-prometheus-1     | ts=2022-06-01T06:14:33.635Z caller=manager.go:973 level=error component="rule manager" msg="loading groups failed" err="/etc/prometheus/rules.yaml: read /etc/prometheus/rules.yaml: is a directory"
play-with-grafana-mimir-prometheus-1     | ts=2022-06-01T06:14:33.635Z caller=main.go:1188 level=error msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
play-with-grafana-mimir-prometheus-1     | ts=2022-06-01T06:14:33.639Z caller=main.go:1097 level=error err="error loading config from \"/etc/prometheus/prometheus.yml\": one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/prometheus.yml\")"
```

#### Expected behavior

I expected all components to start successfully.

#### Environment

```
% docker --version
Docker version 20.10.14, build a224086
% docker-compose --version
Docker Compose version v2.5.1
```

**Comment by pracucci** [comment]
Does it happen if you run it from `docs/sources/tutorials/play-with-grafana-mimir/` directory instead of the symlink one?

**Comment by pracucci** [comment]
> When running from `docs/sources/tutorials/play-with-grafana-mimir/` I do NOT get the same error.

So, does it work or do you get a different issue?

**Comment by pstibrany** [comment]
> > When running from `docs/sources/tutorials/play-with-grafana-mimir/` I do NOT get the same error.
> 
> So, does it work or do you get a different issue?

Sorry for confusion. When running from `docs/sources/tutorials/play-with-grafana-mimir/` it works fine :)
