### ISSUE TITLE
Expose S3 client TLS configuration

### ISSUE THREAD

**Issue by jdbaldry** [grafana/mimir#1981]
#### Is your feature request related to a problem? Please describe.

When using an S3 compatible object storage provider, it might be the case that you need to provision the S3 client with the certificates in order to verify the server certificate. The only solution presently is to enable insecure verification as you cannot provide TLS config to the s3 client via our current configuration parameters.

#### Describe the solution you'd like

The Thanos S3 client used in Mimir supports TLS configuration (https://github.com/grafana/mimir/blob/b1b9882379b899a317425ed7c4aaa9e308498375/vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go#L121) which is passed to the MinIO client that itself has TLS configuration support. I would like to see the full set of TLS configuration options exposed in Mimir configuration parameters.

#### Describe alternatives you've considered

None yet.

#### Additional context

None yet.

**Comment by zalegrala** [comment]
The above PR was closed.  Tempo has recently added support for the TLS config from dskit.  https://github.com/grafana/dskit/blob/main/crypto/tls/tls.go#L87

Mimir may be able to embed this also for consistency of tls options.

**Comment by reidlai** [comment]
still can't find any information how to set up TLS CA cert file for S3/Minio connection

**Comment by zalegrala** [comment]
I was able to work around the lack of config by placing my CA cert in `/etc/ssl/certs/`, which is loaded by Go without config.

**Comment by benoitschipper** [comment]
> I was able to work around the lack of config by placing my CA cert in `/etc/ssl/certs/`, which is loaded by Go without config.

How did you get it there? Via the helm chart? Or did you adjust the Mimir image? I wonder :)

**Comment by zalegrala** [comment]
I'm not using helm, but I just mounted a configmap at the location in k8s.  
![image](https://github.com/grafana/mimir/assets/88330524/07755001-b553-4115-b2d8-a83efdfca70f)

**Comment by Itaykal** [comment]
> I was able to work around the lack of config by placing my CA cert in `/etc/ssl/certs/`, which is loaded by Go without config.

I think the way to go would be either implementing this workaround in the helm chart, or push forward #2652.
Is there any status on re-opening the PR?
