### ISSUE TITLE
Docs: clarify critical and non-critical errors in runbooks

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#2005]
In this PR https://github.com/grafana/mimir/pull/1984#pullrequestreview-992322685 we received the feedback we're not definiting what a "critical" and "non-critical" error is, what it means and why we mention it. We should clarify it in the runbooks doc, so that it's easier to standardise.

**Comment by osg-grafana** [comment]
@pracucci, do we have an existing definition "critical" or "non-critical" anywhere else in our products or projects? cc @RichiH, in case you might know.

**Comment by osg-grafana** [comment]
cc @KMiller-Grafana and @knylander-grafana

**Comment by pracucci** [comment]
> do we have an existing definition "critical" or "non-critical" anywhere else in our products or projects?

Don't think we have a place where we formally define it. By convention, we use "critical" for anything what should be addressed immediately, non-critical the opposite (something you should be aware of, but typically not a big deal).

**Comment by osg-grafana** [comment]
> > do we have an existing definition "critical" or "non-critical" anywhere else in our products or projects?
> 
> Don't think we have a place where we formally define it. By convention, we use "critical" for anything what should be addressed immediately, non-critical the opposite (something you should be aware of, but typically not a big deal).

What about things that need to be addressed because over time they will cause critical issues?

**Comment by osg-grafana** [comment]
Also, I think we are conflating critical versus non-critical with what an error message actually is. Would it not be better for the user to determine whether or not something is critical?

**Comment by pracucci** [comment]
> Would it not be better for the user to determine whether or not something is critical?

An user may not have the required knowledge to assess whether an error or alert is critical or not. That's why we define the severity level on alerts, instead of letting users to pick it "freely".

**Comment by osg-grafana** [comment]
@knylander-grafana, here are two more related terms that we can define in the list of terminology.

**Comment by osg-grafana** [comment]
Closing due to age and low priority.
