### ISSUE TITLE
Proposal: add DNS-based service discovery and multi addresses support to query-scheduler address

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#2012]
When running Mimir with the query-scheduler, the address needs to be specified in two configs:
- `-querier.scheduler-address`
- `-query-frontend.scheduler-address`

Currently, the query-scheduler address is resolved using `grpcutil.NewDNSResolverWithFreq()`, which was forked from gRPC (and in Mimir we only use such resolved for the query-scheduler address):
https://github.com/grafana/mimir/blob/8bc28f1628be47f5e970a2b7f218f0779c073180/pkg/util/dns_watcher.go#L36

We have few drawbacks of using such resolver:
1. Doesn't support our [DNS-based service discovery pattern](https://grafana.com/docs/mimir/next/operators-guide/configuring/about-dns-service-discovery/) 
2. Doesn't support multiple comma-separated addresses

## Proposal

I propose to standardize the query-scheduler address config to:
- [DNS-based service discovery](https://grafana.com/docs/mimir/next/operators-guide/configuring/about-dns-service-discovery/)
- Support for multiple comma-separated addresses (this is handy in environments where DNS service discovery is not an option, like when using docker-compose)

To avoid this to be a breaking change, I propose to adopt an approach similar to #993: we parse each configure address and if it has no "prefix" (e.g. `dns+` prefix) then we just use the old logic.

**Comment by krajorama** [comment]
Seems reasonable.

**Comment by Andy-Robinson-WoodMac** [comment]
I think it's the same case for (--querier.frontend-address) too, which if you're using the scheduler fine but if not I think you run into the same problem. I tried to point it at a DNS that resolves to a loadbalancer, but it resolves it to the instance IPs but still uses the port (intended for the loadbalancer listener), which if using dynamic ports you have no way of telling it what another service might be using. The loadbalancer would take care of that, but yeah doesn't work. 

The SRV record support would be nice as that's the same as the memberlist support.

**Comment by Andysimcoe** [comment]
I think it's the same case for (--querier.frontend-address) too, which if you're using the scheduler fine but if not I think you run into the same problem. I tried to point it at a DNS that resolves to a loadbalancer, but it resolves it to the instance IPs but still uses the port (intended for the loadbalancer listener), which if using dynamic ports you have no way of telling it what another service might be using. The loadbalancer would take care of that, but yeah doesn't work.

The SRV record support would be nice as that's the same as the memberlist support.

**Comment by pracucci** [comment]
Superseeded by #2950.
