### ISSUE TITLE
Enable support for http proxy for alertmanager receivers

### ISSUE THREAD

**Issue by Fantaztig** [grafana/mimir#2044]
#### Describe the bug
Currently it's not possible to configure a proxy for alertmanager receivers.
This is pretty annoying since the receivers also ignore a proxy set via HTTPS_PROXY env variables.

#### To Reproduce
* Set up mimir with alertmanager
* Try to configure a webhook with http proxy via the grafana UI

#### Expected behavior

It should be possible to specify the proxy either when configuring the contact point/receiver or globally via environment variables.

#### Additional Context

It seems this was fixed recently in cortex as well, see: https://github.com/cortexproject/cortex/pull/4741

Setting HTTP(S)_PROXY env variables is a bad solution for this imho as the proxy is currently also used for replication between alertmanager instances in an HA deployment.

**Comment by replay** [comment]
I think this makes sense, would you be interested in creating a PR based on the solution in Cortex?

**Comment by supergicko** [comment]
> 

pr on the way 

https://github.com/grafana/mimir/pull/2050

br

**Comment by pracucci** [comment]
I prefer to not allow it by default, but I'm open to add an advanced configuration option to enable it (and mention it in the doc).

**Comment by pracucci** [comment]
> idk what "advanced configuration option" would mean in this context :/

In Mimir, each configuration option is classified either as `basic`, `advanced`, `experimental` or `deprecated`. See:
https://grafana.com/docs/mimir/next/operators-guide/configuring/reference-configuration-parameters/#parameter-lifecycle

The classification is very simple and it's just about adding a `category: "advanced"` to the related struct field. For example:
https://github.com/grafana/mimir/blob/dd1c12a018615a05b77c7bdc8fa85a0d3a9d326c/pkg/util/validation/limits.go#L70

Alertmanager's firewall config is currently per-tenant:
https://github.com/grafana/mimir/blob/dd1c12a018615a05b77c7bdc8fa85a0d3a9d326c/pkg/util/validation/limits.go#L131-L132

It would be great to make the proxy support config on a per-tenant basis too.

**Comment by supergicko** [comment]
Thx for clarification @pracucci 

My next q for guidance would be following,

assuming i set up limits like

`AlertmanagerReceiversAllowNoProxy          bool                     `yaml:"alertmanager_receivers_allow_no_proxy" json:"alertmanager_receivers_allow_no_proxy" category:"advanced"`
`

and define them in multitenant.go

`AlertmanagerReceiversAllowNoProxy(tenant string) bool`

Whats the best way to pass this down to the api in

https://github.com/grafana/mimir/blob/dd1c12a018615a05b77c7bdc8fa85a0d3a9d326c/pkg/alertmanager/api.go#L415

Passing down the limits to the generic function?

`func validateReceiverHTTPConfig(cfg commoncfg.HTTPClientConfig, limits Limits)`

which also would touch

https://github.com/grafana/mimir/blob/dd1c12a018615a05b77c7bdc8fa85a0d3a9d326c/pkg/alertmanager/api.go#L319

Updating the HTTPClientConfig just for this usecase?

Br

**Comment by supergicko** [comment]
after reading https://github.com/cortexproject/cortex/pull/4129#issuecomment-1120097455 and https://github.com/advisories/GHSA-m45g-f45x-vv22 again i am not sure if disabling setting the proxy_url when saving it via api is needed anymore. If you already disable via api the usage of "The HTTP basic auth password_file", then its ok regarding the CVE - or am i missing something? @replay @pracucci

**Comment by pracucci** [comment]
Thanks @supergicko for the follow up. You made me change my mind. What I didn't consider previously, is that the current "firewall" also protects requests to the HTTP proxy (I've added a test in https://github.com/grafana/mimir/pull/2076), so I think we can just always allow `proxy_url`.

**Comment by supergicko** [comment]
@pracucci great i will update the PR #2050 to allow it in all configs in alertmanager.

**Comment by pracucci** [comment]
>What I didn't consider previously, is that the current "firewall" also protects requests to the HTTP proxy (I've added a test in #2076), so I think we can just always allow `proxy_url`.

After further investigation, the OAuth2 HTTP `proxy_url` is not covered by our firewall, so I've keep it not allowed in #2317 for now.
