### ISSUE TITLE
Unexpected block meta version: 2

### ISSUE THREAD

**Issue by daper** [grafana/mimir#2049]
#### Describe the bug
Migration from prometheus to grafana/mimir. Following: https://grafana.com/docs/mimir/latest/migration-guide/migrating-from-thanos-or-prometheus. Data from migrated chunks not appearing on Mimir. Compactor logs the following error:

```text
level=error ts=2022-06-08T07:42:49.31886033Z caller=blocks_cleaner.go:162 component=cleaner msg="failed to run blocks cleanup and maintenance" err="failed to delete blocks for user: anonymous: unexpected block meta version: 01G4FNPGQ6SFW0Y2FEAJHACD37/meta.json version: 2"
```

The `meta.json`:
```json
{
	"ulid": "01G50M2BWY8HA8VV40QFCASTNW",
	"minTime": 1654646400000,
	"maxTime": 1654653600000,
	"stats": {
		"numSamples": 413540713,
		"numSeries": 1053478,
		"numChunks": 3474965
	},
	"compaction": {
		"level": 1,
		"sources": [
			"01G50M2BWY8HA8VV40QFCASTNW"
		]
	},
	"version": 2,
	"thanos": {
		"labels": {
			"__org_id__": "anonymous"
		},
		"downsample": {
			"resolution": 0
		},
		"source": ""
	}
}
```

#### To Reproduce
Followed the guide (no errors). Compactor starts to produce those errors.

#### Expected behavior

Data from old prometheus to appear on Mimir.

#### Environment

- Infrastructure: kubernetes(eks)
- Deployment tool: helm(mimir-distributed:2.1.0)
- Prometheus instance: `prom/prometheus v2.1.0 c8ecf7c719c1`
- Mimir version: `2.1.0`

**Comment by pstibrany** [comment]
> Hi @pstibrany, I've found [this](https://github.com/prometheus/prometheus/blob/4b9f248e8569fc5163841c2e21b8fa5d3a61b311/tsdb/block_test.go#L40) and I am going to change all version 2 json back to 1 to see if that works.

Thank you! That is good to know if more people run into this problem.

**Comment by daper** [comment]
Updated all the `meta.json`s changing version back to `1`worked: `successfully compacted user blocks`. But the chunks are way too bigger than the [maxSeriesSize](https://github.com/grafana/mimir/blob/6b5cc6a8449dedc3fd9c7f4453e7703f631bdc8a/pkg/storegateway/bucket.go#L74). I am going to explore other options (like [prom-migrator](https://github.com/timescale/promscale/blob/master/migration-tool/cmd/prom-migrator/README.md)).
