### ISSUE TITLE
Docs: document how remote write API works

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#2062]
We're seeing some people asking how they can build custom clients to write metrics to Mimir. There's foundamentally a lack of information on how the remote write API works in our documentation. We should explain:
- Purpose of the remote write API
- The request body format
- Link a reference implementation (e.g. in golang we could show https://github.com/grafana/mimir/blob/29142fc7ae465e31478483d818048070143ee688/pkg/continuoustest/client.go#L176)
- Write proxies (e.g. https://github.com/grafana/influx2cortex/) as an alternative to easily remote write to Mimir using simpler protocols

**Comment by osg-grafana** [comment]
Who are the SMEs (subject matter experts) for this topic?

**Comment by LeviHarrison** [comment]
No, not practically. The remote-write payload is a protobuf object which needs to be serialized.

**Comment by osg-grafana** [comment]
@pracucci, given the age of this issue and its staleness, is it still relevant?

**Comment by pstibrany** [comment]
Note that Prometheus has since published specification for the current remote write protocol: https://prometheus.io/docs/concepts/remote_write_spec/

This covers "The request body format" point.

**Comment by pracucci** [comment]
I'm happy with the Prometheus doc. I think for now there's no bandwidth into invest into this more than what Prometheus community already did.
