### ISSUE TITLE
Long heartbeat-period and unregister-on-shutdown=false cause slowdown during rollout of ingesters

### ISSUE THREAD

**Issue by pstibrany** [grafana/mimir#2074]
#### Describe the bug

Using long `-ingester.ring.heartbeat-period` together with `-ingester.ring.unregister-on-shutdown=false` slows down rollout of ingesters due to bug https://github.com/grafana/dskit/issues/174 in dskit.

**Comment by pracucci** [comment]
Fixed by https://github.com/grafana/mimir/pull/2085.
