### ISSUE TITLE
Report more relevant info (only the configured limit and burst) when -distributor.request-rate-limit or -distributor.ingestion-rate-limit is exceeded

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#2082]
The question https://github.com/grafana/mimir/discussions/2081 made me realise that when `-distributor.ingestion-rate-limit` is hit, we report the local per-distributor limit, instead of a the global (configured) one. We should report the global one, otherwise it's too confusing for the user.

**Comment by zenador** [comment]
This applies to `-distributor.request-rate-limit` as well, and we will remove unnecessary info about the number of items sent right when hitting the limit.
