### ISSUE TITLE
Slow queries dashboard is not supported by grafana 9

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2119]
#### Describe the bug

Slow queries dashboard does not work on grafana 9.0. Table columns are conflated and the dashboard only shows raw log lines.

This is due to a breaking change to the `loki-data-format`. quoting @gabor 

> if you use the `labels to fields` transform, replace it with the `extract fields` transform, and choose the `labels` field in it.
> you can probably remove the `merge` transform
> if you need to keep the same dashboard-json for both grafana8 and grafana9, that will not be possible

#### To Reproduce

1. Import slow queries dashboard into grafana v9.0.0 (b5c56f637)
2. Connect to data source with mimir logs

![Screenshot 2022-05-20 at 11 02 46](https://user-images.githubusercontent.com/21020035/174050888-149b2a27-aa19-4ebc-8a36-649676e0041f.png)

#### Expected behavior

![Screenshot 2022-05-20 at 11 03 02](https://user-images.githubusercontent.com/21020035/174050619-bfa19871-d915-48c7-861a-532137fbe321.png)

#### Environment

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
- Deployment tool: [e.g., helm, jsonnet]

**Comment by pracucci** [comment]
@dimitarvdimitrov Could you report to Grafana too? Theoretically, Grafana should be backward compatible (unless they documented a breaking change).

**Comment by dimitarvdimitrov** [comment]
The breaking chagnge is documented in the [release notes](https://grafana.com/docs/grafana/latest/release-notes/release-notes-9-0-0/)

> In the Loki data source, the dataframe format used to represent Loki logs-data has been changed to a more efficient format. The query-result is represented by a single dataframe with a “labels” column, instead of the separate dataframes for every labels-value. When displaying such data in explore, or in a logs-panel in the dashboard will continue to work without changes, but if the data was loaded into a different dashboard-panel, or Transforms were used, adjustments may be necessary. For example, if you used the “labels to fields” transformation with the logs data, please switch to the “extract fields” transformation. Issue [#47153](https://github.com/grafana/grafana/issues/47153)
