### ISSUE TITLE
Remove -ruler.query-frontend.timeout and use -querier.timeout instead

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#2129]
https://github.com/grafana/mimir/pull/2090 introduced `-ruler.query-frontend.timeout`. We're trying to reduce config options, so an alternative option could be reusing `-querier.timeout`, documenting that needs to be set for ruler too when remote rule evaluation is used. We already use `-querier.timeout` in query-frontend too.

**Comment by pstibrany** [comment]
I think we should fix this before 2.2 release, so that we don't release new flag (`-ruler.query-frontend.timeout`) to the world.

**Comment by stevesg** [comment]
Doing it now :)
