### ISSUE TITLE
Docs: Migrate getting started related content from README.md file to Getting started guide

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#2141]
[Grafana Mimir Helm Chart - README.md](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/README.md)

Mimir and GEM install instructions do reference parts of this README.md!

**Comment by osg-grafana** [comment]
Relates to https://github.com/grafana/mimir-squad/issues?q=is%3Aopen%20is%3Aissue%20project%3Agrafana%2F83.

**Comment by krajorama** [comment]
For references on the README, see for example: https://github.com/grafana/backend-enterprise/pull/3471

**Comment by mattmendick** [comment]
Contained in #2181
