### ISSUE TITLE
Helm deployed Mimir distributed nginx location block missing /api/v1/read

### ISSUE THREAD

**Issue by cgill27** [grafana/mimir#2171]
#### Describe the bug
In the nginx location blocks there is no /api/v1/read location for Prometheus remote read, for Helm deployed Mimir distributed

#### To Reproduce

1. Helm deploy mimir-distributed
2. Configure Prometheus or other client for remote read to Mimir endpoint
3. View logs in grafana-mimir-nginx pod, you'll see 404 errors for remote reads to /api/v1/read

#### Expected behavior

Prometheus should be able to point to Mimir endpoint to be able to do both remote_read aswell as remote_write

#### Environment

- Infrastructure: kubernetes/EKS 1.21
- Deployment tool: helm mimir-distributed 2.0.0

#### Additional Context

022/06/21 22:10:23 [error] 9#9: *8361 open() "/etc/nginx/html/api/v1/read" failed (2: No such file or directory), client: 10.0.2.226, server: , request: "POST /api/v1/read HTTP/1.1", host: "xxxxx │
│ 10.0.2.226 - - [21/Jun/2022:22:10:23 +0000]  404 "POST /api/v1/read HTTP/1.1" 154 "-" "Prometheus/2.36.1" "10.0.1.28"                                                                                            │
│ 2022/06/21 22:10:23 [error] 9#9: *8361 open() "/etc/nginx/html/api/v1/read" failed (2: No such file or directory), client: 10.0.2.226, server: , request: "POST /api/v1/read HTTP/1.1", host: "xxxxx │
│ 10.0.2.226 - - [21/Jun/2022:22:10:23 +0000]  404 "POST /api/v1/read HTTP/1.1" 154 "-" "Prometheus/2.36.1" "10.0.1.28"                                                                                            │
│ 2022/06/21 22:10:23 [error] 9#9: *8361 open() "/etc/nginx/html/api/v1/read" failed (2: No such file or directory), client: 10.0.2.226, server: , request: "POST /api/v1/read HTTP/1.1", host: "xxxxx │
│ 10.0.2.226 - - [21/Jun/2022:22:10:23 +0000]  404 "POST /api/v1/read HTTP/1.1" 154 "-" "Prometheus/2.36.1" "10.0.1.28"

**Comment by krajorama** [comment]
Reference document: https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#remote-read

**Comment by cgill27** [comment]
Hello Josh,

I switched prometheus remote_read to the endpoint /prometheus/api/v1/read and all is good, working fine!
Thx!
