### ISSUE TITLE
Docs: Create "Prepare for production" Helm chart

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#2181]
@mattmendick commented on [Wed Jun 22 2022](https://github.com/grafana/mimir-squad/issues/714)

Note: There are no internal comments via the preceding link; this issue was simply moved from one repo to another.
Audience:
- expectations on the user from getting started guide
Topics:
- pre-requisites (number of nodes, memory, etc)
- sizing (small, large yamls)
- metamonitoring
- external storage
  - minio is not supported and also doesn't work with restricted policy
  - different types, what to set for each
  - refer to https://grafana.com/docs/mimir/latest/operators-guide/running-production-environment-with-helm/configuration-with-helm/
- security

This issue overlaps with https://github.com/grafana/mimir/issues/2141 

Stretch goal: also refer to / incorporate information about how to set up the external storage itself (ask @patrickabrennan )

**Comment by dimitarvdimitrov** [comment]
I'm sharding this outline as I'm starting to write the article. Feedback is welcome (@osg-grafana 👀). 

I'm starting to realize that most of the information already exists in other articles, so this article will be to a large extent a hub which pieces together other articles.

* introduction
	* what does "production" refer to? what's the expected outcome after reading this article? point to "Getting started with Grafana Mimir with Helm" guide
	* explain main differences between the setup in "Getting started" guide and the setup here
* independant instructions sections
	* migrating from cortex or prometheus/thanos
		* link to migration guides (update those migration guides too, since they contain some outdated instructions for helm)
	* capacity planning
		* see "Planning Grafana Mimir capacity" article; mention existing sizing plans for 1M and 10M AS
			* add to that article with some advice on scaling the caches
		* mention podAntiAffinity rules and needing one node per ingester/store-gateway
		* mention zone-aware replication and point to doc for that (will be broken link for now)
	* object storage
		* mention minio is not supported
		* point to "Manage the configuration of Grafana Mimir with Helm"
		* point to "Configure Grafana Mimir object storage backend"
	* security
		* talk about PodSecurityPolicies and Pod Security Standards
	* metamonitoring
		* point to setting up the dashboards and setting up the agent operator
	* setting up clients to remote-write
		* point to section in "Getting started guide" for setting this up
	* setting up HA dedup with consul
		* point to yet unpublished article

**Comment by dimitarvdimitrov** [comment]
we just worked through the editing process of the article with @osg-grafana, I think it's turning into a great resource for our opensource users
