### ISSUE TITLE
Move purger API endpoint to another component

### ISSUE THREAD

**Issue by wilfriedroset** [grafana/mimir#2190]
#### Is your feature request related to a problem? Please describe.

The component "purger" is only responsible for exposing 2 [API endpoints](https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#purger). When called mimir will upload a marker in the bucket which will ultimately trigger the purge of the data. Apart from this the purger does nothing else.

#### Describe the solution you'd like

Migrate the purger to another component, the compactor for example.

#### Describe alternatives you've considered

To achieve the same behavior we could enable the module along with another one

```yaml
target: compactor,purger
```

#### Additional context

In a not monolithic deployment this help save resource (pod or instance)
General idea come from slack channel: https://grafana.slack.com/archives/C039863E8P7/p1655914578345719

**Comment by pracucci** [comment]
I agree compactor is a good component to host the purger API.
