### ISSUE TITLE
Helm: remove redundant service definitions

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#2193]
#### Is your feature request related to a problem? Please describe.

alertmanager, distributor, ingester, query-frontend, store-gateway have both clusterIp and headless services defined.

#### Describe the solution you'd like

Reduce the number of services if possible.

#### Describe alternatives you've considered

N/A

#### Additional context

Related to https://github.com/grafana/helm-charts/issues/1307

**Comment by krajorama** [comment]
Turns out that multizone #2778  will require two kind of service. One service per statefulset and an overall (headless) service for routing from nginx/gateway.

**Comment by Logiraptor** [comment]
Rather than this, let's document what counts as a breaking change and then maybe one day we can remove services that are not part of the compatibility guarantee: https://github.com/grafana/mimir/issues/2246

**Comment by mattmendick** [comment]
Closing this because of @Logiraptor's comment
