### ISSUE TITLE
Helm: remove annoying log message about alertmanager ignoring activity tracker log

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#2194]
#### Describe the bug
Logs contain:
```
  | 2022-06-22 08:21:30 | level=warn ts=2022-06-22T06:21:30.226797919Z caller=multitenant.go:1187 component=MultiTenantAlertmanager msg="ignoring unexpected file while scanning local alertmanager configs" file=/data/metrics-activity.log
-- | -- | --
```

#### To Reproduce

1. Start Mimir from Helm and look at alertmanager logs (or set up metamonitoring and look into loki)
See https://grafana.com/docs/mimir/latest/operators-guide/deploy-grafana-mimir/getting-started-helm-charts/

#### Expected behavior

This message should not appear in the logs.

#### Environment

- Infrastructure: Kubernetes 1.20+
- Deployment tool: helm (v 3.0+)

#### Additional Context

We moved setting the activity tracker from command line to the configuration for consistency, but it means that changing it affects **all** mimir/GEM pods!!!

#### Proposed solution

Add a new volume to each POD (including gateway/admin-api)
```
      - name: active-queries
        emptyDir: {}    
```

which is mounted on
```
        - name: active-queries
          mountPath: /active-query-tracker
```

for each pod.

Change mimir.config to have
```
    activity_tracker:
      filepath: /active-query-tracker/activity.log
```

instead of
```
    activity_tracker:
      filepath: /data/metrics-activity.log
```

**Comment by krajorama** [comment]
hi,

just checked where the activity tracker is located in our  jsonnet based deployments.

There we have a volume:
```
      - name: active-queries
        emptyDir: {}    
```

which is mounted on
```
        - name: active-queries
          mountPath: /active-query-tracker
```

for each pod.

And therefore the value in mimir.config contains:
```
    activity_tracker:
      filepath: /active-query-tracker/activity.log
```

instead of
```
    activity_tracker:
      filepath: /data/metrics-activity.log
```

@goelankitt  let me get some feedback on this internally

**Comment by Logiraptor** [comment]
I think @krajorama's  solution makes sense. Essentially we would move the activity tracker log to a different volume in the Helm chart to avoid it ending up in a data volume.

**Comment by valdemarpavesi** [comment]
Thanks for looking into it.
![image](https://user-images.githubusercontent.com/10376101/177670844-9b68f566-6312-46d1-985f-ab1b773e8e48.png)

**Comment by valdemarpavesi** [comment]
It will work too:
![image](https://user-images.githubusercontent.com/10376101/177674567-d6eeeb52-27c5-492c-940e-27831bfe011b.png)

pod:
/data/tenant # ls
anonymous
/data/tenant # 

no more error:
![image](https://user-images.githubusercontent.com/10376101/177674745-177aa41d-654e-47b8-97f6-d5af22765417.png)
