### ISSUE TITLE
"connection reset by peer" errors during load testing

### ISSUE THREAD

**Issue by zenador** [grafana/mimir#2224]
#### Describe the bug

Under load testing of 100M active series for 24 hours in an Azure cluster, K6 reports "connection reset by peer" errors about 0.21% of the time. [Similar problems have been observed during nginx-ingress rollouts](https://github.com/grafana/mimir/issues/2225), but it also happens when there's no such rollout.

#### To Reproduce

1. Run a similar load test with https://github.com/grafana/mimir/blob/main/operations/k6/load-testing-with-k6.js

#### Expected behavior

No such errors should appear.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: jsonnet

##### Hypothesis 1

Routing is: K6 → Azure LB → ingress-nginx K8S service → nginx-ingress pod → Mimir cloud-gateway

The Azure LB has few rules configured. K6 script is using HTTPS protocol to connect to Mimir, so it uses the “[a7114c443295f481f84db119c22d1094-TCP-443](https://portal.azure.com/#view/Microsoft_Azure_Network/LoadBalancerRulesBladeViewModelV2/loadBalancerId/%2Fsubscriptions%2F44693801-6ee6-49de-9b2d-9106972f9572%2FresourceGroups%2Fmc_prod-eu-west-3-rg_prod-eu-west-3_westeurope%2Fproviders%2FMicrosoft.Network%2FloadBalancers%2Fkubernetes/loadBalancerRuleId/%2Fsubscriptions%2F44693801-6ee6-49de-9b2d-9106972f9572%2FresourceGroups%2Fmc_prod-eu-west-3-rg_prod-eu-west-3_westeurope%2Fproviders%2FMicrosoft.Network%2FloadBalancers%2Fkubernetes%2FloadBalancingRules%2Fa7114c443295f481f84db119c22d1094-TCP-443)” LB rule. This rule is configured with:
Idle timeout: 4 minutes
TCP reset: enabled ([what’s this and why it matters](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-reset))

We need HTTP idle / keepalive timeouts to be set in a cascading fashion, with lowest timeout in the LB and then increasing bigger timeouts in the chain of downstream hops. Currently, we have these idle / keepalive timeouts set:
Azure LB: 4 minutes
Nginx-ingress-controller: 60 seconds checked on the actual config in a ingress pod ([keepalive_timeout](https://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout))
Cortex-gateway: 620s (10m 20s)

The reason why we get “connection reset by peer” is because the LB sends the HTTP request to a TCP connection which is already closed by nginx, due to the keepalive timeout being lower than the Azure LB idle timeout.

###### Action items

- Try to verify the hypothesis:
  - Ensure no other client is issuing requests
  - Create a connection, run http request, nginx response with “Connection: keep-alive”
  - Wait 70 seconds
  - Run another http request and see the actual response. Ensure the previous LB → nginx connection was reused.
- Experiment setting nginx-ingress-controller keepalive_timeout to 5 minutes

##### Hypothesis 2

K6 client could be configured with a keepalive timeout greater than 4m. If so, the “connection reset by peer” we see on the K6 side could be caused by the TCP reset sent by the LB on an idle connection. The client would realize it only once it try to send the next request. See [Azure LB TCP reset doc](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-reset) for more details.

###### Action items

- Investigate if this is feasible

**Comment by pracucci** [comment]
_This not related to Mimir, but specific deployment. I talked offline to @zenador and I'm going to close it._
