### ISSUE TITLE
"connection reset by peer" errors during nginx-ingress rollout

### ISSUE THREAD

**Issue by zenador** [grafana/mimir#2225]
#### Describe the bug

K6 reports "connection reset by peer" during nginx-ingress rollouts.

#### To Reproduce

1. Rollout changes to nginx-ingress

#### Expected behavior

No such errors should appear.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: jsonnet

#### Additional Context

N/A

#### Action Items

- We should investigate if we can drain nginx at shutdown in a graceful way, in order to reduce the failed requests when rolling out changes to nginx-ingress.
- Alternatively, we should consider not using nginx-ingress at all.

**Comment by pracucci** [comment]
_This not related to Mimir, but specific deployment. I talked offline to @zenador and I'm going to close it._
