### ISSUE TITLE
Introduce a limit on "max inflight requests size"

### ISSUE THREAD

**Issue by zenador** [grafana/mimir#2226]
#### Is your feature request related to a problem? Please describe.

Distributors have a limit on number of inflight requests which was introduced to protect them from going OOM under high load. The limit is based on "max number of requests" which doesn't take into account the size of each request, so it doesn’t translate easily to "max memory utilization".

#### Describe the solution you'd like

Introduce a limit on "max inflight requests size" based on the estimated size of each request (in bytes).

#### Additional context

Without this limit, during load testing we had a write path outage caused by distributors getting OOMKilled.

**Comment by dimitarvdimitrov** [comment]
* we can use the Content-Length of the request to keep a running sum of the inflight requests. For those without we can do an estimation. For the estimation: aiming to keep config minimal, WDYT about look at the average of the last `1000` requests and using that as a prediction?

* I want to avoid making the config option(s) too hard to tune. Or to retune. Is it a bad idea to read `/proc/memstat` and parse how much memory the process has? I'm thinking of setting the max inflight requests size as a percentage of the total available memory to the process (between 0 and 1). This will make it still valid after scale ups and scale downs. It will also allow us to give some advice on a healthy value that everyone can use. (And if we know a healthy value, should that even be configurable...? maybe we can remove the option in the future when we know the healthy value)

**Comment by 56quarters** [comment]
> * For the estimation: aiming to keep config minimal, WDYT about look at the average of the last `1000` requests and using that as a prediction?

I wouldn't even go that far. I think it would be easier to reason about to just have a default size hardcoded if the request doesn't include `content-length`. We could base it on the size of a default Prometheus or Agent remote write request.

**Comment by pracucci** [comment]
> we can use the Content-Length of the request

I don't fully understand at which level you want to build it, but I was thinking to do it in the `Distributor.PushWithCleanup()` handler, checking the size of `req *mimirpb.WriteRequest`.

> I want to avoid making the config option(s) too hard to tune

I would keep the discussion separated. As first step, we should have a config field like others. Discussion about self tuning should separated (and it's way more complicated).

**Comment by pracucci** [comment]
> I think it would be easier to reason about to just have a default size hardcoded if the request doesn't include content-length. We could base it on the size of a default Prometheus or Agent remote write request.

I don't want any default size. I just want to read the request body, and base it on the real request. Also keen in mind at Grafana Cloud the write path from gateway to distributor uses gRPC (not HTTP).

**Comment by dimitarvdimitrov** [comment]
> I don't fully understand at which level you want to build it, but I was thinking to do it in the `Distributor.PushWithCleanup()` handler, checking the size of `req *mimirpb.WriteRequest`.

I was thinking of doing it in [`push.Handler`](https://github.com/grafana/mimir/blob/0ef94db02f838c72c8d5e19afec4d57ac591a32a/pkg/util/push/push.go#L39). That has access to the request size.

Isn't PushWithCleanUp too late? Most of the memory for that request is probably already allocated, why reject it then?

**Comment by dimitarvdimitrov** [comment]
or not. let's do the simple thing first

**Comment by bboreham** [comment]
Copied from https://github.com/grafana/mimir/pull/2413#issuecomment-1203788216; I had roughly the same idea as @dimitarvdimitrov:
Empirically this number lags the actual memory consumption.  I suspect that computing it after protobuf decoding is part of the problem; the size is known after 
https://github.com/grafana/mimir/blob/8e900c2e97dace35bb521cf98749fecf54d6114c/pkg/util/http.go#L151

but you could actually reduce `maxSize` to the gap between the currently-tracked size and the limit, thus apply the limit before full decompression.

(and then do equivalent things on the OTEL path)
