### ISSUE TITLE
Enable Thanos Azure client to pass object size when known

### ISSUE THREAD

**Issue by zenador** [grafana/mimir#2231]
#### Is your feature request related to a problem? Please describe.

For each API request to the object storage (counted in `thanos_objstore_bucket_operations_total` metric), the Thanos Azure client makes an additional GetBlobProperties call to retrieve the object size, causing a discrepancy between the number of requests reported by Azure and the previous metric, which is problematic as we bill based on number of requests.

This is also caused by https://github.com/grafana/mimir/issues/2232

#### Describe the solution you'd like

Improve the Thanos Azure client implementation to optionally pass the object size when known so we can avoid an unnecessary GetBlobProperties call. Most of our objects are immutable and this could be cached in-memory as we already do in the chunks cache implementation.

#### Additional context

For each Get() and GetRange() call to Thanos Azure client, we call GetProperties() to get the size of the object:
https://github.com/thanos-io/thanos/blob/ce84ec521c99493e98fb17ec4bb1358b56a68ebb/pkg/objstore/azure/azure.go#L319-L323

**Comment by pracucci** [comment]
This could be address by the work @56quarters is currently testing to reduce Azure client memory utilisation when downloading an object.

**Comment by pracucci** [comment]
An alternative way to do it, is removing the need to have the Thanos azure client knowing the object size, which is what https://github.com/thanos-io/thanos/pull/5451 is doing.

**Comment by pracucci** [comment]
No more required, because #2408 has removed the call to fetch object attributes at all.
