### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by colega** [grafana/mimir#2241]
I'm going to start the release process for the 2.2.0 version, and going to use this issue to group the tasks.

- [x] Release notes by @pstibrany https://github.com/grafana/mimir/pull/2221
  - can be merged into release-2.2 branch later, we can use draft version for RC
- [x] OOO Docs https://github.com/grafana/mimir/pull/2183
- [x] https://github.com/grafana/mimir/issues/2238
- [x] https://github.com/grafana/mimir/issues/2258
  - [x] Fixed in https://github.com/grafana/mimir/pull/2273, but not yet merged to `main`

Wishlist (@pstibrany):
- [x] https://github.com/grafana/mimir/pull/2122
- [x] https://github.com/grafana/mimir/pull/2216

**Comment by pstibrany** [comment]
rc.0 released: https://github.com/grafana/mimir/releases/tag/mimir-2.2.0-rc.0

**Comment by wilfriedroset** [comment]
Do you think it would be possible to add the packaging for this release or the next 🙏🏾?
I've a PR https://github.com/grafana/mimir/pull/1803 wait for review

**Comment by pstibrany** [comment]
> Do you think it would be possible to add the packaging for this release or the next 🙏🏾?

I am afraid we won't have time for a proper review before Mimir 2.2. We should aim for next release.
