### ISSUE TITLE
Alertmanager state is not restored from remote storage if replicationFactor == 1

### ISSUE THREAD

**Issue by callumj** [grafana/mimir#2245]
#### Describe the bug
Alertmanager state is not restored from remote storage if replicationFactor == 1: https://github.com/grafana/mimir/blob/main/pkg/alertmanager/state_replication.go#L205

I understand that running replicationFactor at 1 is a bad idea but for dev or staging environments it usually makes sense to keep things simple or cut down on costs.

I was wondering if this is intentional that we skip reading from storage in these cases?

#### To Reproduce

1. Run Alertmanager with replicationFactor of 1
2. Post an alert to AM
3. Kill the AM process
4. Observe state is not restored from storage

#### Expected behavior

State should be read from storage if no replication option is available

#### Environment

- Infrastructure: k8s
- Deployment tool: manual

**Comment by 56quarters** [comment]
Looking at the change that introduced this, it seems like a bug to me too: https://github.com/grafana/mimir/commit/7896c435e0dfee58a2a61de329b5e32241cb3305

**Comment by 56quarters** [comment]
Actually, looks like it was a combination of the following PRs:
* https://github.com/cortexproject/cortex/pull/3925
* https://github.com/cortexproject/cortex/pull/4021

I'll have something that should fix this up for review shortly.

**Comment by stevesg** [comment]
Good spot - the bug is that we should jump [here](https://github.com/grafana/mimir/blob/08a94862029980e439752d6d7c839a2f232033d2/pkg/alertmanager/state_replication.go#L238) if RF==1.
