### ISSUE TITLE
Improve ruler error message when fails to send notification to alertmanager because not configured

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#2265]
The issue https://github.com/grafana/mimir/issues/2244 made me realize that when the ruler fails to send an alerting notification to the Alertmanager because the Alertmanager is not configured, the ruler logs this confusing error:

`alertmanager=http://<cluster-ip>.mimir-alertmanager-headless.monitoring.svc.cluster.local.:8080/alertmanager/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"`

The error message `bad response status 404 Not Found` makes think that the API endpoint doesn't exist (e.g. it's not configured correctly), but 404 is also returned by the Alertmanager if no configuration is found for the tenant.

The error is logged by the upstream Prometheus ruler, which we have no control over:
https://github.com/prometheus/prometheus/blob/0c3abdc26d4cd2e44549b122799c652c9796f8d8/notifier/notifier.go#L524

A simple improvement could be:
1. Return a different HTTP status code from Alertmanager when configuration is missing. Instead of 404, we could return a simple "400 Bad Request" or 412 "Precondition Failed" or... better ideas?
2. In the alertmanager, we could log an info log whenever an API endpoint is called for a tenant but the configuration is missing, suggesting what to do about it.

**Comment by winston0410** [comment]
@pracucci I have came across the exact same log in my Prometheus server when it tried to push alert to Grafana Cloud. I don't think I have access to Grafana's log, which makes debugging difficult. Do you mind explaining this error, if you still have that in your memory?
