### ISSUE TITLE
Helm: mimir-distributed value `externalConfigVersion` must be quoted when rendered

### ISSUE THREAD

**Issue by pdf** [grafana/mimir#2296]
#### Describe the bug
The default `externalConfigVersion` value is `'0'`, which suggests that numeric values as strings should work correctly, however the value is rendered unquoted by the template helper, resulting in the following output:

```yaml
annotations:
  checksum/config: 0
```

Annotation values _must_ be strings.

#### To Reproduce

1. Deploy `mimir-distributed` helm chart with `useExternalConfig: true`.
2. Deployment is rejected due to malformed annotations.

#### Expected behavior

The `externalConfigVersion` value should be rendered enclosed in quotes:

```yaml
annotations:
  checksum/config: "0"
```

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

#### Additional Context

Helm error:
```
failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field ObjectMeta.spec.template.metadata.annotations of type string
```

**Comment by nasirudheen** [comment]
Facing the same issue here. Is there any work around ?

**Comment by pdf** [comment]
Yes, you can use a value that can only be interpreted as stringish, ie - `aaa` instead of `'0'`

**Comment by nasirudheen** [comment]
But `checksum/config`  is autogenerated. So will have to modify the templates, right ?

**Comment by pdf** [comment]
This issue only applies when you have `useExternalConfig` enabled, in which case the value of `externalConfigVersion` is used verbatim in the annotation. Otherwise, the annotation contains a hash of the config contents, which should be a long string value, though quoting the hash wouldn't hurt either.

**Comment by nasirudheen** [comment]
Ohhh...Thanks indeed for that ! I quoted the externalConfigVersion with some strings and it works !
Appreciate your help !

**Comment by ToonTijtgat2** [comment]
+1

**Comment by dimitarvdimitrov** [comment]
I am not convinced this should be a concern of the mimir-distributed chart. This is a general rule for kubernetes annotations (See first `Note` in [docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#attaching-metadata-to-objects)). I don't think you should get different validation for annotations on an nginx deployed via this chart vs an nginx deployed via any other chart.

**Comment by pdf** [comment]
@dimitarvdimitrov you misunderstand the problem - when a string value is provided that contains content that can be interpreted as a number, it is rendered as numeric, not as the original string..

**Comment by dimitarvdimitrov** [comment]
thanks for clarifying; i opened  a PR to fix this https://github.com/grafana/mimir/pull/6407
