### ISSUE TITLE
Docs: Enhance out-of-order documentation

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#2305]
There is some internal training being drafted by @jesusvazquez and @codesome that will be added to the technical documentation for Mimir.

This documentation needs to incorporate best practices based on information type: concept, task, reference. Ursula can help with that.

**Internal** link: https://docs.google.com/document/d/10lsCkiKx3pXjFk1oFOFjSqeXhQjRxr5ldHoE_52MqHA/

**Comment by codesome** [comment]
Here is the PR for this https://github.com/grafana/mimir/pull/2331
