### ISSUE TITLE
Allow configuring block storage everywhere from a common place

### ISSUE THREAD

**Issue by colega** [grafana/mimir#2319]
#### Is your feature request related to a problem? Please describe.

Currently block storage configuration is spread across different components and it requires an extra effort to identify and configure them all.

#### Describe the solution you'd like

Loki [has a `common` configuration block](https://grafana.com/docs/loki/latest/configuration/#common) for all services that [has a `storage`](https://grafana.com/docs/loki/latest/configuration/#storage) configuration key. 

Configuring an object storage in the `common.storage` key [applies that configuration to all the specific components, unless specific configurations were provided](https://github.com/grafana/loki/blob/7314d95a91d473bc285109b876515a08707e6b24/pkg/loki/config_wrapper.go#L415-L508).

We can try doing the same approach.

I would also mark the specific storage configurations as `advanced` options once there's a common configuration.

#### Describe alternatives you've considered

We could also completely drop the specific configurations, but that removes flexibility (what if I want to store recording rules on S3 but my blocks are on a local Minio?)

**Comment by pracucci** [comment]
> Loki [has a common configuration block](https://grafana.com/docs/loki/latest/configuration/#common) for all services that [has a storage](https://grafana.com/docs/loki/latest/configuration/#storage) configuration key.

I would have expected the `type` (which in Mimir is called `backend`) to be part of the common config too. I think it should be in Mimir.

**Comment by pracucci** [comment]
> I would also mark the specific storage configurations as advanced options once there's a common configuration.

The bucket name shouldn't be, because in Mimir (with the default config) we still require that blocks and ruler/alertmanager buckets to be different.

**Comment by pracucci** [comment]
We should also update our doc as part of this work.

**Comment by colega** [comment]
> we still require that blocks and ruler/alertmanager buckets to be different.

Do we have an issue/plan to solve that?

**Comment by colega** [comment]
I just saw the bucket prefix, and I agree that it's risky, but we have to do it some day maybe? 
What if we take this opportunity to set it to default blocks/ and `rules/` when common config is configured? 

People who would be changing to the `common/` config have to do an explicit change, so that would be a first step.

OTOH, I'd also consider requiring an explicit empty value for the prefix, that would make the change less risky: we wouldn't assume anything.
