### ISSUE TITLE
Errors on Tutorial play-with-grafana-mimir `docker compose up`

### ISSUE THREAD

**Issue by brettpalmberg** [grafana/mimir#2374]
#### Describe the bug

Good afternoon. Following the Mimir tutorial no longer results in a running Mimir cluster on `docker compose up`.  I believe this may be related to https://github.com/grafana/mimir/pull/2330.  Screen-capture of relevant error messages is below.

![image](https://user-images.githubusercontent.com/29417036/178354527-82a6fc80-b4ca-460c-91e6-8895d650445e.png)

#### To Reproduce

https://grafana.com/tutorials/play-with-grafana-mimir/?pg=oss-mimir&plcmt=hero-btn-1

#### Expected behavior

`docker compose up --build` or `docker-compose up` results in running Mimir cluster.

#### Environment

- Infrastructure: Laptop MacOS
- Deployment tool: Docker / Docker Compose

**Comment by aknuds1** [comment]
I can reproduce the issue, thanks for reporting!

**Comment by colega** [comment]
This should be fixed now, sorry for the inconveniences.

You should be able to pull the latest `main` (try just typing `git pull origin main` in your repository) to fix your local copy.

**Comment by brettpalmberg** [comment]
Thank you @aknuds1, @colega!  Confirmed, this is working now.
