### ISSUE TITLE
[After releasing 2.3] Use `common` config in the tutorial

### ISSUE THREAD

**Issue by colega** [grafana/mimir#2377]
## Context

Tutorial uses the `latest` Mimir version, which means that it won't support [`common` config block](https://github.com/grafana/mimir/pull/2330) until `2.3.` is released.

## Action

Once Mimir `2.3` is released (not in `release-2.3` branch! as that happens before), we should start using the `common` config block by reverting this PR: https://github.com/grafana/mimir/pull/2376

**Comment by 09jvilla** [comment]
Also note I created https://github.com/grafana/mimir/issues/2808 with some more docs requests :)
