### ISSUE TITLE
Docs: Document TSDB block upload feature

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#2383]
Partial work is in the following PRs:
* #2281 
* tbd

**Comment by pracucci** [comment]
mimirtool will be documented in https://github.com/grafana/mimir/pull/2481. @pstibrany is anything else left to document after #2481 will be merged?

**Comment by pstibrany** [comment]
> mimirtool will be documented in #2481. @pstibrany is anything else left to document after #2481 will be merged?

Not at the moment. Once we add validation and (hopefully/possibly) index rewrite for Thanos labels, there will be likely some minor updates.

**Comment by osg-grafana** [comment]
This issue looks like a NOP. Please re-open if there is more work to be done.
