### ISSUE TITLE
Docs: Play with Grafana Mimir guide was out-of-date

### ISSUE THREAD

**Issue by hi-rustin** [grafana/mimir#2403]
1. The `Configure your first recording rule` section completely out of date and many fields have been changed
2. The `Configure your first alert rule` section completely out of date and many fields have been changed
3. we shouldn't recommend users to `docker-compose down` because we start with `docker-compose up` instead of `docker-compose up -d`

**Comment by pracucci** [comment]
Thanks for opening this issue! Do you mean it's out of date for Grafana 9? The tutorial was written with Grafana 8 originally.

**Comment by pracucci** [comment]
We should keep running Grafana 9 and update the tutorial. Would be great if you could help us! ❤️
