### ISSUE TITLE
Docs: Helm migration guide from 3.0 to 4.0

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#2455]
#### Is your documentation request related to a feature? If so, which one?

https://github.com/grafana/mimir-squad/issues/731

#### Describe the solution that you’d like or the expected outcome

Document the upgrade procedure from Helm chart version 3.0 to 4.0.

We expect the bulk of it to relate to multi zone migration.

**Comment by mattmendick** [comment]
Majority of this documentation is included in multi-zone PR already (#2778), closing this.
