### ISSUE TITLE
Improve memory utilization in dashboards and alerts

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#2466]
Mimir dashboards and alerts use `container_memory_working_set_bytes` metric to monitor the Mimir process memory utilization, in particular with regards to the configured cgroup memory limit.

Running Mimir in production at Grafana Labs we learned that it's true that when the `working_set` memory hits the limit, the process gets killed, but until then there are some cases where the `working_set` memory shows a value which is significantly inflated by cache page (in particular due to the extensive mmap usage ingesters and store-gateways do).

For example, the following screenshot shows an ingester being OOMKilled at `08:11`. As you can see, the process gets killed once the `working_set` hits the limit. However, before that all mmap pages are freed to make more room (until green and blue lines match):
![Screenshot 2022-07-19 at 15 55 27](https://user-images.githubusercontent.com/1701904/179767934-683a9726-e5cf-4ea1-9f31-cc1dc0ab6cb8.png)

Since the cache pages can be released any time from the kernel under memory pressure, just looking at `working_set` utilization may be deceiving as an indicator on how close the process is to get OOMKilled.

_In this issue I'm going to discuss alternatives metrics to monitor the memory utilization._

## Option: `working_set - mapped_file`

cAdvisor reports the `working_set` memory as `usage - inactive_file` ([code](https://github.com/google/cadvisor/blob/50b23f4ed9bc53cf068316b67bee04c4145f1e73/container/libcontainer/handler.go#L862-L870)). The source statistics are exported by the cgroup ([doc](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt)), specifically:
- `memory.usage_in_bytes`: show current usage for memory
- `inactive_file`: # of bytes of file-backed memory on inactive LRU list

It also exposes the amount of memory in mmap-ed pages:
- `mapped_file`: # of bytes of mapped file (includes tmpfs/shmem)

We may consider to use `working_set - mapped_file`, which looks working in the screenshot above, but doesn't look working in the following case (store-gateway), where it gets negative:

![Screenshot 2022-07-19 at 16 06 11](https://user-images.githubusercontent.com/1701904/179770447-40909c79-a4b2-4a5c-81db-cca8e11ff2b8.png)

My theory is that `inactive_file` could actually include some pages from `mapped_file`, so given `working_set = usage - inactive_file` with `working_set - mapped_file` we end up subtracting the inactive mapped pages twice.

## Option: `usage - cache`

An option may be using `usage - cache`, which looks not suffering the "double counting issue" (described above) and hitting the limit when the process gets OOMKilled.

Case 1 - ingester OOMKilled at `08:11`:
![Screenshot 2022-07-19 at 16 13 40](https://user-images.githubusercontent.com/1701904/179772091-7a5f34ce-cfb4-4438-9cd7-71cc3c267a0d.png)

Case 2 - store-gateway not OOMKilled:
![Screenshot 2022-07-19 at 16 14 02](https://user-images.githubusercontent.com/1701904/179772150-324ffaa4-ae27-4447-b1ae-1a221bdb6a3a.png)

## Option: `rss`

Reading the cgroup [doc](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt) about `usage` (used in the previous option), we can see:

> For efficiency, as other kernel components, memory cgroup uses some optimization to avoid unnecessary cacheline false sharing. usage_in_bytes is affected by the method and doesn't show 'exact' value of memory (and swap) usage, it's a fuzz value for efficient access. (Of course, when necessary, it's synchronized.) If you want to know more exact memory usage, you should use RSS+CACHE(+SWAP) value in memory.stat(see 5.2).

An easier option for the Mimir case may be just tracking the old good RSS.

Case 1 - ingester OOMKilled at `08:11`:
![Screenshot 2022-07-19 at 16 17 56](https://user-images.githubusercontent.com/1701904/179772966-95c171cd-aa5c-4b81-bd8a-6b8826c2b03a.png)

Case 2 - store-gateway not OOMKilled:
![Screenshot 2022-07-19 at 16 18 12](https://user-images.githubusercontent.com/1701904/179772990-ffce8a74-db07-42d9-bac8-b4198cfa7b36.png)

**Comment by pracucci** [comment]
Looking at some store-gateways OOMKilled, looks like the `rss` or even `working_set - mapped_file` may not be a very good indicator. For example, the following store-gateway was OOMKilled at about `02:26:30`:

![Screenshot 2022-07-19 at 17 07 16](https://user-images.githubusercontent.com/1701904/179784307-5d71ddd0-9b57-4181-a5be-985f4cc519f3.png)

I'm wondering if RSS may actually be a good indicator, but since we scrape metrics at regular intervals, we're missing the actual memory utilization right before being OOMKilled in case the allocated memory suddenly spikes (vs an "organic" grows).

**Comment by bboreham** [comment]
I think the reason why people prefer working set (which is RSS minus inactive file-backed) is that it shrinks in line with their expectations.  Linux will keep a page mapped until it has some other use for the memory, which might be many hours later.

I have discussed "which memory metric should I use" dozens of times over decades.  I made two resolutions:
1. There is no one metric which will tell you the full story.
2. No matter which one you choose, also look at hard page faults.  These spike when you run close to your memory limit, and cause chaos.
`container_memory_failures_total{failure_type="pgmajfault"}`

**Comment by pracucci** [comment]
I've run the following query to see for which Deployments/StatefulSets we have a difference between `working_set` and `rss` greater than 20%, across all Mimir clusters running at Grafana Labs (I've excluded any pod using less than 256MB to remove some noise on low memory utilization pods).

```
max by(cluster, namespace, deployment) (label_replace(
    abs(
        1 -
        (
            sum by(cluster, namespace, pod) (container_memory_working_set_bytes{namespace=~"(cortex|mimir).*"})
            /
            sum by(cluster, namespace, pod) (container_memory_rss{namespace=~"(cortex|mimir).*"})
        )
    ) > 0.1
    and
    sum by(cluster, namespace, pod) (container_memory_working_set_bytes{namespace=~"(cortex|mimir).*"}) > (256 * 1024^2)
    , "deployment", "$1", "pod", "(.+)-[^-]+")
)
```

The result is that it's differs more than 10% only for ingesters, store-gateways and compactors, which are the 3 Mimir components using mmap.

**Comment by pracucci** [comment]
_I close the issue for now. We'll see how RSS works for our use case, and we can reopen this issue if it turns out to be not good enough too._
