### ISSUE TITLE
Set default `tokens_file_path` in helm

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2498]
Setting `tokens_file_path` to ingesters and store-gateways means that there won't be series/blocks resharding on each restart. This should reduce the spikiness of memory usage of the two components.

**Comment by krajorama** [comment]
To set it for ingesters and store-gateways only, we need to do it in CLI flags.

**Comment by dimitarvdimitrov** [comment]
the YAML config option is already specific to the component - under `ingester.ring.tokens_file_path` and `store_gateway.sharding_ring.tokens_file_path`. Should we still set it via CLI flags?
