### ISSUE TITLE
`make help` should show all targets

### ISSUE THREAD

**Issue by hi-rustin** [grafana/mimir#2499]
`make help` should show all targets, but for now we only showing a few targets.

See more: https://github.com/grafana/mimir/pull/2462#discussion_r925276281

**Comment by hi-rustin** [comment]
I can help make it happen, but adding it all at once might be difficult for me. I'm going to add them one by one, which may take a long time, but is less stressful for me. Do you think it's OK?

**Comment by pracucci** [comment]
> I can help make it happen, but adding it all at once might be difficult for me. I'm going to add them one by one, which may take a long time, but is less stressful for me. Do you think it's OK?

I wouldn't open a PR adding help only for 1 target :) My suggestion is: when you've some time, you can add help description for some targets and open a PR. Next day, if you have more time, you can do few more.

**Comment by hi-rustin** [comment]
> I wouldn't open a PR adding help only for 1 target :)

Of course, I plan to add them by category. Such as: proto, docs, images.... 
Thanks for your reply!
