### ISSUE TITLE
Smoke Test Helm Template adding Namespace 

### ISSUE THREAD

**Issue by BrandonDalton** [grafana/mimir#2529]
#### Is your feature request related to a problem? Please describe.

When deploying Grafana Mimir, the smoke test deploys in the default namespace. This is fine for most situations however would like control the namespace of it as currently in my organization we are within a shared cluster with multiple teams and due to setup I am unable to access default namespace and deploy to default namespace which causes issues.

#### Describe the solution you'd like

Add namespace field

#### Additional context

Not that big of a deal however small change makes it great for deploying to a specific namespace. As the rest of the deployment deploys to namespace feel like this should too.

**Comment by krajorama** [comment]
merged
