### ISSUE TITLE
Compactor: a tenant's long-running cleanup blocks all other tenants' cleanups

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2560]
### Context

Suppose that a tenant has a long-running cleanup job. Such a cleanup job can be prolonged because the bucket index for the tenant takes a long time to update. It may take a long time to update if there are thousands of blocks marked for deletion - [`UpdateIndex`](https://github.com/grafana/mimir/blob/c1e9a05bb8dcfed4920eef6168e7383e8766a007/pkg/storage/tsdb/bucketindex/updater.go#L50) iterates over all deletion markers to update the index.

The compactor runs cleanup for all tenants concurrently ([code](https://github.com/grafana/mimir/blob/9bb797880165046344d3cd0c0a4c93dc6763f9c8/pkg/compactor/blocks_cleaner.go#L196)) every 15 minutes by default (`-compactor.cleanup-interval`). But it waits for all tenants to complete before completing the cleanup. This means that if tenant X's cleanup takes, say, 1 hour, then tenant Y will be cleaned up again in 1 hour instead of in 15 minutes.

### Proposal

We should run cleanups on regular intervals per tenant, while still respecting the concurrency limit `-compactor.cleanup-concurrency` across all tenants. We can achieve this by having a pool of cleanup workers each running [`cleanUser`](https://github.com/grafana/mimir/blob/9bb797880165046344d3cd0c0a4c93dc6763f9c8/pkg/compactor/blocks_cleaner.go#L313). [`cleanUsers`](https://github.com/grafana/mimir/blob/9bb797880165046344d3cd0c0a4c93dc6763f9c8/pkg/compactor/blocks_cleaner.go#L173) can enqueue cleanup jobs to the workers unless there is already a running cleanup job.

**Comment by pracucci** [comment]
Agree. Looks a nice improvement to me 👍
