### ISSUE TITLE
Create a configuration validation command (probably in `mimirtool`)

### ISSUE THREAD

**Issue by colega** [grafana/mimir#2588]
#### Is your feature request related to a problem? Please describe.

There's no way of knowing beforehand whether a configuration file is valid or not, which may cause issues when it's rendered in CI and applied automatically.

#### Describe the solution you'd like

[François GOUTEROUX](https://app.slack.com/team/U024J9X941J) [suggested to implement a check command in `mimirtool`](https://grafana.slack.com/archives/C039863E8P7/p1659087593032159) just like [grafana agent did](https://github.com/grafana/agent/commit/bd8301e7eaf361a10fc881735d7fde539a309482), something like:

```shell
mimirtool config check /etc/mimir/config.yaml
```

#### Describe alternatives you've considered

Maybe make a Mimir target that doesn't do anything except validating the configuration? This would probably be easier to implement and maintain code-wise (since we'd reuse the same configuration parsaing)

**Comment by pracucci** [comment]
It's a bit obscure, but I think you get it in practice running `mimir --modules=true`, because it validates the config and print modules, then exit.

**Comment by fgouteroux** [comment]
> It's a bit obscure, but I think you get it in practice running `mimir --modules=true`, because it validates the config and print modules, then exit.

Ok it do the job `mimir --modules=true -config.file /etc/mimir/config2.yaml
error loading config from /etc/mimir/config2.yaml: Error parsing config file: yaml: unmarshal errors:
  line 55: field instance_availability_zone not found in type querier.Config
`

**Comment by colega** [comment]
@pracucci maybe we could make that prettier or at least document that?

That's what I had in mind when I considered making it a Mimir target.
