### ISSUE TITLE
Really enforce parity between Jsonnet and Helm

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#2591]
PR https://github.com/grafana/mimir/pull/2067 implemented checking the parity but hasn't turned on actual enforcement, that is CI does not fail due to the test.

We should fail CI when we're ready to enforce this.

**Comment by krajorama** [comment]
Blocked until we decide to enforce it.

**Comment by dimitarvdimitrov** [comment]
what do we need to make that decision? I wasn't aware that there are blockers

**Comment by dimitarvdimitrov** [comment]
we keep having to backfix changes to the chart that break the parity. This means that all PRs get irrelevant comments about the difference - here's an example https://github.com/grafana/mimir/pull/2750#issuecomment-1217860251

**Comment by krajorama** [comment]
we don't have buy in from the rest of the squad, let's talk about this on the weekly
