### ISSUE TITLE
Docs: Helm: how to set up HA dedup with external Consul

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#2597]
#### Is your documentation request related to a feature? If so, which one?

A clear and concise description of the feature that you were trying to use, and what you were trying to achieve.

#### Describe the solution that you’d like or the expected outcome

A clear and concise description of the documentation that you want to add, change, or remove.

**Comment by krajorama** [comment]
Steps to take from scratch:
 - set up Consul
 - set up Mimir 
    - use the `mimir.structuredConfig` value to enable up HA overall
    - use `runtimeConfig` value to set per tenant
- set up two prometheus instances in HA

**Comment by mattmendick** [comment]
This is one of the items on the "helm hot list". Will this one finish in the next 2 weeks?
