### ISSUE TITLE
Add ability to specify limits section of config file to helm chart

### ISSUE THREAD

**Issue by boniek83** [grafana/mimir#2654]
#### Is your feature request related to a problem? Please describe.

Limits configuration can't be specified when using helm chart. I want to enable exemplars.

**Comment by pracucci** [comment]
I'm not an Helm expert, but I think you can now use `structuredConfig` in the Helm Chart values to override specific fields like the `limits` one.

**Comment by boniek83** [comment]
It didn't work for me in 3.0.0 helm chart. It works with 3.1.0-weekly though. Thank you very much!
