### ISSUE TITLE
error: function "mulf' not defined

### ISSUE THREAD

**Issue by oliashish** [grafana/mimir#2661]
## Description
I'm trying to setup grafana-mimir on my k8s cluster using helm chart - grafana/mimir-distributed but not able to setup is up for some reason.

#### Error
`Error: parse error at (mimir-distributed/templates/memcached/_memcached-statefulset.tpl:77): function "mulf" not defined
`
#### Command used 
- `helm repo add grafana https://grafana.github.io/helm-charts`
- `helm repo update`
- `helm install mimir grafana/mimir-distributed` (alternatively used `helm installed <cluster-name> grafana/mimir-distributed`)

Helm version  - `version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}`

I couldn't find anything in docs and also being new to grafana I don't know what/how does `mulf` function works. 
I don't know if this is the right platform to ask for the issue, I'm not able to find anything regarding this issue on other online platforms.
Thanks

**Comment by pstibrany** [comment]
Hello, you may want to update your Helm installation. `mulf` is a function coming from `sprig` library, and this function was added in [December 2020](https://github.com/Masterminds/sprig/releases/tag/v3.2.0), while your version of Helm 3.4.1 was released in Nov 2020.

**Comment by pracucci** [comment]
@krajorama Is there a way to specify the minimum Helm version required by a Chart?

**Comment by krajorama** [comment]
Not that I know of, I'll add this to our backlog to not use undocumented (from helm point of view function). Good first issue for someone this quarter

**Comment by krajorama** [comment]
Should rewrite with functions in  https://helm.sh/docs/chart_template_guide/function_list/

**Comment by oliashish** [comment]
Hey @pstibrany thanks you for the help.
It worked for me.
