### ISSUE TITLE
Exceeding gRPC message sizes in querier->query-frontend results in HTTP 500

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2693]
#### Describe the bug
With query sharding enabled when the querier tries to send back the response to the query-frontend and that response exceeds the configured `-querier.frontend-client.grpc-max-send-msg-size`, the query-frontend returns a 500 error.

Logs by the query frontend, which gets logged [here](https://github.com/grafana/mimir/blob/e38484fa03ac97a1e127b96f2c3493abad5d40f2/pkg/frontend/querymiddleware/retry.go#L74-L80):
```
level=error ts=2022-08-10T12:56:35.679539274Z caller=retry.go:78 user=X traceID=103839b067340f71 msg="error processing request" try=1 err="error decoding response: readObjectStart: expect { or n, but found r, error found in #1 byte of ...|response la|..., bigger context ...|response larger than the max message size (10134162|..."
```

This also implies that the error is retried.

#### Expected behaviour

The query-frontend returns an HTTP 413 and does not retry the query.

#### Details

The size checking happens in the querier - [code](https://github.com/grafana/mimir/blob/b5e7bce69311da4df36e363dce3c3d27c8ed0fb1/pkg/querier/worker/scheduler_processor.go#L193-L201). It returns an HTTP 413 (request entity too large).

The error is parsed in the query-frontend and results in the query-frontend's prometheus codec - [code](https://github.com/grafana/mimir/blob/a228e432ff44804394a48f28d518eb06353e63b4/pkg/frontend/querymiddleware/codec.go#L282-L289)

This is similar to the work done in https://github.com/grafana/mimir/pull/2447

**Comment by dimitarvdimitrov** [comment]
may be a good idea to just generalize the solution for unrecognized 4xx responses. we shouldn't retry these and should not return a 5xx

**Comment by pracucci** [comment]
As a reference, a similar fix has been done for 429 errors in https://github.com/grafana/mimir/pull/2447.
