### ISSUE TITLE
Stagger ingester compactions, to reduce resource peaks

### ISSUE THREAD

**Issue by bboreham** [grafana/mimir#2699]
Prometheus, and hence Mimir, does a "head compaction" every 2 hours, which is very disk and CPU intensive.
Each compaction takes only a minute or so, for an ingester with 1-2 million timeseries.
The data being compacted is from -3 hours to -1 hours; there is one hour grace period in case more data comes in.

So, we don't have to run all compactions exactly at the hour, we could start 2-3 minutes early or late without any impact.
Doing this will spread out the peak load, so we can run just as effectively with lower provision.

We shouldn't stagger blocks for the same tenant too far apart, since we want the compactor to see all three replicas before it starts work. This suggests the staggering could be a hash of the tenant ID.

**Comment by replay** [comment]
Why only spread them out by 2-3 minutes instead of doing something like `hash(<tenant>) % 120` and then offset the compaction time by the resulting number of minutes? 

Note: I did `% 120` because we want the blocks to get compacted once every `2h`. 

This way the compaction times would be completely different from tenant to tenant, but each ingester would still compact the blocks of a given tenant at the same time.

**Comment by pracucci** [comment]
> Note: I did % 120 because we want the blocks to get compacted once every 2h.

Once the TSDB head compaction threshold is reached, the longer you delay the compaction, the longer the stale  series will stay in the head (this has negative side effects both on memory utilization and our limits).

**Comment by bboreham** [comment]
Nit: I said to spread them 2-3 minutes _early or late_, so total spread 6 minutes.  There is some spreading in current behaviour since we do max 10 concurrently; I guess it would be worth analysing in detail.

The earlier you push it, the less you can accommodate late samples.  With out-of-order support that behaviour changes; maybe it's ok to go much earlier.

And going later delays garbage-collection of stale series, as Marco said.

**Comment by replay** [comment]
> Once the TSDB head compaction threshold is reached, the longer you delay the compaction, the longer the stale series will stay in the head (this has negative side effects both on memory utilization and our limits).

Could we move the timing of the head compaction as well by the same offset? Basically what I'm trying to say is: why not just move the timing of everything that happens once every 2h by the same offset of `hash(<tenant>) % 120`.

**Comment by pracucci** [comment]
> Could we move the timing of the head compaction as well by the same offset? Basically what I'm trying to say is: why not just move the timing of everything that happens once every 2h by the same offset of hash(<tenant>) % 120.

I think it will make reasoning about the system even more complex, and I wouldn't add such extra complexity. Right now, it's easy to reason about blocks: for each tenant, each block time range is 2h and **aligned**.

**Comment by pracucci** [comment]
After some discussion internally at Grafana Labs, I think we could easily achieve something similar just setting `-blocks-storage.tsdb.head-compaction-concurrency=1` (default is 5). I would give it a try before working on a more elaborated solution.

**Comment by pracucci** [comment]
> We shouldn't stagger blocks for the same tenant too far apart, since we want the compactor to see all three replicas before it starts work. This suggests the staggering could be a hash of the tenant ID.

This wouldn't spread the TSDB head compaction in Mimir clusters with a single tenant (or with a big tenant among other smaller ones). I think we should just fix it in the compactor, and I've opened a proposal to describe my idea: https://github.com/grafana/mimir/issues/4365

**Comment by bboreham** [comment]
Did we do this?  What's left to keep the issue open?

**Comment by pracucci** [comment]
Nowadays we're spreading the TSDB head compaction over a 15m period and we've improved the compactor to give ingesters time to compact head and upload blocks to the storage before begin compacting 2h blocks.

_We can close this issue._
