### ISSUE TITLE
linter not fully support loki rule syntax

### ISSUE THREAD

**Issue by timansky** [grafana/mimir#2731]
#### Describe the bug
mimirtool lint not fully support loki rule syntax

#### To Reproduce

```
$ cat loki_rule.yml

groups:
  - name: loki_records
    rules:
      - record: rate1m
        expr: |
          sum (
            rate( {app="foo"} | json | __error__="" [1m] )
          )
```
stdout:
```
$ mimirtool rules lint -n --rule-files=loki_rule.yml
ERRO[0000] unable parse rules file                       error="5:15: group \"loki_records\", rule 0, \"rate1m\": could not parse expression: 2:21: parse error: unexpected character: '|'" file=loki_rule.yml
mimirtool: error: prepare operation unsuccessful, unable to parse rules files: file read error, try --help
```

**Comment by pracucci** [comment]
`mimirtool` currently doesn't support Loki. Loki users should use https://github.com/grafana/cortex-tools instead.

**Comment by ramukima** [comment]
Any plans for ```mimirtool``` to support loki ?

**Comment by 56quarters** [comment]
> Any plans for `mimirtool` to support loki ?

Not in mimirtool, no. Loki team is evaluating creating a dedicated tool but that's something they'll have to prioritize (or not).
