### ISSUE TITLE
Provide a built-in Alertmanager default (empty) config

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#2772]
I'm seeing several people trying out Mimir Alertmanager being confused by the need of having to specify a per-tenant Alertmanager configuration in order to get it work. Because of this, in the past we've added `-alertmanager.configs.fallback` which allows you to specify the path to a local `.yaml` file containing a default Alertmanager configuration to use for any tenant for which hasn't been specified a configuration yet. However, most people is not aware of that until they start digging into "why Alertmanager API/UI doesn't work".

**Question**: what if we provide a built-it default Alertmanager config (which you can still override via `-alertmanager.configs.fallback`) to let Alertmanager working with an empty config out of the box?

**Comment by konrad147** [comment]
Is this issue connected to https://github.com/grafana/grafana/issues/49728?

**Comment by pracucci** [comment]
> Is this issue connected to [grafana/grafana#49728](https://github.com/grafana/grafana/issues/49728)?

Yes! I wasn't aware of that issue. The Grafana issue is about how Grafana reacts to a Mimir Alertmanager with no fallback config. The Grafana issue fixes it from Grafana side, but I think we should still fix it from Mimir side, for people accessing the Mimir Alertmanager UI directly, not through Grafana Alerting.
