### ISSUE TITLE
Some distributor metrics are incorrect after middleware refactoring

### ISSUE THREAD

**Issue by 56quarters** [grafana/mimir#2783]
#### Describe the bug

The [sample, exemplar, and metadata metrics](https://github.com/grafana/mimir/blob/main/pkg/distributor/distributor.go#L267-L281) indicate that they are inclusive of HA deduplicated requests. However, they are [only incremented after the HA dedupe middleware](https://github.com/grafana/mimir/blob/main/pkg/distributor/distributor.go#L908-L912) has already run and potentially short-circuiting the request 

#### To Reproduce

N/A

#### Expected behavior

There should potentially be middleware that runs before HA deduplication and forwarding that increments these metrics before the request is deduplicated or forwarded.

#### Additional Context

Noticed by @pstibrany in [#2770](https://github.com/grafana/mimir/pull/2770#issuecomment-1220790932).

**Comment by pstibrany** [comment]
Fixed via https://github.com/grafana/mimir/pull/2790.
