### ISSUE TITLE
Docs: Common configuration

### ISSUE THREAD

**Issue by 09jvilla** [grafana/mimir#2808]
Somewhere in the documentation we need to mention that

-  the common configuration allows you to configure block, alertmanager, and ruler storage all at once. 
- Users can still individually configure storage for each of these components if they desire
- if they configure a component's object storage individually and also configure the common config, the individual storage configuration takes precedence for that component.

**Comment by 09jvilla** [comment]
Right now, all we have is in the configuration reference and it says:
The common block holds configurations that configure multiple components at a time.

**Comment by colega** [comment]
@09jvilla I did the docs here: https://github.com/grafana/mimir/pull/2347

The doc can be read here: https://grafana.com/docs/mimir/next/operators-guide/configure/about-configurations/#common-configurations ([file permalink](https://github.com/grafana/mimir/blob/4a4257f2228abe47b73330a87a1011b50217d29d/docs/sources/operators-guide/configure/about-configurations.md)) and here: https://grafana.com/docs/mimir/next/operators-guide/configure/configure-object-storage-backend/ ([file permalink](https://github.com/grafana/mimir/blob/4a4257f2228abe47b73330a87a1011b50217d29d/docs/sources/operators-guide/configure/configure-object-storage-backend.md))

PTAL

**Comment by 09jvilla** [comment]
Oops - I apologize for missing this @colega ! I didn't see docs on the original pr and didn't look further. This is exactly what we need! I'll link it in the release notes.

**Comment by 09jvilla** [comment]
Also, closing the issue as complete.
