### ISSUE TITLE
Agree on capitalization of `msg` logs

### ISSUE THREAD

**Issue by colega** [grafana/mimir#2809]
#### Is your feature request related to a problem? Please describe.

See our logs:
```logfmt
level=info ts=2022-08-23T03:00:53.010179793Z caller=head.go:1054 user=10428 msg="Head GC completed" duration=1.988020718s
level=info ts=2022-08-23T03:00:50.52193862Z caller=db.go:1508 user=10428 msg="Deleting obsolete block" block=01GB1H181VJT6XWXG30PE04J2T
level=info ts=2022-08-23T03:00:50.27852845Z caller=compact.go:713 user=10428 msg="write block" mint=1661212800000 maxt=1661220000000 ulid=01GB4A9P9V1TD493Y4KWVD07MC duration=27.306824999s
level=info ts=2022-08-23T03:00:29.210914631Z caller=shipper.go:186 user=108343 msg="upload new block" id=01GB4A9P9V4JR0WMGPSANHPVYS
level=info ts=2022-08-23T03:00:29.209473673Z caller=shipper.go:186 user=132829 msg="upload new block" id=01GB4A9P9V4XKHSVZ91W6HQFH3
level=info ts=2022-08-23T03:00:26.111248426Z caller=head.go:1223 user=132829 msg="WAL checkpoint complete" first=959 last=962 duration=1.801534883s
level=info ts=2022-08-23T03:00:24.309818353Z caller=checkpoint.go:97 user=132829 msg="Creating checkpoint" from_segment=959 to_segment=962 mint=1661220000000
```

Especially the part where we say `upload new block`, `write new block` but `Creating checkpoint`, `Deleting obsolete block`.

We should agree on a code style for capitalization of `msg` in the logs, and try do these consistently (and update in boyscout mode as we see them).

I know it will be impossible to achieve completely as some of the pieces are logged by imported dependencies like Prometheus (maybe we should match the style of the biggest dependency we have, like Prometheus?).

#### Describe the solution you'd like

I think `msg` field should be capitalized as it's a human readable sentence. However, I'd be happy just to be consistent with whatever Prometheus does, to minimize the variance.

#### Describe alternatives you've considered

Be evil and do the magic in a logger wrapper. This would make it a hell to debug.

**Comment by aknuds1** [comment]
I thought our convention was to not capitalize log messages, but I can't recall if I was actually told or not. @pstibrany do you know?

**Comment by pstibrany** [comment]
From what I can see, most messages in Mimir are not capitalized and similarly most messages in dskit are not capitalized.

**Comment by replay** [comment]
I think the only way to really enforce a rule like this is via the CI. Even if we somehow make everyone in the current Mimir team aware of this, over time new people will join or the current people will forget. The PR which introduces that check will have to fix all occurrences of log statements that disobey the rule it introduces.

**Comment by aknuds1** [comment]
What @replay says sounds sensible to me. Without enforcement, such a rule is going to slip :)

**Comment by pstibrany** [comment]
Even if we enforce it for our code, we cannot guarantee anything about error messages coming from different libraries, so end result from users' point of view will still be mixed.

In my opinion this is a cosmetic issue, and I would prefer to not to have any CI check for it.
