### ISSUE TITLE
Implement more helm rego checks

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2811]
A follow-up on #2137 

What more checks we can add:

- [x] all containers have the restricted security context - a test for https://github.com/grafana/mimir/issues/2595
- [ ] all pods are covered by some <code class="notranslate">ServiceMonitor</code>/<code class="notranslate">PodLogs</code>; metamonitoring is restricted to pod from the chart
- [ ] some implicit naming conventions: to scrape PVC volumes information for metamonitoring (https://github.com/grafana/mimir/pull/2068) we assume that the PVCs created by the chart have a <code class="notranslate">storage-</code> prefix. If this prefix is changed in any of the <code class="notranslate">StatefulSets</code> the metamonitoring will break and stop collecting data for the volumes. We have no way of knowing this during the review process now.
- [ ] Verify that all component have an attached volume under <code class="notranslate">/data</code>. The default <code class="notranslate">mimir.config</code> assumes <code class="notranslate">/data</code> is a mounted directory.
- [ ] all resources have the standard kubernetes annotations (app.kubernetes.io/)
- [x] verify that all resources have an explicit namespace (#2123)

**Comment by mattmendick** [comment]
Removing the `squad/customer` label from this issue since this is a bit of a pet project. If you feel like this should be something that a larger group of people chip away at officially, put it on the next quarter planning spreadsheet. Creating smaller issues made from this might be another good strategy.

**Comment by dimitarvdimitrov** [comment]
I don't have plans to work on this anymore, so I'm closing it
