### ISSUE TITLE
Fix typo in -query-frontend.align-querier-with-step CLI flag

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#2829]
The CLI flag `-query-frontend.align-querier-with-step` contains a typo and should actually be called `-query-frontend.align-queries-with-step` ("queries" vs "querier"), given the YAML config parameter name is `align_queries_with_step`. We should rename the CLI flag, but keep backward compatibility for 2 releases.

**Comment by hi-rustin** [comment]
@pracucci Could you please assign this issue to me? I'll remove it after 2.6.0 is released.

**Comment by pracucci** [comment]
Closed by #2840.
