### ISSUE TITLE
Helm: nginx config not compatible with istio

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#2845]
#### Describe the bug
https://istio.io/latest/docs/ops/common-problems/network-issues/#envoy-won-t-connect-to-my-http-1-0-service

#### To Reproduce

1. Enable istio injection in your K8S namespace
1. Start Mimir from helm chart 3.1
2. Perform Operations(Read/Write/Others)

#### Expected behavior

Read/Write path works

#### Actual behavior

Getting HTTP status 426
#### Environment

- Infrastructure: latop with microk8s + istio
- Deployment tool: helm 3

#### Additional Context

Workaround helm value that should be enabled by default:
```
nginx:
  nginxConfig:
    httpSnippet: |
      proxy_http_version 1.1;
```

**Comment by mattmendick** [comment]
Context: https://raintank-corp.slack.com/archives/C9KL8THCY/p1660857741053929

**Comment by ceastman-r7** [comment]
I think you need to add proxy_http_version 1.1; to the location stanzas also.

**Comment by rafilkmp3** [comment]
@krajorama  you save my life thanks
