### ISSUE TITLE
ruler-querier does not set gossip_ring_member=true

### ISSUE THREAD

**Issue by stevesg** [grafana/mimir#2849]
#### Describe the bug
Pods that use the ring should set `gossip_ring_member=true`, `ruler-querier` does not.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: jsonnet

**Comment by pracucci** [comment]
This can be fixed adding support to `ruler_querier_deployment` in `operations/mimir/memberlist.libsonnet` (similarly to how it's done for `querier_deployment`).
