### ISSUE TITLE
Creates a custom memcached client to reuse memory

### ISSUE THREAD

**Issue by cyriltovena** [grafana/mimir#285]
The current memcached client always throw away the buffer which creates a lot of allocations.

It would be great to have a reusable buffer, although this might be difficult since there's a lot of cache interface used along the way.

**Comment by bboreham** [comment]
<fx: time passes...>

I have created https://github.com/grafana/gomemcache/ with the above change.

**Comment by 56quarters** [comment]
We're now pooling memory in Mimir when reading from the chunks cache, passing a request-scoped pool from the `CachingBucket` to underlying cache clients: https://github.com/grafana/mimir/commit/c6a4d9306cc0d896eeef1427d352600c659077f5
