### ISSUE TITLE
Alertmanager config validation fails with valid settings

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/mimir#2867]
#### Describe the bug
When running the alertmanager in a standalone setup, config validation can fail with the default argument for `common.storage.backend.filesystem.dir = "blocks"`

#### To Reproduce

1. Start Mimir Alertmanager(SHA or version) with a config setting for alertmanager's data directory:
```
-alertmanager-storage.backend=gcs
-alertmanager-storage.gcs.bucket-name=some-bucket
-alertmanager.storage.path=/data
```
2. Config validation will fail with the error:
`error validating config: the configured blocks storage filesystem directory "blocks" cannot overlap with the configured alertmanager data directory "/data"; please set different paths, also ensuring one is not a subdirectory of the other one`

#### Expected behavior

Startup should not fail. "blocks" is not a directory, and it does not overlap with "/data", and it is not an alertmanager-specific

#### Environment

- Infrastructure: kubernetes
- Deployment tool: jsonnet

#### Additional Context

An unmodified deployment spec failed after a release that includes this commit:
https://github.com/grafana/mimir/commit/6fef60a44e2f662079a8d0fd1cdee986a7ee1db8#diff-65e7b459f8395b478ded668343cf0806f3ee69866e428c3a160e810e60dfe1d6

**Comment by pstibrany** [comment]
As a workaround it's possible to set `-blocks-storage.backend=gcs` in alertmanager. Problem is that code [expects](https://github.com/grafana/mimir/blob/6fef60a44e2f662079a8d0fd1cdee986a7ee1db8/pkg/mimir/mimir.go#L328) that all components use blocks storage, which is not true.

**Comment by joeblubaugh** [comment]
The workaround for now is to set: `-blocks-storage.backend=gcs`. Really any value other than `filesystem`. You must only set that for alertmanager running as its own process.

**Comment by pracucci** [comment]
_I'm looking into this._

**Comment by pracucci** [comment]
`common.storage.backend.filesystem.dir = "blocks"` is a relative directory, which gets resolved to an absolute path. If the current working directory is `/data`, then the location used for blocks will be `/data/blocks` which conflicts with `-alertmanager.storage.path=/data`.

If you're running Alertmanager in monolithic mode, then this is an issue. However, if you run the Alertmanager in microservices modes (so `-target=alertmanager`) then this is **not** an issue, but a false positive reported by the check, which I'm going to fix right now.
