### ISSUE TITLE
Ruler doesn't restore alert state when changing ownership of alert groups

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2888]
#### Context

The ruler can restore the state of an alert when it starts up. This allows the alert to continue where it left off. If not restored, the alert will need to go into "Pending" state, then wait for its `for` duration, then go into "Firing" state.

Rulers are in a ring for sharding rule groups. The ring is with RF=1

#### Describe the bug

The ruler may not restore an alert's state if that rule group gets sharded to the ruler after it has started up.

The ruler manager will attempt to restore an alert group's state when it starts up and `Update`s all rule groups. After the first load the manager sets `m.restored = true` https://github.com/grafana/mimir/blob/8fca3461c1e9f74cdbc98a8fc1fcfbbdcbbe24da/vendor/github.com/prometheus/prometheus/rules/manager.go#L1033

The manager also sets each group's `shouldRestore = !m.restored`. Subsequent calls to `Update` will not update restore the rule group
https://github.com/grafana/mimir/blob/8fca3461c1e9f74cdbc98a8fc1fcfbbdcbbe24da/vendor/github.com/prometheus/prometheus/rules/manager.go#L1119

#### To Reproduce
Consider a scenario with 2 new rulers (N1, N2) rolling out and replacing two old rulers (O1, O2):

1. ruler O1 is terminated and exits cleanly (removed itself from the ruler ring)
2. These can happen in any order:
3. N1 starts up and adds itself to the ring; it lists all rule groups that shard to it (aka the ruler owns them); it restores the state of all rule groups it finds suitable ([logic for deciding if a group is suitable for restoration](https://github.com/grafana/mimir/blob/8fca3461c1e9f74cdbc98a8fc1fcfbbdcbbe24da/vendor/github.com/prometheus/prometheus/rules/manager.go#L790-L797)) and starts evaluating them as normal; N1's rule manager sets `m.restored = true` 
5. O2 is terminated and exits cleanly (removing itself from the ring)
3. N1 notices a change in the ring and recalculates which rule groups it owns; now there are less tokens in the ring, so N1 likely starts owning a new rule group that was owned by O2; N1 does not restore it since its manager already has `m.restored = true`, hence the group's `shouldRestore == false`
6. N2 starts up and adds itself to the ring; N2 determines which groups it owns, restores them, and starts evaluating them; N1 may lose some groups, but will not start owning new ones

The bug happens at step 5. This gets worse the more rulers there are.

#### Expected behavior

Ring changes do not reset the state of alerts.

#### Possible fixes

All of the linked code is in prometheus/prometheus. We can
* soft fork the Manager and change the restoration behaviour to "always"
* add a hook to the manager. The manager uses [`NewGroup(_ GroupOptions)`](https://github.com/grafana/mimir/blob/8fca3461c1e9f74cdbc98a8fc1fcfbbdcbbe24da/vendor/github.com/prometheus/prometheus/rules/manager.go#L1161) to create groups. These options allow to explicitly attempt state restoration. We can add a hook into the rule manager which modifies the options before creating the rule group. In the hook Mimir will always set `RestoreState: true`
  * this will allow us to also not bother restoring the state for rule groups that need less than 4 evaluations to trigger. Why 4? The alertmanager autoresolves an alert if it doesn't get a notification from the ruler [within 4 evaluation intervals](https://github.com/grafana/mimir/blob/8fca3461c1e9f74cdbc98a8fc1fcfbbdcbbe24da/vendor/github.com/prometheus/prometheus/rules/alerting.go#L522).  
* add an option to the prometheus rules manager to always restore alert state when a new alert is added - this change is implemented in https://github.com/grafana/mimir-prometheus/pull/328

To prevent ownership change we can:
* run rulers as a StatefulSet and not remove them from the ring on shutdown, this way ownership will not change as a ruler shuts down, so no new rules can be sharded to the ruler after it has started up. If we do this, the problem still persists during scale-up and scale-down, but that should happen less often.

**Comment by bboreham** [comment]
If we didn’t remove rulers from the ring on rolling restart then the ownership wouldn’t move, right?

However we would still have a problem on scale-up and scale-down.

**Comment by dimitarvdimitrov** [comment]
> If we didn’t remove rulers from the ring on rolling restart then the ownership wouldn’t move, right?

I think so. We currently don't persist token between restarts. And the rulers are running as deployments instead of stateful sets.

**Comment by dimitarvdimitrov** [comment]
I opened a PR in mimir-prometheus with a proposed change https://github.com/grafana/mimir-prometheus/pull/328

**Comment by dimitarvdimitrov** [comment]
we tested the porposed change to prometheus in a dev environment and got what I'd call 100% restoration

you can see how the replicaset changes at around 07:47. This was the ruler deployment being restarted. Firing alerts remained the same after the restart. I'll proceed to merging the mimir-prometheus PR and vendoring it in mimir

![Screenshot 2022-10-06 at 11 04 03](https://user-images.githubusercontent.com/21020035/194502261-9f59cd9c-9f1e-44a2-aa2d-2dba5fc8c70f.png)

**Comment by dimitarvdimitrov** [comment]
queries to the query-frontend seemed to spike by some 25% for a minute, but I think it's manageable. especially given that resource usage didn't move at all for the ruler read path

![Screenshot 2022-10-07 at 10 00 48](https://user-images.githubusercontent.com/21020035/194503458-b02fb966-dca1-42cf-a582-01f703565205.png)
 
![Screenshot 2022-10-07 at 10 00 37](https://user-images.githubusercontent.com/21020035/194503408-31e7e548-403a-4628-89eb-0ff95ff80f22.png)
