### ISSUE TITLE
Helm: update sizing plans (small.yaml, large.yaml, etc)

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2890]
The chart has a few files that have a suggested cluster size (vertical and horizontal) for running 1M AS and 10M AS - [small.yaml](https://github.com/grafana/mimir/blob/94b9ae6edc6b070fd8dfade717ddc39a658f8f1e/operations/helm/charts/mimir-distributed/small.yaml), [capped-small.yaml](https://github.com/grafana/mimir/blob/94b9ae6edc6b070fd8dfade717ddc39a658f8f1e/operations/helm/charts/mimir-distributed/capped-small.yaml), [large.yaml](https://github.com/grafana/mimir/blob/94b9ae6edc6b070fd8dfade717ddc39a658f8f1e/operations/helm/charts/mimir-distributed/large.yaml), [capped-large.yaml](https://github.com/grafana/mimir/blob/94b9ae6edc6b070fd8dfade717ddc39a658f8f1e/operations/helm/charts/mimir-distributed/capped-large.yaml).

Internally we've updated our sizing estimates. After a super quick look, the sizing recommendations in large.yaml for 10M AS are roughly twice as much as the internal sizing estimates suggest. There was also [a comment](https://grafana.slack.com/archives/C039863E8P7/p1660916259958989?thread_ts=1660915006.857309&cid=C039863E8P7) in the community slack that the small.yaml was overprovisioned for the actual load it was supposed to handle.

**Comment by krajorama** [comment]
Also we should round up ingester and store-gateway replica numbers to be divisible by 3 to prep for multi zone on by default.

**Comment by krajorama** [comment]
> Also we should round up ingester and store-gateway replica numbers to be divisible by 3 to prep for multi zone on by default.

Actually I meant to say round down at least for the small one from 4 to 3. Since we're overprovisioning anywya

**Comment by dimitarvdimitrov** [comment]
@pianohacker, @Logiraptor, we spoke with @krajorama about this and thought that it is a prerequisite to doing #2181, which in turn is the current top priority. We want to include some sizing advice in the guide and it will be easier if the sizing presets that the chart comes with are up to date with GL's experience in sizing. 

This issue is still being triaged. Are you ok if I take this up?

on a similar note: @johannaratliff, have you had time to do the finishing touches on the calculator? Is there something there that I can help with there?

**Comment by Logiraptor** [comment]
@dimitarvdimitrov Yes please feel free. The triage process shouldn't block you when you have a good reason to pick something up, as you do in this case!
