### ISSUE TITLE
Include TSDB index downloads in query stats

### ISSUE THREAD

**Issue by 56quarters** [grafana/mimir#2923]
#### Is your feature request related to a problem? Please describe.

We routinely have slow queries caused by latency in the store-gateway. Looking at traces (attached), much of this comes from downloading sections of the TSDB index file on demand as part of the `ExpandedPostings` code path.

#### Describe the solution you'd like

We currently record the number series, chunks, and chunk bytes fetched by a query. HOWEVER, the TSDB index bytes fetched by a query can have a dramatic effect on the speed of a query. We should record this and include it in the [query stats](https://github.com/grafana/mimir/blob/427d556d76315f5d08d25c0987c85757467aab50/pkg/querier/stats/stats.go) we are already recording in the query-frontend.

#### Describe alternatives you've considered

Pain, suffering, getting paged.

#### Additional context

Portion of a trace from our ops cluster attached.
![index](https://user-images.githubusercontent.com/1127373/189216452-63c3a1bc-1169-42ce-b91e-c642db06aabe.png)

**Comment by 56quarters** [comment]
This will actually end up being non-trivial since we'd need to pass a `Stats` object back to the querier from the store-gateway in the response. The definition of the store-gateway response is currently in Thanos protobuf definition so we'd likely have to fork it and include it within the Mimir codebase (because this change probably doesn't make sense for Thanos).

**Comment by 56quarters** [comment]
Using some of the aggregate metrics emitted by the store-gateway, data transferred for "postings" from the TSDB index are very bursty and correspond pretty well to spikes in p99 latency
![Screenshot 2022-09-09 at 14-56-20 Explore - ops-cortex - Grafana](https://user-images.githubusercontent.com/1127373/189424074-c5f26226-aac0-4e3a-94c9-f28212c48e09.png)

**Comment by pracucci** [comment]
> The definition of the store-gateway response is currently in Thanos protobuf definition so we'd likely have to fork it and include it within the Mimir codebase (because this change probably doesn't make sense for Thanos).

I wouldn't consider it a blocker. Back in time, we wanted to reuse Thanos protobuf definition to keep the door open to being able to query a Mimir store-gateway from Thanos and viceversa, but they both already diverged enough that this thing won't come to life.
