### ISSUE TITLE
Can't perform streaming remote read

### ISSUE THREAD

**Issue by leizor** [grafana/mimir#2929]
#### Describe the bug
Attempting to use streaming remote read against Mimir results in this error message being returned by the querier:
```
can't select: querier.Select: can't perform remote read: remote server [http://cortex-gw-internal.cortex-dev-01.svc.cluster.local:80/api/prom/api/v1/read](http://cortex-gw-internal.cortex-dev-01.svc.cluster.local/api/prom/api/v1/read) returned http status 400 Bad Request: internal http.ResponseWriter does not implement http.Flusher interface
```
That error message comes from here: https://github.com/grafana/mimir/blob/ed68eb059984b4724aa4f6cef7c6e099076e277d/pkg/querier/remote_read.go#L131-L135

I think the error is caused by this default middleware that Mimir uses:
https://github.com/weaveworks/common/blob/d2f56921e6b08313750997ad1d6ee1297c38de92/server/server.go#L391-L395

More specifically, `middleware.Log` is wrapping the `http.ResponseWriter` with [badResponseLoggingWriter](https://github.com/weaveworks/common/blob/master/middleware/response.go) but `badResponseLoggingWriter` does not implement `http.Flusher`.

#### To Reproduce

Attempt to use streaming remote read against Mimir (current SHA is `68b619729466c6d984bed26e5eb1c3dfbbac3d31`).

#### Expected behavior

Streaming remote read should stream data back to the requestor and not error out.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: jsonnet

#### Additional Context

I'm working on a fix from the weaveworks/common end of things here: https://github.com/weaveworks/common/pull/257

There's [an integration test for this](https://github.com/grafana/mimir/blob/ed68eb059984b4724aa4f6cef7c6e099076e277d/integration/querier_remote_read_test.go#L133-L247) ~~but it doesn't include all the default middleware Mimir uses so it's currently passing when it probably shouldn't be.~~ but it's currently passing--why/how?

**Comment by leizor** [comment]
This update to the integration test will cause it to show the 400 we were seeing: https://github.com/grafana/mimir/commit/3014f4ad47a1849acc94e9a1ef38e59d46c037b0

**Comment by pracucci** [comment]
Thanks Justin for reporting this issue and taking care of fixing it! ❤️
