### ISSUE TITLE
Helm file _memcached-statefulset.tpl is missing  securityContext, release 2.3.0-rc0

### ISSUE THREAD

**Issue by valdemarpavesi** [grafana/mimir#2932]
#### Describe the bug
Helm file _memcached-statefulset.tpl is missing  securityContext

      {{- if $.ctx.Values.memcachedExporter.enabled }}
        - name: exporter
          {{- with $.ctx.Values.memcachedExporter.image }}
          image: {{ .repository}}:{{ .tag }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          ports:
            - containerPort: 9150
              name: http-metrics
          args:
            - "--memcached.address=localhost:{{ .port }}"
            - "--web.listen-address=0.0.0.0:9150"
          resources:
            {{- toYaml $.ctx.Values.memcachedExporter.resources | nindent 12 }}
          securityContext:
            {{- toYaml $.ctx.Values.memcachedExporter.containerSecurityContext | nindent 12 }}
      {{- end }}

and values.yaml missing:

memcachedExporter:

  containerSecurityContext:
    readOnlyRootFilesystem: true

#### To Reproduce
helm install, cluster require readOnlyRootFilesystem true

#### Expected behavior

deploynent fail

#### Environment

- Infrastructure:Kubernetes
- Deployment tool: helm

#### Additional Context

mimir release 2.3.0-rc0
mimir helm  mimir-distributed-3.0.0.tgz

**Comment by dimitarvdimitrov** [comment]
the memcached templates have both a container and a pod security context

https://github.com/grafana/mimir/blob/14cc93085c276e87a262d92ea40a7292342a4718/operations/helm/charts/mimir-distributed/templates/memcached/_memcached-statefulset.tpl#L43-L44

https://github.com/grafana/mimir/blob/14cc93085c276e87a262d92ea40a7292342a4718/operations/helm/charts/mimir-distributed/templates/memcached/_memcached-statefulset.tpl#L105-L106

https://github.com/grafana/mimir/blob/14cc93085c276e87a262d92ea40a7292342a4718/operations/helm/charts/mimir-distributed/templates/memcached/_memcached-statefulset.tpl#L122-L123


Does this address your use-case?

I am working on #2595 which will also make the chart run with the new "restricted" pod security standard, which includes `readOnlyRootFilesystem`

**Comment by dimitarvdimitrov** [comment]
i think this is already addressed; feel free to reopen if you think something's still missing
