### ISSUE TITLE
Ruler API does not return `For` value when it is `0`

### ISSUE THREAD

**Issue by replay** [grafana/mimir#2946]
#### Describe the bug
When I save an alerting rule to the ruler API with a `For` value of `0` then it appears to get saved correctly, but when querying that rule from the API the `For` value does not get returned at all. The response looks like this:

```
{
    "name": "memcached",
    "rules": [
        {
            "alert": "MemcachedDown",
            "expr": "memcached_up == 0\n",
            "labels": {
                "severity": "critical"
            },
            "annotations": {
                "message": "Memcached Instance {{ $labels.job }} / {{ $labels.instance }} is down for more than 15mins."
            }
        }
    ]
}
```

If the `For` value is `>0` then it does get returned correctly, like for example here:

```
{
    "name": "memcached",
    "rules": [
        {
            "alert": "MemcachedDown",
            "expr": "memcached_up == 0\n",
            "for": "2m",
            "labels": {
                "severity": "critical"
            },
            "annotations": {
                "message": "Memcached Instance {{ $labels.job }} / {{ $labels.instance }} is down for more than 15mins."
            }
        }
    ]
}
```

The absence of the `For` value makes the alerting UI in Grafana replace it with its default value, which is `1min`. This means that when a user saves an alerting rule with a `For` value of `0min` via the UI and then looks at it the UI shows a `For` of `1min`. I guess it is arguable whether this is a UI bug or an API bug, but I think it makes sense that the UI would fill in its default for a value which is undefined by the response of the ruler API, so I'm leaning towards saying that's an API bug.

#### To Reproduce

Create an alerting rule via the ruler API which has a `For` value of `0`, then query it via the ruler API, the response does not show the `For` value.

#### Expected behavior

I think the ruler API should be explicit about the fact that the `For` value is `0`.

#### Environment

Grafana Cloud

**Comment by dimitarvdimitrov** [comment]
I wonder what the prometheus behaviour is for this - how does prometheus treat a missing `for` duration?

The code at least treats a zero-value as unset and vice-versa. https://github.com/grafana/mimir/blob/8fca3461c1e9f74cdbc98a8fc1fcfbbdcbbe24da/vendor/github.com/prometheus/prometheus/model/rulefmt/rulefmt.go#L161

which also means we need to fork this from prometehsu to make the change, if we choose to make the change in mimir.

I think the UI should be prepared for unset `for` and treat it like Prometheus does

**Comment by aknuds1** [comment]
@dimitarvdimitrov makes a good point, it's generally best to mirror Prometheus' design.

**Comment by pracucci** [comment]
I agree with Arve. We should get consistent with Prometheus. If we think this is an issue, then we should propose a change upstream.

**Comment by pracucci** [comment]
_Closing for now cause it looks like just the Prometheus behaviour._
