### ISSUE TITLE
Move rpm/deb Mimir package builds from fpm to nfpm

### ISSUE THREAD

**Issue by treid314** [grafana/mimir#2986]
#### Is your feature request related to a problem? Please describe.

Other Grafana projects, Loki, Tempo, and synthetic monitoring, have moved to using [nfpm](https://github.com/goreleaser/nfpm) for packaging the project as rpm and deb files while we are still using fpm.

#### Describe the solution you'd like
migrate the package builds to use nfpm/gorelaser similar to Tempo or Loki or Synthetic Monitoring

#### Describe alternatives you've considered

Keep using fpm which is lacking Grafana internal support and it's based on ruby rather than Go

#### Additional context
[Synthetic Monitoring Packaging](https://github.com/grafana/synthetic-monitoring-agent/blob/main/.goreleaser.yaml)
[Tempo Packaging](https://github.com/grafana/tempo/blob/main/.goreleaser.yml)
[Loki Packaging](https://github.com/grafana/loki/blob/main/tools/packaging/nfpm.jsonnet)

**Comment by aknuds1** [comment]
Didn't know about nFPM, sounds great that it's written in Go though! A recurring pain with FPM is it's in Ruby, and building the build image breaks e.g. due to the Ruby version being too old.
