### ISSUE TITLE
mimir-tool: analyse prometheus: ux: refactor / resiliency / concurrency

### ISSUE THREAD

**Issue by Dentrax** [grafana/mimir#3062]
[analyse_prometheus.go](https://github.com/grafana/mimir/blob/main/pkg/mimirtool/commands/analyse_prometheus.go) is not cleanly written and contains lots of duplicate logics. Also it does not have any resiliency and concurrency mechanism if we run against very large Prometheus instance. (it takes a few hours or longer). Here are my two cents:

* introduce [semgroup](https://github.com/fatih/semgroup) library for rate-limited concurrency (while traversing metrics x 2 times)
* introduce [backoff](https://github.com/cenkalti/backoff) library for retrying `v1api.Query()`
* use `sync.Map` and `sync.RWMutex` (for concurrency safety)
* move duplicate logics to basic functions (clean code practices)

cc @anilmisirlioglu

**Comment by dimitarvdimitrov** [comment]
FWIW I think it makes sense. Some notes on your suggestions:

> * introduce [semgroup](https://github.com/fatih/semgroup) library for rate-limited concurrency (while traversing metrics x 2 times)

we already use dskit's concurrency package to do that, see [the ruler](https://github.com/grafana/mimir/blob/f966684a65ac2dd44532eb990d5833297796bcc3/pkg/ruler/ruler.go#L727)

> * introduce [backoff](https://github.com/cenkalti/backoff) library for retrying v1api.Query()

we already use dskit's backoff - [example](https://github.com/grafana/mimir/blob/4b8cf2019a88d39231ab0b230701eeeb02079d12/vendor/github.com/grafana/dskit/grpcclient/backoff_retry.go#L16-L29)
