### ISSUE TITLE
Query-frontend should not query too far into the future

### ISSUE THREAD

**Issue by colega** [grafana/mimir#3144]
#### Is your feature request related to a problem? Please describe.

Query-frontend is currently splitting the entire query range, without checking if it's spanning into the future.

However, the `creation_grace_period` limit prevents samples from being ingested too far into the future, so these queries are useless.

While they would return almost instantly, in a long (days into the future) those queries take part of the max sharding quota which won't happen in reality.

#### Describe the solution you'd like

Query-frontend should truncate the range queries at `now + creation_grace_period` in the future before splitting and sharding them.

**Comment by kitrak-rev** [comment]
I will like to contribute to this issue.

**Comment by pracucci** [comment]
Exciting! Let me write some guidelines (_will post shortly_).

**Comment by pracucci** [comment]
Mimir supports a configuration option which allows you to limit samples from being ingested too far into the future. It's default value is 10 minutes:

```yaml
# (advanced) Controls how far into the future incoming samples are accepted
# compared to the wall clock. Any sample with timestamp `t` will be rejected if
# `t > (now + validation.create-grace-period)`.
# CLI flag: -validation.create-grace-period
[creation_grace_period: <duration> | default = 10m]
```

The configuration for this limit is here:
https://github.com/grafana/mimir/blob/244289a001cc828996cc708d51a18c019b151f24/pkg/util/validation/limits.go#L185-L186

When this limit is > 0 it means that it should be applied, while if the value is <= 0 then the limit should not be enforced. When the limit is > 0 we can safely truncate the time range of a range query whose `end` is more than `create-grace-period` in the future.

Where can do this truncation? Here, were we already do something similar:
https://github.com/grafana/mimir/blob/244289a001cc828996cc708d51a18c019b151f24/pkg/frontend/querymiddleware/limits.go#L81

For example, we do something similar with the `start`:
https://github.com/grafana/mimir/blob/244289a001cc828996cc708d51a18c019b151f24/pkg/frontend/querymiddleware/limits.go#L107-L115

Just today another person is working on that function (to fix another issue), so you can you look at this PR as reference:
https://github.com/grafana/mimir/pull/3134

**Comment by hi-rustin** [comment]
I would like to try it. Could you please assign this issue to me? Thanks!

**Comment by pracucci** [comment]
> I would like to try it. Could you please assign this issue to me? Thanks!

@hi-rustin Sure, it's your!

**Comment by dimitarvdimitrov** [comment]
I have doubts about this change: there are some legitimate cases when using `predict_linear` for example. I think we should keep allowing queries arbitrarily into the future. I came across this while reviewing the impact of https://github.com/grafana/mimir/pull/7496
