### ISSUE TITLE
Track the installation mode via the anonymous usage statistics

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#3149]
I would like to track via the anonymous usage statistics how was installed Mimir (Helm, Jsonnet, other). To make the tracking reliable I propose to add a new configuration option `-usage-stats.installation-mode` (defaults to `custom`), and then have Helm setting it to `helm`, and jsonnet to `jsonnet`.

**Comment by hi-rustin** [comment]
This looks like very fun. Can I have a try? Could you please add some guides?

**Comment by pstibrany** [comment]
> This looks like very fun. Can I have a try? Could you please add some guides?

You will need to 
1) add configuration option as suggested by this issue
2) initialize installation mode in [`initUsageStats`](https://github.com/grafana/mimir/blob/c996c46110e81ca908a0c12ad592d4b2c21dc103/pkg/mimir/modules.go#L761-L782), by using `usagestats.GetString(...).Set(value)` similar to what `initUsageStats` does for `"blocks_storage_backend"` [here](https://github.com/grafana/mimir/blob/c996c46110e81ca908a0c12ad592d4b2c21dc103/pkg/mimir/modules.go#L777-L778).

I think that's it.

**Comment by pracucci** [comment]
> Then we should modify Jsonnet and Helm to set the values.

Yes, this too.

For jsonnet you can just inject a CLI flag to each component (e.g. a way could be define a dedicated config block `usageStatsConfig` similarly to `grpcConfig` in `operations/mimir/config.libsonnet` and merge it in every component args (similarly to what do we with `grpcConfig`).

For Helm, let's ask some help to @Logiraptor.

**Comment by Logiraptor** [comment]
For helm I would add an entry under `mimir.config` in the default `values.yaml` file here: https://github.com/grafana/mimir/blob/e7199818e100ab5d2038bd3bf0b1a6163624a347/operations/helm/charts/mimir-distributed/values.yaml#L83

So this means the new configuration option would be available via both CLI and yaml configuration like most other flags.
