### ISSUE TITLE
Upgrade mimir-prometheus

### ISSUE THREAD

**Issue by codesome** [grafana/mimir#3175]
mimir-prometheus is being synced with upstream Prometheus ([here](https://github.com/grafana/mimir-prometheus/pull/337)) and it comes with few changes. So I am opening this PR with a checklist of things to do before/when upgrading mimir-prometheus here.

- [x] Prometheus changed the block meta format for identifying out of order block. We need to update mimir-prometheus to identify both old and new way for the next Mimir release and get rid of old way after 2 releases (that is the usual time to wait to remove something, right?).
- [x] Overlapping compaction is now enabled by default in TSDB. Make sure to explicitly set it to false for ingesters.

**Comment by pracucci** [comment]
> and get rid of old way after 2 releases (that is the usual time to wait to remove something, right?).

I think we need to wait at least the next next Mimir release (so 2.6.0) before dropping it.

**Comment by 56quarters** [comment]
I merged the update to Prometheus in Mimir without noticing this issue. Overlapping compaction is is false in Mimir but I didn't update mimir-prometheus to identify old and new meta formts. I will begin working on that now.

**Comment by 56quarters** [comment]
If I understand correctly:
* Upstream Prometheus uses a  [hint in the `BlockMetaCompaction` struct](https://github.com/prometheus/prometheus/blob/5ac12ac3517be1f1150d68e05df030edec4e85d4/tsdb/block.go#L196-L206) to indicate if a block contains OOO samples.
* Our fork previously used an `OutOfOrder` bool directly only the `BlocksMeta` struct.
* Now, our fork uses [both the `OutOfOrder` bool and the compaction hint](https://github.com/grafana/mimir-prometheus/blob/c77b24bcb23f9c2281ee9596be272f884a9c2bd7/tsdb/db.go#L1666-L1679) to determine if a block contains OOO samples.

So it seems like the first task of changing mimir-prometheus to identify the old and new way is already done (as part of grafana/mimir-prometheus#337)? Can you confirm if this is the case @codesome or have I missed something?

**Comment by codesome** [comment]
@56quarters you are right, everything is taken care.

**Comment by 56quarters** [comment]
Excellent. I'll open another issue to remove the use of the `OutOfOrder` bool later. OOO is an experimental feature so I don't think we're under any obligation beyond mentioning it in the changelog. On the other hand, it probably makes sense to do one Mimir release supporting both ways before removing the `OutOfOrder` bool so we're not purposefully breaking people that wanted to try the feature out.
