### ISSUE TITLE
Distributor returns 500 HTTP status code on 400 from ingester

### ISSUE THREAD

**Issue by Logiraptor** [grafana/mimir#3210]
#### Describe the bug

Between weekly-r206 and weekly-r207 a regression was introduced that causes the distributor to return a 500 status code on receiving a 400 from the ingester. This is problematic because it means remote write clients will retry the request indefinitely despite it being invalid.

#### To Reproduce

1. Start Mimir (weekly-r207)
2. Write a too-old sample
3. Observe that the ingester rejects with 400
4. Observe that the distributor rejects with 500

#### Expected behavior

The distributor should reject with the same status code as ingester.

#### Environment

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
- Deployment tool: [e.g., helm, jsonnet]

**Comment by Logiraptor** [comment]
I think I know what the issue is.

https://github.com/grafana/mimir/pull/3055 wraps errors from the ingesters with errors.Wrap.
This changes the type of the error from `status.ErrorProto` created here: https://github.com/grafana/mimir/blob/d857bf9a34e9cd48c3441ce01d8e7027722abc55/vendor/github.com/weaveworks/common/httpgrpc/httpgrpc.go#L29-L33
In turn, this makes the httpgrpc error handling break here: https://github.com/grafana/mimir/blob/d857bf9a34e9cd48c3441ce01d8e7027722abc55/vendor/github.com/gogo/status/status.go#L144-L146

The error no longer satisfies that interface.

**Comment by pr00se** [comment]
Yes, any `error` that does not succeed `status.FromError()` will be turned into a 500:
https://github.com/grafana/mimir/blob/main/pkg/util/push/push.go#L131-L133
