### ISSUE TITLE
Queries timing out before querier.timeout is reached

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#3248]
### Background

We have (at least) two settings for timeouts on the read path:

does that mean we need to align this param
```
-server.http-write-timeout (default 30s)
```
and 
```
-querier.timeout (default 2m)
```

The former applies to all requests. The latter applies to queries only.

### Problem

A big query times out because of the server limit and the request returns a 502 and the query-frontend logs this error
```
level=warn caller=logging.go:67 msg="POST /prometheus/api/v1/query_range 1m0.37145661s, error: write tcp 10.133.34.34:9009->10.133.34.34:44326: i/o timeout ws: false; Accept-Encoding: gzip; ..."
```

but it actually completes if it's under the querier limit. Once it completes, it's cached. So another invocation will serve the cached result.

This is a weird behaviour and from the first error it's not obvious what the root cause it.

### Proposal 

Align the two values - either make the server timeout equal the querier one or vice versa. I don't see a problem in having a longer timeout exactly because there are some heavy queries that take longer. 

Furthermore, add validation to mimir so that a querier timeout that's longer than the server timeout crashes mimir on startup. This may be tricky since the two are in two faraway places in the config. One way to do this is to pass the whole config to the [validation method of the querier config](https://github.com/grafana/mimir/blob/6ebce3c775352c515474b5ae8efeb042b408d616/pkg/querier/querier.go#L82) so it can validate itself holistically.

**Comment by pracucci** [comment]
> Furthermore, add validation to mimir so that a querier timeout that's longer than the server timeout crashes mimir on startup. This may be tricky since the two are in two faraway places in the config. 

We already have such time of checks. Add such checks to `Config.Validate()` in `pkg/mimir/mimir.go` (e.g. `validateBucketConfigs()`).

**Comment by stevesg** [comment]
FWIW At Grafana Labs, we have increased `-server.http-write-timeout` on the `query-frontend` to our upstream timeout + 30s.

**Comment by hi-rustin** [comment]
I am working on this.
