### ISSUE TITLE
Docs: How to use tools

### ISSUE THREAD

**Issue by ddellarocca** [grafana/mimir#3259]
In our Mimir installation we have a partial block that causes compactor to spit warnings in log whenever it starts, we want to mark that block to delete as in the docs https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimirtenanthaspartialblocks.

But how can i use that tool? (markblock) in the docs is not present https://grafana.com/docs/mimir/latest/operators-guide/tools/ and it doesn't show how to use them (spawn a pod in the mimir namespace? run it locally? run it inside a shell of the compactor?)

**Comment by pstibrany** [comment]
> spawn a pod in the mimir namespace? run it locally? run it inside a shell of the compactor?

Markblock is standalone CLI tool. It doesn't matter where or how you run it from, but it needs to have access to the bucket with blocks (specified via cli flags).

We currently don't build binaries of `markblock` or provide Docker images. You will need to build it manually.

**Comment by ddellarocca** [comment]
Is there any guide on how to build that tool?

**Comment by aknuds1** [comment]
I don't think it's documented, but you can build it as follows:

```shell
make tools/markblocks/markblocks
```
