### ISSUE TITLE
Restructure Helm chart documentation in its new location ./docs/sources/helm-chart/

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#3275]
The new rewritten documentation should live under `docs/sources/helm-chart`

- [x] Add release notes for Grafana Mimir Helm chart; leave the release notes for previous Mimir releases as-was.
- [x] Retroactively create release notes for the previous two releases of Grafana Mimir Helm chart.
- [x] Remove Helm-related content from `docs/sources/mimir/operators-guide/monitor-grafana-mimir/collecting-metrics-and-logs.md`.
- [x] Remove non-Helm-related content from `docs/sources/helm-charts/mimir-distributed/collecting-metrics-and-logs.md`.
- #3925
- #3926
- Reconcile #3867.
- [x] Figure out what to do with all the aliases; should they exist? It does not make sense to add any aliases because pages have been removed from Mimir.
- #3924

### Proposed structure

- Helm chart  - overview and mention that the chart is officially supported
  - Get started - current _Get started with Helm chart_ (non-production)
  - Run in production - the new _Run in production_ guide
  - Concepts(?) (TO BE VETTED BY URSULA AND KRAJO and posted here thereafter)
    - HA deduplication with consul
    - Configure management with Helm
    - Metamonitor ...

**Comment by dimitarvdimitrov** [comment]
i can pick up the changes around `docs/sources/mimir/migration-guide/migrating-from-cortex.md` and `docs/sources/helm-charts/mimir-distributed/migrating-from-cortex.md`

**Comment by osg-grafana** [comment]
Created follow-on issues for engineers to work on and I am moving over to core Mimir content work.
