### ISSUE TITLE
Publish Mimir / GEM Helm chart documentation under Mimir documentation

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#3277]
**Note: This is a potential, workaround interim solution.**

Create a new top level item in the published Mimir documentation for the Helm chart

![image](https://user-images.githubusercontent.com/13435893/197160977-9e8391a5-c746-4b1d-8250-7af3c462f43c.png)

**Comment by dimitarvdimitrov** [comment]
looks good to me as long as existing link into the `latest` version don't break

**Comment by Logiraptor** [comment]
No objection from me :+1:

**Comment by osg-grafana** [comment]
Closed in favor of https://github.com/grafana/website/pull/10518.
