### ISSUE TITLE
Docs: storage retention 

### ISSUE THREAD

**Issue by David-aylward** [grafana/mimir#3279]
Hi,
This may be a stupid question, but How do I set the retention period of data in Mimir? 

In Prometheus, this is achieved with(
--storage.tsdb.retention.time command-line flag for configuring the lifetime for the stored data).

But I cannot find out how to set storage retention for data that has been written to the S3 storage.

Please point me in the right direction if I've missed something.

Thanks.

**Comment by pracucci** [comment]
Hi @David-aylward, the storage retention can be configured using this configuration option:
```
# Delete blocks containing samples older than the specified retention period.
# Also used by query-frontend to avoid querying beyond the retention period. 0
# to disable.
# CLI flag: -compactor.blocks-retention-period
[compactor_blocks_retention_period: <duration> | default = 0s]
```

Duplicated of https://github.com/grafana/mimir/issues/93
