### ISSUE TITLE
Add TSDB index bytes used by query to slow query dashboard

### ISSUE THREAD

**Issue by 56quarters** [grafana/mimir#3293]
#### Is your feature request related to a problem? Please describe.

In #3206 the number of TSDB bytes used by a particular query was added to the query logs because it's useful for identifying unexpectedly expensive queries.

#### Describe the solution you'd like

We should start including this stat in the slow queries dashboard.

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by hi-rustin** [comment]
> We should start including this stat in the slow queries dashboard.

@56quarters Could you please give some tips about how to test it?

**Comment by 56quarters** [comment]
Actually it seems this field is being automatically added to the "Slow Queries" dashboard already by virtue of being included in the query-frontend query logs. Nothing to do here!
