### ISSUE TITLE
Store-Gateway: High memory allocation loading bucket block chunks

### ISSUE THREAD

**Issue by ortuman** [grafana/mimir#3306]
#### Describe the bug

Store-gateway memory profiles shows a high memory usage when populating chunks from a bucket block. 

![prof](https://user-images.githubusercontent.com/888899/197781687-a78329b1-483b-4fd8-aa45-bdfea8eceae0.png)

The above screenshot shows that roughly `26%` of total allocated objects are generated while invoking `loadChunks`, and `22%` is distributed between the functions `populateChunk` and `loadChunk` itself.

[store-gateway.cortex-prod-01.mem.profile.zip](https://github.com/grafana/mimir/files/9860518/store-gateway.cortex-prod-01.mem.profile.zip)

**Comment by dimitarvdimitrov** [comment]
this should be accounted for with the pooling done for chunks now https://github.com/grafana/mimir/blob/02a486421b79a76a5f5ec703b0d78639e51a0f6f/pkg/storegateway/series_chunks.go#L398
