### ISSUE TITLE
PromQL compatibility: Functions and aggregations operating on longer range of data than available returns NaN 

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/mimir#3317]
#### Describe the bug
Running any of the functions or aggregations listed below on a range vector longer than the history of the selected time serie, the result is `NaN` which is inconsistent with Prometheus which returns a result computed based just on the data available. 

> Interestingly Thanos appears to handle this for the `rate` and `increase` but also resturns NaN for the rest of functions/aggregations

**Affected functions:** `rate`, `increase`, `delta`
**Affected aggregations `_over_time`:** `avg`, `sum`, `stddev`

Maybe more functions/aggregations are affected, I did not test all of them.

#### To Reproduce

Run `rate(<selector>[<duration_longer_than_retention>])` on Prometheus and Mimir and compare results. Mimir will return `NaN`.
Or if not possible to run query on longer time period than retention than choose some metric which got recently created and use that.

#### Expected behavior

Mimir PromQL execution to be compliant with Prometheus. 

#### Additional Context
Maybe such test should be added to the https://github.com/prometheus/compliance? :thinking:

**Comment by bboreham** [comment]
Thanks for your report.  I suspect "duration_longer_than_retention" is the key part, since it is very common to query data older than one specific series and we do not see NaN all the time.

I was unable to replicate your symptom on a couple of Mimir installs at hand. Perhaps because we set `querier.max-query-lookback` slightly shorter than the store retention period.

Could you reply with some more specifics about what you queried, and your retention and lookback settings?

**Comment by FUSAKLA** [comment]
Mimir version used is 2.4.0 but same happening on 2.3.0
Retention is currently disabled and lookback is set to 5m (default).

But the issue is not necessarily related just to retention. If you find a newly created time series (for example new instance after rollout) and run `increase(up{instance="<new_pod_name>"}[5m])` so that the 10m window overlaps start of the time series so the range vector selector to start at point where the data does not exist and end in the point where the data already do exist.
See image below for illustration.

![image](https://user-images.githubusercontent.com/6112562/199717563-05cfba76-473a-4f0d-b425-b5881f00380f.png)

**Comment by pracucci** [comment]
Does it happen with query sharding enabled or disabled?

**Comment by FUSAKLA** [comment]
Hm, ⁣:thinking: that's good question, now it’s enabled, I'll try disabling it if it helps.

**Comment by pracucci** [comment]
> Hm, ⁣🤔 that's good question, now it’s enabled, I'll try disabling it if it helps.

Ok thanks. Let me know if disabling query sharding solves this issue, cause that's the only thing that's coming to my mind may cause it. If so, we'll then investigate it in query sharding, trying to reproduce with a test first.

**Comment by FUSAKLA** [comment]
Hmm, I investigated the issue a bit deeper and found out the issue is probably something else.
I suspected there were no data, but that was not the case, actually there were `NaN`s causing the result (not sure how the `NaN`s got there, but that is a different issue, They are not in the original Prometheus but are remote written in Mimir :thinking: ). 

```
NaN @1666186814.964
NaN @1666186834.966
NaN @1666186854.964
NaN @1666186874.964
NaN @1666186894.964
2 @1666187009.154
2 @1666187029.154
2 @1666187049.154
2 @1666187069.154
2 @1666187089.154
2 @1666187109.154
2 @1666187129.154
2 @1666187149.154
2 @1666187169.154
```

Tested with promtool, PromQL handles `NaN`s the same way, so it is not a case of compatibility issue with PromQL
```yaml
tests:
    - interval: 1m
      input_series:
          - series: 'test1'
            values: 'NaN NaN NaN NaN NaN 1 1 1 1 1 1 1 1 1'
          - series: 'test2'
            values: '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'
      promql_expr_test:
        - expr: rate(test1[4m])
          eval_time: 10m
        - expr: rate(test2[1h])
          eval_time: 10m
        - expr: rate(test1[10m])
          eval_time: 10m
```

```bash
Unit Testing:  etst.yaml
  FAILED:
    expr: "rate(test1[4m])", time: 10m,
        exp: nil
        got: {} 0E+00

    expr: "rate(test2[1h])", time: 10m,
        exp: nil
        got: {} 0E+00

    expr: "rate(test1[10m])", time: 10m,
        exp: nil
        got: {} NaN
```

I'm sorry for misinterpretation of the issue. Closing this one.
