### ISSUE TITLE
enforce max_fetched_series_per_query in store-gateway

### ISSUE THREAD

**Issue by 56quarters** [grafana/mimir#3382]
#### Is your feature request related to a problem? Please describe.

There are a few limits related to the max amount of work a query may do. A non-exhaustive list:

* `max_fetched_chunks_per_query`
* `max_fetched_series_per_query`

Both of these limits can be set and are enforced in the queriers. `max_fetched_chunks_per_query` is _also_ enforced in the store-gateways. For some reason, `max_fetched_series_per_query` is [not enforced in the store-gateway](https://github.com/grafana/mimir/blob/453ae5a0ba03f1759a846980a2564d9bdced985e/pkg/storegateway/bucket_stores.go#L477). I don't know the motivation behind this but as I recently discovered, expensive _series_ requests can cause OOMs in store-gateways before the limit is even applied in the querier. E.g. `/prometheus/api/v1/series` request with the matcher `{cluster=~"prod-.*"}`

#### Describe the solution you'd like

Add the ability to enforce a maximum number of series per query, enforced in the store-gateway in addition to how it is currently enforced in the querier.

#### Describe alternatives you've considered

Adding more computer so these requests can succeed.

#### Additional context

:cry: 

![Screenshot 2022-11-03 at 13-53-39 Mimir _ Reads resources - Dashboards - Grafana](https://user-images.githubusercontent.com/1127373/199798121-523c3f3a-82da-49b6-b4d9-8d8d7ff1b5ac.png)

**Comment by 56quarters** [comment]
I think I've misunderstood the `max_fetched_series_per_query` limit. It is enforced in the querier during `query` or `query_range` requests, not during `series` requests.

So that means there are two problems here:

* `max_fetched_series_per_query` not enforced in store-gateway during `query`, `query_range`, or `series` requests.
* `max_fetched_series_per_query` not enforced in queriers during `series` requests though looking at the code, seems like it should be. Perhaps I'm misunderstanding it.

I think both of these should be fixed since it's quite possible to run very expensive `/series` requests and cause OOMs in the store-gateways and queriers.

**Comment by 56quarters** [comment]
_deleted a previous comment that was incorrect_

One complication with this is that queriers currently treat all errors from the store-gateways the same: they'll try another store-gateway to get results from the expected blocks and if they don't, they'll return a "consistency check failed" message to the caller. This will make it very difficult for users to figure out what's actually going on (that they are hitting a limit).

**Comment by pracucci** [comment]
> I don't know the motivation behind this but as I recently discovered, expensive series requests can cause OOMs in store-gateways before the limit is even applied in the querier.

I think the reason why it's not enforced in the store-gateway is that we though it's unlikely to be hit there if the query touches many blocks (spread across many store-gateways). The limit is global (applies to the whole query), but each store-gateway only processes a subset of the series.

Anyway, I think enforcing it in the store-gateway too doesn't hurt. If a limit is hit in the store-gateway then it will be definitely hit in the querier too, so the earlier we detect it, the better.

> One complication with this is that queriers currently treat all errors from the store-gateways the same

This is just an implementation detail. We can use the grpc error code as usual to propagate the type of error from store-gateway to querier (e.g. 429 in case of limit hit), and then modify the querier to correctly handle it.

**Comment by 56quarters** [comment]
I'm not sure this issue is relevant anymore now that streaming has been implemented for series requests in the store-gateway.
