### ISSUE TITLE
OTLP Endpoint not working in Helm Chart

### ISSUE THREAD

**Issue by jasase** [grafana/mimir#3424]
#### Describe the bug
Endpoint for OTLP does not exists in nginx configuration of distributed Helm Chart

#### To Reproduce

1. Start mimir-distributed helm chart without configuration
2. Sending otlp request to http://<address-of-nginx>/otlp

Resulting in HTTP Status 404

#### Expected behavior

Request should be excepted as described in documentation: https://grafana.com/docs/mimir/latest/operators-guide/configure/configure-otel-collector/

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

**Comment by Logiraptor** [comment]
Good find! Would you be interested in opening a PR? I'd be happy to review one for you.
