### ISSUE TITLE
Add S3 storage class configuration

### ISSUE THREAD

**Issue by amitsetty** [grafana/mimir#3438]
Hey,
Right now if I understand correctly Mimir only works with the “Standard” storage class. Due to price concerns we’d want to run Mimir with the “Standard-IA” Storage Class in the same way this ( https://github.com/grafana/tempo/pull/1714 ) pr adds storage class configuration for tempo

**Comment by pracucci** [comment]
👋 Hi! Can you configure the storage class directly at the bucket level?

That being said, make sure you take in account the read operations cost when comparing "Standard" vs "Standard-IA". Even if "Standard-IA" storage may be cheaper, each read request may be more expensive, and depending on your access pattern you may end up with higher costs at the end. Have you considered it?

**Comment by paalkr** [comment]
I would recommend using intelligent tiering for the Mimir buckets.
https://aws.amazon.com/s3/storage-classes/intelligent-tiering/

You will absolutely save money, as AWS tracks your objects and only moves infrequent accessed object to other storage tiers. Some very unlikely usage patterns might not be suited for intelligent tiering.

Her is an example from one of our Mimir S3 buckets, using intelligent tiering
![image](https://user-images.githubusercontent.com/9726307/202019470-743b7220-c364-4a36-beaf-088321dbf7fa.png)

**Comment by amitsetty** [comment]
Intelligent tiering seems useful but due to our on prem solution it seems it won’t work for us 

It seems that when uploading blocks to s3 a header must be added in order to tell the s3 what the storage class is. 

Thanos objstore supports this since (https://github.com/thanos-io/objstore/pull/25) 

The only change that would be necessary would be to make this configurable
