### ISSUE TITLE
Docs feedback: /operators-guide/monitor-grafana-mimir/requirements.md

### ISSUE THREAD

**Issue by amyyenjungpeng** [grafana/mimir#3494]
Hi Team,
  For Deployment type part, there is a typo in `If you’re running Mimir on baremental`. Thank you.

**Comment by pracucci** [comment]
👋 Thanks @amyyenjungpeng for reporting it! Willing to open a PR to fix it, please?

**Comment by 56quarters** [comment]
Fixed via #3482
