### ISSUE TITLE
mimirtool rules sync should delete missing rules

### ISSUE THREAD

**Issue by bilbof** [grafana/mimir#3495]
#### Is your feature request related to a problem? Please describe.

`mimirtool rules sync` lets you upload and update rule groups, but it does not delete rules groups that aren't in code.

We've decided to use Thanos Ruler instead, since it has Prometheus operator support.

#### Describe the solution you'd like

`mimirtool rules sync --delete` would delete rule groups not present in the directory

**Comment by pracucci** [comment]
The `mimirtool rules sync` command is expected to delete rule groups not existing anymore in the local config files. Could you provide an example to reproduce it, please?

**Comment by bilbof** [comment]
I'll close this - I ended up dropping my use of mimirtool in favor of using Thanos Ruler -> Mimir for rule evaluation (for PrometheusRule CRD support), but I have been meaning to try out the Grafana Agent integration lately - this is really cool https://github.com/grafana/agent/pull/2604
