### ISSUE TITLE
Querier error : the consistency check failed because some blocks were not queried (err-mimir-store-consistency-check-failed)

### ISSUE THREAD

**Issue by vikasbudhwat** [grafana/mimir#3499]
#### Describe the bug
Mimir querier giving error when queried for data.
`querier ts=2022-11-23T13:12:20.458786731Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.LabelName │
│ s level=warn msg="unable to get store-gateway clients while retrying to fetch missing blocks" err="no store-gateway  │
│ instance left after checking exclude for block 01GJJ72920HJX9HR5S56*****"                                           │
│ querier ts=2022-11-23T13:12:20.458815269Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.LabelName │
│ s level=warn user=anonymous msg="failed consistency check" err=null                                                  │
│ querier ts=2022-11-23T13:12:20.460855041Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.selectSor │
│ ted level=warn msg="unable to get store-gateway clients while retrying to fetch missing blocks" err="no store-gatewa │
│ y instance left after checking exclude for block 01GJJ72W4YKGC8P2ZE91*****"                                         │
│ querier ts=2022-11-23T13:12:20.460887132Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.selectSor │
│ ted level=warn user=anonymous msg="failed consistency check" err=null`

#### To Reproduce
keep the mimir running for enough time till local storage is fulled by header index

1. Start Mimir (SHA or version): 
2. Perform Operations(Read/Write/Others): Read

#### Expected behavior

When queried for metrics/data querier should return the result.

#### Environment

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
- Deployment tool: [e.g., helm, jsonnet]

#### Additional Context

Mimir is running on cluster since 2 weeks.
it was tested and querier were fetching the metrics.
mimir config for bucket_store was
`bucket_store:
        sync_dir: /data/tsdb-sync
        ignore_blocks_within: 5m
        bucket_index:
          max_stale_period: 1h`

Error logs from querier
`querier ts=2022-11-23T13:12:20.458786731Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.LabelName │
│ s level=warn msg="unable to get store-gateway clients while retrying to fetch missing blocks" err="no store-gateway  │
│ instance left after checking exclude for block 01GJJ72920HJX9HR5S56QYESCC"                                           │
│ querier ts=2022-11-23T13:12:20.458815269Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.LabelName │
│ s level=warn user=anonymous msg="failed consistency check" err=null                                                  │
│ querier ts=2022-11-23T13:12:20.460855041Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.selectSor │
│ ted level=warn msg="unable to get store-gateway clients while retrying to fetch missing blocks" err="no store-gatewa │
│ y instance left after checking exclude for block 01GJJ72W4YKGC8P2ZE91QPGZKJ"                                         │
│ querier ts=2022-11-23T13:12:20.460887132Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.selectSor │
│ ted level=warn user=anonymous msg="failed consistency check" err=null`

**post error it was observed that sync-dir(/data/tsdb-sync) was fulled (50Gi), this has header index since few weeks(old one as well).
and the block mentioned in logs are latest blocks(checked in backend storage s3). which are not synced in index-header due to lack of space**

tried to set some parameter to clean the header index from locar disk space by configuring 
`      bucket_store:
        sync_dir: /data/tsdb-sync
        ignore_blocks_within: 5m
        index_header_lazy_loading_enabled: true
        index_header_lazy_loading_idle_timeout: 1d
        bucket_index:
          max_stale_period: 1h`

but this didn't work .. and no cleanup happens for block index-header.

may be I am missing to parameter to set the block index-header cleanup, timeout to clean local disk. please suggest

**Comment by aknuds1** [comment]
Converting this to a discussion, since I don't think it identifies a bug.
