### ISSUE TITLE
Ingesters crash when trying to rename WAL/WBL file for repair (no such file or directory)

### ISSUE THREAD

**Issue by sysedwinistrator** [grafana/mimir#3635]
#### Describe the bug

During ingester restarts (mostly due to StatefulSet rollout), sometimes some ingesters crash with this error message:
```json
{
  "caller": "ingester.go:1748",
  "err": "unable to open TSDB for user AFFECTED_TENANT: failed to open TSDB: /data/tsdb/AFFECTED_TENANT: repair corrupted WAL: rename /data/tsdb/AFFECTED_TENANT/wal/00000666 /data/tsdb/AFFECTED_TENANT/wal/00000666.repair: no such file or directory",
  "level": "error",
  "msg": "error while opening existing TSDBs",
  "ts": "2022-12-02T12:13:26.76264231Z"
}
{
  "caller": "mimir.go:771",
  "err": "invalid service state: Failed, expected: Running, failure: opening existing TSDBs: unable to open TSDB for user AFFECTED_TENANT: failed to open TSDB: /data/tsdb/AFFECTED_TENANT: repair corrupted WAL: rename /data/tsdb/AFFECTED_TENANT/wal/00000666 /data/tsdb/AFFECTED_TENANT/wal/00000666.repair: no such file or directory",
  "level": "error",
  "module": "ingester-service",
  "msg": "module failed",
  "ts": "2022-12-02T12:13:26.788767051Z"
}
```
When opening a shell on the affected container, the file does indeed not exist. However, whenever we checked for the file, we **did find a file of the same name in the `wbl` directory of the TSDB dir**. We have enabled out-of-order ingestion by setting `limits.out_of_order_time_window` to `2m` in the Mimir config, which is probably why there is any data in the WBL (write-behind-log) at all.  

It looks like the code that repairs corrupted files in the WBL incorrectly calls code that assumes them to be in the WAL.

#### To Reproduce

1. Start Mimir 2.3.1 with out-of-order-ingestion enabled
2. Restart ingesters
3. Possibly get corrupted files due to OOMKills of ingesters during startup

#### Expected behavior

When trying to repair corrupted files in the WBL, the correct path should be used.

#### Environment

- Infrastructure: Kubernetes (GKE)
- Deployment tool: helm

**Comment by pracucci** [comment]
Thanks for reporting it! Let me loop in @jesusvazquez which worked on the OOO ingestion.

**Comment by tonychoe** [comment]
We've experienced the same issue.

**Comment by sysedwinistrator** [comment]
> We've experienced the same issue.

@tonychoe Do you also have out-of-order ingestion enabled?

**Comment by wrdls** [comment]
We hit this issue as well after an OOMKill with `limits.out_of_order_time_window` set.

```
caller=mimir.go:837 level=error msg="module failed" module=ingester-service err="invalid service state: Failed, expected: Running, failure: opening existing TSDBs: unable to open TSDB for user anonymous: failed to open TSDB: /data/tsdb/anonymous: repair corrupted WAL: rename /data/tsdb/anonymous/wal/00000018 /data/tsdb/anonymous/wal/00000018.repair: no such file or directory"
```

Is there any workaround for this?

---

mimir version: `2.9.0`
helm chart version: `5.0.0`
kubernetes version: `v1.27.3-gke.1700`

**Comment by jesusvazquez** [comment]
We merged the fix into prometheus a few days ago https://github.com/prometheus/prometheus/commit/4df2f2432bc017fd21c81aff91f4845b5d44dd93

Mimir will eventually catch up and this will be fixed :+1:

**Comment by pracucci** [comment]
_Closing for now, but can re-opened any time if the change doesn't fix the issue._

**Comment by lookcrabs** [comment]
Cross commenting here just in case it helps anyone -- and to find out if this is a bad idea. 
I'm on the helm chart for `mimir-distributed 5.2.1` with mimir `2.10` in it. 


This is one of the top hits in google when I searched for "mimir" "corruption" "file not found"
I don't know if this helps but this is what I did to fix this on my corrupt ingester that was failing to start. 

if you're in kubernetes: 
Replace the existing pod with a debug pod:
```
kubectl -n mimir debug mimir-ingester-zone-a-4 -it --copy-to mimir-ingester-zone-a-4 --same-node --replace --image=ubuntu:latest --share-processes -- /bin/bash
```

* Inside your debug container find the pid of the mimir process and cd into /proc/${MIMIR_PID}/root/data/ -- for me this was /proc/7/root/data/

* find the wdb // wal file for your corrupt chunk and rename it to ${CHUNK}.repair
IE this would be `mv /proc/7/root/data/tsdb/anonymous/wal/0000000011{,.repair}` AND/OR `mv /proc/7/root/data/tsdb/anonymous/wdb/0000000011{,.repair}` 


This let my ingester start again but I don't know if this causes any issues on the compactor or any other part of the cluster. My guess is anything in that chunk will be removed so keep that in mind.
