### ISSUE TITLE
Docs: Wrong path to the tutorial "Play with Grafana Mimir"

### ISSUE THREAD

**Issue by egarbi** [grafana/mimir#3659]
#### Is your documentation request related to a feature? If so, which one?

It's not, It's a bug.

#### Describe the solution that you’d like or the expected outcome
The path to playing with the Grafana tutorial is wrong
<img width="646" alt="Screenshot 2022-12-06 at 14 12 23" src="https://user-images.githubusercontent.com/2984201/205921820-6237a5df-f311-40dd-884a-5f0ca33e34bd.png">

It should be `docs/sources/mimir/tutorials/play-with-grafana-mimir/`

**Comment by egarbi** [comment]
It seems this is already fixed in the code, it might be just waiting for the release. 
See [here](https://grafana.com/tutorials/play-with-grafana-mimir/)

**Comment by GrafanaWriter** [comment]
@osg-grafana - can you please confirm whether this has been released? If so, please close.

**Comment by osg-grafana** [comment]
We added subdirectories for `mimir` and `helm-charts`, which made it into the 2.6 release; see https://github.com/grafana/mimir/tree/mimir-2.6.0/docs/sources.

**Comment by osg-grafana** [comment]
The link in the file is correct and released as such:

```
cd docs/sources/mimir/tutorials/play-with-grafana-mimir/
```
