### ISSUE TITLE
Rollout progress dashboard incorrectly uses Enterprise Gateway metrics even when gateway_enabled is false

### ISSUE THREAD

**Issue by klagroix** [grafana/mimir#3674]
#### Describe the bug

The 'Rollout Progress' mixin dashboard attempts to query for Enterprise Gateway metrics (`job=~"($namespace)/((gateway|cortex-gw|cortex-gw-internal))" `) even when the `gateway_enabled` config is set to false.

This can be seen in the precompiled dashboards in both the latest helm release ([mimir-distributed-3.3.0](https://github.com/grafana/mimir/blob/mimir-distributed-3.3.0/operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json#L219)) as well as [main](https://github.com/grafana/mimir/blob/main/operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json#L219)

#### To Reproduce

1. Run mimir-distributed helm chart in OSS mode (i.e. without enterprise enabled) 
2. Set `metaMonitoring.serviceMonitor.enabled: true` and have Prometheus scrape metrics 
3. Load the pre-compiled [Rollout Progress](https://github.com/grafana/mimir/blob/mimir-distributed-3.3.0/operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json) dashboard into Grafana
4. Note all the latency panels (the three rightmost panels) are all showing 'No Data'

#### Expected behavior

Enterprise Gateway metrics (`job=~"($namespace)/((gateway|cortex-gw|cortex-gw-internal))" `) should not be used when there is no gateway. In this case, nginx is used and the lines should be rewritten to use distributor / query-frontend metrics.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

#### Additional Context

There was a discussion about this in the Grafana Labs Community slack: https://grafana.slack.com/archives/C039863E8P7/p1670451226489819?thread_ts=1670448139.881039&cid=C039863E8P7

It was suggested that the lines here should be rewritten to use distributor / query-frontend metrics: https://github.com/grafana/mimir/blob/c44a07dd4c4e38a19ba01d676555c3c84d30b461/operations/mimir-mixin/dashboards/rollout-progress.libsonnet#L93-L190

**Comment by pracucci** [comment]
That's right @klagroix! Willing to work on the fix? I can provide some guidance if you need it.

**Comment by klagroix** [comment]
I took a quick crack at this here: https://github.com/grafana/mimir/pull/3709

Please let me know if this isn't the direction you were thinking or if there are any changes you think should be made.
