### ISSUE TITLE
Docs feedback: Finding where to install mimirtool

### ISSUE THREAD

**Issue by mjseaman** [grafana/mimir#3680]
## Background
I found myself in an odd docs loop and could use a hand detangling the steps in this process.

I set out to deploy some Grafana Cloud Rules from an alert rule config file. 

1. I went to grafana.com and found the alert component of my stack: https://grafana.com/orgs/[org]/hosted-alerts/[tenant].
2. This referred me to cortextool as a way to add my rules to Cloud. So far so good.
    > Our [Cloud rules and alerts documentation](https://grafana.com/docs/grafana-cloud/metrics/prometheus/alerts_rules/) explains in more detail how to use [cortextool](https://github.com/grafana/cortex-tools) to upload your rules and alerts.
4. So I clicked on the word cortextool which took me to the cortextool readme. But then the [Cortextool readme](https://github.com/grafana/cortex-tools) referred me to [mimirtool](https://grafana.com/docs/mimir/latest/operators-guide/tools/mimirtool/).
    > If you're using this tool with Grafana Mimir, please use the new mimirtool instead:
    > - [mimirtool documentation](https://grafana.com/docs/mimir/latest/operators-guide/tools/mimirtool/)
    > - [mimirtool releases](https://github.com/grafana/mimir/releases)
6. The [Mimirtool docs page](https://grafana.com/docs/mimir/latest/operators-guide/tools/mimirtool/#installation) referred me to the latest release to learn how to install it:
    > To install Grafana Mimirtool, refer to the [latest release](https://github.com/grafana/mimir/releases).
7. But that [Mimir release page](https://github.com/grafana/mimir/releases) didn't include any details on how to install Mimirtool. 
8. So I went back to cortextool and installed that, and figured out how to use it. But was I supposed to install mimirtool?

This was confusing and I'm wondering: 
1. Which tool do we want people to use to communicate with Cloud Metrics and Alertmanager? 
3. How do I actually install mimirtool?

## So here are some ideas after looking into it further:

1. https://grafana.com/orgs/[org]/hosted-alerts/[instance] says
    > Our [Cloud rules and alerts documentation](https://grafana.com/docs/grafana-cloud/metrics/prometheus/alerts_rules/) explains in more detail how to use [cortextool](https://github.com/grafana/cortex-tools) to upload your rules and alerts.

    However, maybe it should refer the user to [mimirtool docs](https://grafana.com/docs/grafana-cloud/legacy-alerting/alerts-rules/#download-and-install-mimirtool) instead.

2. The Main [Mimirtool docs page](https://grafana.com/docs/mimir/latest/operators-guide/tools/mimirtool/#installation) sends you to the mimir releases page to install mimirtool:
    > To install Grafana Mimirtool, refer to the [latest release](https://github.com/grafana/mimir/releases).

    However, maybe it should _also_ refer the user to [mimirtool](https://grafana.com/docs/grafana-cloud/legacy-alerting/alerts-rules/#download-and-install-mimirtool) instead.

4. The [mimirtool installation instructions I'm recommending above](https://grafana.com/docs/grafana-cloud/legacy-alerting/alerts-rules/#download-and-install-mimirtool) link to the same installation method twice:
    > Download or update to the latest version of mimirtool, either as a binary or a Docker image:
    > - https://github.com/grafana/cortex-tools/releases

    > If you prefer to use the binary then follow the instructions published as part of each [release](https://github.com/grafana/cortex-tools/releases).
    
    We can probably remove one of those.

    And for a final brain-explosion, this duplicated docs link actually sends me to the [_cortextool_ release page](https://github.com/grafana/cortex-tools/releases)... So how exactly do I actually install mimirtool from binary??

**Comment by charleskorn** [comment]
Thanks for the feedback @mjseaman.

I've just put together https://github.com/grafana/mimir/pull/3692 which should clarify some of our documentation, and I'm looking in to fixing the other outdated references to `cortextool`.

To answer your specific questions:

> 1. Which tool do we want people to use to communicate with Cloud Metrics and Alertmanager?

`mimirtool` is the recommended tool - as you pointed out, `cortextool` is deprecated.

> 2. How do I actually install mimirtool?

The easiest way is to go to [the latest release of Mimir](https://github.com/grafana/mimir/releases/latest) and download the appropriate `mimirtool` binary for your machine.

**Comment by mjseaman** [comment]
Thanks @charleskorn !

**Comment by charleskorn** [comment]
I believe this is resolved now - the docs and UI have been updated with correct information. Thanks again for the feedback @mjseaman!
