### ISSUE TITLE
Docs: parametrize versions of documentation when refering to Mimir/GEM from the Helm chart docs

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#3736]
#### Is your documentation request related to a feature? If so, which one?

N/A

#### Describe the solution that you’d like or the expected outcome

Store the Mimir and GEM version (that is included in the helm chart) in a parameter and use the parameter in statements and links to point to the correct Mimir/GEM version everywhere.

For example when referring to Collect metrics and logs via Grafana Agent documentation in Mimir from the Helm chart docs.
helm-charts/mimir-distributed/run-production-environment-with-helm/collect-metrics-and-logs.md

**Comment by osg-grafana** [comment]
@krajorama, I think this is done. If so, please close.

**Comment by krajorama** [comment]
implemented by parameters in the frontmatter of https://github.com/grafana/mimir/blob/main/docs/sources/helm-charts/mimir-distributed/_index.md
