### ISSUE TITLE
cleaner partial block issue

### ISSUE THREAD

**Issue by chrish987** [grafana/mimir#3760]
#### Describe the bug
Many thousands of errors in the log files about 'partial blocks' example below.

`mimir            | level=warn ts=2022-12-16T21:56:02.469543812Z caller=updater.go:113 component=cleaner user=apcups msg="skipped partial block when updating bucket index" block=01GHYHHCG31199H9XWQR7HQ1WW`

#### To Reproduce
this happens continuously in my system - but not sure exactly how to reproduce.

on a hard restart 'docker-compose down' + 'docker-compose up' the error is logged many times at startup.

#### Expected behavior

This error should not occur. The issue is the volume of logs created, and i don't really want to log at a level that excludes warn level messages.

#### Environment

I am running mimir as a remote write target from prometheus. Storage is S3 in minio. All docker containers under compose on the same host. All latest release versions of software. I did have site replication configured in minio and the required versioning - i saw an issue that suggested the versioning may be the issue, but i have disabled this and the issue still occurs.

#### Additional Context

If i lookup one of the blocks referenced in the error message I can see that the 'folder' is empty apart from a folder called chunks, which is also empty. I am guessing that minio is not deleting the block as the directory is still there and the lack of any content in the block is causing the error - but i am guessing.

Can provide any relevant information if required. I have not paste lots of configs etc for now as not sure what might be helpful or not.

**Comment by pstibrany** [comment]
"partial block" means that there is `01GHYHHCG31199H9XWQR7HQ1WW` present when listing `apcups`  (tenant ID) in your storage (Minio), but `apcups/01GHYHHCG31199H9XWQR7HQ1WW/meta.json` object doesn't exist.

Typical scenario when partial blocks occur is when ingester or compactor are interrupted during block upload, or unfinished backfill call. Mimir ignores such blocks (that's what the message says), and will eventually delete them, but if there are too many of them, if may indicate some problem that would be good to investigate.

**Comment by chrish987** [comment]
I have so many of them it seems that a block is never deleted. Is there any way to force the delete? I do have the _compactor_partial_block_deletion_delay_ set, is this what you are referring to with the comment about Mimir eventually deleting the blocks? Below is the config which seems fairly simple, and minio is just defaults.

**Comment by pstibrany** [comment]
> I have so many of them it seems that a block is never deleted. Is there any way to force the delete? I do have the _compactor_partial_block_deletion_delay_ set, is this what you are referring to with the comment about Mimir eventually deleting the blocks? Below is the config which seems fairly simple, and minio is just defaults.

Yes, I was referring to `compactor_partial_block_deletion_delay` setting, which must be set to at least 4h to be enabled. When enabled, compactor compares the most-recent modification time of objects in the partial block (ie. with no `meta.json`) to determine whether that partial block should now be deleted.

**Comment by aknuds1** [comment]
I think the problem here must be that Minio leaves empty directories behind. Mimir only deletes objects (files) when cleaning partial blocks, and doesn't have any notion of eventual directories (in case the object storage supports and creates them). 

Can Minio be configured to not create directories? Since we support Minio, I should think it can be run this way.

**Comment by aknuds1** [comment]
If you see [this](https://github.com/minio/minio/discussions/15257) Minio discussion, I think the dangling directories could be due to an unhealthy Minio bucket. Closing until further evidence is provided.
