### ISSUE TITLE
Use redis to completely replace memcached?

### ISSUE THREAD

**Issue by wgliang** [grafana/mimir#3762]
#### Is your feature request related to a problem? Please describe.

Use `redis` to completely replace `memcached`. 

#### Describe the solution you'd like

Creating multiple `memcached` each time makes the whole architecture look more cumbersome and complex. Using `redis` to simplify (replace `memcached`) mimir's architecture also meets the design goals of `mimir`.

#### Describe alternatives you've considered

The size of value may be a challenge for `redis`.

#### Additional context

No

**Comment by 56quarters** [comment]
Support for Redis is planned and being worked on in https://github.com/grafana/dskit/pull/245. Is this issue for adding the ability to use Redis as a replacement for Memcached in Mimir as-is?
