### ISSUE TITLE
Add a new option to always persist alertmanager state to allow multiple storage backends

### ISSUE THREAD

**Issue by MrFreezeex** [grafana/mimir#3819]
#### Is your feature request related to a problem? Please describe.

We have one S3 cluster per datacenter so we currently aim at deploying one mimir cluster per datacenter. To increase availability we would make prometheus do remote write on at least two mimir clusters (so the data would be sent to two datacenters). We however would still want to have one set of alerts, meaning a single alertmanager cluster on both DC (that have different S3 buckets).

This could be useful as well for mimir deployment in AWS if you have one mimir cluster per region with one alertmanager cluster for multiple regions, but in that case S3 Cross-Region Replication could be setup as well which should work fine in the alertmanager context...

#### Describe the solution you'd like

Add a new `alertmanager.always_persist` (disabled by default) config that disable the condition to only persist the state for the first replica (https://github.com/grafana/mimir/blob/main/pkg/alertmanager/state_persister.go#L106-L109). This should allow to use different S3 buckets/storage backend across replicas (provided that alertmanager is configured with the zone awareness mode and that every alertmanager in the same zone has the same storage backend settings).

#### Describe alternatives you've considered

Replicate the content of the bucket asynchronously in both s3 cluster instead of adding this to Mimir's alertmanager.

#### Additional context

Happy to send the necessary PR, if you agree with the approach described above.

**Comment by pracucci** [comment]
The alertmanager should support a storage outage without affecting the alertmanager capabilities, which means the alerts would still be routed. For this reason, I would suggest to setup a cross-region alertmanager cluster backed by the same S3 bucket (and not two different buckets). What I'm basically suggesting is to run Mimir Alertmanager separately from the Mimir cluster, building a cross-region Alertmanager cluster backed by a single bucket.

**Comment by MrFreezeex** [comment]
> The alertmanager should support a storage outage without affecting the alertmanager capabilities, which means the alerts would still be routed. For this reason, I would suggest to setup a cross-region alertmanager cluster backed by the same S3 bucket (and not two different buckets). What I'm basically suggesting is to run Mimir Alertmanager separately from the Mimir cluster, building a cross-region Alertmanager cluster backed by a single bucket.

My goal is indeed to build a separated cross-region AlertManager. But the issue is that we are not using any cloud so a "cross region bucket" is something that we would have to add to our on-prem infra.... Probably a separated process that would mimic AWS cross region replication to replicate the bucket periodically across our two different s3 clusters. This is slightly more complicated than configuring S3 Cross-Region Replication on an AWS bucket though.

Correct me if I am wrong but it seems to me that this simple-ish extra option should work well and allow us to not bother about replicating the bucket outside Mimir control... I guess there would maybe are other use-cases for that like if you are trying to build a Mimir Alertmanager cluster across two different cloud providers maybe?

**Comment by MrFreezeex** [comment]
> The alertmanager should support a storage outage without affecting the alertmanager capabilities, which means the alerts would still be routed. For this reason, I would suggest to setup a cross-region alertmanager cluster backed by the same S3 bucket (and not two different buckets). What I'm basically suggesting is to run Mimir Alertmanager separately from the Mimir cluster, building a cross-region Alertmanager cluster backed by a single bucket.

Oh indeed that's a nice solution too, thanks :D!
