### ISSUE TITLE
Helm 4.0.0 Gateway nginx config is not working with zone-aware alertmanager configuration (mimir oss)

### ISSUE THREAD

**Issue by df-cgdm** [grafana/mimir#3830]
#### Describe the bug
Helm 4.0.0 Gateway nginx config is not working with zone-aware alertmanager configuration (mimir oss)

#### To Reproduce

1. Install mimir-distributed version 3.3.x
2. Upgrade to mimir-distributed version 4.0.0 with zone-aware configuration disabled
3. Migrate to unify proxy deplouyment using following procedure https://grafana.com/docs/mimir/v2.5.x/operators-guide/deploy-grafana-mimir/migrate-to-unified-proxy-deployment/ 
4. Migrate alertmanager single zone to zone-aware replication using following procedure https://grafana.com/docs/mimir/latest/migration-guide/migrating-from-single-zone-with-helm/

#### Expected behavior

Expect the alert manager to be available through the gateway configuration but it is not.

The problem is that the gateway nginx.conf is not correct. The service "mimir-alertmanager" has been replaced by
"mimir-alertmanager-zone-a", "mimir-alertmanager-zone-b" and "mimir-alertmanager-zone-c"

```

    # Alertmanager endpoints

    location /alertmanager {

      proxy_pass      http://mimir-alertmanager.mimir.svc.cluster.local:8080$request_uri;

    }

    location = /multitenant_alertmanager/status {

      proxy_pass      http://mimir-alertmanager.mimir.svc.cluster.local:8080$request_uri;

    }

    location = /api/v1/alerts {

      proxy_pass      http://mimir-alertmanager.mimir.svc.cluster.local:8080$request_uri;

    }
```

### resolution proposal
change the gateway nginx.conf (see: https://github.com/grafana/mimir/blob/mimir-distributed-4.0.0/operations/helm/charts/mimir-distributed/values.yaml#L2485) to have something like that

```

    # Alertmanager endpoints

    location /alertmanager {

      proxy_pass      http://mimir-alertmanager-headless.mimir.svc.cluster.local:8080$request_uri;

    }

    location = /multitenant_alertmanager/status {

      proxy_pass      http://mimir-alertmanager-headless.mimir.svc.cluster.local:8080$request_uri;

    }

    location = /api/v1/alerts {

      proxy_pass      http://mimir-alertmanager-headless.mimir.svc.cluster.local:8080$request_uri;

    }
```

**Comment by dimitarvdimitrov** [comment]
thank you for reporting this @df-cgdm! I oversaw this when writing the gateway templates. The difference was probably caused by merging the multi-zone and gateway PRs shortly after one another. I opened https://github.com/grafana/mimir/pull/3851 to fix it.
