### ISSUE TITLE
mimir Monolithic - 2 VM cluster - err-mimir-bucket-index-too-old

### ISSUE THREAD

**Issue by elangela** [grafana/mimir#3834]
#### Describe the bug
Initially when the cluster starts the first VM gets bucket-index.json.gz under .blocks. In this initial state both mimir databases can be queried for the same data(older than 12hours). If "master" db is rebooted the secondary db also receives  bucket-index.json.gz under .blocks. From now on bucket-index.json.gz in the old master is not updated, but in the new master bucket-index.json.gz is updated. Trying to query data older than 12h from the old master will result in err-mimir-bucket-index-too-old.

#### To Reproduce
- Setup a 2 VM monolithic cluster Mimir, version 2.5.0 utilizing memberlist

#### Expected behavior
The expected behavior is that the cluster should handle a single VM restart without responding err-mimir-bucket-index-too-old from secondary cluster-db.

#### Environment
VMWARE, Linux RHEL 8.7

**Comment by elangela** [comment]
Might be a configuration issue

**Comment by pstibrany** [comment]
> @elangela i got the same behaviour, how did you fix it ?

I'd suggest starting new discussion, and providing details about your configuration.

**Comment by elangela** [comment]
I did post the solution here but it has been removed?

If I remember correctly we had tried to set up a cluster but had a separate nfs storage on each VM and this caused this issue. I tried a shared nfs storage but that did not work at all

So we changed to monolitic single VMs, not cluster, and this worked well

**Comment by pstibrany** [comment]
> I did post the solution here but it has been removed?

Perhaps you mean this discussion? https://github.com/grafana/mimir/discussions/3841
