### ISSUE TITLE
Unable to set query_store_after to a lower value (ideally 0)

### ISSUE THREAD

**Issue by oneacl** [grafana/mimir#3843]
#### Describe the bug

Reducing query_store_after causes queries to fail with `internal: expanding series: the consistency check failed because some blocks were not queried (err-mimir-store-consistency-check-failed). The non-queried blocks are:  <block id>`

#### To Reproduce

I'm running a setup where the ingesters don't have persistent storage (limitation on my custom k8s installation). Up until a few versions back this worked fine but now, on ingester restart the queriers return no data for the past 12 hours.
After the 12h have gone past, data comes back (as it's now queried from S3).

Querying now-2d to now-1d works fine (as it gets pulled from s3) but any recent query fails with the consistency check.

As an alternative to query_store_after I'm also good with forcing the ingesters to pull the last 12h from S3 on startup?

Thank you.

#### Environment

- Infrastructure: kubernetes
- Deployment tool: helm

**Comment by pstibrany** [comment]
Hi. There is also `-blocks-storage.bucket-store.ignore-blocks-within` option, which tells store-gateways to ignore blocks that are too new. Idea behind that flag is that store-gateways should only download older and compacted blocks.

If you set `-querier.query-store-after` to 0, you will also need to set `-blocks-storage.bucket-store.ignore-blocks-within=0` (it defaults to 10h), otherwise no store-gateway will have those most recent blocks and querier will return consistency check error.

**Comment by oneacl** [comment]
Thanks for the quick reply - I initially misunderstood the purpose of ignore-blocks-within but now it makes sense and I can also confirm that setting both options works as expected.

> This means that any restart of ingesters will cause data loss at given ingester. If all ingesters restart / crash at the same time, latest 2-3h of data is lost.

Thank you for taking the time in mentioning this. I have `flush_blocks_on_shutdown: true` and a replication factor of 3. You are correct, a failure in all ingesters would mean data loss but they run on different availability zones (so the chances of concurrent crash are somewhat reduced) but a single ingester restart (even graceful rolling restarts) should not cause data loss assuming the replication completed correctly.

**Comment by pracucci** [comment]
> I can also confirm that setting both options works as expected.

Thanks for following up! I'm going to close the issue, but feel free to reopen if necessary.
