### ISSUE TITLE
-distributor.ingestion-rate-limit is not working

### ISSUE THREAD

**Issue by a0s** [grafana/mimir#3861]
#### Describe the bug

-distributor.ingestion-rate-limit do nothing

#### To Reproduce

Run grafana-mimir:2.5.0 image with CMD=[
"-server.http-listen-port","8080",
"-server.grpc-listen-port","9095",
"-memberlist.join","dns+grafana-mimir.ecs.local:7946",
"-common.storage.backend","s3",
"-common.storage.s3.endpoint","s3.eu-central-1.amazonaws.com",
"-common.storage.s3.region","eu-central-1",
"-blocks-storage.s3.bucket-name","xxx-testing-grafana-mimir-blocks",
"-alertmanager-storage.s3.bucket-name","xxx-testing-grafana-mimir-alertmanager",
"-ruler-storage.s3.bucket-name","xxx-testing-grafana-mimir-ruler",
"-auth.multitenancy-enabled","true",
"-distributor.ingestion-rate-limit","500000",
"-distributor.ingestion-burst-size","5000000"
]

But still getting error with `10000 items/s` text inside at prometheus side
```
prometheus-kube-prometheus-stack-prometheus-0 prometheus ts=2023-01-05T12:41:50.401Z caller=dedupe.go:112 component=remote level=error remote_name=94272d url=http://grafana-mimir.ecs.local:8080/api/v1/push msg="non
-recoverable error while sending metadata" count=500 err="server returned HTTP status 429 Too Many Requests: the request has been rejected because the tenant exceeded the ingestion rate limit, set to 10000 items/s
with a maximum allowed burst of 200000. This limit is applied on the total number of samples, exemplars and metadata received across all distributors (err-mimir-tenant-max-ingestion-rate). To adjust the related per
-tenant limits, configure -distributor.ingestion-rate-limit and -distributor.ingestion-burst-size, or contact your service administrator."
```

#### Expected behavior

It should affect the message at least. Should increase the limit

#### Environment

- Infrastructure: ECS
- Deployment tool: Terraform

Looks like its related to https://github.com/grafana/mimir/issues/901 somehow

**UPD**:

It works when "limits" is not the latest arg in cli, this is works:

CMD=[
"-server.http-listen-port","8080",
"-server.grpc-listen-port","9095",
"-memberlist.join","dns+grafana-mimir.ecs.local:7946",
"-common.storage.backend","s3",
"-common.storage.s3.endpoint","s3.eu-central-1.amazonaws.com",
"-common.storage.s3.region","eu-central-1",
"-blocks-storage.s3.bucket-name","xxx-testing-grafana-mimir-blocks",
"-alertmanager-storage.s3.bucket-name","xxx-testing-grafana-mimir-alertmanager",
"-ruler-storage.s3.bucket-name","xxx-testing-grafana-mimir-ruler",
"-distributor.ingestion-rate-limit","500000",    <== not the latest in list
"-distributor.ingestion-burst-size","5000000" <== not the latest in list
"-auth.multitenancy-enabled","true"
]

**Comment by pracucci** [comment]
👋 Hi!

> It works when "limits" is not the latest arg in cli, this is works:

The positional order of CLI flags shouldn't matter in Mimir. Can you make sure that all the CLI flags are actually passed to the Mimir process in your infrastructure? I just would like to exclude an issue outside of Mimir but related to the deployment.

**Comment by bboreham** [comment]
@a0s can you confirm that the problem re-appears when you move options around?

**Comment by a0s** [comment]
@bboreham I am sorry, I have postponed testing Mimir for now in favor of simpler solutions (I want to try JuiceFS as storage).
I tested mimir docker - and the order of parameters didn't matter.
I'm almost sure that somewhere in the chain (in my case) typescript -> compiler -> json -> terraform -> ECS API, the parameter is corrupted and mimir itself has nothing to do with it.
