### ISSUE TITLE
Let mimir-continuous-test generate native histograms

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#4044]
Mimir continuous test should be able to generate histograms beside float series

Requirements
- generation of float and histogram series can be controlled separatelly
- possible to generate float and histogram series at the same time
- be able to generate counter/gauge integer histograms and counter/gauge float histograms (4 different kinds)
- in gauge histograms the sine wave pattern can be encoded in bucket counter
- in counter histograms the sine wave pattern can be encoded in the rate of increase of bucket counter

**Comment by codesome** [comment]
> enough to generate float histograms (not integer histograms)

Since float and integer histograms have different chunk encoding underneath, it would be good to test both of them

**Comment by codesome** [comment]
Also, testing counter vs gauge histograms
