### ISSUE TITLE
`TestBucketIndexReader_ExpandedPostings` should test the new `StreamBinaryReader` too

### ISSUE THREAD

**Issue by colega** [grafana/mimir#4068]
[TestBucketIndexReader_ExpandedPostings](https://github.com/grafana/mimir/blob/909708f91607deba0c8851f3757f4f6ea4740c52/pkg/storegateway/bucket_test.go#L479-L479) is one of our most exhaustive test suites in the blocks storage, heavily testing the interaction with the index reader.

We've implemented a new `StreamBinaryReader` now, but this test suite relies on the old BinaryReader:

https://github.com/grafana/mimir/blob/909708f91607deba0c8851f3757f4f6ea4740c52/pkg/storegateway/bucket_test.go#L825-L826

We should update this test, and the related benchmark, to also run on top of the new StreamBinaryReader.

**Comment by charleskorn** [comment]
Will be resolved by https://github.com/grafana/mimir/pull/4075.
