### ISSUE TITLE
Docs: Add disk space requirements for WAL (write-ahead-logs)

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#4070]
@fernandografana writes:
Within the [Mimir write-ahead logs](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/ingester/) topic, It seems there is no specification information about the disk space requirements, so it’s been a bit difficult to dimension the requirements of hardware.

For Loki [there is such information ](https://grafana.com/docs/loki/latest/operations/storage/wal/#disk-space-requirements)so it could be a good idea to add this in the Mimir documentation. Thanks!

**Comment by osg-grafana** [comment]
@pracucci, what do you technically recommend?

**Comment by pracucci** [comment]
> @pracucci, what do you technically recommend?

Disk space requirement for ingesters (which include WAL but also TSDB blocks temporarily stored on local disk) is documented here: https://grafana.com/docs/mimir/latest/operators-guide/run-production-environment/planning-capacity/#ingester

**Comment by osg-grafana** [comment]
Oops, forgot to close this because documentation exists for this.
