### ISSUE TITLE
Extract `UserRegistries` into http://github.com/grafana/dskit

### ISSUE THREAD

**Issue by gotjosh** [grafana/mimir#4082]
Hello Miminauts,

I have a need to use `UserRegistries` within Grafana.

https://github.com/grafana/mimir/blob/7fab438f6baece22a07899f7f77cf42a006ce4d7/pkg/util/metrics_helper.go#L586

Grafana, by default, is also multi-tenant, so all the plumbing we have here is helpful for me to allow metrics from individuals running non-multitenant components (e.g. Alertmanager) to expose their metrics. 

Would there be any objection to extracting it into a commonplace that can be re-used easier than importing mimir? 

- [x] Copy `UserRegistries` to `grafana/dskit`
- [x] Replace references of `UserRegistries` in favour of the `dskit` alternative
- [x] Remove `UserRegistries` references from Mimir

**Comment by pracucci** [comment]
They're non trivial to rebuild and I see value in them for other Grafana projects, so I have no objection in moving them to a shared lib.

**Comment by gotjosh** [comment]
Blocked by https://github.com/grafana/mimir/pull/4078
