### ISSUE TITLE
Use estimated query cardinality in query sharding

### ISSUE THREAD

**Issue by flxbk** [grafana/mimir#4108]
#### Is your feature request related to a problem? Please describe.

The way we currently shard queries does not take into account query cardinality. This means that queries that turn out to be low cardinality later on in the request lifecycle are still sharded the same as high-cardinality queries, which leads to overhead that could be avoided. 

#### Describe the solution you'd like

Many queries are executed regularly and in relatively short time intervals (e.g. those from recording rules or Grafana dashboards). For these queries, result cardinality likely doesn't change very much between individual executions, which makes it likely that the cardinality of the previously returned result is still a good estimate for the next execution.

After a query has been processed, we could cache the observed cardinality and reuse it for subsequent matching queries which touch a similar time range. For example, we could assign the same cardinality estimate to any matching query expression that touches the same 24 hour time range.

When no cardinality estimate from a previous query execution is available, sharding would remain unchanged.

#### Describe alternatives you've considered

@colega created an [issue](https://github.com/grafana/mimir/issues/3459) for this problem that proposes adding a dedicated endpoint to retrieve cardinality before sharding happens. This would allow us to use a verifiably correct cardinality at the cost of more latency. If the assumption that cardinality of the same query doesn't change much in between executions is correct, this seems like a high price to pay for information that is pretty stable in most cases.

Under-sharding that could lead to OOMs would then happen only if series cardinality increases drastically in a short time frame. To mitigate this, we could clear cardinality estimates in the face of errors to revert to the default number of shards for the next query execution.

**Comment by pracucci** [comment]
Once #4121 is merged, I would suggest to do few improvements on top of it:
- Update documentation
- Apply an offset (based on the query hash) to bucketing, so that all cached estimations don't expire at the same time ([initially suggested here](https://github.com/grafana/mimir/pull/4121#issuecomment-1415118671))

**Comment by pracucci** [comment]
I think we can close this issue, since has been addressed by the PRs referenced above.
