### ISSUE TITLE
Ruler: load more tenants in parallel during startup

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#4115]
### Problem

During startup the ruler syncs all rules from the bucket and one-by-one starts a ruler manager for each tenant. With many tenants the second step may take up to 30s. This means that for the last tenant to be loaded there could be 30s gap in which its rule are not being evaluated. This is an example of the logs for a ruler pod that was starting in a big cell at Grafana Labs

```
ts=2023-01-25T16:04:26.751782525Z caller=manager.go:1019 level=info user=X msg="Starting rule manager..."
ts=2023-01-25T16:05:05.857925695Z caller=manager.go:1019 level=info user=Y msg="Starting rule manager..."
```

### Proposed solution

One way to alleviate this is to load tenants in parallel in this function https://github.com/grafana/mimir/blob/4ee079a33a6057e5431d2202b053b6ef8780b9ce/pkg/ruler/manager.go#L108-L110

Loading each tenant involves only writing some files to disk (AFAICT), so there shouldn't be a reason to not be able to do this concurrently for N number of tenants.

**Comment by callumj** [comment]
Could this be something done for the store-gateway too?

**Comment by 56quarters** [comment]
> Could this be something done for the store-gateway too?

The store gateway already does its "tenant sync" (and a few other sync operations) [in parallel](https://grafana.com/docs/mimir/latest/reference-configuration-parameters/#blocks_storage).
