### ISSUE TITLE
Ruler: reduce time between becoming ACTIVE in ring and starting ruler managers 

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#4117]
### Problem

The ruler becomes active in the ring after all its services are started. When the ruler becomes ready it automatically starts "owning" rule groups. So other rules in the ring stop evaluating these rule groups because they now shard to the new ruler.

After becoming ACTIVE, the ruler proceeds to sync the rule groups for all the tenants that it ows; to do that it needs to iterate the bucket and fetch the rule groups for all tenants. For larger cells with many tenants the time to iterate the bucket can exceed a minute. These are example logs from a ruler pod - there is a minute of listing and loading rules after becoming ACTIVE

```
ts=2023-01-25T16:03:27.195056609Z caller=ruler.go:347 level=info msg="waiting until ruler is ACTIVE in the ring"
ts=2023-01-25T16:03:27.387579533Z caller=ruler.go:351 level=info msg="ruler is ACTIVE in the ring"
ts=2023-01-25T16:03:27.38763535Z caller=ruler.go:399 level=info msg="ruler up and running"
ts=2023-01-25T16:03:27.387760519Z caller=mimir.go:785 level=info msg="Application started"
// 1 minute of loading rules from the bucket
ts=2023-01-25T16:04:26.751782525Z caller=manager.go:1019 level=info user=266236 msg="Starting rule manager..."
```

### Proposed solution 1

Increase concurrency of loading groups; loading groups seems to take around 30s, which is also as much as the listing takes

<img width="3306" alt="Screenshot 2023-01-31 at 12 17 16" src="https://user-images.githubusercontent.com/21020035/215746564-140c4e65-74d0-42e5-bdbb-cbbdfedbcac5.png">

currently we load 10 tenants concurrently; we can consider making this configurable or simply increasing it; code:

https://github.com/grafana/mimir/blob/7ca89a72580ae084fe387037680c964be251d28d/pkg/ruler/ruler.go#L56

### Proposed solution 2

The ruler can download all the rules initially when starting and become ACTIVE in the ring only after it has all the rules.

Becoming ACTIVE in the ring happens as part of the start procedure here

https://github.com/grafana/mimir/blob/7ca89a72580ae084fe387037680c964be251d28d/pkg/ruler/ruler.go#L344-L351

But synching rules happens as the service runs (i.e. after becoming ACTIVE)

https://github.com/grafana/mimir/blob/7ca89a72580ae084fe387037680c964be251d28d/pkg/ruler/ruler.go#L398-L408

Rule groups are only sharded to ACTIVE rulers, so delaying becoming ACTIVE to later should be safe 

https://github.com/grafana/mimir/blob/fbfc9f1b001d2a1bcf4379c37c7c9fc87a13d54f/pkg/ruler/ruler_ring.go#L25-L29

---

My preference is for solution 2 because it will work at any scale, whereas solution 1 will only partially alleviate the problem

**Comment by pracucci** [comment]
> Proposed solution 2
> The ruler can download all the rules initially when starting and become ACTIVE in the ring only after it has all the rules.

I'm not sure I understand proposal 2. Do you mean synching all rules at startup, then wait to become ACTIVE, and then discard all rules not belonging to the ruler's shard and just run the remaining ones?

**Comment by pracucci** [comment]
> This has the drawback that instead of loading only the groups that are sharded to this particular ruler, it will download all rule groups

I'm concerned about it. We shouldn't introduce vertical scalability limits to Mimir. If a component is sharded (like the ruler) there should be no operation which linearly increase with the number of tenants and/or rules you have.

**Comment by dimitarvdimitrov** [comment]
In that case we can try with a new read operation for the ring, which shards to all instances, not only the ACTIVE ones.

We should also probably still wait for stability in the ring before doing the initial sync. There may be other ruler replicas that have recently started. We want to perform sharding after all have joined the ring.

**Comment by pracucci** [comment]
About proposal 2: what we do in other services (e.g. store-gateway), which I think could be applied to this use case too, is to use the JOINING state in the ring.

It may work something like this (we need to look in details how it works in the store-gateway, cause I remember there are some edge cases I had to handle):

- Rulers, during their normal operation, shard rule groups among ACTIVE healthy instances
- At startup, a ruler joins the ring in JOINING state
  - Other rulers keep evaluating the rule groups that will soon belong to the JOINING ruler too, because it's not ACTIVE yet
  - The JOINING ruler shard rule groups among ACTIVE + JOINING instances (this is done using a different ring operation)
  - Once the JOINING ruler has done the initial synching, it switches its state to ACTIVE
  - Switching to ACTIVE, cause the other rulers to drop the rule groups belonging to the ruler who just started

Would a similar approach work to solve this issue?
