### ISSUE TITLE
Fix gateway auto-scaling panels

### ISSUE THREAD

**Issue by aknuds1** [grafana/mimir#4134]
#### Describe the bug
Fix gateway auto-scaling panels so the labels are unique between different gateway instances. @colega says to check the querier auto-scaling panels for a solution.

The below screenshot shows the problem of there being one Min/Max/Current label for each gateway type (there being two in this case), and they're not possible to tell apart:

![panel](https://user-images.githubusercontent.com/281303/216345067-5e080df9-acfe-48ec-b0eb-78c3aa9761fc.png)

**Comment by pracucci** [comment]
> Fix gateway auto-scaling panels so the labels are unique between different gateway instances

Can you show an example of the problem, please?

**Comment by aknuds1** [comment]
@pracucci I can add a screenshot.

**Comment by aknuds1** [comment]
@pracucci I added a screenshot exemplifying the problem.
