### ISSUE TITLE
Ingester: idle or flush compaction do not compact OOO Head

### ISSUE THREAD

**Issue by pstibrany** [grafana/mimir#4160]
#### Describe the bug

When ingesters compact TSDB as a result of `/ingester/flush` or due to TSDB being idle, ingesters only call `(*tsdb.DB).CompactHead(...)`, but this doesn't compact OOO data. For that we need to call `(*tsdb.DB).CompactHead(...)`.

When TSDB is idle, ingester checks if Head has 0 series before closing the TSDB. Series with OOO count as head-series too, and due to not compacting OOO, ingester will never close such idle TSDB.

This is still true as of Mimir 2.6 (but the bug was introduced with support for out-of-order data).

#### Expected behavior

Ingesters should compact OOO data too when TSDB is idle or as a result of calling `/ingester/flush` endpoint. Ingester should be able to close idle TSDB if there is OOO data.

**Comment by pstibrany** [comment]
Fix should be pretty straightforward, we need to also call `u.db.CompactOOOHead()` call in this method: https://github.com/grafana/mimir/blob/a261162a18c927b7479bdc23f3c6f8d8a2ce5bc0/pkg/ingester/user_tsdb.go#L240-L270

**Comment by jesusvazquez** [comment]
:wave: @pstibrany I'm happy to help with this, @pstibrany told me there is probably people interested in the Mimir team to work on this so I can help if any questions come up!

**Comment by kubicgruenfeld** [comment]
we have enabled out of order window a few days ago and can now observe some failed tsdb compactions (cortex_ingester_tsdb_compactions_failed_total). does this issue relate to our observations?

**Comment by pstibrany** [comment]
> we have enabled out of order window a few days ago and can now observe some failed tsdb compactions (cortex_ingester_tsdb_compactions_failed_total). does this issue relate to our observations?

That's difficult to say without knowing more details. But we have seen this problem manifest as failed compaction once,  although haven't quite figured out why yet. However typically this problem shows as ingesters being unable to get rid of "idle" TSDB, and compacting such TSDB again and again -- but not producing any blocks (becaue of missing OOO compaction).

**Comment by pstibrany** [comment]
> But we have seen this problem manifest as failed compaction once, although haven't quite figured out why yet.

In our case, compaction failed due to TSDB not being in "active" state, but we didn't know what state it was in. https://github.com/grafana/mimir/pull/4211 should help us next time we see it.

**Comment by kubicgruenfeld** [comment]
I'm not sure if this helps, but we are seeing this a lot in the ingester logs:

```
level=info ts=2023-02-09T11:58:18.600948526Z caller=ingester.go:1983 msg="TSDB is idle, forcing compaction" user=tenantA
level=info ts=2023-02-09T11:58:18.653716128Z caller=compact.go:700 user=tenantA msg="write block resulted in empty block" mint=1675937071975 maxt=1675937071976 duration=52.754036ms
```

these same tenants were we are seeing this, also did out of order writes.

**Comment by pstibrany** [comment]
> I'm not sure if this helps, but we are seeing this a lot in the ingester logs:
> 
> ```
> level=info ts=2023-02-09T11:58:18.600948526Z caller=ingester.go:1983 msg="TSDB is idle, forcing compaction" user=tenantA
> level=info ts=2023-02-09T11:58:18.653716128Z caller=compact.go:700 user=tenantA msg="write block resulted in empty block" mint=1675937071975 maxt=1675937071976 duration=52.754036ms
> ```

Yes, this is exactly what we saw too and lead to creating and fixing this issue.
