### ISSUE TITLE
Rename GenericSamplePair.GetTimestampVal to not include Val

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#4191]
https://github.com/grafana/mimir/pull/4159#discussion_r1097160769

Rename to something that doesn't conflict with existing methods on this types, in particular the generated code from protobuf IDL, which uses pointer receiver.

Suggestion:  `Timestamp`

**Comment by codesome** [comment]
Another suggestion: The function could be just `.Timestamp()`, and similarly if you have to access, it could be `.Histogram()`, `.FloatHistogram()`, and `.Float()` or `.FloatVal()`if you prefer.

**Comment by codesome** [comment]
Prometheus also uses functions like `T() V() H() FH()` in some interfaces. (We don't use `Get` prefix). But I leave it up to you.

**Comment by krajorama** [comment]
Eventually removed generic due to performance and flexibility issues #4490
