### ISSUE TITLE
Proposal: split requests across memcached differently

### ISSUE THREAD

**Issue by bboreham** [grafana/mimir#423]
Currently, we (in Mimir pkg/storage/tsdb/cache/memcached.go) come up with say 1,000 keys to request.
We (in Thanos memcached_client.go) split them into 10 batches of 100, and call memcached client lib on 10 goroutines.
For each batch of 100 keys, memcached client lib splits them across say 10 memcached instances.
This last split is hashed; maybe some instances get 15 keys and some get 5.
Memcached client lib calls each real memcached on another goroutine, so 100 goroutines and 100 memcached requests total.
It seems to me it would be more efficient to hash the 1,000 keys across instances before splitting into batches.

**Comment by 56quarters** [comment]
Submitted a PR upstream to not use an unbounded number of goroutines for waiting: https://github.com/thanos-io/thanos/pull/5301

As far as your other idea, the Thanos memcached client (`memcached_client.go`) [keeps a reference to the `ServerSelector`](https://github.com/thanos-io/thanos/blob/0a6287fda8ef1a1f14236688532801ce2722c263/pkg/cacheutil/memcached_client.go#L165) that the underlying memcache client is using so I think it would be fairly straightforward to modify the batching logic to take destination server into account.

**Comment by 56quarters** [comment]
I've got a rough version of your idea to hash keys before batching them here: https://github.com/56quarters/thanos/commit/bd93be6cb63517d1c01e7b706f16e1cef4d955a6

Is this roughly what you had in mind @bboreham?

**Comment by bboreham** [comment]
Yes that's very neat, thanks!.
