### ISSUE TITLE
Blocks cleaner: stale partial block time checks can be optimized

### ISSUE THREAD

**Issue by andyasp** [grafana/mimir#4239]
One of the responsibilities of the blocks cleaner is to scan through partial blocks to determine if any should be marked for deletion.

This is currently accomplished by listing the block directory with `Iter` (mapping to [ListObjects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html)) and then calling `Attributes` (mapping to [HeadObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html)) to determine the last modified time for each object in the block directory. Calling `Attributes` per-object shouldn't be necessary, since an object listing contains the last modified time for each object ([reference](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html#API_ListObjects_ResponseSyntax)). `Iter` isn't exposing it and instead is discarding all information besides object names.

- [ ] If we could somehow use the information from the listing according to the S3 API then we could avoid all external calls besides the listing.
- [x] A change that could be made shorter term (but useful even long term) would be not trying to find the most recent last modified time in all cases and instead stop iterating (by returning a recognizable error) when any object more recent than the stale cutoff time is found. Done in #4246 

For reference, [findMostRecentLastModifiedTimeForBlock](https://github.com/grafana/mimir/blob/6ab88a8e57094b2d6db62015a2d11b26d95e10e6/pkg/compactor/blocks_cleaner.go#L575) is currently implemented as follows:
```go
// findMostRecentModifiedTimeForBlock finds the most recent modification time for all files in a block.
func findMostRecentModifiedTimeForBlock(ctx context.Context, blockID ulid.ULID, userBucket objstore.Bucket) (time.Time, error) {
	var result time.Time

	err := userBucket.Iter(ctx, blockID.String(), func(name string) error {
		if strings.HasSuffix(name, objstore.DirDelim) {
			return nil
		}
		attrib, err := userBucket.Attributes(ctx, name)
		if err != nil {
			return errors.Wrapf(err, "failed to get attributes for %s", name)
		}
		if attrib.LastModified.After(result) {
			result = attrib.LastModified
		}
		return nil
	}, objstore.WithRecursiveIter)
	return result, err
}
```

**Comment by 56quarters** [comment]
We inherit the `Bucket.Iter` method from the [Thanos objstore](https://github.com/thanos-io/objstore/blob/11ffbc490204bedf6d422e06a5fc1bfa0d861258/objstore.go#L71-L74) project. This seems like a pretty worthwhile fix with the potential to save a lot of work. We should discuss with the Thanos folks to see if a change to the `BucketReader` interface makes sense (maybe a new method that exposes some sort of Metadata object in addition to item name).

**Comment by pstibrany** [comment]
I just checked how many `attributes` operations we're doing from compactors compared to total operations, and the number of `attributes` from our compactors is pretty insignificant:

<img width="1366" alt="Screenshot 2023-02-14 at 11 48 59" src="https://user-images.githubusercontent.com/895919/218713947-597d2329-cc0e-4e6e-a505-09ced5b03ae0.png">

This is what we would optimize away.

I used this query:
```
sum (rate(thanos_objstore_bucket_operations_total{namespace=~"mimir.*|cortex.*",component="compactor", operation="attributes"}[$__rate_interval]))
/
sum (rate(thanos_objstore_bucket_operations_total{namespace=~"mimir.*|cortex.*",component="compactor"}[$__rate_interval]))
```

**Comment by andyasp** [comment]
> I just checked how many attributes operations we're doing from compactors compared to total operations, and the number of attributes from our compactors is pretty insignificant

Well that's good at least. I was originally looking at this because we may be exercising this more with backfill in the future. I opened the issue to make the problem at least known because this feels like something fixable.

> We should discuss with the Thanos folks to see if a change to the BucketReader interface makes sense (maybe a new method that exposes some sort of Metadata object in addition to item name).

I haven't contributed there yet, is there precedence for breaking changes? From a first glance `ObjectAttributes` type seems like it could fit for the metadata type. It's not everything, but it's the current return type of `Attributes` too so there may be reasons the other information is being dropped.

```go
type ObjectAttributes struct {
	// Size is the object size in bytes.
	Size int64 `json:"size"`

	// LastModified is the timestamp the object was last modified.
	LastModified time.Time `json:"last_modified"`
}
```

> I'd make sure that other supported object stores have this available, and have a plan for object stores that don't support this feature.

Assuming the target is `ObjectAttributes`:

| Provider | Listing has Size + Last Modified? |
| -------- | --------------------------------- |
| Azure     | [Yes](https://learn.microsoft.com/en-us/rest/api/storageservices/List-Blobs?tabs=azure-ad) |
| BOS       | [Yes](https://intl.cloud.baidu.com/doc/BOS/s/Njwvyq8ho-en#bucket-api)
| COS       | [Yes](https://www.tencentcloud.com/document/product/436/30614)
| Filesystem | [Yes (`DirEntry.Info()` may cause extra calls)](https://pkg.go.dev/io/fs#FileInfo)
| GCS      | [Yes](https://cloud.google.com/storage/docs/xml-api/get-bucket-list#response_body_elements)
| OCI       | [Yes (fields param)](https://docs.oracle.com/en-us/iaas/api/#/en/objectstorage/20160918/Object/ListObjects)
| OSS      | [Yes](https://www.alibabacloud.com/help/en/object-storage-service/latest/getbucket#section-cfq-tdw-bz)
| S3         | [Yes](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html#API_ListObjects_ResponseSyntax)
| Swift     | [Yes](https://docs.openstack.org/api-ref/object-store/index.html#id25)


It looks like Filesystem (which makes sense) and Swift are the the least S3-like from a first glance. I checked the code while I was doing this and one thing that caught my eye was the BOS provider [executing](https://github.com/thanos-io/objstore/blob/11ffbc490204bedf6d422e06a5fc1bfa0d861258/providers/bos/bos.go#L214) the passed function on [CommonPrefixes](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CommonPrefix.html), which seems like a bug to me.

**Comment by pstibrany** [comment]
> > We should discuss with the Thanos folks to see if a change to the BucketReader interface makes sense (maybe a new method that exposes some sort of Metadata object in addition to item name).
> 
> I haven't contributed there yet, is there precedence for breaking changes?

Extending existing `Iter` call to handle attributes may be tricky (it will break all clients of the library), while adding `IterWithAttibutes` will break all implementations. I don't see a good option, but would prefer breaking people extending the library than people using it, as first group is likely smaller. It may be best to send issue / PR to objstore repository to start a discussion there.

> Provider	Listing has Size + Last Modified?
> [del]
> It looks like Filesystem (which makes sense) and Swift are the the least S3-like from a first glance.

Thanks, looks like adding this should be straightforward.

> I checked the code while I was doing this and one thing that caught my eye was the BOS provider [executing](https://github.com/thanos-io/objstore/blob/11ffbc490204bedf6d422e06a5fc1bfa0d861258/providers/bos/bos.go#L214) the passed function on [CommonPrefixes](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CommonPrefix.html), which seems like a bug to me.

This seems fine to me. `CommonPrefixes` is only returned when not iterating recursively, so we want to call passed function on those paths.

**Comment by andyasp** [comment]
> This seems fine to me. CommonPrefixes is only returned when not iterating recursively, so we want to call passed function on those paths.

You're right. In my head I was thinking the function was being called per object, but it's per entry. That could make providing `f(name, attributes)` cleanly a bit harder without doing something like passing a zero value.

**Comment by andyasp** [comment]
Yeah we can close this. I may still propose the above listing change to objstore, but that would be tracked separately.
