### ISSUE TITLE
Don't set query-frontend address on queriers when we run query-scheduler.

### ISSUE THREAD

**Issue by colega** [grafana/mimir#4259]
This issue is about our jsonnet manifests in `operations/mimir`.

When query-scheduler is enabled, or we don't run in the microservices mode:
https://github.com/grafana/mimir/blob/c87020a36be7c6ba483e9bc7e17f2ee956b29131/operations/mimir/query-scheduler.libsonnet#L44-L44

There's no need for queriers to find query-frontends, as they talk to query-scheduler, or mimir-backend in read-write mode.

So this option doesn't need to be set:
https://github.com/grafana/mimir/blob/c87020a36be7c6ba483e9bc7e17f2ee956b29131/operations/mimir/querier.libsonnet#L24-L24

And the query-frontend-discovery service doesn't have to be created:

https://github.com/grafana/mimir/blob/c87020a36be7c6ba483e9bc7e17f2ee956b29131/operations/mimir/query-frontend.libsonnet#L57-L62

**Comment by kushalnl7** [comment]
Hi, I am interested to do this. Can I try this?

**Comment by pstibrany** [comment]
> Hi, I am interested to do this. Can I try this?

Yes please, feel free to send a PR!
