### ISSUE TITLE
Support `api/v1/format_query` for compatibility with Prometheus

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/mimir#4260]
Hi, not sure if valid or not for Mimir.
I suppose formatting does Grafana also, but we have Prometheus UI running on top of Mimir and that supports server-side query formatting, but that is not working with Mimir right now.

Querier/query-frontend could implement this to be fully compatible with the Prometheus API

**Comment by pracucci** [comment]
Looks sensible to me.
