### ISSUE TITLE
 Support the type param in /api/v1/rules endpoint

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/mimir#4261]
Mimir implements the `/api/v1/rules` endpoint, but does not support the documented `type=alert|record` query parameter

see https://prometheus.io/docs/prometheus/latest/querying/api/#rules

Should be easy to implement [here](https://github.com/grafana/mimir/blob/main/pkg/ruler/api.go#L178), the question is if that would be a change in API now or just additional functionality/bugfix

**Comment by pracucci** [comment]
> the question is if that would be a change in API now or just additional functionality/bugfix

I don't think would be a breaking change, because if the parameter is not specified then no filtering will happen. So, I would consider it a bugfix, given this API endpoint is expected be Prometheus-compatible.
