### ISSUE TITLE
Docs: Figure out why "Related documentation" has duplicate content that differs only by version number

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#4347]
@digitalemil writes via email:

"I came to this page (which says: This page has moved to a new location in [the Grafana Mimir Helm chart documentation](https://grafana.com/docs/helm-charts/mimir-distributed/latest/).)
from here:
https://grafana.com/docs/mimir/latest/operators-guide/deploy-grafana-mimir/getting-started-helm-charts/

Can we just link to the new location? Also the pages includes two links to the same:
[Get started with Grafana Mimir using the Helm chart](https://grafana.com/docs/helm-charts/mimir-distributed/latest/get-started-helm-charts/)
[Get started with Grafana Mimir using the Helm chart](https://grafana.com/docs/helm-charts/mimir-distributed/v4.1.0/get-started-helm-charts/)"

**Comment by osg-grafana** [comment]
@jdbaldry, this is related to the auto-generated `Related documentation` content. How can we have more granular control over that?

cc @GrafanaWriter

**Comment by krajorama** [comment]
This is an engineering task that we do from time to time. So adding a new t-shirt size would be on engineering.

**Comment by osg-grafana** [comment]
Moved to @jdbaldry, because I would not be providing the solution for this PR because it is on the engineering side and likely related to Hugo fine tuning.

**Comment by GrafanaWriter** [comment]
This is automatically managed by the website team who have already tuned the Related documentation portion. Please open a new issue in the #website repo if there's further issues.

**Comment by osg-grafana** [comment]
Note that I was not able to reproduce this via testing.
