### ISSUE TITLE
Docs: Specify correct port number values

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#4367]
Feedback came in that I paraphrased somewhat, "At https://grafana.com/docs/mimir/latest/operators-guide/get-started/, if I just run `docker run --rm --name=grafana --network=host grafana/grafana`, there's no Grafana service available on port `3000` as specified later in the tutorial. I had to use `-p 3000:3000`:

`docker run --rm --name=grafana -p 3000:3000 grafana/grafana`

The problematic section: https://grafana.com/docs/mimir/latest/operators-guide/get-started/#query-data-in-grafana"

**Comment by krajorama** [comment]
You are right, actually the Helm chart getting started guide did get this right: see https://grafana.com/docs/helm-charts/mimir-distributed/v4.1.0/get-started-helm-charts/#query-metrics-in-grafana
