### ISSUE TITLE
Rewrite mockQuerier to be able to return histograms

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#4379]
Rewrite mockQuerier to be initialized with implicit native histograms to be able to serve them during Select

https://github.com/grafana/mimir/blob/651a8edda93f1532ed8997d89d9c930b9fd4f3fc/pkg/querier/remote_read_test.go#L45

**Comment by leizor** [comment]
I think I've got this in one of my branches already--I'll dig it up

**Comment by krajorama** [comment]
done in #4425

**Comment by krajorama** [comment]
also partly done in #4444
