### ISSUE TITLE
Mimir http API for ingester flush and shutdown doesnt work

### ISSUE THREAD

**Issue by ofiry-tm** [grafana/mimir#4480]
I set a route in nginx:

```
  nginx:
    enabled: true
    nginxConfig:
      serverSnippet: |
        location /ingester {
          set $ingester {{ my_release}}-mimir-ingester-headless.{{ my_namespace }}.svc.cluster.local;
          proxy_pass      http://$ingester:8080$request_uri;
        }
```

and i sent these 2 http calls (respectfully):

https://mimir.myhost.example/ingester/flush
https://mimir.myhost.example/ingester/shutdown

I have 3 replicas of ingester, one in each AZ,
this is some of the logs of one of them after the http api calls (the other replicas showed similar logs):

```
ts=2023-03-13T17:50:26.610636979Z caller=lifecycler.go:466 level=info msg="lifecycler loop() exited gracefully" ring=ingester
ts=2023-03-13T17:50:26.610759642Z caller=lifecycler.go:791 level=info msg="changing instance state from" old_state=ACTIVE new_state=LEAVING ring=ingester
ts=2023-03-13T17:50:26.61112057Z caller=lifecycler.go:858 level=info msg="transfers are disabled"
ts=2023-03-13T17:50:26.611225033Z caller=ingester.go:2339 level=info msg="starting to flush and ship TSDB blocks"
ts=2023-03-13T17:50:26.847929177Z caller=grpc_logging.go:43 level=warn method=/cortex.Ingester/Push duration=151.181µs err="rpc error: code = Unavailable desc = Stopping" msg=gRPC
ts=2023-03-13T17:50:28.692767229Z caller=compact.go:709 level=info user=anonymous storage=persistent msg="write block" mint=1678724863062 maxt=1678729825500 ulid=01GVE1GM9KBXGXWB9MJ626JDGE duration=2.081439914s
ts=2023-03-13T17:50:28.900904083Z caller=head.go:1246 level=info user=anonymous storage=persistent msg="Head GC completed" caller=truncateMemory duration=205.722381ms
ts=2023-03-13T17:50:28.944913999Z caller=shipper.go:189 level=info user=anonymous msg="upload new block" id=01GVE1GM9KBXGXWB9MJ626JDGE
ts=2023-03-13T17:50:29.401948271Z caller=ingester.go:2348 level=info msg="finished flushing and shipping TSDB blocks"
ts=2023-03-13T17:50:29.402020751Z caller=lifecycler.go:875 level=info msg="lifecycler entering final sleep before shutdown" final_sleep=0s
ts=2023-03-13T17:50:29.402329373Z caller=lifecycler.go:518 level=info msg="instance removed from the KV store" ring=ingester
ts=2023-03-13T17:50:29.409722206Z caller=module_service.go:114 level=info msg="module stopped" module=ingester-service
```

afterwords, i deleted all the mimir pods, and persistentVolumes, 
and then redeployed mimir again.

I was expecting to see all see in the grafana all the old data, including the last 12 hours, but the last 12 hours were gone.

does someone knows what can be the issue ?
i understood that the "shutdown" api call should flush all the data that is on the persistentVolumes to the s3, so that i should have been able to see the last 12 hours data in the grafana after the redeployment.
what am I missing here?

**Comment by krajorama** [comment]
Hi, the ingester endpoints are not exposed on nginx on purpose: 
- your end-users typically shouldn't call those 
- nginx randomly selects an ingester to forward requests to but you'd want to call these endpoints on specific/all ingesters

So the procedure is to port forward to each ingester and call the `/ingester/shutdown` endpoint directly.

**Comment by ofiry-tm** [comment]
@krajorama @pstibrany 
do you by any chance know what is the configuration that decide once in how long the ingester auto-flush the data from persistenVolume to the long-term storage ?

**Comment by pstibrany** [comment]
> @pstibrany and is this configurable? i mean, can it be every 1 hour instead of every 2 hours ?

It depends on the TSDB block range. We don't recommend changing it. What is your use case for lowering this?

**Comment by ofiry-tm** [comment]
actually im just asking for curiosity, maybe ill want to change it in the future
