### ISSUE TITLE
Alertmanager Fallback Config not loaded automatically

### ISSUE THREAD

**Issue by butschi84** [grafana/mimir#4495]
**Describe the bug**
We are using the "mimir-distributed" helm chart and wanted to specify an alertmanager fallback config.
This can be done by setting the value in the helm chart values.yaml file: alertmanager.fallbackConfig
But a fallback config is not activated by just setting this property. I needed to add "alertmanager.extraArgs":
'alertmanager.configs.fallback': '/configs/alertmanager_fallback_config.yaml'

**To Reproduce**
- Configure an alertmanager fallback config by using the helm chart
- check the logs of the alertmanager container. It will tell you that there is no fallback config configured.

**Expected behavior**
- the extra arg in the helm chart (statefulset of alertmanager) should be automatically added when there is a fallback config confgigured (alertmanager.fallbackConfig)
- https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml

**Environment**
openshift, mimir distributed helm chart 2.6

**Comment by dimitarvdimitrov** [comment]
The fallback config is set in the `mimir.config` when the fallback string is provided. 

https://github.com/grafana/mimir/blob/08dba2d37a715af96dac467d0307a7bf1675a91a/operations/helm/charts/mimir-distributed/values.yaml#L136

Did you override the `mimir.config` value?

**Comment by butschi84** [comment]
Thats right, my bad. Yes we actually had to overwrite the config. Over time, it seems we have not taken over all the new items of mimir.config

**Comment by dimitarvdimitrov** [comment]
if you use `mimir.structuredConfig` you don't have to do these regular updates. It doesn't support templating though. Do you need the templating in `mimir.config`?
