### ISSUE TITLE
Docs: remove Helm docs move notifier documents from Mimir

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#4498]
#### Is your documentation request related to a feature? If so, which one?

N/A

#### Describe the solution that you’d like or the expected outcome

We have placeholder docs in Mimir that just say that the doc is moved to the Helm docs. Enough time passed, removed them all.

**Comment by osg-grafana** [comment]
@krajorama and I removed placeholder files from Mimir. If any remain, open a PR to remove any remaining files.
