### ISSUE TITLE
Have per-tenant limit on the number of buckets per native histogram

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#4542]
Add new per-tenant limit

- Implement https://github.com/prometheus/prometheus/issues/12134 
- Implement setting the prometheus TSDB configuration introduced in the above
- Only active if native histograms ingestion is enabled for the tenant
- Limit of 0 means no limit, default is 0.
- Positive limit means push is partial rejected with 4xx and appropriate error message
- Have unit test
- #4547
- #4548
- https://github.com/grafana/cloud-docs/issues/767

**Comment by codesome** [comment]
> Best place is in ingester when we convert the remote write histogram (mimirpb.Histogram) to TSDB histogram (histogram.Histogram)

If we also check limits in distributors, it is an easy and more efficient check there as well which can be checked before the conversion to `histogram.Histogram`.

**Comment by krajorama** [comment]
> > Best place is in ingester when we convert the remote write histogram (mimirpb.Histogram) to TSDB histogram (histogram.Histogram)
> 
> If we also check limits in distributors, it is an easy and more efficient check there as well which can be checked before the conversion to `histogram.Histogram`. **Edit**: On another thought, since it is a partial error, ingesters makes sense since we want to ingest other samples.

My reasoning for ingesters was to avoid looping through the spans/buckets twice - once in the distributor and once in the ingester.

**Comment by krajorama** [comment]
Revisiting where the limit should live, ingester or distributor. 
1) there is no need to iterate the histogram additionally since the bucket count is equal to either len(positiveCounts)+len(negativeCounts) or len(positiveDeltas)+len(negativeDeltas), depending on whether the histogram is a float or integer kind.
2) There's already provisions to partial accept push request and the ability to prune offending series.

Going with distributor after all it seems. Making PR.

**Comment by krajorama** [comment]
implemented on prometheus and mimir sides
