### ISSUE TITLE
Docs: Fix redirect issue for Configure content in `latest`

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#4554]
@dimitarvdimitrov writes, https://grafana.com/docs/mimir/latest/operators-guide/configuring/reference-configuration-parameters/ (latest)
I get redirected to https://grafana.com/docs/mimir/v2.6.x/reference-configuration-parameters/, which is not the latest version

**Comment by osg-grafana** [comment]
@osg-grafana writes, "Should I add ../../operators-guide/configuring/reference-configuration-parameters/ to https://github.com/grafana/mimir/blob/main/docs/sources/mimir/references/configuration-parameters/index.md?plain=1?" and @jdbaldry responds, "Yeah, though I think each of those aliases is probably incorrect"

**Comment by jdbaldry** [comment]
The current aliases will mean each of the following pages will redirect to https://grafana.com/docs/mimir/latest/references/configuration-parameters/
  - https://grafana.com/docs/mimir/latest/references/operators-guide/configuring/references/configuration-parameters/
  - https://grafana.com/docs/mimir/latest/references/operators-guide/configure/references/configuration-parameters/
  - https://grafana.com/docs/mimir/latest/references/references/configuration-parameters/

**Comment by osg-grafana** [comment]
The current state is that folks get a 404 when they go to configuration documentation, at least for the latest version.

**Comment by osg-grafana** [comment]
Some background on this issue:
https://github.com/grafana/mimir/pull/4550
https://github.com/grafana/mimir/pull/4551
https://github.com/grafana/mimir/pull/4552
https://github.com/grafana/mimir/pull/4145
