### ISSUE TITLE
store-gateway: record request metrics for LabelValues & LabelNames calls

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#4595]
Currently the metrics we have for Series RPCs are not recorded for LabelNames and LabelValues. This means that there are sometimes spikes in resource usage that don't seem to correlate with neither chunks, postings, nor series data processing. We should record these metrics for the other two RPCs as well.

A starting point you can where these metrics are defined https://github.com/grafana/mimir/blob/96824523f6308b122c9608962beec3c2329833a8/pkg/storegateway/bucket_store_metrics.go#L58 
and where they are reported https://github.com/grafana/mimir/blob/71b5cf53a059744d34014b5a455b9ebb3fd6a6a2/pkg/storegateway/bucket.go#L828 

Some of these metrics are summaries and probably shouldn't be reported by the LabelValues/Names RPCs if they will always be 0 (e.g. `cortex_bucket_store_sent_chunk_size_bytes`)

<details>
<summary>List of metrics we should probably report too</summary>

* `cortex_bucket_store_series_data_fetched_count`
* `cortex_bucket_store_series_data_fetched_sum`
* `cortex_bucket_store_series_data_size_fetched_bytes_count`
* `cortex_bucket_store_series_data_size_fetched_bytes_sum`
* `cortex_bucket_store_series_data_size_touched_bytes_count`
* `cortex_bucket_store_series_data_size_touched_bytes_sum`
* `cortex_bucket_store_series_data_touched_count`
* `cortex_bucket_store_series_data_touched_sum`
* `cortex_bucket_store_cached_postings_compressions_total`
* `cortex_bucket_store_cached_postings_compression_time_seconds`
* `cortex_bucket_store_cached_postings_original_size_bytes_total`
* `cortex_bucket_store_cached_postings_compressed_size_bytes_total`
* `cortex_bucket_store_cached_series_fetch_duration_seconds`
* `cortex_bucket_store_cached_postings_fetch_duration_seconds`
* `cortex_bucket_store_series_hash_cache_requests_total`
* `cortex_bucket_store_series_hash_cache_hits_total`
* `cortex_bucket_store_series_blocks_queried`
* (only LabelNames) `cortex_bucket_store_series_request_stage_duration_seconds`
* (only LabelNames) `cortex_bucket_store_series_batch_preloading_load_duration_seconds`
* (only LabelNames) `cortex_bucket_store_series_batch_preloading_wait_duration_seconds`
* (only LabelNames) `cortex_bucket_store_series_refs_fetch_duration_seconds`

</details>

**Comment by Gabrielopesantos** [comment]
Hello,
I would like to own on this issue, is that ok? Thank you

**Comment by dimitarvdimitrov** [comment]
Hello, sure! Let me know if you have any questions

**Comment by dimitarvdimitrov** [comment]
hey @Gabrielopesantos, have you had a chance to take a look at this? Is there anything I can help with?

**Comment by Gabrielopesantos** [comment]
Hey @dimitarvdimitrov. Thanks for reaching out.

Yes, I made some progress but its a bit more complex that I thought it would be. If you wanna have a look, here's the current [progress](https://github.com/grafana/mimir/pull/4673) (Don't mind the comments).

I understand the idea of the issue but not the meaning of some variables and where to get their values.
