### ISSUE TITLE
store-gateway load block failed , create index header reader: write index header: get posting offset table from object

### ISSUE THREAD

**Issue by kwenzh** [grafana/mimir#4607]
#### Describe the bug
query data error:
![image](https://user-images.githubusercontent.com/38367518/228412880-1f5a08a8-80f4-43ca-ba60-32abb2ede6d5.png)
the consistency check failed because some blocks were not queried (err-mimir-store-consistency-check-failed). The non-queried blocks are: 01GWK2HSMTYSZPTB0J0198BDC2

#### To Reproduce
query metric range in bad block

#### Environment

- Infrastructure: k8s
- Deployment tool: helm
- mimir version:  2.4.0

#### Additional Context
store-gw error log:
```
 msg="loading block failed" elapsed=405.567182ms id=01GWK2HSMTYSZPTB0J0198BDC2 err="create index header reader: write index header: get posting offset table from object storage of 01GWK2HSMTYSZPTB0J0198BDC2/index: Invalid range specified: start=405872851 end=403211710"
```
querier log:
```
ts=2023-03-29T02:50:29.567360365Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.selectSorted level=warn msg="unable to get store-gateway clients while retrying to fetch missing blocks" err="no store-gateway instance left after checking exclude for block 01GWK2HSMTYSZPTB0J0198BDC2"
ts=2023-03-29T02:50:29.567424733Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.selectSorted level=warn user=anonymous msg="failed consistency check" err=null
level=warn ts=2023-03-29T02:50:29.567595755Z caller=logging.go:86 traceID=22673e7c95edfb05 orgID=anonymous msg="GET /prometheus/api/v1/query_range?end=1679971140&query=bookie_ACTIVE_ENTRY_LOG_COUNT&start=1679961600&step=60 (500) 8.87322ms Response: \"{\\\"status\\\":\\\"error\\\",\\\"errorType\\\":\\\"internal\\\",\\\"error\\\":\\\"expanding series: the consistency check failed because some blocks were not queried (err-mimir-store-consistency-check-failed). The non-queried blocks are: 01GWK2HSMTYSZPTB0J0198BDC2\\\"}\" ws: false; X-Scope-Orgid: anonymous; uber-trace-id: 22673e7c95edfb05:3daabbb38f5082e6:0452aa3bde0fe236:0; "
ts=2023-03-29T02:50:29.813809018Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.LabelValues level=warn msg="unable to get store-gateway clients while retrying to fetch missing blocks" err="no store-gateway instance left after checking exclude for block 01GWK2HSMTYSZPTB0J0198BDC2"
ts=2023-03-29T02:50:29.813865245Z caller=spanlogger.go:80 user=anonymous method=blocksStoreQuerier.LabelValues level=warn user=anonymous msg="failed consistency check" err=null
```

i check s3 bucket data:
s3/mimir-product-tsdb/anonymous/01GWK2HSMTYSZPTB0J0198BDC2
[2023-03-28 10:53:56 CST] 392MiB STANDARD index
[2023-03-28 10:53:56 CST]   638B STANDARD meta.json
[2023-03-29 10:03:53 CST]     0B chunks/

try to download it ,  can not download index file
 mc: <ERROR> Failed to copy `http://xxxxxxxxx/anonymous/01GWK2HSMTYSZPTB0J0198BDC2/index`. Input reader closed pre-maturely. Expected `411600319` bytes, but only received `403211711` bytes.

so  i think The index of data uploaded to the bucket is abnormal. As a result, the data cannot be loaded.  

how to support mimir skip bad block ?

**Comment by kwenzh** [comment]
Temporary  fix：

I found a bad block in the data directory of the ingester, uploaded it again to the bucket, then restarted the store, and query metric data, which has been restored.

but it is not a Long-term solution。 

Can we support skipping bad blocks in the architecture? For bad blocks, we can choose not to display the data for that time interval, to ensure that the query data is not interrupted.

**Comment by dimitarvdimitrov** [comment]
A block is considered complete when it has the `meta.json` file. That file is uploaded by the ingester after all the other files in the block are successfully uploaded.

Is there anything in the logs of the ingester which points to why the upload was partial in the first place? According to the ULID the block should have been created and uploaded around 2023-03-28T03:00:27.418 UTC. Can you try looking in the logs of the ingester around that time?

**Comment by kwenzh** [comment]
> A block is considered complete when it has the `meta.json` file. That file is uploaded by the ingester after all the other files in the block are successfully uploaded.
> 
> Is there anything in the logs of the ingester which points to why the upload was partial in the first place? According to the ULID the block should have been created and uploaded around 2023-03-28T03:00:27.418 UTC. Can you try looking in the logs of the ingester around that time?

Which file was uploaded last, meata.json or index?

**Comment by kwenzh** [comment]
> A block is considered complete when it has the `meta.json` file. That file is uploaded by the ingester after all the other files in the block are successfully uploaded.
> 
> Is there anything in the logs of the ingester which points to why the upload was partial in the first place? According to the ULID the block should have been created and uploaded around 2023-03-28T03:00:27.418 UTC. Can you try looking in the logs of the ingester around that time?



> A block is considered complete when it has the `meta.json` file. That file is uploaded by the ingester after all the other files in the block are successfully uploaded.
> 
> Is there anything in the logs of the ingester which points to why the upload was partial in the first place? According to the ULID the block should have been created and uploaded around 2023-03-28T03:00:27.418 UTC. Can you try looking in the logs of the ingester around that time?

ingester upload block logs
```
level=info ts=2023-03-28T03:02:03.167804204Z caller=compact.go:709 user=anonymous msg="write block" mint=1679961600022 maxt=1679968800000 ulid=01GWK2HSMTYSZPTB0J0198BDC2 duration=1m35.748912376s
level=info ts=2023-03-28T03:02:07.992946491Z caller=db.go:1515 user=anonymous msg="Deleting obsolete block" block=01GWG99BCVB684EWHD73GC92AY
level=info ts=2023-03-28T03:02:16.645516477Z caller=head.go:1215 user=anonymous msg="Head GC completed" caller=truncateMemory duration=8.652502845s
level=info ts=2023-03-28T03:02:17.40734283Z caller=checkpoint.go:97 user=anonymous msg="Creating checkpoint" from_segment=36450 to_segment=36470 mint=1679968800000
level=info ts=2023-03-28T03:02:28.167719275Z caller=shipper.go:185 user=anonymous msg="upload new block" id=01GWK2HSMTYSZPTB0J0198BDC2
level=info ts=2023-03-28T03:09:25.812820715Z caller=head.go:1187 user=anonymous msg="WAL checkpoint complete" first=36450 last=36470 duration=7m8.679695615s
level=info ts=2023-03-28T03:09:43.763284701Z caller=compact.go:649 user=anonymous msg="compact ooo head" mint=1679968800000 maxt=1679976000000 ulid=01GWK32Q3819J2YJ920Y63SHK6 duration=1.898815672s shard=1_of_1
level=info ts=2023-03-28T03:09:44.785206438Z caller=db.go:1515 user=anonymous msg="Deleting obsolete block" block=01GWGG52MV9XGHWKAVKBHCXAW6

```

**Comment by kwenzh** [comment]
> Temporary fix：
> 
> I found a bad block in the data directory of the ingester, uploaded it again to the bucket, then restarted the store, and query metric data, which has been restored.
> 
> but it is not a Long-term solution。
> 
> Can we support skipping bad blocks in the architecture? For bad blocks, we can choose not to display the data for that time interval, to ensure that the query data is not interrupted.

after i  uploaded it again , store error log
```
level=warn ts=2023-03-30T02:17:01.173451102Z caller=bucket.go:392 user=anonymous msg="loading block failed" elapsed=20.330889ms id=01GWK2HSMTYSZPTB0J0198BDC2 err="create index header reader: write index header: new index reader: new TOC: read TOC: invalid checksum"

```
![image](https://user-images.githubusercontent.com/38367518/228713293-d0188dab-0748-405c-b13b-d3cd3bc569d8.png)


it looks like  index file corrupted

**Comment by dimitarvdimitrov** [comment]
I'm not sure how to diagnose the corrupt index.

So this is a level 1 block from an ingester. Because of the 3-way replication of mimir there was no data loss because 2 other ingesters had the same data  (assuming you didn't have an outage in that time). It is safe to ignore this block from being queried and/or compacted. To ignore it you can append `corrupted-` to the name of the block in the bucket.

**Comment by kwenzh** [comment]
> I'm not sure how to diagnose the corrupt index.
> 
> So this is a level 1 block from an ingester. Because of the 3-way replication of mimir there was no data loss because 2 other ingesters had the same data (assuming you didn't have an outage in that time). It is safe to ignore this block from being queried and/or compacted. To ignore it you can append `corrupted-` to the name of the block in the bucket.

thansk you, like this `01GWK2HSMTYSZPTB0J0198BDC2-corrupted` ?

**Comment by kwenzh** [comment]
> I'm sorry I should have said prepend. So `corrupted-01GWK2HSMTYSZPTB0J0198BDC2`. This is what one of the playbooks say - [MimirCompactorSkippedBlocksWithOutOfOrderChunks](https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimircompactorskippedblockswithoutoforderchunks)

ok  let me try it
