### ISSUE TITLE
Docs: Use latest stable version of Helm for Mimir Helm chart installation instructions

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#4615]
@krajorama and I might or might not have run across a bug in Helm 3.4.2, which does not appear in Helm 3.8.2:

`helm -n mimir-test install mimir grafana/mimir-distributed -f custom.yaml`

The following error message displayed:

`$ helm -n mimir-test install mimir grafana/mimir-distributed -f custom.yaml
Error: parse error at (mimir-distributed/templates/validate.yaml:38): unclosed action`

**Comment by krajorama** [comment]
I think @dimitarvdimitrov and I've seen this in the wild as well, but a while ago

**Comment by osg-grafana** [comment]
cc @knylander-grafana, is this an issue for Helm for Tempo too?

**Comment by kurumoorthi89** [comment]
Hi Team, 

I am facing the same issue when deploying mimir-distributed helm chart in a GKE cluster via ArgoCD. 

However I was able to deploy the same successfully from my local (after helm version upgrade to 3.11.2)
 
But the issue persists when deploying via ArgoCD.

_Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in mimir/gke-dev: rpc error: code = Unknown desc = `helm template . --name-template mimir-dev --namespace mimir-dev --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apps/v1 --api-versions events.k8s.io/v1 --api-versions authentication.k8s.io/v1 --api-versions authorization.k8s.io/v1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions policy/v1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions apiextensions.k8s.io/v1 --api-versions scheduling.k8s.io/v1 --api-versions coordination.k8s.io/v1 --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1 --api-versions discovery.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions acme.cert-manager.io/v1 --api-versions acme.cert-manager.io/v1beta1 --api-versions acme.cert-manager.io/v1alpha3 --api-versions acme.cert-manager.io/v1alpha2 --api-versions cert-manager.io/v1 --api-versions cert-manager.io/v1beta1 --api-versions cert-manager.io/v1alpha3 --api-versions cert-manager.io/v1alpha2 --api-versions containerthreatdetection.googleapis.com/v1 --api-versions crd.projectcalico.org/v1 --api-versions monitoring.coreos.com/v1 --api-versions monitoring.coreos.com/v1alpha1 --api-versions snapshot.storage.k8s.io/v1 --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions internal.autoscaling.gke.io/v1alpha1 --api-versions internal.autoscaling.k8s.io/v1alpha1 --api-versions monitoring.grafana.com/v1alpha1 --api-versions nodemanagement.gke.io/v1alpha1 --api-versions pep.optum.com/v1alpha1 --api-versions etcd.database.coreos.com/v1beta2 --api-versions metrics.k8s.io/v1beta1 --include-crds` failed exit status 1: Error: parse error at (mimir-dev/charts/mimir-distributed/templates/validate.yaml:38): **unclosed action Use --debug flag to render out invalid YAML**_

Please let me know how do I overcome this error while deploying via ArgoCD.

**Comment by kurumoorthi89** [comment]
I was able to resolve this by upgrading my ArgoCD appVersion to the latest one which had the Helm version >3.8 bundled within it.

**Comment by osg-grafana** [comment]
The minimum requirement for Helm is documented at https://grafana.com/docs/helm-charts/mimir-distributed/latest/get-started-helm-charts/#software-requirements.

**Comment by osg-grafana** [comment]
Closing per feedback from @krajorama that this issue is resolved via the aforementioned SW requirement.
