### ISSUE TITLE
Track number of optimised regexp label matchers

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#4638]
In `mimir-prometheus` we employ several tricks to optimise the regexp label matcher, using [`FastRegexMatcher`](https://github.com/grafana/mimir-prometheus/blob/main/model/labels/regexp.go#L41).

Since in the query-frontend we parse the query, would be nice to track the total number of regex matchers found and how many of them have been optimized by `FastRegexMatcher` (we may need to expose `FastRegexMatcher.IsOptimized()`). This way we can compute the % of regexp matchers optimized and act if it goes below a critical threshold (we expect a large number of them being optimized).

**Comment by dhanusaputra** [comment]
hi, can I help with this please, thanks

**Comment by jhalterman** [comment]
@dhanusaputra Are you still interested to work on this?

**Comment by dhanusaputra** [comment]
yes @jhalterman :pray:
but feels free to take it, in case need to be resolved quick

**Comment by jhalterman** [comment]
@dhanusaputra This issue is not urgent so feel free to work on it.
