### ISSUE TITLE
Mimir release for FreeBSD

### ISSUE THREAD

**Issue by Crapworks** [grafana/mimir#4652]
It looks like current releases are available for Darwin and Linux platforms only. Are there any plans to provide build for FreeBSD as well?

**Comment by wilfriedroset** [comment]
Hello, if I'm not mistaking we could update the list of GOOS used when building dist.
I've manually tested that to build mimir for freebsd with the following command: `GOOS=freebsd GOARCH=amd64 go build`

We are using [nfpm](https://nfpm.goreleaser.com/configuration/) to package it for debian based and redhat based OS. nfpm does not support packaging for freebsd.

Would this  be enough for your use case?

**Comment by Crapworks** [comment]
Having a binary to download from releases would be perfect! No packaging required.

**Comment by wilfriedroset** [comment]
Alright then, I've submitted the PR to add support for freebsd.
