### ISSUE TITLE
Docs feedback: /operators-guide/get-started/_index.md

### ISSUE THREAD

**Issue by raulmarinperez** [grafana/mimir#4668]
When trying to suggest an edit for this page, I'm redirected to the non-existing resource [https://github.com/grafana/mimir/edit/main/docs/sources/mimir/operators-guide/get-started/_index.md](https://github.com/grafana/mimir/edit/main/docs/sources/mimir/operators-guide/get-started/_index.md)

After some research, it looks like the right URL should be [https://github.com/grafana/mimir/blob/main/docs/sources/mimir/get-started/_index.md](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/get-started/_index.md) instead

**Comment by osg-grafana** [comment]
@raulmarinperez, is this still an issue for you? What version were you looking at when you found this?

**Comment by osg-grafana** [comment]
When pages move around, a suggest-an-edit link can become stale in an older version of the documentation.

The guidance is to either go to the most current version of the documentation and suggest an edit there, or to use the search function to find the respective page that has been moved.

**Comment by osg-grafana** [comment]
Closing because there is a workaround for this issue.
