### ISSUE TITLE
Mimirtool analyze prometheus - add parameter for X-Scope-OrgID (multi tenancy)

### ISSUE THREAD

**Issue by dpunkturban** [grafana/mimir#4738]
#### Is your feature request related to a problem? Please describe.

We are running Mimir with Multi-Tenancy (mimir-distributed helm chart), and therefore we need to set the `X-Scope-OrgID` Header in every request. Currently, it's not possible to use `mimirtool analyze prometheus` when multi-tenancy is enabled or i missed some ways or docs :/ 

#### Describe the solution you'd like

 Would be nice  to have a parameter to set X-Scope-OrgID such as:

```
mimirtool analyze prometheus --address="https://mimir.acme.com/prometheus" --id example--key example --tenant exampleTenant
```

#### Describe alternatives you've considered

It is possible to get the desired metrics if I change the default tenant (which is anonymous) to a tenant that exists. However, this approach is very manual and not applicable from a security perspective.

I also tried to get the metrics directly from the query frontend, but that also needs the x-scope-orgid and didn't work.

#### Additional context

Output from mimirtool when we query against our mimir, where `anynmous` is the default tenant:

```
INFO[0001] Found 0 metric names
INFO[0013] 0 active series are being used in dashboards
INFO[0013] 0 active series are NOT being used in dashboards
INFO[0013] 0 in use active series metric count
INFO[0013] 0 not in use active series metric count
```

Thanks :)

**Comment by xgattuso** [comment]
Hello,

after insisting a bit, I found a workaround. I used `tenant-injector` and made the request like this

```
tenant-injector -local-address :8081 -remote-address http://query-frontend:8080 -tenant-id mytenant
```

```
mimirtool analyze prometheus --address http://127.0.0.1:8081/prometheus
```
And it works. Hope it helps.

**Comment by dimitarvdimitrov** [comment]
existing commands such as `mimirtool alertmanager` and `mimirtool analyze ruler` use the existing `--id` flag and `MIMIR_TENANT_ID` environment variable to set the x-scope-orgid header. For `mimirtool analyze prometheus` this flag is only used for [basic auth](https://github.com/grafana/mimir/blob/8856cd474df3d4514ed0844061c64a06be279b18/pkg/mimirtool/commands/analyse_prometheus.go#L91-L94). I think it's reasonable to use the same flag for the x-scope-orgid header and always set the header if `--id` was set.

**Comment by jmichalek132** [comment]
I would be interested in fixing this Also just ran into it.
