### ISSUE TITLE
[Security] HTTP API /integrator/shutdown

### ISSUE THREAD

**Issue by a-patos** [grafana/mimir#4849]
#### Describe the bug
Hello,

I don't know if this is a bug or a request
but following automated tests by our security teams,

 we realized that the /integrator/shutdown API was exposed by our Mimir-Write instances to all

is it planned to be able to restrict access to this api, either by an authent, or by ip filtering?
or did I miss a piece of configuration that would allow this protection?

#### To Reproduce

call http://myHostIP:8080/integrator/shutdown

#### Expected behavior

have a protection on the stop of the ingestor

#### Environment

- Infrastructure: bare-metal on Amazon AutoScaling
- Deployment tool: CloudFormation

**Comment by charleskorn** [comment]
Mimir does not include any authentication or authorisation on any endpoint - check out the [docs](https://grafana.com/docs/mimir/latest/operators-guide/secure/authentication-and-authorization/#:~:text=To%20protect%20Grafana%20Mimir%20from%20accidental%20or%20malicious%20calls%2C%20you%20must%20add%20a%20layer%20of%20protection%20such%20as%20a%20reverse%20proxy%20that%20authenticates%20requests%20and%20injects%20the%20appropriate%20tenant%20ID%20into%20the%20X%2DScope%2DOrgID%20header.) for more information.

If you'd like to restrict access to any endpoints, we recommend running a reverse-proxy in front of Mimir that performs appropriate authentication and authorisation checks, and limiting direct network access to Mimir components to that reverse proxy.
