### ISSUE TITLE
expose a configuration option to increase the number of tokens per store-gateways

### ISSUE THREAD

**Issue by agardiman** [grafana/mimir#4863]
#### Is your feature request related to a problem? Please describe.
We have one tenant with around 10k blocks. We have 180 store-gateways, in one zone only. The difference between min and max disk utilisation in store-gateways is huge, 81% (min 0.53% disk utilisation, max 0.98%).

#### Describe the solution you'd like
At the moment the number of tokens per store-gateway is hardcoded and set to 512. We are wondering if having more tokens in the ring would alleviate this huge different between store-gateways disk usage. 
In this case, we would like to have the possibility to increase the number of tokens per store-gateway though a CLI option, like the ingesters have.

Having said that, we see that the ownership difference between store-gateways in the ring is not 81% but it's 23.6% (min ownership is 0.495% and max is 0.612%). So after fixing the inbalance, there is still a big difference in disk consumption that I can't fully explain.

#### Describe alternatives you've considered
Not sure if increasing the tokens in this case would fix the issue.

Mimir 2.7.1 on Kubernetes.

**Comment by pstibrany** [comment]
Something to check: Do you use shuffle sharding in your setup? Small shuffle shard for a tenant will concentrate all blocks for given tenant on possibly small number of store-gateways.

**Comment by agardiman** [comment]
@pstibrany we don't use shuffle sharding

**Comment by pracucci** [comment]
> Having said that, we see that the ownership difference between store-gateways in the ring is not 81% but it's 23.6% (min ownership is 0.495% and max is 0.612%). So after fixing the inbalance, there is still a big difference in disk consumption that I can't fully explain.
> [...]
> Mimir 2.7.1 on Kubernetes.

Hi @agardiman. The % of tokens ownership displayed in the UI was wrong. I fixed it in #4730, which is included in Mimir 2.8.0. Can you double check it after upgrading to 2.8.0, please?

**Comment by agardiman** [comment]
really sorry @pracucci, I lost your comment on the way. With 2.8.0 and 190 store-gateways, the min is 0.421% and the max is 0.592%, so ~40% of ownership difference.

**Comment by sarthaktyagi-505** [comment]
Hi @pracucci I have raised a PR for this can you please have a look https://github.com/grafana/mimir/pull/6594

**Comment by pracucci** [comment]
Closing this issue because the config option has been introduced in #6594.
