### ISSUE TITLE
loading block failed" elapsed=24.498963111s id=01GZ8BQFG4W5ZT21YQ4EH1G5SX err="create index header reader: write index header: new index reader: get TOC from object storage of 01GZ8BQFG4W5ZT21YQ4EH1G5SX/index: unexpected EOF

### ISSUE THREAD

**Issue by hexiang1219** [grafana/mimir#4878]
#### query data error:
<img width="600" alt="图片" src="https://user-images.githubusercontent.com/34543240/235402425-76323839-10bb-4c2d-b29b-56b74aa144a6.png">
the consistency check failed because some blocks were not queried (err-mimir-store-consistency-check-failed). The non-queried blocks are: 01GZ89RMHEPW2B6QWT9KPE0P5W 01GZ8BQFG4W5ZT21YQ4EH1G5SX

#### Environment
    Infrastructure: k8s
    Deployment tool: helm
    mimir version: 2.4.0

#### Additional context
store-gw error log:
`loading block failed" elapsed=24.498963111s id=01GZ8BQFG4W5ZT21YQ4EH1G5SX err="create index header reader: write index header: new index reader: get TOC from object storage of 01GZ8BQFG4W5ZT21YQ4EH1G5SX/index: unexpected EOF`

querier log:
` GET /prometheus/api/v1/query_range?end=1682899080&query=sto&start=1682812800&step=120 (500) 1.953675ms Response: \"{\\\"status\\\":\\\"error\\\",\\\"errorType\\\":\\\"internal\\\",\\\"error\\\":\\\"expanding series: the consistency check failed because some blocks were not queried (err-mimir-store-consistency-check-failed). The non-queried blocks are: 01GZ89RMHEPW2B6QWT9KPE0P5W 01GZ8BQFG4W5ZT21YQ4EH1G5SX\\\"}\" ws: false; X-Scope-Orgid: test; uber-trace-id: 47e5152743abe96b:57cf93de9c8dbf8c:38104b73dd91e182:0;`

i check s3 bucket data:
<img width="864" alt="图片" src="https://user-images.githubusercontent.com/34543240/235403562-207c8cee-866b-4adc-9afc-2d623b222a0f.png">

unthought of block index directory on store-gw:
<img width="952" alt="图片" src="https://user-images.githubusercontent.com/34543240/235403606-4dee3083-b9fd-450e-bd42-5f989e258e9e.png">

So I think it is store-gw timed out or failed to pull from s3 ?

**Comment by dimitarvdimitrov** [comment]
The unexpected EOF suggests a problem in the connection to s3 or the object itself. Is the file in s3 intact (can you download it, does the content length match the actual length)?

This block seems like it was compacted from an ingester block. Can you check the compactor logs around 2023-04-30T05:56:17.540Z (+/- 1 hour) about this block ID `01GZ8BQFG4W5ZT21YQ4EH1G5SX`? Maybe that will contain more info if something went wrong with this block.

**Comment by hexiang1219** [comment]
compactor logs: 
`level=error ts=2023-04-30T06:58:58.976532722Z caller=bucket_compactor.go:277 component=compactor user=cost-kcs groupKey=0@17241709254077376921-merge-1_of_3-1682820000000-1682827200000 minTime="2023-04-30 02:04:27.091 +0000 UTC" maxTime="2023-04-30 04:00:00 +0000 UTC" msg="compaction job failed" duration=21.126053053s duration_ms=21126 err="download block 01GZ8BQFG4W5ZT21YQ4EH1G5SX: copy object to file: unexpected EOF"`

**Comment by hexiang1219** [comment]
Failed to download index file
![图片](https://user-images.githubusercontent.com/34543240/236379321-22ccadad-a58f-40f6-8f65-b4d4ee71adee.png)
![图片](https://user-images.githubusercontent.com/34543240/236379292-c209b17f-7068-45ab-9496-ab78dcaeaf6c.png)

**Comment by dimitarvdimitrov** [comment]
This looks very similar to https://github.com/grafana/mimir/issues/4607

> compactor logs:

those seem to be from one hour after the block was compacted. Can you check earlier logs from when the block was uploaded in the first place?

**Comment by hexiang1219** [comment]
compact related logs about this block：
```
evel=info ts=2023-04-30T05:56:17.880484217Z caller=compact.go:510 component=compactor msg="compact blocks" count=1 mint=1682820267091 maxt=1682827200000 ulid=01GZ8BQFG4W5ZT21YQ4EH1G5SX sources=[01GZ892RGWNHQHFK45P31F8K7C] duration=340.320657ms shard=1_of_3
level=info ts=2023-04-30T05:56:17.880647772Z caller=bucket_compactor.go:380 component=compactor user=cost-kcs groupKey=0@17241709254077376921-split-3_of_3-1682820000000-1682827200000 minTime="2023-04-30 02:04:27.091 +0000 UTC" maxTime="2023-04-30 04:00:00 +0000 UTC" msg="compacted blocks" new="[01GZ8BQFG4W5ZT21YQ4EH1G5SX 01GZ8BQFG4EQTZCA5SC9XBVH4F 01GZ8BQFG4NQEWD4K3J63VA80A]" blocks=[/data/compactor/compact/0@17241709254077376921-split-3_of_3-1682820000000-1682827200000/01GZ892RGWNHQHFK45P31F8K7C] duration=340.481204ms duration_ms=340
level=info ts=2023-04-30T05:56:17.922494374Z caller=bucket_compactor.go:425 component=compactor user=cost-kcs groupKey=0@17241709254077376921-split-3_of_3-1682820000000-1682827200000 minTime="2023-04-30 02:04:27.091 +0000 UTC" maxTime="2023-04-30 04:00:00 +0000 UTC" msg="uploaded block" result_block=01GZ8BQFG4W5ZT21YQ4EH1G5SX duration=35.665636ms duration_ms=35 external_labels="{__compactor_shard_id__=\"1_of_3\"}"
level=info ts=2023-04-30T06:58:37.850665546Z caller=bucket_compactor.go:302 component=compactor user=cost-kcs groupKey=0@17241709254077376921-merge-1_of_3-1682820000000-1682827200000 minTime="2023-04-30 02:04:27.091 +0000 UTC" maxTime="2023-04-30 04:00:00 +0000 UTC" msg="compaction available and planned; downloading blocks" blocks=3 plan="[01GZ89RMHEPW2B6QWT9KPE0P5W (min time: 1682820267091, max time: 1682827200000) 01GZ8BZY152DJMZZ55M3QV98R9 (min time: 1682820267091, max time: 1682827200000) 01GZ8BQFG4W5ZT21YQ4EH1G5SX (min time: 1682820267091, max time: 1682827200000)]"
level=warn ts=2023-04-30T06:58:58.976190096Z caller=objstore.go:387 component=compactor user=cost-kcs groupKey=0@17241709254077376921-merge-1_of_3-1682820000000-1682827200000 minTime="2023-04-30 02:04:27.091 +0000 UTC" maxTime="2023-04-30 04:00:00 +0000 UTC" msg="failed to remove file on partial dir download error" file=/data/compactor/compact/0@17241709254077376921-merge-1_of_3-1682820000000-1682827200000/01GZ8BQFG4W5ZT21YQ4EH1G5SX err="remove /data/compactor/compact/0@17241709254077376921-merge-1_of_3-1682820000000-1682827200000/01GZ8BQFG4W5ZT21YQ4EH1G5SX: directory not empty"
level=error ts=2023-04-30T06:58:58.976532722Z caller=bucket_compactor.go:277 component=compactor user=cost-kcs groupKey=0@17241709254077376921-merge-1_of_3-1682820000000-1682827200000 minTime="2023-04-30 02:04:27.091 +0000 UTC" maxTime="2023-04-30 04:00:00 +0000 UTC" msg="compaction job failed" duration=21.126053053s duration_ms=21126 err="download block 01GZ8BQFG4W5ZT21YQ4EH1G5SX: copy object to file: unexpected EOF"
```

**Comment by hexiang1219** [comment]
I look at this issue

**Comment by hexiang1219** [comment]
There are many bad blocks, do I need to add corrupted-? Will these bad blocks have an impact on subsequent larger levels of compression?
![图片](https://user-images.githubusercontent.com/34543240/236600124-d7ab8543-f733-486e-ab68-7ec81ef57503.png)

**Comment by dimitarvdimitrov** [comment]
> ```
> level=info ts=2023-04-30T05:56:17.922494374Z caller=bucket_compactor.go:425 component=compactor user=cost-kcs groupKey=0@17241709254077376921-split-3_of_3-1682820000000-1682827200000 minTime="2023-04-30 02:04:27.091 +0000 UTC" maxTime="2023-04-30 04:00:00 +0000 UTC" msg="uploaded block" result_block=01GZ8BQFG4W5ZT21YQ4EH1G5SX duration=35.665636ms duration_ms=35 external_labels="{__compactor_shard_id__=\"1_of_3\"}"
> ```

this log line means that the compactor received an HTTP 2xx from the object store indicating the upload was successful, but in reality the object is invalid. Are you using AWS S3 or something self-hosted? I would try to look at the logs in the object store from around this time (`2023-04-30T05:56:17.922494374Z`).


> There are many bad blocks, do I need to add corrupted-? Will these bad blocks have an impact on subsequent larger levels of compression?

It's difficult to tell. You can find the blocks in the object store and check the `compaction.level` in the `meta.json` file and compare their times.

If the level is 1 and there are less than 3 such corrupted blocks from the same time range (looking at `minTime` and `maxTime` from meta.json), then you can safely delete them because there will be another replicated block from another igester. If the level is higher (like with `01GZ8BQFG4W5ZT21YQ4EH1G5SX` for example), this means that this block was already deduplicated; in that case I'm afraid the data in those blocks is lost.

Does this happen only for the `index` files of all these blocks? Are any of the files in `chunks/` directory of these blocks also empty?

**Comment by hexiang1219** [comment]
> this log line means that the compactor received an HTTP 2xx from the object store indicating the upload was successful, but in reality the object is invalid. Are you using AWS S3 or something self-hosted? I would try to look at the logs in the object store from around this time (2023-04-30T05:56:17.922494374Z).

The S3 we use is hosted, and the logs cannot be seen, but the S3 service was abnormal during that time, which can be determined. I want to know more about how to skip these bad blocks, because when the query contains these bad blocks, the entire query will be abnormal, and the data in other normal time periods will not be displayed

> This looks very similar to https://github.com/grafana/mimir/issues/4607

I added corrupted- to the bad block according to the method of this issue, but the error of bad block consistency check failure will still be reported when querying, resulting in the failure of the entire query. For example, `01GZ8BQFG4W5ZT21YQ4EH1G5SX` is changed to `corrupted-01GZ8BQFG4W5ZT21YQ4EH1G5SX`. Is it the way I modified it?
![图片](https://github.com/grafana/mimir/assets/34543240/ec7f9e3a-e85a-4278-ae95-f885eb31dd48)

> Does this happen only for the index files of all these blocks? Are any of the files in chunks/ directory of these blocks also empty

Some chunks have a compression level of 1, and the chunks directory is empty. But some compression levels are not 1, like `01GZ8BQFG4W5ZT21YQ4EH1G5SX`, the data under the chunks directory is not empty

**Comment by dimitarvdimitrov** [comment]
> The S3 we use is hosted, and the logs cannot be seen, but the S3 service was abnormal during that time, which can be determined.

Mimir assumes the object store is durable, so Mimir can't withstand data loss within the object store.


> I added corrupted- to the bad block according to the method of this issue, but the error of bad block consistency check failure will still be reported when querying, resulting in the failure of the entire query.

Prefixing all the objects (i.e. renaming the folder) in object store is sufficient, yes. It can take up to 30-60 minutes for the blocks marked as `corrupted-` to stop being queried. Has this time passed already?

> Some chunks have a compression level of 1

I assume you meant "blocks" instead of "chunks". For those you will likely not see any data loss. 

> But some compression levels are not 1, like `01GZ8BQFG4W5ZT21YQ4EH1G5SX`

For these there will be data loss unfortunately.

**Comment by hexiang1219** [comment]
> Prefixing all the objects (i.e. renaming the folder) in object store is sufficient, yes. It can take up to 30-60 minutes for the blocks marked as corrupted- to stop being queried. Has this time passed already?

The query was just modified yesterday. I checked today and there will be no error

This problem is generally understood, thank you very much！
