### ISSUE TITLE
Jsonnet read-write deployment: alertmanager storage hardcoded to filesystem 

### ISSUE THREAD

**Issue by colega** [grafana/mimir#4891]
When using read-write deployment mode, the configuration options for alertmanager storage are ignored and it's hardcoded to `filesystem`:

https://github.com/grafana/mimir/blob/0ace5da36b97a3cce795806729aa3736261b4461/operations/mimir/read-write-deployment/backend.libsonnet#L28-L29

Is that made on purpose or is it an unintended leftover of upstreaming Grafana's internal deployment mode? cc @pracucci

**Comment by pracucci** [comment]
It was on purpose at Grafana Labs, but it was a mistake upstreaming it. We shouldn't upstream it with such config, while we keep it as is at Grafana Labs.

**Comment by colega** [comment]
Thank you, I imagined that, I tried with S3 and it worked fine, but I was wondering if there was still some kind of hidden bit pending to be fixed.

Let me upstream the fix.
