### ISSUE TITLE
OTLP Metrics don't send metadata

### ISSUE THREAD

**Issue by gouthamve** [grafana/mimir#4910]
#### Describe the bug
When ingesting OTLP metrics, we drop the metadata (HELP and TYPE) without propagating it.

#### To Reproduce
Push OTLP Metrics. 

Currently the translation function from upstream OTel Collector doesn't return metadata so we just ignore it: https://github.com/grafana/mimir/blob/4d4a9a9d6bc3a9799e254fe55c7094cf3326d35d/pkg/util/push/otel.go#LL128C1-L128C1

#### Expected behavior

We also append the metadata.

cc @kovrus

**Comment by jmichalek132** [comment]
Hey, while I am at least I am holding off on implementing support for this on otel side until it's clear if there are going to be changes in how metadata is handled as part of remote write protocol https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13849#issuecomment-1621354017 it would be trivial to implement this on mimir side given otel already sends the metadata in every request. Would there be an interest in that? 
I got it working locally, and even tried it in our dev env. Here is draft PR on my fork. https://github.com/jmichalek132/mimir/pull/1

I would like to know if there would be interest in getting this into mimir in the mean time before I spent more of my time on it.

**Comment by jmichalek132** [comment]
Hi, I have a draft of a PR for adding support for sending metadata.
https://github.com/jmichalek132/mimir/pull/1

@gouthamve would you mind taking a look at it if it seems fine before I add tests & change log for it?

**Comment by gouthamve** [comment]
Looks good to me, but let me poke some Mimir maintainers to take a look.

**Comment by charleskorn** [comment]
Thanks @jmichalek132! Your changes generally look good (although I haven't considered them too deeply), so if you could add some tests and open a PR, that would be great.

**Comment by jmichalek132** [comment]
So I raised https://github.com/grafana/mimir/pull/5693 but I have few questions:
* For changelog is this an ENHANCEMENT or a change?
* I am using a function from OTEL `BuildCompliantName` which has a bool `addMetricSuffixes` this control whether simple or more "advanced" translation of otel to prometheus happens, should this be exposed in configuration? (More details here https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/prometheus)
* This whole change should there be a feature flag/configuration option to enable it?
* For the tests, can I extend the existing test case https://github.com/grafana/mimir/blob/main/pkg/util/push/push_test.go#L44C9-L44C9 or should I add another one?
