### ISSUE TITLE
docgen tool should generate documentation for runtimeconfig

### ISSUE THREAD

**Issue by 56quarters** [grafana/mimir#492]
**Is your feature request related to a problem? Please describe.**

New settings typically go into the global configuration and get a corresponding CLI flag or into runtime configuration (if we suspect they will need to be changed often and can be safely reloaded at runtime). Configuration in the global config is automatically included in the reference documentation while runtime configuration is not and must be manually added. This means some runtime configuration options go undocumented.

**Describe the solution you'd like**

The documentation build step to generation a reference markdown file for the runtime config.

**Describe alternatives you've considered**

Continuing to manually document runtime config features.

**Comment by osg-grafana** [comment]
@56quarters, is this still relevant?

**Comment by pracucci** [comment]
Yes.

**Comment by osg-grafana** [comment]
This involves build automation.

**Comment by osg-grafana** [comment]
Moving to `Icebox` until priority changes or resources become available.

**Comment by osg-grafana** [comment]
Keeping this issue alive, and it involves tooling rather than documentation by a technical writer.

**Comment by osg-grafana** [comment]
@jdbaldry, does this sound like something within your remit?

**Comment by jdbaldry** [comment]
I think this is more project specific tooling than a Docs squad initiative but I can take a look if I end up having some free time.

**Comment by Eve832** [comment]
@jdbaldry can you "own" this ticket then? if you're not going to work on it, then no one else on the team is going to and we need to make a decision. it's been _years_ and it's okay to say no.

**Comment by jdbaldry** [comment]
I don't believe it is going to be a priority for me to work on this this quarter. In that case, should we remove this issue from the Docs squad project board?

**Comment by osg-grafana** [comment]
Removing the Docs Squad as owners, and Crístian and I agreed to close it due to low priority, lack of ownership, and docs-specific tooling that engineers are not necessarily going to know about and therefore be less inclined to work on this.
