### ISSUE TITLE
add flag in helm chart values to ignore minio helm chart installation

### ISSUE THREAD

**Issue by reidlai** [grafana/mimir#4951]
#### Is your feature request related to a problem? Please describe.

I have minio cluster installation for Loki and Tempo setup and never expected Mimir helm chart requires minio helm chart installation.  I found there is no option to disable minio subchart installation.

#### Describe the solution you'd like

When I turn off minio.enabled, I expect minio installation will be ignored by helm

**Comment by dimitarvdimitrov** [comment]
hi, can you provide steps to reproduce?

I tried running `helm template grafana/mimir-distributed --set minio.enabled=false` and this doesn't render any resources related to minio.

**Comment by dimitarvdimitrov** [comment]
I'll close this until we know more
