### ISSUE TITLE
Support key prefixes in KV store

### ISSUE THREAD

**Issue by liamkinne** [grafana/mimir#4969]
#### Is your feature request related to a problem? Please describe.

When using Fly.io's Consul service, they partition their consul instance by only allowing access to a key prefix in the ACLs, e.g. `app-name-23sxdf/`. This causes Mimir to fail when setting up rings as it tries to use paths such as `collectors/ring` instead of `app-name-23sxdf/collectors/ring`.

#### Describe the solution you'd like

A new configuration option in the [consul](https://grafana.com/docs/mimir/latest/references/configuration-parameters/#consul) block `key_prefix` which allows configuring a key prefix.

#### Describe alternatives you've considered

I have tried adding the key prefix to the host name, which doesn't work as the client will fail to look up the host, trying to use `hostname.com/app-name-23sxdf` as the host. This would fail anyway as the client would try to make API calls to `hostname.com/app-name-23sxdf/v1/kv/collectors/ring`.

#### Additional context

I imagine this should really be implemented as a client config option in dsutils?? Just thought I would make the issue here as it provides much better context for the use case. This would also apply to Loki.

**Comment by charleskorn** [comment]
Have you tried using the `*.ring.kvstore.prefix` configuration options or the equivalent CLI `-*.ring.prefix` flags? 

(Note that the config file options and CLI flags use slightly different patterns - the options in the config file are nested under `kvstore`, whereas the CLI flags omit `kvstore`.)

For example, to configure the prefix for the distributor, set `distributor.ring.kvstore.prefix` to `app-name-23sxdf/` in your configuration file or pass `-distributor.ring.prefix=app-name-23sxdf/`.

**Comment by liamkinne** [comment]
Just found that... my mistake. Was looking too much at the consul config and missed the kvstore config entirely.

Thanks for the quit reply.
