### ISSUE TITLE
Query-scheduler overhead introduced by GetNextRequestForQuerier()

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#498]
I've observed an unexpected high CPU utilization (constant) in query-scheduler with a large number of querier workers connected (> 1k worker connected to each query-scheduler) and I took a [CPU profile](https://share.polarsignals.com/9d823b4/):

![Screenshot 2021-11-16 at 10 47 30](https://user-images.githubusercontent.com/1701904/141962101-da450027-809d-470c-8d7a-294d4169d7d3.png)

I think we have a bottleneck in `GetNextRequestForQuerier()`. The problem is that each worker waits for the next query, calling `sync.Cond.Wait()`. As soon as a new request arrives, we wake up all workers calling `sync.Cond.Broadcast()`: all workers fight to get the query out of the queue, but only 1 will get it, and then they wait again. This go on over and over.

**Comment by dimitarvdimitrov** [comment]
The sync.Cond usage was removed in https://github.com/grafana/mimir/pull/5880
