### ISSUE TITLE
Getting started link is broken

### ISSUE THREAD

**Issue by rajdevworks** [grafana/mimir#4998]
On the main README.md file, the link to getting started is broken
[Getting started guide](https://grafana.com/docs/mimir/latest/operators-guide/get-started/) - is broken.

#### To Reproduce
Go to [mimir](https://github.com/grafana/mimir) Github page and scroll down to README.md. Click on the Getting started guide.

#### Expected behavior
The hyperlinked URL should work.

**Comment by charleskorn** [comment]
Thanks for reporting this @rajdevworks, I've raised #4999 to fix it.
