### ISSUE TITLE
Docs feedback: /docs/sources/mimir/operators-guide/secure/securing-communications-with-tls.md

### ISSUE THREAD

**Issue by marinnedea** [grafana/mimir#5087]
Please add somewhere a note that this TLS configuration option is available starting with [Mimir 2.4 ](https://grafana.com/docs/mimir/latest/release-notes/v2.4/). Took me an hour to find that information.

**Comment by krajorama** [comment]
Seems to be a duplicate of #4502 . I'll make a note there.

**Comment by krajorama** [comment]
duplicate
