### ISSUE TITLE
Docs: Improve auto-forget feature documentation

### ISSUE THREAD

**Issue by aldernero** [grafana/mimir#5093]
#### Is your documentation request related to a feature? If so, which one?

One of the hash ring features used by many Mimir components is auto-forget. However this feature is not described in the Hash Ring doc, and is only mentioned in the Store Gateway doc.

#### Describe the solution that you’d like or the expected outcome

It makes sense to remove the [auto-forget section](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/store-gateway/#auto-forget) from the Store Gateway doc and add the same description to the [features section](https://grafana.com/docs/mimir/latest/operators-guide/architecture/hash-ring/#features-that-are-built-using-a-hash-ring) of the Hash Ring doc. At the same time it would make sense to review how hash ring features are covered in each of the component docs and ensure the message is consistent.

I'm happy to update the docs, but wanted to create an issue first, as I may not be able to work on it right away.

**Comment by Eve832** [comment]
> I'm happy to update the docs

That would be fantastic—thank you!

**Comment by Eve832** [comment]
tagging @osg for visibility

**Comment by osg** [comment]
Please use my other GH account. :)

**Comment by osg-grafana** [comment]
@aldernero, two questions: is this still relevant? Would you like to update the docs and add me as a reviewer?

**Comment by aldernero** [comment]
After taking a closer look, I realized the store-gateway is the only component that has a flag related to the auto-forget feature, so I think the docs make sense as-is. I'll close the issue.
