### ISSUE TITLE
mimirtool backfill returns 413 Request Entity Too Large

### ISSUE THREAD

**Issue by LSparkzwz** [grafana/mimir#5120]
Hi,
I'm trying to use mimirtool backfill command to upload Prometheus blocks to mimir.
The blocks are up to 40G in size and the endpoint I'm using is the nginx gateway.

I set
mimir.structuredConfig.limits.compactor_block_upload_enabled: true

And
client_max_body_size 0;
inside the http, server and location /api/v1/upload/block/ sections of the nginx config.

Why am I still getting the 413 error?

**Comment by pstibrany** [comment]
Hi. Mimir can return this error too if uploaded `meta.json` file is too big (over 1 MiB), in that case it would return message `The block metadata was too large (maximum size allowed is 1048576 bytes)` in the response.

If the response is different, problem will likely be in some other component. Can you see the full response (preferably including the HTTP headers)?

**Comment by LSparkzwz** [comment]
```
/prometheus $ ./mimirtool backfill --address=http://mimir.com/ --id=test /prometheus/01H1PM2CCWWFD1D1VXZJVBYR23
INFO[0000] Backfilling                                   blocks=/prometheus/01H1PM2CCWWFD1D1VXZJVBYR23 user=test
INFO[0000] making request to start block upload          block=01H1PM2CCWWFD1D1VXZJVBYR23 file=meta.json path=/prometheus/01H1PM2CCWWFD1D1VXZJVBYR23
INFO[0000] uploading block file                          block=01H1PM2CCWWFD1D1VXZJVBYR23 file=index path=/prometheus/01H1PM2CCWWFD1D1VXZJVBYR23 size=5176926965
ERRO[0000] response                                      body="<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity T
oo Large</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" status="413 Request Entity Too Large"
ERRO[0000] failed uploading block                        error="request to upload file \"/prometheus/01H1PM2CCWWFD1D1VXZJVBYR23/index\" failed: POST request to http://mimir.com/api/v1/upload/block/01H1PM2CCWWFD1D1VXZJVBYR23/files?path=index failed: server returned HTTP status: 413 Request Entity Too Large, body: \"
<html>\\r\\n<head><title>413 Request Entity Too Large</title></head>\\r\\n<body>\\r\\n<center><h1>413 Request Entity Too Large</h1></center>\\r\\n<hr><center>nginx</center>\\r
\\n</body>\\r\\n</html>\\r\\n\"" path=/prometheus/01H1PM2CCWWFD1D1VXZJVBYR23
INFO[0000] finished uploading blocks                     already_exists=0 failed=1 succeeded=0
mimirtool: error: blocks failed to upload 1 block(s), try --help
```

This is the response I get after trying the command.

In the nginx gateway I only see this:
```
200 "POST /api/v1/upload/block/01H1PM2CCWWFD1D1VXZJVBYR23/start HTTP/1.1" 0 "-" "mimirtool/2.8.0 (version=2.8.0, branch=release-2.8, revision=f917e084d)"
```

Meanwhile I can't find log errors in the compactor with log level info. But I did try making the request directly to the compactor and I still get 413.

**Comment by LSparkzwz** [comment]
At log_level debug I do see the compactor getting the request even when going through the nginx gateway so I don't think it's its fault:

```
ts=2023-05-31T09:59:42.138321401Z caller=block_upload.go:205 level=debug component=compactor user=test block=01H1PM2CCWWFD1D1VXZJVBYR23 msg="starting block upload"
ts=2023-05-31T09:59:42.138385754Z caller=block_upload.go:457 level=debug component=compactor user=test  block=01H1PM2CCWWFD1D1VXZJVBYR23 msg="uploading uploading-meta.json to bucket" dst=01H1PM2CCWWFD1D1VXZJVBYR23/uploading-meta.json
ts=2023-05-31T09:59:42.167023876Z caller=logging.go:76 level=debug traceID=3402333629cd01f3 msg="POST /api/v1/upload/block/01H1PM2CCWWFD1D1VXZJVBYR23/start (200) 144.998971ms"
```

**Comment by pstibrany** [comment]
Is it possible that there is another nginx in the play? HTML error message returned indicates that it's `<center>nginx</center>` server returning the error.

**Comment by LSparkzwz** [comment]
Yes that was the cause thank you.
But now the backfill command returns me "500 Internal Server Error".

The mimir nginx is returning me:
"104: Connection reset by peer) while reading upstream"
While the nginx ingress controller doesn't show me anything (so I'm not sure if it's still its fault this time too).

The mimir nginx has this config in the http, server and /api/v1/upload/block/ locations:
  client_max_body_size 0;
  client_body_timeout 9999999999s;
  proxy_connect_timeout       9999999999s;
  proxy_send_timeout          9999999999s;
  proxy_read_timeout          9999999999s;
  send_timeout                9999999999s;
  keepalive_timeout 9999999999s;

The ingress controller nginx has similar settings in the configmap which is applied to every location:
  client-body-timeout: '99999999'
  keep-alive: '9999999'
  keep-alive-requests: '999999'
  proxy-body-size: 10000000m
  proxy-connect-timeout: '99999999'
  proxy-next-upstream-timeout: '99999999'
  proxy-next-upstream-tries: '9999999'
  proxy-read-timeout: '99999999'
  proxy-send-timeout: '99999999'
  proxy-stream-next-upstream-timeout: '99999999'
  proxy-stream-timeout: '99999999'
  ssl-session-timeout: 9999m
  upstream-keepalive-requests: '9999999'
  upstream-keepalive-timeout: '99999999'
  
  
Lastly I'm using the backfill command to upload to an oci bucket, but I don't think that's the issues since I've successfully tested large upload outside of mimir.

**Comment by LSparkzwz** [comment]
Alternatively, if I upload the Prometheus blocks from Prometheus itself directly into the bucket without going through Mimir, is that a problem? Shouldn't the compactor scan the bucket and create the index?

**Comment by pstibrany** [comment]
> Alternatively, if I upload the Prometheus blocks from Prometheus itself directly into the bucket without going through Mimir, is that a problem? Shouldn't the compactor scan the bucket and create the index?

No, it's not the problem. Compactor would basically do the same, but it also does lot of checks on the block to make sure it's not corrupted in any way.

**Comment by LSparkzwz** [comment]
Thank you
