### ISSUE TITLE
Docs: Get Started with the Mimir Helm Chart doc instructions fail to install self/meta monitoring

### ISSUE THREAD

**Issue by francoposa** [grafana/mimir#5154]
#### Is your documentation request related to a feature? If so, which one?

The Mimir Get Started with Helm doc
Hosted here: https://grafana.com/docs/helm-charts/mimir-distributed/latest/get-started-helm-charts/
Code here: https://github.com/grafana/mimir/blob/3ec4c9520317733bc979bba2ef52541bcb449286/docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md

The flow instructs users to first install the helm chart as default, then `helm upgrade` with custom values to enable self-monitoring using the `metaMonitoring` section of the chart values.

But that will fail, as documented in values.yaml https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml#L2732-L2735

```yaml
    # -- Controls whether to install the Grafana Agent Operator and its CRDs.
    # Note that helm will not install CRDs if this flag is enabled during an upgrade.
    # In that case install the CRDs manually from https://github.com/grafana/agent/tree/main/production/operator/crds
    installOperator: false
```

#### Describe the solution that you’d like or the expected outcome

Option 1: Add instructions to the docs on manually installing the CRDs.
Much easier, but a bit less ideal in terms of presentation and convenience

Option 2: Rework Helm chart if possible to enabled CRDs to be installed on `helm upgrade`.
I am not familiar with CRDs in Helm charts but I came across this in another repo's issues:
https://github.com/emissary-ingress/emissary/issues/2057#issuecomment-560007192
```
Helm 3 deprecated the hook for crds and has now a policy that there should be a crd directory
https://v3.helm.sh/docs/topics/charts_hooks/
```

**Comment by dimitarvdimitrov** [comment]
> Option 1: Add instructions to the docs on manually installing the CRDs.
> Much easier, but a bit less ideal in terms of presentation and convenience

I think we should do this for the time being. The agent-operator is deprecated at this point too, so the way we do metamonitoring will change.


> Option 2: Rework Helm chart if possible to enabled CRDs to be installed on `helm upgrade`.
> I am not familiar with CRDs in Helm charts but I came across this in another repo's issues:

None of the CRDs are owned by Mimir. I'm also not sure of a good way to vendor CRDs from other repositories/charts (FWIW the agent operator subchart is already present as an archive locally). It may have to be something that we do upon releases.
