### ISSUE TITLE
Docs: How to enable native_histogram in mimir?

### ISSUE THREAD

**Issue by danielnaumau** [grafana/mimir#5179]
These configs don't work:
<img width="769" alt="image" src="https://github.com/grafana/mimir/assets/87636735/502003bb-61a5-4de1-9760-ca2e89babbda">

**Comment by danielnaumau** [comment]
I also tried to use but it didn't help too
<img width="458" alt="image" src="https://github.com/grafana/mimir/assets/87636735/312644ef-6c81-42e4-a581-55d7cd131264">

**Comment by danielnaumau** [comment]
I'm trying to remote write metrics with k6

**Comment by krajorama** [comment]
Hi, we're looking for feedback on native histograms. Have you managed to turn them on? Also note that we have some relevant fixes in the upcoming 2.9 Mimir release for native histograms.
Any chance you're on our community slack: https://grafana.slack.com/archives/C039863E8P7 ?
