### ISSUE TITLE
HA Tracker to Handle Shards

### ISSUE THREAD

**Issue by EStork09** [grafana/mimir#5217]
#### Is your feature request related to a problem? Please describe.

I want my prometheus instances to be able to shard and have replicas without having the metrics being dropped by the HA Tracker

#### Describe the solution you'd like

HA Tracker be able to handle shards, rather than only take 1 shard at a time.

#### Describe alternatives you've considered

Looking at the shard numbers themselves but realized that is exactly the same issue. Opening question also to the prometheus operator to see if there is a way to just get replica number without the pod name.

#### Additional context

If you have multiple shards, and multiple replicas, ideally the HA Tracker should just filter out the replicas, but when targeting the default `prometheus_replica` label, it also filters out shards. Is there a way to just filter between replica sets and not shards?

**Comment by dimitarvdimitrov** [comment]
Is it possible to add the shard ID to the `cluster` label (the default label for `-distributor.ha-tracker.replica`)? I think that was the intended usage of the HA tracker - replicas have the same `cluster` label and only differ by the `__replica__` label. In what you're describing it sounds like different replicas with the same `cluster` value hold different data.

**Comment by EStork09** [comment]
So now:

```
cluster="foo",prometheus_replica="prometheus-0"
cluster="foo",prometheus_replica="prometheus-shard-0-1"
cluster="foo",prometheus_replica="prometheus-1"
cluster="foo",prometheus_replica="prometheus-shard-1-1"
```

and if I did as you were saying it would become:

```
cluster="foo-0",prometheus_replica="prometheus-0"
cluster="foo-1",prometheus_replica="prometheus-shard-0-1"
cluster="foo-0",prometheus_replica="prometheus-1"
cluster="foo-1",prometheus_replica="prometheus-shard-1-1"
```

My only issue with that is a lot of dashboards use the cluster label to be able to support having multiple clusters, and it would be a constant search for which cluster actually has the data, and not all the clusters would have the data as the other one so if you had multiple queries they would get wildly confusing, if that makes sense. I am asking to see if there is just a label to have only the replica number on the operator itself.

As for your question, yes each shard contains different data and when they all come together with a solution like mimir or thanos it is all in one spot. They by default today shard based upon `__address__` labels so that not all prometheus instances have to scrape the data. [More info here](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/shards-and-replicas.md)

**Comment by gespi1** [comment]
I dont understand and need a little clarification please. Why prometheus-0 and prometheus-1 have the same `ha_cluster` label? As from what i understand those are the replicas. `ha_cluster: foo-0` should be composed of prometheus-0 and prometheus-shard-0-1. The for `ha_cluster: foo-1` prometheus-1 and prometheus-shard-1-1. What am i missing? 🤔
