### ISSUE TITLE
Docs: Clarify what URL displays by default for Jsonnet

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#5309]
We don't override `-http.prometheus-http-prefix` flag in Jsonnet, so it defaults to `/prometheus` there as well.

_Originally posted by @pstibrany in https://github.com/grafana/mimir/pull/5292#discussion_r1238372171_

**Comment by krajorama** [comment]
The jsonnet doc https://grafana.com/docs/mimir/latest/set-up/jsonnet/ doesn't have a section to describe how to test the deployment like the helm docs has, so I don't think this has a good place and without adding a  lot of overhead. Seeing that jsonnet isn't priority I propose to close this issue.
