### ISSUE TITLE
Ruler should use regular query path via query-frontend

### ISSUE THREAD

**Issue by simonswine** [grafana/mimir#531]
**Is your feature request related to a problem? Please describe.**

Currently, the ruler integrates a dedicated querier to execute its scheduled instant queries. 

This is not ideal as the ruler has similar risks of running out of memory due to too large queries as queriers do, in the ruler case it might also affect other tenants rule execution (e.g. if it comes to a OOM event).

Also, to support longer ranges or larger datasets, it might be beneficial to use the query-frontend, once it supports breaking up of instant queries using time-splitting and query-sharding.

**Describe the solution you'd like**

The ruler using the query path similarly as other query workloads would use it. To ensure a seamless rule evaluation, a separate per tenant queue should be used for rulers than for queries received by other API clients. 

**Next steps**:

- Provide a more detailed design document

**Comment by pstibrany** [comment]
Thanks to https://github.com/grafana/mimir/pull/1536 ruler can now be configured to use query-frontend and benefit from query-sharding. This can be configured with `-ruler.query-frontend.address` option.
