### ISSUE TITLE
mimir-distributed Helm Chart | Can't define Service Account labels

### ISSUE THREAD

**Issue by ragb** [grafana/mimir#5337]
#### Describe the bug

using the mimir-distributed helm chart, it's not possible to add extra labels to the default serviceAccount (see [template](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/serviceaccount.yaml#L7). I'm not sure this is on purpose or not, but makes it required to create own service account to add extra labels, for instance to configure [azure workload identities](https://azure.github.io/azure-workload-identity/docs/introduction.html) (probably other but it's my particular use case).

I believe adding an extra labels to that template and serviceAccount values would do the trick (and I can' do the required PR), however the context parameter for the mimir.labes template is unclear to me, maybe that has something to do with it.

**NOTE**: I'm unsure is this is a bug or feature request. service account labels seem to be a standard for grafana charts (Loki, etc.) but not present on this.

#### To Reproduce

1. Try defining labels in the service account as annotations and run `helm template`
2. Look at the output, labels are not on the template.

#### Expected behavior

We can pass labels to the created serviceAccount object.

#### Environment

- Infrastructure: AKS, kubernetes 1.26, mimir-distributed chart 4.4.1
- Deployment tool:helm

**Comment by dimitarvdimitrov** [comment]
thanks for reporting this, I've opened #5355 to make labels configurable on the service account
