### ISSUE TITLE
Mimir rollout_operator failed for ARM based system

### ISSUE THREAD

**Issue by kadhamecha-conga** [grafana/mimir#5388]
hi team,

Need support for ARM based deployment for rollout_operator in mimir.

Error:
exec /bin/rollout-operator: exec format error

let me know, if you need more info.

thanks.

**Comment by pstibrany** [comment]
Hello. Starting from version v0.4.0 rollout-operator now has multiplatform amd64 + arm64 Docker images: https://hub.docker.com/r/grafana/rollout-operator/tags
