### ISSUE TITLE
max_query_into_future seems ignored

### ISSUE THREAD

**Issue by xgattuso** [grafana/mimir#5445]
#### Describe the bug
Using `predict_linear()` function to get 1h metrics in the future (but any value after all) only returns back 10m in the future which match default `max_query_into_future: 10m`

By setting `max_query_into_future` to any value we still get 10m.

#### To Reproduce

1. Start Mimir 2.8
2. predict_linear(node_filesystem_avail_bytes{instance="your_instance"}[1h],3600)
3. When I ask Grafana `now-1h` to `now+1h` I only get 10m in the future

#### Expected behavior

When I use Prometheus I have metrics up to `1h` in the future. It's not the case when I query Mimir (same metrics, as Prometheus remote writes to Mimir)

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: Our internal tooling system.

#### Additional Context

![image](https://github.com/grafana/mimir/assets/79837141/6e700f26-f2d3-4d47-a954-a46fb92aca13)

![image](https://github.com/grafana/mimir/assets/79837141/ee9b527d-c0e3-4acc-80d4-4d209492181c)

**Comment by xgattuso** [comment]
I managed to make it works as Prometheus by changing `creation_grace_period` to more than `10m`.

Leaving it open, but feel free to close it if it's not an issue.

**Comment by dimitarvdimitrov** [comment]
we can probably add some validation to not allow setting `max_query_into_future` to a higher value than `creation_grace_period` because of these unexpected results.

An alternative is to make the query-frontend not take `creation_grace_period` into account for queries, but that's already documented and I'm not sure of its purpose.

From the docs

> Also used by query-frontend to avoid querying too far into the future. 0 to disable.

**Comment by wilfriedroset** [comment]
Following https://github.com/grafana/mimir/pull/7496 `max_query_into_future` is deprecated and will be removed in 2.14.
I guess we will be able to close this issue at the release time.
