### ISSUE TITLE
Too new data is reported as "too old"

### ISSUE THREAD

**Issue by bboreham** [grafana/mimir#5643]
#### Describe the bug

[This bug is about the phrasing of the log line; the underlying issue is #5642]
We had two ingesters rejecting all data for one tenant as 'too old', although it was from the current time.
Investigation showed TSDB had blocks from a week earlier, so the data was actually 'too new'.
The Prometheus error is "out of bounds".

```
ts=2023-08-01T08:54:23.27338209Z caller=grpc_logging.go:47 level=warn method=/cortex.Ingester/Push duration=135.107µs err="rpc error: code = Code(400) desc = user=redacted: the sample has been rejected because its timestamp is too old (err-mimir-sample-timestamp-too-old). The affected sample has timestamp 2023-08-01T08:54:22.335Z and is from series {redacted}" msg=gRPC
```

#### Expected behavior

"the sample has been rejected because its timestamp is too new"

This would be easier to debug if both messages stated what the acceptable max/min is, though I'm not sure if it's useful to the end-user.

#### Environment

This was inside Grafana Cloud.

#### Additional Context

This phrasing arrived in #2066, and was suggested by myself in #1908.  However I did not mean it to be used when incorrect.

**Comment by bboreham** [comment]
I am now doubting this is what happened.

**Comment by algo7** [comment]
> I am now doubting this is what happened.

So what happened exactly? Kind of having the same issue now.
