### ISSUE TITLE
Docs: Tempo distributed small, large example setup

### ISSUE THREAD

**Issue by NissesSenap** [grafana/mimir#5692]
#### Is your documentation request related to a feature? If so, which one?

Tempo distributed is an advanced piece of technology and to save time for new community members it would be very good to have an example deployment with small and large setup just like mimir got https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/small.yaml

#### Describe the solution that you’d like or the expected outcome

I would like to have at least 1 example values file that uses the main tempo distributed one to that helps to setup number of replicas and resource requirements to help community members get started on their tempo journey.

**Comment by 56quarters** [comment]
Did you mean to open this issue in the [tempo](https://github.com/grafana/tempo/) repo?

**Comment by 56quarters** [comment]
> 
> Since the helm chart is here, I thought it made sense to open it here. Don't know if this should be classified as documentation or a feature.

I'm confused. The helm chart for Mimir is here, the helm chart for Tempo isn't though. As far as I can tell, the Mimir helm chart doesn't depend on the Tempo chart. Having a `small.yaml` and `large.yaml` for Tempo seems reasonable to me but if you'd like the Tempo developers to take a look, you should open the issue in that repo.

**Comment by NissesSenap** [comment]
Oh, I'm so sorry, I thought I was in the granfana Helm chart repo, too many tabs open. I will fix that tomorrow.

**Comment by NissesSenap** [comment]
Created this in the correct location: https://github.com/grafana/helm-charts/issues/2581
