### ISSUE TITLE
License operations (manifests) like Tempo and Loki

### ISSUE THREAD

**Issue by BronzeDeer** [grafana/mimir#5750]
#### Is your feature request related to a problem? Please describe.

I'm currently authoring an open-source platform stack for kubernetes. Using the Grafana LGTM stack in a non-SaaS capacity has come with some troubles, since it isn't always clear in which cases the AGPLv3 License propagates. In the case of deploying Tempo and Loki as unmodified containers the question is easier to answer since the jsonnet manifests [are specifically licensed under Apache2](https://github.com/grafana/tempo/commit/37aeb4d1c9a66662dfe9e8655d199886739f52af), ensuring that our jsonnet code that depends on them does not need to license under AGPL just to use the unmodified software, however such a provision does not exist for the Mimir manifests. We are now worried that our already open-source code would have to relicense to AGPLv3 just to track the upstream deployment manifests for Mimir.

#### Describe the solution you'd like

Put the `operations/` folder under apache2 licensing like [Loki](https://github.com/grafana/loki/commit/a9d85de4aa5290cf2f8b2dca5d08645bbd0dc66c) and [Tempo](https://github.com/grafana/tempo/commit/37aeb4d1c9a66662dfe9e8655d199886739f52af) have done.

#### Describe alternatives you've considered

We've considered quarantining Mimir into a separate module in a separate repo, however we expect that the mere inclusion/import of the said repo would trigger the whole jsonnet code to require AGPL licensing.

The only alternative would be manually writing and maintaining fully feature jsonnet deployment manifests for mimir on our own that share no copyright connection at all to the code written an maintained in this repository.

**Comment by pstibrany** [comment]
Thanks for raising this problem. I believe that was our original intent, but we missed it. I've created PR with suggested change: https://github.com/grafana/mimir/pull/5753.
