### ISSUE TITLE
Docs: Wrong path to the tutorial "Play with Grafana Mimir"

### ISSUE THREAD

**Issue by abhinavkumar7** [grafana/mimir#5789]
#### Is your documentation request related to a feature? If so, which one?

It's not, it's a bug.

#### Describe the solution that you’d like or the expected outcome

The path to `playing with Grafana` tutorial is wrong.

The incorrect path in docs is `docs/sources/mimir/tutorials/play-with-grafana-mimir/`

The correct path is `docs/sources/mimir/get-started/play-with-grafana-mimir/`

Also, the link is broken for `suggest an edit` option on the same [page](https://grafana.com/docs/mimir/latest/tutorials/play-with-grafana-mimir/).

**Comment by osg-grafana** [comment]
Fixed by #6665.

**Comment by franzwong** [comment]
I don't want to open a new issue because it is not a big issue. The path in the [tutorial video](https://grafana.com/docs/mimir/latest/get-started/) is still `tutorials/play-with-grafana-mimir`.
