### ISSUE TITLE
Run integration tests on an image built with race detector enabled

### ISSUE THREAD

**Issue by colega** [grafana/mimir#5801]
#### Is your feature request related to a problem? Please describe.

We run unit tests with `-race`, but they don't cover race conditions that may happen on unrelated parts of the code, or even in third party libraries. This is especially relevant in the network-related pieces of code where we heavily rely on byte slices pooling.

#### Describe the solution you'd like

Run the integration tests on an image built with `-race` flag.

#### Describe alternatives you've considered

Just ignore it.

**Comment by pstibrany** [comment]
Mimir PR (in progress at the moment): https://github.com/grafana/mimir/pull/5835
