### ISSUE TITLE
`mimirtool analyze grafana --read-timeout` applies to entire process rather than per-request

### ISSUE THREAD

**Issue by colega** [grafana/mimir#5915]
#### Describe the bug

`mimirtool analyze grafana` has a flag:

```
--read-timeout=300s         timeout for read requests
```

However, that timeout is applied to the entire command execution, instead of each request:

https://github.com/grafana/mimir/blob/cf87d8fbd702930a4b62e735d38fe8fe2de3d19b/pkg/mimirtool/commands/analyse_grafana.go#L51-L52

This causes timeout to be reached while fetching individual dashboards later:

https://github.com/grafana/mimir/blob/e1731c57f5c8ea0695043c9b1b6d27946780a67e/pkg/mimirtool/commands/analyse_grafana.go#L88-L88

In other words, this setting has to be updated as your Grafana instance grows and has more dashboards, which is not the purpose of it.

#### To Reproduce

Run `mimirtool analyze grafana` on a fairly big instance, even though all requests go fast, it reaches the timeout and fails analyzing.

#### Expected behavior

The timeout should protect from individual long requests, not stop an entirely long process. In order to achieve that, `AnalyzeGrafana`:

https://github.com/grafana/mimir/blob/e1731c57f5c8ea0695043c9b1b6d27946780a67e/pkg/mimirtool/commands/analyse_grafana.go#L72-L72

Should take a timeout param, and create a new context for each request.

#### Additional Context

This is a good and easy issue for new people who want to contribute.

**Comment by Mihai22125** [comment]
Hi @colega, I'd like to work on this issue. Can you assign it to me, please?

**Comment by colega** [comment]
Sure! Thank you.
