### ISSUE TITLE
mimirtool: LDAP search for admin users

### ISSUE THREAD

**Issue by Dentrax** [grafana/mimir#6007]
#### Is your feature request related to a problem? Please describe.

Admin users can able to inspect users LDAP groups under `/api/admin/ldap/<USERNAME>`. I usually do a `cURL` to API to get users LDAP info. It'd be nice to introduce a new `ldap` subcommand in `mimirtool` for easy check.

#### Describe the solution you'd like

Add new `ldap` subcommand in `mimirtool`.

`mimirtool ldap user.name`: returns list of groups

#### Describe alternatives you've considered

`-`

#### Additional context

`-`

**Comment by dimitarvdimitrov** [comment]
I think i'm missing how this relates to Mimir. Mimir doesn't offer a direct LDAP integration and it doesn't support the `/api/admin/ldap/` endpoint

**Comment by 56quarters** [comment]
This isn't something that makes sense to add to `mimirtool` and would be better served by another tool. I'm going to close this issue.
