### ISSUE TITLE
Unable to successfully connect to configured object storage - issue with bucket connectivity for ap-south-2 region

### ISSUE THREAD

**Issue by Vaibhav-1995** [grafana/mimir#6018]
**Issue**
Trying to deploy mimir helm chart in EKS cluster which is in ap-south-2 region - also created s3 bucket for block storage in ap-south-2 region for the same and configure bucket for block storage and updated the s3 configuration but pods showing below error log -

_ts=2023-09-01T14:05:41.314666075Z caller=sanity_check.go:115 level=warn msg="Unable to successfully connect to configured object storage (will retry)" err="blocks storage: unable to successfully send a request to object storage: The ap-south-2 location constraint is incompatible for the region specific endpoint this request was sent to."_

**Steps to reproduce the behavior:**
- create s3 bucket in ap-south-2 region and try to configure it 
- use IRSA with s3 full access policy for giving permissions
- mimir version v2.9.0
- infrastructure: EKS

**Expected behavior**
Bucket should get configured as same setup is working fine for the ap-south-1 region

**Comment by 56quarters** [comment]
Could you please include your configuration (with any secrets redacted)?

**Comment by Vaibhav-1995** [comment]
@56quarters  Please see below updated configuration - highlighted the main config changes in bold text

serviceAccount:
  # -- Whether to create a service account or not. In case 'create' is false, do set 'name' to an existing service account name.
  create: true
  # -- Override for the generated service account name.
  name:
  **annotations:**
      **eks.amazonaws.com/role-XXX: XXX:aws:iam::XXXXXXXXXXXX:role/XXXXXXXXXX**
  labels: {}

mimir:
  # -- Base config file for Grafana Mimir and Grafana Enterprise Metrics. Contains Helm templates that are evaulated at install/upgrade.
  # To modify the resulting configuration, either copy and alter 'mimir.config' as a whole or use the 'mimir.structuredConfig' to add and modify certain YAML elements.
  config: |
    multitenancy_enabled: false
    no_auth_tenant: anonymous

    usage_stats:
      installation_mode: helm

    activity_tracker:
      filepath: /active-query-tracker/activity.log

    **common:**
        **storage:**
           **backend: s3**
            **s3:**
               **endpoint: s3.ap-south-2.amazonaws.com**
               **region: ap-south-2**

    # This configures how the store-gateway synchronizes blocks stored in the bucket. It uses Minio by default for getting started (configured via flags) but this should be changed for production deployments.
    blocks_storage:
      backend: s3
      bucket_store:
        {{- if index .Values "chunks-cache" "enabled" }}
        chunks_cache:
          backend: memcached
          memcached:
            addresses: {{ include "mimir.chunksCacheAddress" . }}
            max_item_size: {{ mul (index .Values "chunks-cache").maxItemMemory 1024 1024 }}
            timeout: 450ms
            max_idle_connections: 150
        {{- end }}
        {{- if index .Values "index-cache" "enabled" }}
        index_cache:
          backend: memcached
          memcached:
            addresses: {{ include "mimir.indexCacheAddress" . }}
            max_item_size: {{ mul (index .Values "index-cache").maxItemMemory 1024 1024 }}
            max_idle_connections: 150
        {{- end }}
        {{- if index .Values "metadata-cache" "enabled" }}
        metadata_cache:
          backend: memcached
          memcached:
            addresses: {{ include "mimir.metadataCacheAddress" . }}
            max_item_size: {{ mul (index .Values "metadata-cache").maxItemMemory 1024 1024 }}
            max_idle_connections: 150
        {{- end }}
        sync_dir: /data/tsdb-sync
      {{- if .Values.minio.enabled }}
      s3:
        access_key_id: {{ .Values.minio.rootUser }}
        bucket_name: {{ include "mimir.minioBucketPrefix" . }}-tsdb
        endpoint: {{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc:9000
        insecure: true
        secret_access_key: {{ .Values.minio.rootPassword }}
      {{- else }}
      **s3:**
        **bucket_name: as2-qa-ss-mimir-blocks**
      {{- end }}
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 15m
        wal_replay_concurrency: 3

_Please ignore indentation mistake if any which may have been due to copy paste of config_

**Comment by Vaibhav-1995** [comment]
@56quarters Any update on above provided configurations ?

**Comment by Vaibhav-1995** [comment]
Hi Team,

Has anyone encountered the mentioned issue or has anyone performed the test case for the provided configurations ?

**Comment by Vaibhav-1995** [comment]
Hi Team,

URGENT help needed on this

**Comment by Vaibhav-1995** [comment]
> **Issue** Trying to deploy mimir helm chart in EKS cluster which is in ap-south-2 region - also created s3 bucket for block storage in ap-south-2 region for the same and configure bucket for block storage and updated the s3 configuration but pods showing below error log -
> 
> _ts=2023-09-01T14:05:41.314666075Z caller=sanity_check.go:115 level=warn msg="Unable to successfully connect to configured object storage (will retry)" err="blocks storage: unable to successfully send a request to object storage: The ap-south-2 location constraint is incompatible for the region specific endpoint this request was sent to."_
> 
> **Steps to reproduce the behavior:**
> 
> * create s3 bucket in ap-south-2 region and try to configure it
> * use IRSA with s3 full access policy for giving permissions
> * mimir version v2.9.0
> * infrastructure: EKS
> 
> **Expected behavior** Bucket should get configured as same setup is working fine for the ap-south-1 region

Hi Team,

Any updates ?
We are facing this issue in production. Need urgent help?

**Comment by Vaibhav-1995** [comment]
Hi Team,

Any update ?
Your help will be appreciated!

**Comment by Vaibhav-1995** [comment]
#6781 Issue is opened here
