### ISSUE TITLE
About 2.9.1 release

### ISSUE THREAD

**Issue by chenrui333** [grafana/mimir#6036]
👋 it looks like there is some semantics issue, ie the release did not get marked as latest release, let me know if that makes sense. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/142628

![image](https://github.com/grafana/mimir/assets/1580956/8774f6c0-84af-452d-b420-a48faff68a1d)

**Comment by charleskorn** [comment]
Thanks for reporting this @chenrui333 - I've marked 2.9.1 as the latest release now.

**Comment by chenrui333** [comment]
Thanks @charleskorn!
