### ISSUE TITLE
Query-scheduler performance issue after #5880

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#6090]
We're analyzing some read path latency which recently got worse and we've found that looks like there's an issue with the query-scheduler after #5880, which causes the time it takes to enqueue a query in the query-scheduler to grow over time. Looking when the issue started, it began with the rollout of the weekly release n. 255.

The average enqueue latency is measured using:
```
sum by(namespace) (rate(cortex_query_scheduler_enqueue_duration_seconds_sum{container="query-scheduler"}[5m]))
/
sum by(namespace) (rate(cortex_query_scheduler_enqueue_duration_seconds_count{container="query-scheduler"}[5m]))
* 1000
```

We can observe that it grows over time. For example, this is our staging environment:

![Screenshot 2023-09-21 at 12 50 52](https://github.com/grafana/mimir/assets/1701904/b1cfb372-9f1a-46d2-8710-d625d92b03fd)

These are a couple of our production environments:

![Screenshot 2023-09-21 at 12 53 12](https://github.com/grafana/mimir/assets/1701904/015287d8-6859-4374-bb81-3f6a45ca73e6)

**Comment by pracucci** [comment]
In our staging environment, it looks like the issue didn't show after upgrading from weekly release 255 to 256. The weekly release 256 was rolled out on 2023-09-20 at 16:30 UTC:

![Screenshot 2023-09-21 at 13 29 00](https://github.com/grafana/mimir/assets/1701904/1712a352-8789-4d5a-8daf-e9616d414f0e)

**Comment by charleskorn** [comment]
I believe #6100 will fix this issue. See the description in the PR for more details.
