### ISSUE TITLE
Dashboards selectors are too broad

### ISSUE THREAD

**Issue by nicoche** [grafana/mimir#6102]
Hey! First of all, thx for Mimir dashboards, they are gorgeous.

#### Describe the bug

Mimir dashboards show data that is not related to mimir

<img width="638" alt="image" src="https://github.com/grafana/mimir/assets/78445450/843909d6-0240-4472-9c60-c8d7f076c73e">

The labels used to catch series are `container=name_of_the_component` (e.g. `container="ingester"`). I have a loki setup running in the same namespace. Loki turns out to have many components with the same names (e.g. ingester, distributor). Hence, Loki timeseries are showed in mimir dashboards.

#### To Reproduce

- Deploy mimir-distributed chart with dashboards enabled
- Deploy loki-distributed chart

#### Expected behavior

Only show mimir-related timeseries on Mimir dashboards

#### Environment

I deployed loki and mimir using the helm charts.

___

We could probably fix it by filtering on the pod name, which should begin by "mimir": `mimir-ingester-.*`.

I can open a PR to replace the matching labels from 

```
{cluster=~"$cluster", namespace=~"$namespace",container=~"COMPONENT_NAME"}
```

to

```
{cluster=~"$cluster", namespace=~"$namespace",container=~"COMPONENT_NAME",pod=~"mimir-COMPONENT_NAME-.*"}
```

if that looks good to you.

For example: 

```
sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~"$cluster", namespace=~"$namespace",container=~"query-frontend",pod=~"mimir-query-frontend-.*"}[$__rate_interval]))
```

**Comment by charleskorn** [comment]
Thanks for opening this issue @nicoche!

>I have a loki setup running in the same namespace

We generally don't recommend this - it's best if they run in separate namespaces to avoid any name conflicts etc.

>We could probably fix it by filtering on the pod name, which should begin by "mimir"

This prefix is only present when deploying Mimir with the Helm chart, while the Jsonnet library does not include the same prefix.

If deploying Mimir in a separate namespace is not possible, you could compile the Grafana mixin  yourself with this extra filter.

**Comment by nicoche** [comment]
Hey!

Thanks for your answer. I guess this is expected behavior then, if mimir is supposed to be deployed in its own namespace.

We can probably close this 🤝
