### ISSUE TITLE
Docs: link to migrating from Prometheus in README.md is broken

### ISSUE THREAD

**Issue by voltagex** [grafana/mimir#6114]
https://grafana.com/docs/mimir/latest/migrate/migrating-from-thanos-or-prometheus/ is in the readme but is not found on your site, it should be https://grafana.com/docs/mimir/latest/set-up/migrate/migrate-from-thanos-or-prometheus/

**Comment by charleskorn** [comment]
Thanks for reporting this @voltagex! #6115 should fix this.
