### ISSUE TITLE
Allow S3 Storage Provider to support sts_endpoint

### ISSUE THREAD

**Issue by EStork09** [grafana/mimir#6172]
**Is your feature request related to a problem? Please describe.**

Minio has added [sts support](https://min.io/docs/minio/kubernetes/upstream/developers/sts-for-operator.html) to work with the k8s service account JWTs. Currently because it is a different url to hit for sts, we are unable to leverage this feature.

**Describe the solution you'd like**

objstore has added the sts_endpoint in their [configuration file](https://github.com/thanos-io/objstore/blob/main/providers/s3/s3.go#L143), if that could be added to the s3 configuration that would be great!

**Describe alternatives you've considered**

manually creating a service account.

**Additional context**

https://min.io/docs/minio/kubernetes/upstream/developers/sts-for-operator.html
https://github.com/thanos-io/objstore/blob/main/providers/s3/s3.go#L143

**Comment by dimitarvdimitrov** [comment]
it should be simple to inject the sts into the mimir config. This is the conversion between the mimir data struct and the thanos struct if anyone is interested in giving it a shot https://github.com/grafana/mimir/blob/14622a8a3e536cc03d0a46833b02bcdd5a38f1e6/pkg/storage/bucket/s3/bucket_client.go#L40-L77

**Comment by TimKotowski** [comment]
https://github.com/grafana/mimir/pull/6990 (here is the ticket). 
1. Looking at the the tests, i only really see client_test.go that needed a change in the testing. I was looking at the s3 config testing and didn't see it needed, but i want to double make sure that the tests added are in the step in the correct direction. 
2. Do you have any E2E testing for this that I need to check for?

**Comment by dimitarvdimitrov** [comment]
> Does this need an `about-versioning.md` update? and documentation update? Or can am I safe to check both `Documentation Added` and `about-versioning.md` to the check box for the PR.

Thanks for the [PR](https://github.com/grafana/mimir/pull/6990) :) I had a look and I'd say the configuration flag changes that you have there are sufficient.

**Comment by narqo** [comment]
I believe, this has been resolved in #6990 and will be supported in the next release.
