### ISSUE TITLE
False alerts are generated for probe_success metric alert rule when there is metric latency/unavailability in grafana

### ISSUE THREAD

**Issue by Vaibhav-1995** [grafana/mimir#6207]
**Issue**
We have created alert rule using probe_success metric of blackbox exporter to monitor services in our organization. But we are facing issue of false alerts when there is metric break in grafana as below details - 
![image](https://github.com/grafana/mimir/assets/103194544/1b3f3bed-3452-49d2-aa5e-24c005521cb2)

As per above graph - if metric are missing for sometime then already firing alerts are released (UP) when metrics start coming on graph and again goes under firing (DOWN)

**Steps to reproduce the behavior**
1. create alerts rule as - expr: (probe_success == 0)
2. for testing force stop incoming metric in mimir datasource in grafana by removing remotewrite URL from configured prometheus to mimir

**Expected behavior**
If there are already any alerts in firing state in grafana and notification for firing is already send on email then there should not be false alert generated for UP and DOWN again if metrics are stopped for sometime due to xyz issue 

**Environment**
- Infrastructure: Kubernetes
- Deployment tool: helm
- Mimir version: v2.9.0

**Comment by dimitarvdimitrov** [comment]
this is working as expected. When the query stops returning results the alerts stop firing. Sometimes metrics are emitted as a way of triggering an alert. It's the same effect as what you're describing.

Consider using the new [alertmanager feature `keep_firing_for`](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/) on alerting rules.

**Comment by Vaibhav-1995** [comment]
@dimitarvdimitrov Thank you for your reply

But I am facing below issue after updating **keep_firing_for** feature in rules. Please see below - 
![image](https://github.com/grafana/mimir/assets/103194544/d7d339b0-5319-4029-be9b-7123b2a22219)

And below is updated rule - 
![image](https://github.com/grafana/mimir/assets/103194544/a38edbb2-8e78-4da1-8ae5-462207ec3f20)

**Comment by dimitarvdimitrov** [comment]
I believe this will be fixed in grafana 10.1 - see https://github.com/grafana/grafana/issues/75029

**Comment by Vaibhav-1995** [comment]
> I believe this will be fixed in grafana 10.1 - see [grafana/grafana#75029](https://github.com/grafana/grafana/issues/75029)

Hi @dimitarvdimitrov Is this fixed yet or not ? 

Because as I went to https://github.com/grafana/grafana/issues/75029 it says that this is been fixed in https://github.com/grafana/grafana/pull/75163 but when I use new grafana with latest image tag **10.1.4** still facing below issue - 

![image](https://github.com/grafana/mimir/assets/103194544/0c494155-0f9c-47f7-aa6e-80c7750f4038)
