### ISSUE TITLE
Add option to remove schema from jsonnet deployment

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#651]
Our jsonnet still deploys the schema configmap (and empty one) and configures services to load it, but schema file is not used anymore in the blocks storage. We should add an option to conditionally remove it from deployment, so that can be rolled out progressively on clusters and then cleanup jsonnet to fully remove it.

**Comment by andyasp** [comment]
Closing since the schema config was removed by https://github.com/grafana/mimir/pull/812
