### ISSUE TITLE
Helm - Missing Gateway NodePort

### ISSUE THREAD

**Issue by AnthonyKeydel** [grafana/mimir#6548]
Hey, while trying to [migrate to the unifiex proxy deployment](https://grafana.com/docs/helm-charts/mimir-distributed/latest/migration-guides/migrate-to-unified-proxy-deployment/) via Helm chart, our service broke.

We use a NodePort type service, and there is a value in the chart - [gateway.service.nodePort](https://github.com/grafana/mimir/blob/dc6ff683ddeafef9ecba366b18d92ba34ea0b531/operations/helm/charts/mimir-distributed/values.yaml#L2553C7-L2553C7) - that isn't used by the [template](https://github.com/grafana/mimir/blob/dc6ff683ddeafef9ecba366b18d92ba34ea0b531/operations/helm/charts/mimir-distributed/templates/gateway/gateway-svc.yaml#L23).
The value for [nginx.service.nodePort](https://github.com/grafana/mimir/blob/dc6ff683ddeafef9ecba366b18d92ba34ea0b531/operations/helm/charts/mimir-distributed/templates/nginx/nginx-svc.yaml#L27C83-L27C92) *is* used.

In order to successfully update to the newest version, this needs to be fixed.

**Comment by AnthonyKeydel** [comment]
I made the changes here:
https://github.com/grafana/mimir/commit/745c6ba5e4aef7d6aa60903cc7488cdfa41c68b2
(and re-ordered that Port group to match naming conventions)
but I think we also need a new value for legacyPort?

**Comment by dimitarvdimitrov** [comment]
the change looks good. Why do you say we would need a new value for legacyPort?

**Comment by AnthonyKeydel** [comment]
Well, I do not fully understand the purpose of that legacy port.
But if service type is set to NodePort, there is no way to define a static nodePort for legacy-http-metrics.

**Comment by dimitarvdimitrov** [comment]
> the purpose of that legacy port.
I believe this was to aid a migration from an old version of the chart, some time around March 2022.

Both legacyPort and port point to the same pod port. I don't see the need to have two different node ports pointing to the same pod port. From the [Service docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#serviceport-v1-core) it looks like if nodePort isn't specified, then Kubernetes will allocate one which is available. So we should be ok to set the nodePort on the main `port` and leave the `legacyPort` autoassigned.

**Comment by AnthonyKeydel** [comment]
If it points to the same pod port, then I agree. 
In that case, mind if I add some logic to not-create a nodePort for legacyPort?
```
 {{- with .service.legacyPort }}
 {{- if not (eq "NodePort" .service.type) }}
```

**Comment by dimitarvdimitrov** [comment]
if you set the legacy port to `null`, then it doesn't get created
https://github.com/grafana/mimir/blob/745c6ba5e4aef7d6aa60903cc7488cdfa41c68b2/operations/helm/charts/mimir-distributed/values.yaml#L2561-L2562
