### ISSUE TITLE
Ruler Remote Querier shouldn't retry when payload exceeding server.grpc-max-send-msg-size-bytes

### ISSUE THREAD

**Issue by lamida** [grafana/mimir#6609]
#### Is your feature request related to a problem? Please describe.

When RemoteQuerier payload is exceeding `server.grpc-max-send-msg-size-bytes` limit, grpc will refused the request with [grpc error](https://github.com/grpc/grpc-go/blob/f1a1fcd042af436be0eb3ac08ed81e2e29fcde4f/server.go#L1146): `err="rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (%s vs. %s)"`. In Mimir, via dskit, all messages with code.ResourceExhausted will be [retried](https://github.com/grafana/mimir/blob/ff4a68a0e5cc2b183c7fdc82fd4c1be66ed5dcc2/pkg/ruler/remotequerier.go#L303).

However since the same query will be retried, it will hit the same limit again, therefore retry seems futile.

#### Describe the solution you'd like

Skip retry when payload exceeding this limit.

#### Describe alternatives you've considered

NA

#### Additional context

NA

**Comment by pracucci** [comment]
@duricanikolic Is this something that could be easier to do on top of all your errors handling refactoring?
