### ISSUE TITLE
when ingester dynamically added in  production, how the cluster works ?  will it be unavailable for a period of time？

### ISSUE THREAD

**Issue by z7658329** [grafana/mimir#6624]
i have see doc, mimir use  fnv32a hash function, when ingester dynamically added in  production,  there must be a data migration issue involved,  so how the cluster works?

**Comment by krajorama** [comment]
Hi, 

there is no data migration , some series will just start to be written to the new ingester(s). There is no downtime for this operation. On query all ingesters are queried so it doesn't matter where the data is. Eventually the data is written from the old and new ingesters as well to storage where it can be queried . Also later compactor consolidates and de-duplicates the

**Comment by z7658329** [comment]
> Hi,
> 
> there is no data migration , some series will just start to be written to the new ingester(s). There is no downtime for this operation. On query all ingesters are queried so it doesn't matter where the data is. Eventually the data is written from the old and new ingesters as well to storage where it can be queried . Also later compactor consolidates and de-duplicates the series.

ok , thank you
