### ISSUE TITLE
Ingester left in a inconsistent state in the ring if terminated while starting()

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#6753]
#### Describe the bug

Today we had an ingester which received the SIGTERM while opening TSDBs (replaying WAL). The TSDB opening intentionally doesn't stop when the context is cancelled (to reduce the likelihood of on-disk corruptions), but then the ring lifecycler has been started, the ingester switched from `LEAVING` to `ACTIVE` state in the ring, and then the `Ingester.starting()` function has been interrupted because of the context cancellation.

Due to how our service design works, a service doesn't get the `stopping()` function called when the `starting()` fails (for any reason). This means that the ingester was left `ACTIVE` in the ring instead of being switched back to `LEAVING`.

#### Details

The affected ingester was `ingester-zone-a-0`. From its logs we can see:

```
ts=2023-11-27T10:12:55.895412993Z caller=ingester.go:2348 level=info msg="opening existing TSDBs"
2023-11-27 10:16:59.308
ts=2023-11-27T10:16:59.308834995Z caller=ingester.go:2415 level=info msg="successfully opened existing TSDBs"
ts=2023-11-27T10:16:59.308918168Z caller=lifecycler.go:614 level=info msg="not loading tokens from file, tokens file path is empty"
ts=2023-11-27T10:16:59.308970543Z caller=mimir.go:862 level=error msg="module failed" module=ingester-service err="starting module ingester-service: context canceled"
ts=2023-11-27T10:16:59.309516932Z caller=lifecycler.go:660 level=info msg="existing instance found in ring" state=LEAVING tokens=512 ring=ingester
```

We notice two things:

- The ingester failed to start because `context canceled`
- The ring lifecycler logged `existing instance found in ring` which means the `Lifecycler.initRing()` was running and it’s very likely that it switched the instance state to `ACTIVE` in the ring

However, since the ingester logged `err="starting module ingester-service: context canceled"` it means that `Ingester.starting()` didn’t complete successfully. This means, that the `Ingester.stopping()` wasn’t called after that and so the ingester was left in `ACTIVE` state in the ring, even if it was terminated.

As a counter proof, we can see that after the next restart, the same ingester logged:

```
ts=2023-11-27T10:22:34.013538939Z caller=lifecycler.go:660 level=info msg="existing instance found in ring" state=ACTIVE tokens=512 ring=ingester
```

This ☝️  log is telling us that the ingester was already `ACTIVE` in the ring, while we would expect it to be `LEAVING`.

##### Sequence of events

- 10:12:50 - Ingester stopped
- 10:12:55 - Ingester started
- 10:16:59 - Successfully opened existing TSDBs
- 10:16:59 - Ingester switches state to ACTIVE in the ring
- 10:16:59 - Ingester service terminated while still running Ingester.starting()
- 10:18:08 - Ingester stopped
- 10:18:12 - Ingester started
- 10:22:34 - Successfully opened existing TSDBs
- 10:22:34 - Ingester supposed to switch to ACTIVE in the ring, but found out it was already ACTIVE

**Comment by pracucci** [comment]
A couple of things can be done to fix it:

1. Check context cancellation after `openExistingTSDB()` and before `lifecycler.StartAsync()`
2. After calling `lifecycler.StartAsync()`, register a `defer()` to stop the lifecycler (and await for termination) if the `Ingester.starting()` returns an error. 

_We should check all other components having a ring `Lifecycler` or `BasicLifecycler` to fix them if they suffer the same issue._

**Comment by dimitarvdimitrov** [comment]
>A couple of things can be done to fix it:

returning a nil error in `starting` is also an option. That way `stopping` will be called after `starting` exits.

**Comment by pstibrany** [comment]
> returning a nil error in `starting` when the context is cancelled is also an option. That way `stopping` will be called after `starting` exits.

I wouldn't suggest doing this. Returning `nil` from `starting` means that other services, watching ingester service, will think that ingester has started successfully.

Another possibility could be to make Lifecycler a service listener, and make it listen on ingester states. If ingester moves to `Terminated` or `Failed` state, lifecycler could automatically switch state to `Leaving`.

**Comment by pracucci** [comment]
> Another possibility could be to make Lifecycler a service listener, and make it listen on ingester states. If ingester moves to Terminated or Failed state, lifecycler could automatically switch state to Leaving.

Lifecycler is so tricky that I would prefer to not touch it. I would try to just fix it making changes in Ingester.

**Comment by pstibrany** [comment]
> > Another possibility could be to make Lifecycler a service listener, and make it listen on ingester states. If ingester moves to Terminated or Failed state, lifecycler could automatically switch state to Leaving.
> 
> Lifecycler is so tricky that I would prefer to not touch it. I would try to just fix it making changes in Ingester.

This specific change would be quite trivial to make -- it doesn't even need to be in the lifecycler, we just need to add listener to ingester and then stop lifecycler. It's few lines of code.

I agree that your proposal using `defer` is simpler, but it only covers `starting` state. My proposal would cover entire lifecycle of ingester. (But then it's also becoming bigger change.)

Let me just point out that the whole point of "services" library was to have objects with an observable lifecycle. "Lifecycler" could use it.
