### ISSUE TITLE
docs: does Mimir support the `delete_series` endpoint?

### ISSUE THREAD

**Issue by hobbsh** [grafana/mimir#6799]
#### Is your documentation request related to a feature? If so, which one?

I have been unable to find information on support for the [delete_series](https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-admin-apis) endpoint with Mimir. I am deploying via the `mimir-distributed` helm chart and am having difficulty finding a path through to this endpoint, if it exists in Mimir.

Also, for deletes to fully work, [clean_tombstones](https://prometheus.io/docs/prometheus/latest/querying/api/#clean-tombstones) would also need to be supported, or really just the entire set of `tsdb-admin-apis`.

#### Describe the solution that you’d like or the expected outcome

If support exists, it would be great if [this page was updated](https://grafana.com/docs/mimir/latest/references/http-api/) along with some helm chart changes potentially to make things more clear. If not, I guess this would turn into a feature request.

**Comment by osg-grafana** [comment]
Closing this doc issue because there is not action to take.

**Comment by hobbsh** [comment]
Thanks @pstibrany, any plans to add support for the `tsdb-admin-apis`?

**Comment by pstibrany** [comment]
> Thanks @pstibrany, any plans to add support for the `tsdb-admin-apis`?

No immediate plans at the moment. We would like to support series deletion API (with async block rewriting), but I don't see Mimir supporting "snapshot" or "clean tombstones" APIs. 

Ping @zhehao-grafana.

**Comment by hobbsh** [comment]
Makes sense given Mimir's architecture. Thanks @pstibrany!
