### ISSUE TITLE
query-frontend/query-scheduler: query queue time is incorrect 

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#6830]
I spotted this instance of queue time reported as ~1400 seconds (23 minutes), while the whole query took less than 2 minutes.
<img width="470" alt="Screenshot 2023-12-05 at 17 46 47" src="https://github.com/grafana/mimir/assets/21020035/a3212be5-9cd9-418a-b4ea-22f9aa812188">

**Comment by narqo** [comment]
After looking through a couple of more examples, this doesn't seem like a bug.

That is, the `queue_time_seconds` and `query_wall_time_seconds` values render the **total time**, across multiple shards and/or splits of a query (which are being processed concurrently)

<img width="636" alt="Screenshot 2024-01-18 at 09 06 02" src="https://github.com/grafana/mimir/assets/88045/ce5eaeeb-55c0-4620-8075-263bd35c4371">
