### ISSUE TITLE
Docs: Documentation Missing for `block_ranges_period` in `blocks_storage.tsdb` Section

### ISSUE THREAD

**Issue by weidaolee** [grafana/mimir#6856]
### Description
The official Grafana Mimir documentation for `blocks_storage` [configuration parameters](https://grafana.com/docs/mimir/latest/references/configuration-parameters/#blocks_storage) lacks information about the `block_ranges_period` configuration option. This option is crucial for understanding how and when ingesters upload chunks, manage disk space usage, and prevent potential issues related to disk space depletion.
The `block_ranges_period` configuration option is implemented in the Mimir source code, which can be referenced here: [Mimir GitHub Repository - config.go L198](https://github.com/grafana/mimir/blob/main/pkg/storage/tsdb/config.go#L198).

### Importance
The absence of detailed documentation on the `block_ranges_period` and its implications can lead to critical operational issues. For instance, with the default `block_ranges_period` value set to 2 hours and the default Persistent Volume Claim (PVC) size for `ingester` being 2 Gi, there is a significant risk of running out of disk space in approximately 10 minutes. This situation can lead to operational disruptions and requires urgent attention in the documentation to guide proper configuration settings.

### Expected Documentation Enhancements
1. **Inclusion of `block_ranges_period` Details:**
   - Add a section explaining the `block_ranges_period` configuration option, including its purpose, usage guidelines, and impact on Mimir operations.
   
2. **Deep Dive into Data Flow Impacted by Configurations:**
   - A detailed guide on how specific configuration settings influence data flow processes such as:
     - **Data Retention:** How configurations determine the duration for which data is retained and the mechanism of data deletion post-retention period.
     - **Compaction:** Explanation of how data is compacted, the role of various configurations in this process, and its impact on system performance and storage efficiency.
     - **Cleanup Delay and Mark-Delete Processes:** Understanding the delayed cleanup operations and mark-delete mechanisms, including the effect of relevant configurations on these processes.

**Comment by pstibrany** [comment]
`block_ranges_period` is one of those options that we do NOT expect people to modify, as it has serious implications on the overall functionality and stability of Mimir cluster. 

We do not plan to document this option to the level suggested in this issue, and would instead strongly suggest not to change it.

> For instance, with the default block_ranges_period value set to 2 hours and the default Persistent Volume Claim (PVC) size for ingester being 2 Gi, there is a significant risk of running out of disk space in approximately 10 minutes.

While 2 Gi size for ingester can be just fine for tiny installations, it really seems to be very small. However the solution is not to change `block_ranges_period`, but increase disk size.

**Comment by weidaolee** [comment]
Thank you @osg-grafana, that's OK with me.
