### ISSUE TITLE
Cloudwatch metrics alert is not going to Firing state through Mimir Alertmanager - URGENT !!!!

### ISSUE THREAD

**Issue by Vaibhav-1995** [grafana/mimir#6858]
#### Issue
We are using prometheus-cloudwatch-exporter to scrape cloudwatch metrics and push them to mimir datasource. We are able to see those metrics in grafana explore under mimir datasource. But when we created alert rule in mimir ruler it is not going to Firing State even though the metric exceeds threshold value.

#### Please refer below details : -
![image](https://github.com/grafana/mimir/assets/103194544/c204b211-0e1f-42a5-9166-4b20f4dbd99a)

Alert rule in ruler configmap -
![image](https://github.com/grafana/mimir/assets/103194544/b6a888db-1856-4e01-9ac5-df9f5ce9be61)

Not going to Firing State from listed rule -
![image](https://github.com/grafana/mimir/assets/103194544/12264fea-1c4a-4d3b-a34d-4c5e3feadd3f)

#### Environment
- Infrastructure:  Kubernetes
- Mimir Version: 2.9.0
- Prometheus Cloudwatch Exporter Version: 0.25.1
- Deployment tool:  helm

#### Expected behavior

It should go to the Firing state and alert should get triggered for set rule as all required configurations in alertmanger are done.

Also if when I tested the same alert rule in grafana UI by creating it with Grafana managed alert then its going in firing state. Please see below image -
![image](https://github.com/grafana/mimir/assets/103194544/753c2006-d7c2-4671-8e09-f16fd74f9087)

**Comment by Vaibhav-1995** [comment]
HI Team,

Any updates?

**Comment by pstibrany** [comment]
Mimir evaluates rules as instant queries at "now" timestamp (in fact, `now - 1m` by default). At that point there are no series above 30, so no alert notification is sent.

<img width="1999" alt="SCR-20231211-jmyv" src="https://github.com/grafana/mimir/assets/895919/f1d7596c-ad65-4bc0-a34e-b66a1d946cfb">
