### ISSUE TITLE
Docs: explain reason for why caches should be separated

### ISSUE THREAD

**Issue by andsens** [grafana/mimir#6887]
Under "[production tips](https://github.com/grafana/mimir/blob/6b214e14bd93728dae55aa1775bb46b55e8705f4/docs/sources/mimir/manage/run-production-environment/production-tips/index.md#L121-L122)" the documentation states:

> We also recommend running a dedicated Memcached cluster for each type of cache: query results, metadata, index, and chunks. Running a dedicated Memcached cluster for each cache type is not required, but recommended so that each cache is isolated from the others.

To paraphrase: "The caches should be separated by type, so that they are separated by type".  
I would love to know a less tautological reason for the separation.

The compelling advantage of running all cache types on one (or multiple replicated) instance is reduction in overhead (or conversely, the ability to cheaply overprovision).

**Comment by dimitarvdimitrov** [comment]
Thanks for pointing this out. I agree this piece of docs can be improved. I'm leaving some of my thoughts, perhaps other can chime in as well


Benefits of using the same cache:
* preventing different caches from interfering - index cache can hold some large items (order of 10s of 100s of MBs). Multiple of those items can end up as a considerable % of the cache size. Keeping multiple caches allows to reduce the impact of such large items. For example chunks cache performance wouldn't be affected by large `/series` requests.
* being able to track memcached stats on a per-cache basis. For example tracking item age is only possible on a per-slab basis. If we mix multiple items in the same cache we don't know where the churn is coming from. This is a somewhat niche use case.
* being able to scale the caches independently. Once you've identified a bottlenecking cache you can scale only that and make sure its items take the full benefit from the scaleout.

Drawbacks of using the same cache:
* it's much harder to figure out which cache to scale. When you have a single cluster you just scale it until hit rate and item age are sufficient.

**Comment by 56quarters** [comment]
My thoughts (to help with docs):

Chunks cache and index-queries cache are the most used caches but they have very different usage patterns. Values from the chunks are typically 16KB in size and are requested 100 at a time by store-gateways. This means these caches store a large amount of data and have high bandwidth requirements but relatively little CPU usage. Values from the index-queries cache are smaller (usually less than 1KB) but much more numerous. They're also often requested one-at-a-time. This means more CPU usage for these caches. You can see this reflected in the default sizing of each of these caches in the Helm chart: chunks cache is 0.5 CPU per 6GB of RAM while the index-queries cache is 0.5 CPU per 1GB of RAM.

Another (minor) benefit of using separate caches for each type of cache makes it easier to invalidate them if required. E.g. if you need to invalidate all cached query results you can do that by restarting all `memcached-frontend` instances.
