### ISSUE TITLE
2.11.0 release did not get marked as latest release

### ISSUE THREAD

**Issue by chenrui333** [grafana/mimir#6986]
👋 looks like 2.11.0 did not get marked as latest release, also the `latest release` designation is pointing to 2.10.4. Thanks! 

relates to https://github.com/Homebrew/homebrew-core/pull/158021

**Comment by dimitarvdimitrov** [comment]
Since @leizor is the shepherd of that release, maybe he can pitch in there? But we still haven't promoted a release candidate to a final release, not sure why 2.11.0 is showing up in Releases 🤔

**Comment by leizor** [comment]
[Release 2.11.0](https://github.com/grafana/mimir/releases/tag/mimir-2.11.0) is now published, and the latest release designation now points to it.
