### ISSUE TITLE
Continuous  error logs  observed in mimir-querier service  when used without query-scheduler

### ISSUE THREAD

**Issue by BhargavNalluri** [grafana/mimir#7023]
#### Describe the bug
There's a lot of error logs in the querier service as soon as the chart was installed by using this [values file](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml) ,just couple of  changes-- s3 is added as backend, ingestor,storage gateway zone aware replication is false and query scheduler and alert manager are disabled and for resources allocation changes are made according to handle 1million by following this [file resources](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/small.yaml) ,that it. All the service are running with out no errors or atleast warnings except querier .
 

```
ts=2023-12-29T05:34:05.280080309Z caller=frontend_processor.go:89 level=error msg="error processing requests" address=10.90.10.260:9095 err="rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: NO_ERROR, debug data: \"max_age\""
ts=2023-12-29T05:34:05.28008376Z caller=frontend_processor.go:89 level=error msg="error processing requests" address=10.90.10.260:9095 err="rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: NO_ERROR, debug data: \"max_age\""
``` 

#### To Reproduce

1. Install the chart with attached values file, please change service account and s3 . 
2. Observe all the services will enter running state and Check the logs of querier.
3. Used values file  -[Values-mimir.txt](https://github.com/grafana/mimir/files/13791252/Values-mimir.txt)
4. Revision and version -- version=2.10.4, branch=r270, revision=297e905

#### Expected behavior

The querier service is filled with above error logs , and the endpoint it's pointing to is querier-frontend-headless which seems to be correct from helm chart as well. Not sure how to resolve this ,Any help is highly appreciated thanks ..!

#### Environment

- Infrastructure: [Kubernetes (eks)]
- Deployment tool: [helm]

#### Additional Context

Even though the querier service is filled with error of such , there's not issues observed while data queries or while loading dashboards in grafana.
It's observed  in all of our environments. No changes have been done on the env from mimir side like upgrade or any restart of pods are not  observed.

**Comment by dimitarvdimitrov** [comment]
This should be a recoverable error. 

I believe the error should be coming from [here](https://github.com/grafana/mimir/blob/576787503bcdc7c5ca7ce0b4d175a73664f9318f/pkg/querier/worker/frontend_processor.go#L88-L92). It's valid gRPC behaviour to [return EOF](https://github.com/grafana/mimir/blob/badb73d84f094db154d1e146c1d0a3a57b0b3880/vendor/google.golang.org/grpc/stream.go#L133-L136). I suspect that handling EOF [here](https://github.com/grafana/mimir/blob/576787503bcdc7c5ca7ce0b4d175a73664f9318f/pkg/querier/worker/frontend_processor.go#L88-L92) should do the job.

**Comment by narqo** [comment]
Related to https://github.com/grpc/grpc-go/issues/6504, I think it's a bit more tricky.

The actual error (formatted for readability):

> ```
> rpc error: 
> code = Unavailable 
> desc = closing transport due to: connection error: 
>     desc = \"error reading from server: EOF\", received prior goaway: code: NO_ERROR, 
>     debug data: \"max_age\"
> ```

Note that the `error reading from server: EOF` is not an error the `frontendProcessor` receives, but a **string**, that its gRPC transport embedded into the error's description.

If I follow it right, this comes after the gRPC server's defaults, the Helm chart sets (see [values.yaml][1]). That is, with `grpc_server_max_connection_age` or `grpc_server_max_connection_idle` set, the server asks the client to close the connection, by sending GoAway. I believe, if the client doesn't follow the instruction, the server forcefully closes the client's connection after a "grace" period.

[1]: https://github.com/grafana/mimir/blob/c39af792988826fed28950fed15f3d5a48291cf1/operations/helm/charts/mimir-distributed/values.yaml#L368-L371

**Comment by dimitarvdimitrov** [comment]
> if the client doesn't follow the instruction

is this a responsibility of the gRPC library or of Mimir?

**Comment by narqo** [comment]
> is this a responsibility of the gRPC library or of Mimir?

It's a bit of a gray area to me. The [HTTP/2 suggests (ref RFC 7540/6.8)][1] this to be done by the client. But gRPC servers don't expose the knowledge about the first GOWAY to the client. The suggestion from https://github.com/grpc/grpc-go/issues/6504 is that the client should implement their own side of connection lifetime tracking, and set the liefetime lower than server's `max_connection_age`, to gracefully respawn the connection and the stream.

[1]: https://www.rfc-editor.org/rfc/rfc7540#section-6.8

**Comment by dimitarvdimitrov** [comment]
> 1. if the current behaviour causes any problems, or maybe we could skip these error logs, and keep restarting the connection

I can't tell from the logs that @BhargavNalluri has shared. But looking at the code the error should be retired, so it's fairly safe to swallow and keep going.

> 2\. are there other parts of Mimir that should have shown the same problem, but they don't 🤔

So this issue is when the querier receives queries directly via the query-frontend. I can't tell how the querier's query-scheduler client handles these errors. From a brief look at [the code](https://github.com/grafana/mimir/blob/9b742c1b701f6c0690b12e4aaa25663b4b498299/pkg/querier/worker/scheduler_processor.go#L127-L135), it looks like it's handling it in the same way (logging the error)? Worth verifying though.
