### ISSUE TITLE
Release a module with mimir's proto files only

### ISSUE THREAD

**Issue by jkremser** [grafana/mimir#7249]
Currently, there is no way to add the .proto files as a dependency w/o adding the whole grafana/mimir that depends on tons of other stuff. It would be nice to have it as a separate repo/module on which users can depend.

Depending on `grafana/mimir` adds a lot of transitive dependencies and leads to dependency conflicts.

**Comment by pstibrany** [comment]
Mimir does not have any .proto files for public consumption. If you want to push requests to Mimir using [Prometheus remote-write protocol](https://prometheus.io/docs/concepts/remote_write_spec/#protocol), I would suggest to use [the definition from Prometheus repository instead.](https://github.com/prometheus/prometheus/blob/v2.24.0/prompb/remote.proto)
