### ISSUE TITLE
[mimir-distributed] Compactor headless service is missing

### ISSUE THREAD

**Issue by alita1991** [grafana/mimir#7263]
#### Is your feature request related to a problem? Please describe.

StatefulSets currently requires a Headless Service to be responsible for the network identity of the Pods.
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations

#### Describe the solution you'd like

Create a headless service that is already defined for other components.

#### Additional context

This was discovered while running kube-score and kube-linter, which is used to align the helm chart to NFRs.

**Comment by dimitarvdimitrov** [comment]
mimir doesn't need a headless service for the compactors. I am not sure if adding a service just for the sake of it makes sense. It's a maintenance burden (even though only a small one).

Have you considered using `extraObjects`?

https://github.com/grafana/mimir/blob/7640ca1b5fa214f9b0d752d8879697f2dd2166a1/operations/helm/charts/mimir-distributed/values.yaml#L3803-L3811
