### ISSUE TITLE
error on resource metrics with no metrics 

### ISSUE THREAD

**Issue by zeitlinger** [grafana/mimir#7272]
#### Describe the bug

When I send a `resource_metrics` protobuf request with no metrics in it, I get a 400.

#### To Reproduce

1. Send the protobuf request to mimir OTLP receiver - it has a resource, but no metrics
2. Get a 400 with the message below

```
resource_metrics:{resource:{attributes:{key:"service.name" value:{string_value:"unknown_service:dice"}} attributes:{key:"telemetry.sdk.language" value:{string_value:"go"}} attributes:{key:"telemetry.sdk.name" value:{string_value:"opentelemetry"}} attributes:{key:"telemetry.sdk.version" value:{string_value:"1.23.0-rc.1"}}} schema_url:"https://opentelemetry.io/schemas/1.24.0"}
```

```
failed pushing to ingester ingester-zone-c-15: user=807628: the sample has been rejected because another sample with a more recent timestamp has already been ingested and this sample is beyond the out-of-order time window of 10m (err-mimir-sample-timestamp-too-old). The affected sample has timestamp 1970-01-01T00:00:00Z and is from series target_info{job="shopping-cart", telemetry_sdk_language="go", telemetry_sdk_name="opentelemetry", telemetry_sdk_version="1.23.0-rc.1"} (sampled 1/10)
```

#### Expected behavior

No error

#### Environment

- Infrastructure: Grafana Cloud

#### Additional Context

`AppendEmpty()` might be the problem: https://github.com/grafana/mimir/blob/88617303a6c784aa52c8346d57f75272faabfc25/vendor/go.opentelemetry.io/collector/pdata/pmetric/json.go#L52

**Comment by zeitlinger** [comment]
no changes to the DB I'd say.

**Comment by alexfalkowski** [comment]
I found this error in another repo and I can reproduce it as seen in the comment https://github.com/open-telemetry/opentelemetry-go/issues/4133

**Comment by aknuds1** [comment]
To clarify, wouldn't this OOO error happen also if the OTLP write request did have metrics? I.e., the error is independent of the fact that Mimir tries to write a `target_info` sample even with no corresponding time series?

**Comment by aknuds1** [comment]
Also, why is it a problem in itself that Mimir writes to `target_info` if the write request lacks other metrics?

**Comment by aknuds1** [comment]
Oh, I see the timestamp is the Unix epoch, that is the root problem, right? Trying to understand what leads to this.

**Comment by aknuds1** [comment]
Aha, I think the actual bug is that the timestamp is only set if there are any metrics. @zeitlinger do you have any particular reason to think that OTel metrics backends should ignore requests with only resource attributes and no metrics? What if the non-identifying resource attributes change for example, shouldn't Mimir record this?

**Comment by aknuds1** [comment]
I'll make a PR to opentelemetry-collector-contrib.

**Comment by zeitlinger** [comment]
> What if the non-identifying resource attributes change for example, shouldn't Mimir record this?

I haven't thought about this edge case.
I guess ideally Mimir should record this.

**Comment by aknuds1** [comment]
Asked for feedback in CNCF [Slack](https://cloud-native.slack.com/archives/C01LSCJBXDZ/p1712829450266559), to see if I can rustle up some feedback.

**Comment by aknuds1** [comment]
Come to think of it, I'm wondering if it's bad to assume current time for the `target_info` timestamp in case the writer is behind (out of order) and it would override an update that was generated more recently on the client side.

**Comment by aknuds1** [comment]
I opened an opentelemetry-collector-contrib [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32318), opting to _not_ generate `target_info` if metrics are not included.

**Comment by alexfalkowski** [comment]
I saw the PR was merged, though I am not sure when this fix will be released. Which package will have this fix and when?

Appreciate your help.

**Comment by aknuds1** [comment]
This should now be fixed, as of #8012.

**Comment by aknuds1** [comment]
@alexfalkowski Mimir main should now be fixed.

**Comment by alexfalkowski** [comment]
Thanks, @aknuds1 appreciate all the work :heart:
