### ISSUE TITLE
Head compaction range check prevents timely compaction

### ISSUE THREAD

**Issue by jhalterman** [grafana/mimir#7306]
#### Describe the bug
Ingester head compaction currently performs a [range check](https://github.com/grafana/mimir/blob/52939301aef31985a8639de361e0080871f6e8fc/vendor/github.com/prometheus/prometheus/tsdb/head.go#L1655-L1660) to ensure that at least 1.5 times the chunk range worth of data is present in the head before allowing a regularly occurring compaction to proceed. This means that in some situations, data for an earlier time range, ex: 16:00-18:00, which would normally be uploaded at 19:00, may not be uploaded until much later. This can prevent timely block compaction from happening (#7279), which in turn, allows non-compacted blocks to be queried when running Mimir with settings that query more recent data from store-gateways.

Situations where less than 1.5 times the chunk range worth of data to be present in the head include:

- Soon after a tenant first starts sending data
- Following an early compaction

#### To Reproduce

- Start sending data for a user, or trigger early compaction, just prior to a regularly scheduled compaction.
- Observe that later a block will be uploaded much later for an earlier period

#### Expected behavior

Ingesters should create and upload blocks in a timely manner.

**Comment by bboreham** [comment]
[Your PR suggests you know this, however it seems important to me to state it]

I think the point of the 1.5x was to allow for some data arriving late, particularly where OOO is not supported.
Once Prometheus-without-OOO has started compaction, it cannot accept any new data after the end of the block being compacted.

If this is true then the current implementation is simply wrong; it should check the end of the block not the range of the head.
