### ISSUE TITLE
Support for credentials from AWS default provider chain

### ISSUE THREAD

**Issue by fstehle** [grafana/mimir#7339]
#### Is your feature request related to a problem? Please describe.

At the moment you need to configure static access key credentials using an IAM user when you want configure s3 as object storage.
However when already running on AWS instances in EKS, ECS or EC2 already have credentials assigned with a role.

#### Describe the solution you'd like

The configuration should be extended, that no static credentials are required but the default credentials provider chain of AWS is used when no credentials are provided.

#### Describe alternatives you've considered

None

**Comment by 56quarters** [comment]
The S3 backend has a flag `native_aws_auth_enabled` that uses the default SDK provider chain. Does that work for your usecase?

**Comment by fstehle** [comment]
Thanks a lot, will try that
