### ISSUE TITLE
Inhibit executing a query asap for 5 minutes if the same query was rejected due to busting limits

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#7340]
#### Is your feature request related to a problem? Please describe.

If a query loads too much data (chunks/samples/series) and we rejected, nothing stops the user from issuing the same query again right away. This is not a good strategy as we can be reasonably sure that we cannot execute the query a second time around and generate useless load.

#### Describe the solution you'd like

Reject repeated queries as soon as possible for 5 minutes if the query failed due to limits and has the same query and same/similar time range.

#### Describe alternatives you've considered

N/A

#### Additional context

N/A

**Comment by 56quarters** [comment]
Sounds like negative caching for the results cache in the query-frontend.

**Comment by pracucci** [comment]
Looks a duplicate of https://github.com/grafana/mimir/issues/2676.
