### ISSUE TITLE
Alertmanager docs: mention how to run alertmanager with monolithic deployment

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#7405]
> The [alertmanager component is optional ](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/alertmanager/) and not started by default. If you want to run it as part of your monolithic deployment you should just run mimir with the command `./mimir -target=all,alertmanager`.

I couldn't find this anywhere in the documentation. Any way this could be added? Even if to the configuration reference `-target` comment...

_Originally posted by @adamcstephens in https://github.com/grafana/mimir/discussions/2698#discussioncomment-8495466_

**Comment by Rajakavitha1** [comment]
Hi @dimitarvdimitrov  marking this issue as closed because it has now been addressed in https://github.com/grafana/mimir/pull/7414. Please feel free to reopen if any other changes need to be made.
