### ISSUE TITLE
helm: ImagePullSecrets for grafana agent image

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#7406]
I need to define custom image repository links for mimit-metamonitoring pods, similar to what is described [here](https://github.com/grafana/mimir/discussions/4875)
However, our private image registry requires authentication, and it seems that the configuration [here](https://github.com/grafana/mimir/blob/2500b56c8c36976bdc57a6d725546adddf0730b9/operations/helm/charts/mimir-distributed/values.yaml#L2718) does not consider the pullSecrets that are set in toplevel 'image' section.
The statefulset is created without imagePullSecrets and the image cannot be pulled.

_Originally posted by @tagathi in https://github.com/grafana/mimir/discussions/7401_

**Comment by jadolg** [comment]
I believe this is already solved https://github.com/grafana/mimir/commit/be1ba89a3841383620c7ccbf759666e4e91a6eb8

**Comment by dimitarvdimitrov** [comment]
You're right! Solved by https://github.com/grafana/mimir/pull/8670
