### ISSUE TITLE
Docs: Sync documentation to the Grafana website

### ISSUE THREAD

**Issue by jdbaldry** [grafana/mimir#746]
1. Ensure that no sync'd documentation is published until release.
  2. Implement the GitHub action that publishes versioned documentation to grafana/website on merges to the main branch.
  3. Commit patch that would publicize the docs to the long-lived mimir launch branch (to be created)

**Comment by osg-grafana** [comment]
@jdbaldry, all of this work seems complete. Please reopen if not.
