### ISSUE TITLE
[mimir-distributed] kedaAutoscaling can set threshold to 0

### ISSUE THREAD

**Issue by lasermoth** [grafana/mimir#7473]
The helm chart `mimir-distributed` kedaAutoscaling implementation currently runs a `| floor | int64` on the threshold calculation.

However if a cpu request value is anything under 1000m, this would lead to the resulting threshold being 0, which is not a valid value and will result in an error like:

```
"keda-hpa-mimir-query-frontend\" is invalid: spec.metrics[0].external.target.averageValue: Invalid value: resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:\"0\", Format:\"DecimalSI\"}: must be positive
```

In the case of the default requests of `100m`, and default `targetCPUUtilizationPercentage` of 100, we end up with a calculated threshold that looks like:

100 * 0.001 = 0.1 * (100/100) = 0.1

Both the `floor` and `int64` functions will round this down to 0. This would be the case for anything under 1000m.

https://github.com/grafana/mimir/blob/9e9d4769a426e4bdd827e53139a961b7727395de/operations/helm/charts/mimir-distributed/templates/distributor/distributor-so.yaml#L30

I'm not sure if the `floor` and `int64` functions are very necessary here, it could be omitted or potentially replaced with `float64`

From the [keda trigger spec](https://keda.sh/docs/2.13/scalers/prometheus/#trigger-specification)

```
threshold - Value to start scaling for. (This value can be a float)
```

**Comment by edwintye** [comment]
I ran into the same issue while experimenting. I not sure using trigger that queries back to prometheus/mimir is providing us more value than just the standard [cpu](https://keda.sh/docs/2.13/scalers/cpu/) and [memory](https://keda.sh/docs/2.13/scalers/memory/) triggers

```yaml
triggers:
  - metadata:
      type: Utilization
      value: "70"
    type: cpu
triggers:
  - metadata:
      type: Utilization
      value: "80"
    type: memory
```

In the event that we do want to query back, I think the current query

```promql
sum(sum by (pod) (rate(container_cpu_usage_seconds_total{container="ruler",namespace="default"}[5m]))
```

is computing the total cpu usage from all pods, and should be divided by the current number of pods.  The current threshold does not account for the pods post scaling as far as I can tell.

**Comment by dimitarvdimitrov** [comment]
> I not sure using trigger that queries back to prometheus/mimir is providing us more value than just the standard [cpu](https://keda.sh/docs/2.13/scalers/cpu/) and [memory](https://keda.sh/docs/2.13/scalers/memory/) triggers

the querier autoscaling uses the size of the query queues for example

> is computing the total cpu usage from all pods, and should be divided by the current number of pods. The current threshold does not account for the pods post scaling as far as I can tell.

the keda `threshold` should determine the number of desired pods. So in this case we don't look at how well scaled the current pods are (i.e. how far is each from the average or from its limit) - we look at how many pods we want given the current load of all pods.

**Comment by lasermoth** [comment]
Revisiting this, the `floor | int64` behaviour is similar to that of the jsonnet version.

However the helper functions differ, which is what is causing a behavioural change with the `floor | int64` operations. 

In the jsonnet version we [convert everything to milli cpu](https://github.com/grafana/mimir/blob/2091e9a4ec177e950d065a4afed000825c72a22a/operations/mimir/autoscaling.libsonnet#L365C1-L374C5) 

```jsonnet
  local cpuToMilliCPUInt(str) = (
    // Converts any CPU requests to millicores. (eg 0.5 = 500m)
    // This is due to KEDA requiring an integer.

    if (std.isString(str) && std.endsWith(str, 'm')) then (
      std.parseInt(std.rstripChars(str, 'm'))
    ) else (
      std.parseJson(str + '') * 1000
    )
  ),
  ```
  
  Where as helm is using a [helper function](https://github.com/grafana/mimir/blob/2091e9a4ec177e950d065a4afed000825c72a22a/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L676) that converts the CPU to a float of the CPU core representation. 
  
  ```go
  {{/*
parseCPU is used to convert Kubernetes CPU units to the corresponding float value of CPU cores.
The returned value is a string representation. If you need to do any math on it, please parse the string first.

mimir.parseCPU takes 1 argument
  .value = the Kubernetes CPU request value
*/}}
{{- define "mimir.parseCPU" -}}
    {{- $value_string := .value | toString -}}
    {{- if (hasSuffix "m" $value_string) -}}
        {{ trimSuffix "m" $value_string | float64 | mulf 0.001 -}}
    {{- else -}}
        {{- $value_string }}
    {{- end -}}
{{- end -}}
```

So using the earlier example of `100m` CPU requests, we end up with the right value if keeping the conversion as MilliCPU.

Current implementation that converts to CPU cores via * 0.001: 

`100 * 0.001 = 0.1 * (100/100) = 0.1`

Jsonnet implementation where we use MilliCPU:

`100 * (100/100) = 100`
  
  Since we no longer end up with a decimal figure, the `float | int64` operations no longer cause a problem.
  
  The current helper `mimir.parseCPU` is used in some other parts of the chart for calculating `GOMAXPROCS`.  
  The best option is likely to just add another helper that can generate the MilliCPU value.
