### ISSUE TITLE
Mimir mixin: alerts make range interval configurable

### ISSUE THREAD

**Issue by jmichalek132** [grafana/mimir#7546]
#### Is your feature request related to a problem? Please describe.

In our case we have scrape interval of 1m, however alerts in the mixin seem to have hardcoded range interval, examples:

* https://github.com/grafana/mimir/blob/main/operations/mimir-mixin/alerts/alerts.libsonnet#L39
* https://github.com/grafana/mimir/blob/main/operations/mimir-mixin/alerts/alertmanager.libsonnet#L24

Because of that some of these alerts won't work in our case.

#### Describe the solution you'd like

Have a config option for the range interval window in alerts, similar to what is already present for recording rules https://github.com/grafana/mimir/blob/main/operations/mimir-mixin/config.libsonnet#L659.

Given the range interval is not the same in the alert the variable could be something like `min_alerts_range_interval` and do something like:
```
1 * %(min_alerts_range_interval)
```
To calculate the desired interval while keeping in mind the minimum possible rate interval.
#### Describe alternatives you've considered

Manually editing the alerts after they are rendered, which kind of defeats the point of mixins imho.

#### Additional context

https://www.robustperception.io/what-range-should-i-use-with-rate/

**Comment by dimitarvdimitrov** [comment]
thanks for bringing this up. I think the helm chart metamonitoring setup suffers from the same problem. 

Suggestion for naming: wdyt about `scrape_interval` instead? It's easier to understand and we can use 2x or 4x that period in alerts (similar to how `$__rate_interval` works in Grafana)

**Comment by dimitarvdimitrov** [comment]
> yeah I wonder what was the assumed scrape interval since some of the alerts i.e. https://github.com/grafana/mimir/blob/main/operations/mimir-mixin/alerts/alertmanager.libsonnet#L84 use `1m` so either `15s` (to have at least 4 samples) or it's a mistake in the alert.

I believe it was 15s. That's what we've been running internally with for a long time.



> On the same note do we want to do something like: in the case of https://github.com/grafana/mimir/blob/main/operations/mimir-mixin/alerts/alertmanager.libsonnet#L24
> 
> ```
> scrape_interval=15 
> alert_range_interval = 4 * scrape_interval * 2
> ```
> 
> since the interval is double of the min range, to keep the ratios working with different scrape intervals?

I think that makes sense. `4 * scrape_interval` would also work IMO, but let's not change the alert as part of this fix.

Maybe we can declare some other variable which itself is `4 * scrape_interval` and use that in all alerts and recording rules. 


---

Regarding `min_alerts_range_interval` and `scrape_interval`. I realized that there is already `recording_rules_range_interval`, which makes your initial suggestion more consistent with what's already in the mixin. It's the base unit and then different alerts use multiples of it. It might be difficult to support the same values (e.g. `"1m"`, `"120s"`), and IMO it's easier to have it just contain the number of seconds. So waht do you think about changing `min_alerts_range_interval` to `base_alerts_range_interval_seconds`?

**Comment by jmichalek132** [comment]
Will raise a PR.
