### ISSUE TITLE
Docs: clarify `monitor-grafana-mimir/requirements.md` cadvisor/kubelet relabeling requirements

### ISSUE THREAD

**Issue by madaraszg-tulip** [grafana/mimir#7570]
#### Describe the bug

The Mimir dashboards from mimir-mixin show no data in the Disk panels

#### To Reproduce
1. Deploy Mimir on kubernetes
2. Deploy the Mimir dashboards to grafana
3. Visit the mimir-writes-resources dashboard

#### Expected behavior

I would expect the Disk writes and Disk reads panels to show data

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

#### Additional Context

Here is an actual query that gets executed: 

```
sum by(instance, pod, device) (
  rate(
    node_disk_written_bytes_total[$__rate_interval]
  )
)
+
ignoring(pod) group_right() (
  label_replace(
    count by(
      instance,
      pod,
      device
    )
    (
      container_fs_writes_bytes_total{
        cluster=~".*", namespace=~"monitoring",
        container=~"ingester",
        device!~".*sda.*"
      }
    ),
    "device",
    "$1",
    "device",
    "/dev/(.*)"
  ) * 0
)

```

The problem is that the first metric comes from prometheus-node-exporter, while the second metric comes from kubelet. The instance values are different, because they are of the format of <ip>:<port> and the ports differ, so the two series cannot be added.

**Comment by dimitarvdimitrov** [comment]
the mixin needs a single label that matches on both metrics and contains the name of the node where mimir is running. It's mentioned in the monitoring requirements. I believe other dashbaords and/or alerts may be broken if that's not met. https://grafana.com/docs/mimir/latest/manage/monitor-grafana-mimir/requirements/ It looks like you need to change either the node exporter or cadvisor metrics so they match their labels.

Did I understand the problem correctly?

**Comment by madaraszg-tulip** [comment]
Thank you, I have found the following line in that docs which is relevant: 

`Metrics from node_exporter must all have an instance label on them that has the same value as the instance label on Mimir metrics.`

My concern is that prometheus by default sets instace to `<ip>:<port>`. Perhaps the Mimir documentation should be more explicit and actually advise about reconfiguring prometheus to remove the port from the instance label. 

I am also worried if we'd lose some other information if we removed the port from there - I assume there is a reason prometheus adds it. 

An alternative solution would be for the promql in the dashboards to remove the port portion of the instance labels before matching across metrics.

**Comment by madaraszg-tulip** [comment]
I now added metric relabelings to the node-exporter and kubelet servicemonitors to remove the port from the instance label, and disk metrics now show up. I want to note that the line in the docs references node-exporter and mimir metrics for instance label matching, it is in fact node-exporter and kubelet metrics that need to match.

**Comment by dimitarvdimitrov** [comment]
in the example you posted isn't `container_fs_writes_bytes_total` a [cadvisor metric](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md)?

**Comment by madaraszg-tulip** [comment]
It is, collected through the kubelet ServiceMonitor on the /metrics/cadvisor path
