### ISSUE TITLE
Make /ingester/shutdown react on POST method only

### ISSUE THREAD

**Issue by pstibrany** [grafana/mimir#7623]
It's too easy to trigger ingester shutdown by `GET /ingester/shutdown` endpoint. 

We should make it react on `POST` method only. We need to do this in steps:

1) Modify endpoint, but keep option to allow `GET /ingester/shutdown` to work too
2) Remove the option after two Mimir releases.

#### Additional context

Internal scanners that traverse links can trigger shutdown of ingester just by visiting the link.

**Comment by kevinmingtarja** [comment]
Hi, I'm interested to contribute to this!

**Comment by pstibrany** [comment]
> Hi, I'm interested to contribute to this!

Thank you. Please feel free to send a PR for review. Check out our contributing guideline too:  https://github.com/grafana/mimir/tree/main/docs/internal/contributing

**Comment by kevinmingtarja** [comment]
Hi, I've made a PR for this
