### ISSUE TITLE
Provide charts through OCI registry

### ISSUE THREAD

**Issue by PlayMTL** [grafana/mimir#7628]
#### Is your feature request related to a problem? Please describe.

Feature Request: As a consumer of the helm chart "mimir-distributed" i would like to use OCI helm charts for better automation on my side.

#### Describe the solution you'd like

Is it possible to release the helm charts of mimir to an oci registry?

#### Describe alternatives you've considered

Using the helm chart the documented way ;)

**Comment by narqo** [comment]
I think there is some work being done in https://github.com/grafana/helm-charts/issues/2481 (it seems to me mimir uses this GH workflow for helm releases).

**Comment by PlayMTL** [comment]
Hey, I opened the issue here, because the helm chart was moved over here (https://github.com/grafana/helm-charts/tree/main/charts/mimir-distributed)

**Comment by narqo** [comment]
Sure, thank you for the issue. What I've noted above is that [mimir's CI workflow][1], which releases the chart, uses the one the lives in `grafana/helm-charts`. After they resolve https://github.com/grafana/helm-charts/issues/2481 I expect mimir to get the feature automatically.

[1]: https://github.com/grafana/mimir/blob/460bb22789a5880e3c2f542e9bb84c81b84dafc6/.github/workflows/helm-release.yaml#L10-L18

**Comment by narqo** [comment]
Starting with this weekly release, the `mimir-distributed` helm chart is also pushed to the ghcr.io also.

```
% gh auth token | helm registry login ghcr.io -u <user> --password-stdin

% helm template oci://ghcr.io/grafana/helm-charts/mimir-distributed --devel --version 5.6.0-weekly.316
```
