### ISSUE TITLE
Different object storage buckets for different tenants

### ISSUE THREAD

**Issue by shindebshekhar** [grafana/mimir#7630]
Hello,

1. Can we use different s3 buckets for different tenants? Is this feature available only available in enterprise edition?

2. If not, how to can we set different retention period for different tenant's data. We need to have only one mimir instance but the tenants can be from non-prod/prod environment. For prod we need to set different retention period and for non-prod different. Is it possible?

**Comment by pstibrany** [comment]
> 1. Can we use different s3 buckets for different tenants? Is this feature available only available in enterprise edition?

Hello, neither Mimir or Grafana Enterprise Metrics have such feature currently.

> 2. If not, how to can we set different retention period for different tenant's data. We need to have only one mimir instance but the tenants can be from non-prod/prod environment. For prod we need to set different retention period and for non-prod different. Is it possible?

Yes, this is possible. You can set retention per tenant by using `compactor_blocks_retention_period` per-tenant override.

**Comment by shindebshekhar** [comment]
Thanks for your immediate response.

Referring to  [](https://grafana.com/docs/mimir/latest/configure/configure-metrics-storage-retention/)
So tenant name is same that we specify in headers (X-Scope-OrgID) under remote_write, correct?
remoteWrite:
  headers:
    X-Scope-OrgID: <<tenantname>>

**Comment by pstibrany** [comment]
> Thanks for your immediate response.
> 
> Referring to https://grafana.com/docs/mimir/latest/configure/configure-metrics-storage-retention/ So tenant name is same that we specify in headers (X-Scope-OrgID) under remoteWrite, correct?

Yes, that is correct.

Make sure to keep multitenancy enabled (which is the default value, but can be disabled by setting `-auth.multitenancy-enabled` CLI option to `false`), otherwise this `X-Scope-OrgID` header is ignored and Mimir will use `anonymous` tenant instead.

Once you start writing to the Mimir and Mimir starts uploading blocks, tenant name is also used as top-level prefix inside the bucket.

**Comment by shindebshekhar** [comment]
Yes, Multitenancy is enabled in our environment. I will set the retention per tenant and test it out. Many Thanks!!

In line to similar topic if we want to add two headers while adding datastource in Grafana we need to enable **tenant_federation:** correct?

**Comment by pstibrany** [comment]
> In line to similar topic if we want to add two headers while adding datastource in Grafana we need to enable **tenant_federation:** correct?

Do you want to query both tenants? In that case yes, you will need to enable tenant federation, and then you need to specify *both* tenants in one ` X-Scope-OrgID` header, and separate them with `|` (pipe) character. For example `X-Scope-OrgID: tenant-1|tenant-2|tenant-3`.

**Comment by shindebshekhar** [comment]
Thanks, that answers my question!!
