### ISSUE TITLE
Lookup style for S3 bucket

### ISSUE THREAD

**Issue by arsbest** [grafana/mimir#7673]
Hello!

What style of accessing the S3 bucket is used in mimir distributed?
I couldn't find the S3 access style (path-style or virtual hosted style) settings options in the storage configuration https://grafana.com/docs/mimir/latest/references/configuration-parameters/#s3_storage_backend , https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml

What is the default style?
I need the ability to set the required connection type as in the [loki settings parameter](https://grafana.com/docs/loki/latest/storage/#object-storage) `s3forcepathstyle`.

**Comment by narqo** [comment]
> What style of accessing the S3 bucket is used in mimir distributed? [..] I need the ability to set the required connection type

For AWS S3, Mimir will use DNS lookup (virtual hosted style). As of today, there is no configuration to alter this behaviour, although there is a related issue to add one #7512. Could you expand what is the particular issue you're facing?

**Comment by arsbest** [comment]
Haven't encountered a problem yet.
But the cloud provider (not AWS, Google, Alibaba) from which we use the S3 service will soon abandon path-style access in favor of virtual hosted style. 
Therefore, we are concerned about the correct operation of the Mimir monitoring service. And we want to explicitly set these parameters.

The workaround I currently see (is based on the minio source code) is to leave the backet_name field empty and move the name of the bucket to the endpoint:
```
    alertmanager_storage:
      s3:

        endpoint: mimir-alertmanager.some_endpoint 
        bucket_name: ""
    blocks_storage:
      s3:
        endpoint: mimir-blocks.some_endpoint 
        bucket_name: ""
  common:
      storage:
        backend: s3
        s3:
          access_key_id: some_ak
          endpoint: some_endpoint
          region: some_region
          secret_access_key: some_sk
