### ISSUE TITLE
Cardinality API returns wrong number of in-memory series when using 5 zones and RF=3

### ISSUE THREAD

**Issue by pstibrany** [grafana/mimir#7738]
#### Describe the bug

`/api/v1/cardinality/label_values` endpoint returns number of in-memory or active series as part of the response.

This number can be wrong in a setup with 5 zones and replication factor three.

Observed in-memory series per zone:
* 22218014
* 22159603
* 22074077
* 22204646
* 22505493

Total in-memory series: 110992564. Because replication factor is three, that means 110992564 / 3 = 37M series before replication.

However `/api/v1/cardinality/label_values` reports ~22M series in `series_count_total` field.

Configuration:
* Mimir 2.11, with default values for ingester request minimization (= true).
* 5 zones
* replication factor 3

Details:
* `/api/v1/cardinality/label_values` [uses](https://github.com/grafana/mimir/blob/42ccb78851f02cfe70e5681332fc2486b206a1f3/pkg/distributor/distributor.go#L1638-L1648) distributors' `UserStats` ([code from release-2.11](https://github.com/grafana/mimir/blob/42ccb78851f02cfe70e5681332fc2486b206a1f3/pkg/distributor/distributor.go#L2003-L2066)) to compute in-memory series. UserStats will query in-memory series from zones until the quorum is reached. After reaching quorum, [`approximateFromZones` function](https://github.com/grafana/mimir/blob/42ccb78851f02cfe70e5681332fc2486b206a1f3/pkg/distributor/distributor.go#L1865-L1893) is used to compute approximate number of in-memory series. When using multi-zone setup, this function simply returns maximum of per-zone values. **This would only be correct when number of zones is equal to replication factor.**

Expected behaviour: computation of number of series should correctly handle the case where number of zones is different from replication factor.

**Comment by doanbutar** [comment]
Hi @pstibrany do you might have any updates on this issue?
