### ISSUE TITLE
Meta-monitoring mixin dashboards rely on deprecated graph visualisation plugin

### ISSUE THREAD

**Issue by hedss** [grafana/mimir#7746]
#### Describe the bug
The Meta-monitoring dashboards in `operation/[mimir-mixin.*]` still work, but are based on the old timeseries data graph, pre-Grafana 10.

#### To Reproduce

1. Install Mimir, scrape metrics from each service
2. Install mixin dashboards and view
3. Note warning in top left of affected visualisation panels

![image](https://github.com/grafana/mimir/assets/8259026/83a6b3f7-df4a-4da5-9467-1d24f87f17a2)

#### Expected behavior

 No warning should occur and the newer timeseries graph visualisation should be used.

#### Environment

- Infrastructure: N/A
- Deployment tool: N/A

**Comment by narqo** [comment]
All dashboards were supposed to be updated from "graph" (deprecated) to "timeseries" panels in #7413. Which version of the mixin do you use?

**Comment by narqo** [comment]
Should be fully fixed with the [latest release (v4.1.1) of GEM plugin][1]

[1]: https://grafana.com/grafana/plugins/grafana-metrics-enterprise-app/?tab=changelog
