### ISSUE TITLE
Docs feedback: /docs/sources/mimir/get-started/play-with-grafana-mimir/index.md

### ISSUE THREAD

**Issue by davecb** [grafana/mimir#7844]
In doing the demo at https://grafana.com/docs/mimir/latest/get-started/play-with-grafana-mimir/,
my page at http://localhost:9000/alerting/new/alerting  lacks the two field below
I'm therefore blocked.

- Type example-namespace in the “Namespace” field.
- Type example-group in the “Group” field.

![Screenshot_2024-04-08_09-44-04](https://github.com/grafana/mimir/assets/559505/77d251b0-69c6-4d18-ba97-c1a2d0c245d2)

Am I even using the right Grafana? This looks like one that failed for us before...

**Comment by pstibrany** [comment]
Hello. Could you please try to use "Data source-managed" rule type?

**Comment by davecb** [comment]
Sure, just a sec...
![Screenshot_2024-04-08_20-15-02](https://github.com/grafana/mimir/assets/559505/f4d470f9-86b4-4ba6-a4ee-b0c43fed9244)

**Comment by davecb** [comment]
and save ...
![Screenshot_2024-04-08_20-17-40](https://github.com/grafana/mimir/assets/559505/63849a4e-3483-491d-80a7-76e5a5ded250)

**Comment by davecb** [comment]
Thanks folks: I had to guess that you wanted two non-default values: Code and Data source managed.
I've written "worked examples" before, and I usually recommend the very _first_ time you show something, you be extra explicit.
I fiddled around with different settings, but failed to notice the right fields farther down the page in Data source managed

**Comment by davecb** [comment]
Unblocked, on to the next thing (:-))

**Comment by davecb** [comment]
Closed with my thanks!
