### ISSUE TITLE
Chart 5.3.0: Mimir push API doesn't allow X-Scope-OrgID with special characters

### ISSUE THREAD

**Issue by bobbeeke** [grafana/mimir#7868]
#### Describe the bug
Upgraded chart version (mimir-distributed) from 5.2.3 to 5.3.0
My Prometheus pushes to the Mimir push URL with a X-Scope-OrgID which in my current setup contain special characters.
This worked without problems until this version.

#### To Reproduce
Push content with X-Scope-OrgID which contains a comma to the Mimir push API:

The new code dismisses a comma character with:
```
server returned HTTP status 400 Bad Request: Sending multiple X-Scope-OrgID headers is not allowed. Use a single header with | as separator instead."
``` 

Push content with X-Scope-OrgID which contains other special characters to the Mimir push API:

The new code dismisses several characters with:
```
server returned HTTP status 401 Unauthorized: tenant ID 'OrgID-with-?' contains unsupported character '?'
```

#### Expected behavior

Either accept the traffic with special characters or clearly document what the new restrictions are and why.
It could well be I missed this change.

Right now I'm not sure if this behavior is intended or if it is a unwanted result of some other change.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: Helm
- Chart: mimir-distributed

#### Additional Context

Tested by removing special characters out of X-Scope-OrgID and this just work.

It will take some work for my whole environment to change all X-Scope-OrgIDs everywhere so I prefer to know first if this is intended behavior.

**Comment by narqo** [comment]
> [..] clearly document what the new restrictions are and why

It seems that the issue is a degradation after #7700. Note the document, that lists the [requirements for tenant ID][1].

[1]: https://grafana.com/docs/mimir/latest/configure/about-tenant-ids/

**Comment by bobbeeke** [comment]
Clear, thanks for pointing out @narqo 
I will change my X-Scope-OrgIDs.
It is however strange that until now I had no problem. I used random strings with all kind of characters and it did never complain. 

Feel free 
to close this one if no further action is required.

**Comment by narqo** [comment]
Thank you, for having a look. If you further bump into an unexpected behaviour in the validation of the tenant's header, please re-open this one.

**Comment by 56quarters** [comment]
Question marks in tenant IDs have never been allowed per the docs _but_ this wasn't enforced when tenant federation was disabled until Mimir 2.12. Version 2.12 fixed this oversight.

PR: https://github.com/grafana/mimir/pull/6959
Changelog:
```
[CHANGE] Validate tenant IDs according to [documented behavior](https://grafana.com/docs/mimir/latest/configure/about-tenant-ids/) even when tenant federation is not enabled. Note that this will cause some previously accepted tenant IDs to be rejected such as those longer than 150 bytes or containing | characters. #6959
```
