### ISSUE TITLE
To avoid ingester container to be killed due out-of-memory

### ISSUE THREAD

**Issue by valdemarpavesi** [grafana/mimir#7971]
To avoid ingester container to be killed.
![image](https://github.com/grafana/mimir/assets/10376101/14f9eae0-9975-4edd-8f6c-eb24f9488278)
![image](https://github.com/grafana/mimir/assets/10376101/5f4401de-3e8f-438f-b72b-d61b956a38a5)

Add to yaml pod container:
        env:
        - name: GOMAXPROCS
          value: "8"
        - name: GOMEMLIMIT
          value: 42GiB
          
add to ingester code:
          	_ "go.uber.org/automaxprocs" // Automatically set GOMAXPROCS to match Linux container CPU quota

**Comment by 56quarters** [comment]
When setting `GOMAXPROCS` we prefer to do it in the Jsonnet or Helm chart based on testing. It's unlikely we'd ever want components doing it automatically.

**Comment by valdemarpavesi** [comment]
yes, it goes over a variable, same as the limit/requests are set.

but, we have to inform the container about the resources that linux will provide.

to avoid the container to be killed, it will go slow but will not be killed.
and cpu the same, it will run slow but it will not be throttled.

slow x crash.

**Comment by valdemarpavesi** [comment]
it will work like this, close to limit, but never cross it:

![image](https://github.com/grafana/mimir/assets/10376101/85e60963-c8e6-4c58-9c36-bb34bb13d554)

**Comment by valdemarpavesi** [comment]
the documentation:
https://github.com/uber-go/automaxprocs

**Comment by valdemarpavesi** [comment]
not sure why it is marked closed.

it is related to Mimir 
https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed

**Comment by 56quarters** [comment]
I don't understand your point. `GOMAXPROCS` and `GOMEMLIMIT` can already be set via the Helm chart or Jsonnet today to whatever values you like. Automatically setting them from the application binary using `automaxproc` is not something we're interested in doing. The behavior you're describing is already possible today with no changes.

**Comment by valdemarpavesi** [comment]
today, we are getting ingester crash due OutofMemory.

in order to use  GOMAXPROCS and GOMEMLIMIT, we shall include into the code 

_ "go.uber.org/automaxprocs"

and compile it.

during the startup it will show :

![image](https://github.com/grafana/mimir/assets/10376101/d3b16eca-0f50-4b8c-a2b2-bd6a3cf96eea)

must be on import:

![image](https://github.com/grafana/mimir/assets/10376101/0f4150b9-852e-4eea-909b-628267b2071b)

**Comment by 56quarters** [comment]
> in order to use GOMAXPROCS and GOMEMLIMIT, we shall include into the code

Using these variables doesn't require the `automaxprocs` library, they're supported by the go runtime. 

I'd suggest you read this documentation:

https://pkg.go.dev/runtime#GOMAXPROCS

https://dave.cheney.net/2015/11/29/a-whirlwind-tour-of-gos-runtime-environment-variables

**Comment by valdemarpavesi** [comment]
good point, Thanks Nick

I will test it

![image](https://github.com/grafana/mimir/assets/10376101/103f6e8b-66c4-4e1e-94e2-7ef08c50f144)

**Comment by valdemarpavesi** [comment]
it is working, it get close to limit but never over the limit:

![image](https://github.com/grafana/mimir/assets/10376101/6e9fd9e4-1994-44e1-9291-8a4eb41c1734)

just added env into ingester:
![image](https://github.com/grafana/mimir/assets/10376101/def8af9b-321c-4fd0-859a-0471cc085bb1)
