### ISSUE TITLE
Calls to /cardinality/label_values fail during rollouts

### ISSUE THREAD

**Issue by stevesg** [grafana/mimir#818]
**Describe the bug**
The `/cardinality/label_values` API fails if one (or more) ingesters are down, as is typical during a rollout.

**To Reproduce**

1. Start Mimir (SHA or version)
2. Shut down a single ingester / leave in ring. (e.g. rolling restart)
3. Make a request to `/api/prom/api/v1/cardinality/label_values`

**Expected behavior**
The API request should succeed.

**Environment:**

- Infrastructure: n/a
- Deployment tool: n/a

**Storage Engine**

- [x] Blocks
- [ ] Chunks

**Additional Context**

**Comment by ortuman** [comment]
Unfortunately cardinality computation for label values requires to obtain a successful response from all ingesters, as series for a given set of matchers may be spread across any of the replicas in the tenant subring. Plus, this type of operation can be heavy to compute, reaching latencies of up to 30 sec. depending on the data set, which means that errors during a rollout are very likely to occur.

As an attempt to mitigate this situation, I've opened a PR in the mimir repository (https://github.com/grafana/mimir/pull/3044) to improve the performance of this endpoint, with the idea of reducing cardinality latency, making this more unlikely to happen.

**Comment by bboreham** [comment]
How about: during a rollout we put up a banner in the UI saying “cardinality dashboards temporarily unavailable; please try later” ?

**Comment by ortuman** [comment]
Mitigation PR: https://github.com/grafana/mimir/pull/3044

**Comment by pracucci** [comment]
> Unfortunately cardinality computation for label values requires to obtain a successful response from all ingesters, as series for a given set of matchers may be spread across any of the replicas in the tenant subring.

Would that change when zone-aware replication is enabled? Why do we need to lookup all 3 zones and 2 out of 3 is not enough?
