### ISSUE TITLE
Store-gateway doesn't release goroutine if request is cancelled while loading index-header

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#8257]
The store-gateway triggers the index-header lazy loading here:
https://github.com/grafana/mimir/blob/960f22479e10f04eee19f37f10aba576e76538a9/pkg/storegateway/bucket.go#L1305-L1308

Which then calls:
https://github.com/grafana/mimir/blob/960f22479e10f04eee19f37f10aba576e76538a9/pkg/storegateway/bucket.go#L1967-L1968

However, `b.indexHeaderReader.IndexVersion()` doesn't take the context in input, so if the store-gateway request is canceled, the goroutine waiting for `b.indexHeaderReader.IndexVersion()` is not released until the lazy loading is completed.

**Comment by dimitarvdimitrov** [comment]
we also shouldn't abort lazy-loading when the request is cancelled

**Comment by pracucci** [comment]
> we also shouldn't abort lazy-loading when the request is cancelled

Absolutely.

To get this work done I think some refactoring is required in `LazyBinaryReader`. The main idea I have to cleanly address this issue, is to  pass `context.Context` to each `indexheader.Reader` function, so that when the reader is wrapped by `LazyBinaryReader` can stop waiting for an index-header to be loaded once the context is canceled.

However, we don't want to cancel the loading when the context is canceled. We just want to stop waiting for it. For this reason, I believe we have to decouple the logic used to lazy load an index-header from `LazyBinaryReader` (e.g. move it to a new `LazyBinaryLoader`), so that `LazyBinaryReader` will just trigger the lazy loading and waiting for it (stop waiting once context is canceled) but the new `LazyBinaryLoader` doesn't stop loading once the context is canceled.

**Comment by dimitarvdimitrov** [comment]
this ended up muuuch less trivial than I anticipated, so the PR will less easy to review. I tried to lay everything necessary for the review in the description
