### ISSUE TITLE
Ability to set `client_max_body_size` in nginx to be able to fix 502 Bad Gateway

### ISSUE THREAD

**Issue by mrclrchtr** [grafana/mimir#8293]
#### Is your feature request related to a problem? Please describe.

I have connected prometheus to mimir and have often received the following error message:

```
ts=2024-06-06T07:23:31.218Z caller=dedupe.go:112 component=remote level=warn remote_name=3d9cdd url=http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push msg="Failed to send batch, retrying" err="Post \"http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push\": context deadline exceeded"
ts=2024-06-06T07:24:01.279Z caller=dedupe.go:112 component=remote level=warn remote_name=3d9cdd url=http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push msg="Failed to send batch, retrying" err="server returned HTTP status 502 Bad Gateway: <html>"
```

After some research I found out that the body is probably too big.

After setting `client_max_body_size` I got a peak at the ingests and the error is solved:

![image](https://github.com/grafana/mimir/assets/16151098/f89a683f-d526-490f-8162-f30c712b5ea4)

It would probably be useful to be able to simply adjust the parameter.

#### Describe the solution you'd like

Ability to set `client_max_body_size`.

Edit:
I found this PR: https://github.com/grafana/mimir/pull/7960
I think it's the required one...

**Comment by mrclrchtr** [comment]
Solution is described in #7960

**Comment by dimitarvdimitrov** [comment]
what was the value that resolve it for you @mrclrchtr? maybe we can increase the default in the chart

**Comment by dimitarvdimitrov** [comment]
1GiB is too much I agree. But something in the low tens of MiBs might be ok, 10-20 MiB might be ok

2.13 will expose `cortex_distributor_uncompressed_request_body_size_bytes` which would be able to answer this accurately


```
histogram_quantile(0.99, sum(rate(cortex_distributor_uncompressed_request_body_size_bytes{}[$__rate_interval])))
```

**Comment by mrclrchtr** [comment]
It happened again. Setting it to 10m was enough to fix it.

**Comment by dimitarvdimitrov** [comment]
the one last thing I'm not sure about is what would happen if both the default in the helm chart nginx config and the serverSnippet are configured with `client_max_body_size`. If setting a default in the helm chart prevents users from overriding it via `serverSnippet`, then we have to take the approach in https://github.com/grafana/mimir/pull/7960; otherwise, we can hardcode a `10m` default

**Comment by mrclrchtr** [comment]
I can't answer that, but it's a good point. It should always be possible for the user to adjust the value. That's why I would probably prefer https://github.com/grafana/mimir/pull/7960. This gives the user the possibility to change the value easily.

**Comment by dimitarvdimitrov** [comment]
> the one last thing I'm not sure about is what would happen if both the default in the helm chart nginx config and the serverSnippet are configured with `client_max_body_size`

nginx rejects duplicate directives, so we can't just set the default. So I agree the approach in https://github.com/grafana/mimir/pull/7960 is the best we can take. I'll leave some follow-up comments there
