### ISSUE TITLE
mapping no retryable 5xx errors to retryable error in otlp handler

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/mimir#8310]
unlike prometheus which retry on 5xx errors, otlp retry only on certain error codes, see doc: https://opentelemetry.io/docs/specs/otlp/#failures-1, the solution would be mapping error code to retryable error code in otlp handler in order to avoid losing data.

**Comment by aknuds1** [comment]
I'm reopening this PR, because there's still some [uncertainty](https://github.com/grafana/mimir/pull/8339#discussion_r1635164039) about to which degree this issue was solved by #8324.

**Comment by aknuds1** [comment]
@duricanikolic is working to complete this issue in https://github.com/grafana/mimir/pull/8339.

**Comment by aknuds1** [comment]
Fixed by https://github.com/grafana/mimir/pull/8339.
