### ISSUE TITLE
Promote Mimir dashboards

### ISSUE THREAD

**Issue by jdbaldry** [grafana/mimir#838]
**Is your feature request related to a problem? Please describe.**
The Mimir dashboards are some of the best service oriented dashboards and are pivotal in our own monitoring of Mimir at Grafana. However, they are somewhat hidden in the repository and not easily consumed by users.

**Describe the solution you'd like**
- Publish dashboards to https://grafana.com/grafana/dashboards/
- Prominent display of the dashboards in documentation

**Comment by bboreham** [comment]
We did the publishing, right?

**Comment by pracucci** [comment]
Yes, we both published dashboards and included them in the doc:
https://grafana.com/docs/mimir/next/operators-guide/visualizing-metrics/
