### ISSUE TITLE
Release 2.13

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#8390]
### Publish the release candidate (rc.0)

- [x] Begin drafting the [release notes](https://github.com/grafana/mimir/blob/main/RELEASE.md#write-release-notes-document) https://github.com/grafana/mimir/pull/8445
  - Create the release notes PR targeting the main branch
  - This step shouldn't block from publishing release candidate
  - After the release notes PR is merged (which usually happen after RC is published), cherry-pick them into the release branch
- [x] Wait for any open PR we want to get merged before cutting the release candidate
  - We shouldn't wait for the open PRs beyond the scheduled release date
  - [x] Eventually open a PR for every experimental feature we want to promote to stable https://github.com/grafana/mimir/pull/8400
  - [x] Eventually open a PR to remove any deprecated feature or configuration option that should be removed in this release   https://github.com/grafana/mimir/pull/8395
- [x] Update `CHANGELOG.md` https://github.com/grafana/mimir/pull/8459
  - [x] Run `./tools/release/check-changelog.sh LAST-RELEASE-TAG...main` and add missing PRs to CHANGELOG
  - [x] Ensure CHANGELOG entries are [sorted by type](https://github.com/grafana/mimir/blob/main/docs/internal/contributing/README.md#changelog)
  - [x] Add a new section for the new release so that `## main / unreleased` is blank and at the top. The new section should say `## x.y.0-rc.0`.
- [x] Run `./tools/release/notify-changelog-cut.sh`
- [x] Run `make mixin-screenshots`
  - Before opening the PR, review all updated screenshots and ensure no sensitive data is disclosed https://github.com/grafana/mimir/pull/8470
- [x] Create new release branch
  - [x] Create the branch
    ```bash
    git checkout r<xxx> # xxx is the latest weekly release
    git checkout -b release-<version>
    git push -u origin release-<version>
    ```
  - [x] Remove "main / unreleased" section from the CHANGELOG https://github.com/grafana/mimir/pull/8477
  - [x] If a new minor or major version is being released, adjust the settings in the `renovate.json` configuration on the `main` branch by adding the new version.
        This way we ensure that dependency updates maintain the new version, as well as the latest two minor versions.
        For instance, if versions 3.0 and 2.10 are configured in `renovate.json`, and version 3.1 is being released,
        during the release process `renovate.json` should keep updated the following branches: `main`, `release-3.1`, `release-3.0` and `release-2.10`. https://github.com/grafana/mimir/pull/8478
- [x] Publish the Mimir release candidate
  - [x] Update VERSION in the release branch and update CHANGELOG with version and release date. https://github.com/grafana/mimir/pull/8479
    - Keep in mind this is a release candidate, so the version string in VERSION and CHANGELOG must end in `-rc.#`, where `#` is the release candidate number, starting at 0.
  - [x] [Tag the release](https://github.com/grafana/mimir/blob/main/RELEASE.md#how-to-tag-a-release)
    ```bash
    git checkout release-<version>
    ./tools/release/tag-release.sh
    ```
  - [x] Wait until the CI pipeline succeeds
  - [x] [Create a pre-release on GitHub](https://github.com/grafana/mimir/blob/main/RELEASE.md#creating-release-on-github) https://github.com/grafana/mimir/releases/tag/mimir-2.13.0-rc.0
    ```bash
    git checkout release-<version>
    ./tools/release/create-draft-release.sh
    ```
  - [x] [Merge the release branch release-<version> into main](https://github.com/grafana/mimir/blob/main/RELEASE.md#merging-release-branch-into-main)
    ```bash
    ./tools/release/create-pr-to-merge-release-branch-to-main.sh
    ```
    ```
    pull request create failed: GraphQL: No commits between main and merge-release-2.13-to-main (createPullRequest)
    ```
  - [x] Publish the Github pre-release draft after getting review from at least one maintainer
  - [x] Announce the release candidate on social media such as on Mimir community slack using your own Twitter, Mastodon or LinkedIn account
- [x] Vendor the release commit of Mimir into Grafana Enterprise Metrics (GEM)
  - _This is addressed by Grafana Labs_
- [x] Publish a `mimir-distributed` Helm chart release candidate. Follow the instructions in [Release process for a release candidate](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/RELEASE.md#release-process-for-a-release-candidate)
  - [x] https://github.com/grafana/mimir/pull/8481
  - [x] https://github.com/grafana/mimir/pull/8483
  - [x] https://github.com/grafana/mimir/pull/8501
- [ ] Promote experimental features to experimental and remove deprecated features for the **next** release:
  - [x] Open a PR for every experimental feature we want to promote to stable 
    - [x] https://github.com/grafana/mimir/pull/8694
    - [x] https://github.com/grafana/mimir/pull/8696
    - [x] https://github.com/grafana/mimir/pull/8702 
  - [x] Open a PR to remove any deprecated feature or configuration option that should be removed in the next release 
    - [x] https://github.com/grafana/mimir/pull/8698 
    - [x] https://github.com/grafana/mimir/pull/8699 
    - [x] https://github.com/grafana/mimir/pull/8700 
    - [x] https://github.com/grafana/mimir/pull/8701
    - [ ] remove max-query-into-future

### Publish the release candidate (rc.1)

- [x] Publish the Mimir release candidate
  - [x] Update VERSION in the release branch and update CHANGELOG with version and release date. https://github.com/grafana/mimir/pull/8539
    - Keep in mind this is a release candidate, so the version string in VERSION and CHANGELOG must end in `-rc.#`, where `#` is the release candidate number, starting at 0.
  - [x] [Tag the release](https://github.com/grafana/mimir/blob/main/RELEASE.md#how-to-tag-a-release)
    ```bash
    git checkout release-<version>
    ./tools/release/tag-release.sh
    ```
  - [x] Wait until the CI pipeline succeeds
  - [x] [Create a pre-release on GitHub](https://github.com/grafana/mimir/blob/main/RELEASE.md#creating-release-on-github) 
    ```bash
    git checkout release-<version>
    ./tools/release/create-draft-release.sh
    ```
  - [x] [Merge the release branch release-<version> into main](https://github.com/grafana/mimir/blob/main/RELEASE.md#merging-release-branch-into-main) https://github.com/grafana/mimir/pull/8550
    ```bash
    ./tools/release/create-pr-to-merge-release-branch-to-main.sh
    ```
  - [x] Publish the Github pre-release draft after getting review from at least one maintainer
  - [x] Announce the release candidate on social media such as on Mimir community slack using your own Twitter, Mastodon or LinkedIn account

### Publish the release candidate (rc.2)

- [x] Publish the Mimir release candidate
  - [x] Update VERSION in the release branch and update CHANGELOG with version and release date. https://github.com/grafana/mimir/pull/8612
    - Keep in mind this is a release candidate, so the version string in VERSION and CHANGELOG must end in `-rc.#`, where `#` is the release candidate number, starting at 0.
  - [x] [Tag the release](https://github.com/grafana/mimir/blob/main/RELEASE.md#how-to-tag-a-release)
    ```bash
    git checkout release-<version>
    ./tools/release/tag-release.sh
    ```
  - [x] Wait until the CI pipeline succeeds
  - [x] [Create a pre-release on GitHub](https://github.com/grafana/mimir/blob/main/RELEASE.md#creating-release-on-github) https://github.com/grafana/mimir/releases/tag/mimir-2.13.0-rc.2
    ```bash
    git checkout release-<version>
    ./tools/release/create-draft-release.sh
    ```
  - [x] [Merge the release branch release-<version> into main](https://github.com/grafana/mimir/blob/main/RELEASE.md#merging-release-branch-into-main) https://github.com/grafana/mimir/pull/8625
    ```bash
    ./tools/release/create-pr-to-merge-release-branch-to-main.sh
    ```
  - [x] Publish the Github pre-release draft after getting review from at least one maintainer
  - [x] Announce the release candidate on social media such as on Mimir community slack using your own Twitter, Mastodon or LinkedIn account

### Publish the stable release

- [x] Publish the Mimir stable release
  - [x] [Write release notes](https://github.com/grafana/mimir/blob/main/RELEASE.md#write-release-notes-document)
    - Ensure the any change to release notes in `main` has been cherry picked to the release branch
  - [x] Update version in release-<version> branch https://github.com/grafana/mimir/pull/8639
    - VERSION
    - CHANGELOG
    - `operations/mimir/images.libsonnet` (`_images.mimir` and `_images.query_tee` fields)
    - `operations/mimir-rules-action/Dockerfile` (`grafana/mimirtool` image tag)
  - [x] [Tag the release](https://github.com/grafana/mimir/blob/main/RELEASE.md#how-to-tag-a-release)
    ```bash
    git checkout release-<version>
    ./tools/release/tag-release.sh
    ```
  - [x] Wait until the CI pipeline succeeds
  - [x] [Create a release on GitHub](https://github.com/grafana/mimir/blob/main/RELEASE.md#creating-release-on-github) https://github.com/grafana/mimir/releases/tag/mimir-2.13.0
    ```bash
    git checkout release-<version>
    ./tools/release/create-draft-release.sh
    ```
  - [x] [Merge the release branch release-<version> into main](https://github.com/grafana/mimir/blob/main/RELEASE.md#merging-release-branch-into-main) https://github.com/grafana/mimir/pull/8625
    ```bash
    ./tools/release/create-pr-to-merge-release-branch-to-main.sh
    ```
  - [x] If during the release process settings in the `renovate.json` have been modified in such a way that dependency updates maintain more than the latest two minor versions,
        modify it again to ensure that only the latest two minor versions get updated.
        For instance, if versions 3.1, 3.0 and 2.10 are configured in `renovate.json`, `renovate.json` should keep updated the following branches:
        `main`, `release-3.1` and `release-3.0`. https://github.com/grafana/mimir/pull/8642
  - [x] Announce the release on socials
  - [x] Open a PR to add the new version to the backward compatibility integration test (`integration/backward_compatibility_test.go`) https://github.com/grafana/mimir/pull/8659
  - [x] Open a PR to update the mixin in ["Self-hosted Grafana Mimir" integration](https://grafana.com/docs/grafana-cloud/monitor-infrastructure/integrations/integration-reference/integration-mimir/) https://github.com/grafana/cloud-onboarding/pull/7207
    - _This is addressed by Grafana Labs_
  - [x] [Publish dashboards to grafana.com](https://github.com/grafana/mimir/blob/main/RELEASE.md#publish-a-stable-release)

**Comment by duricanikolic** [comment]
These PRs should be included in Mimir 2.13:
- https://github.com/grafana/mimir/pull/8411
- https://github.com/grafana/mimir/pull/8446

**Comment by dimitarvdimitrov** [comment]
we also want to backport 

* #8399
* #8405

**Comment by dimitarvdimitrov** [comment]
@grobinson-grafana asked me to backport these two PRs

* https://github.com/grafana/mimir/pull/8456
* https://github.com/grafana/mimir/pull/8525
