### ISSUE TITLE
Docs: Feature stability matrix

### ISSUE THREAD

**Issue by mattmendick** [grafana/mimir#844]
When new features come to Mimir, a lot of times they are added as experimental with a flag, or experimental as part of a different feature. It would be great to have a list, perhaps a table in the docs which indicate the status of various features which are not yet GA (assuming when features go GA there's proper documentation for it), as well as the date when they were added. All of this information is knowable from git commits and other places in the docs, but nowhere is it in one place. This would help to track the lifecycle of a feature, and keep track of features that get added and perhaps need to be removed over time if they never make it to GA in a reasonable amount of time.

Potentially there could be a "graduated to GA" table that the features move to once they are no longer in experimental status.

cc @simonswine (and hat tip 🎩 to Christian for the idea as well)

**Comment by GrafanaWriter** [comment]
Fixed with https://github.com/grafana/mimir/pull/913
