### ISSUE TITLE
zstd compression support between distributors and ingesters

### ISSUE THREAD

**Issue by aallawala** [grafana/mimir#8522]
#### Is your feature request related to a problem? Please describe.
Are there plans for zstd support between distributors and ingesters using the `grpc_compression` flag? 

Enabling zstd compression would help significantly reduce the amount of cross-AZ traffic our org pays for running Mimir. gzip gets some wins, at the expense of CPU.

Now that there is a pure Go zstd implementation, are there any major blockers for introducing it to Mimir?

#### Describe the solution you'd like
Support for `zstd` when using the `grpc_compression`.

**Comment by aknuds1** [comment]
Are you specifically asking for the `-ingester.client.grpc-compression` flag to also support zstd?

**Comment by aallawala** [comment]
> Are you specifically asking for the `-ingester.client.grpc-compression` flag to also support zstd?

I'm specifically looking for compression support on the ingester-client, yes. That's our most expensive client. 

Though, judging by how the config is laid out, I suspect it is a shared compressor for all the gRPC clients?

**Comment by aknuds1** [comment]
> Though, judging by how the config is laid out, I suspect it is a shared compressor for all the gRPC clients?

In effect yes. I just needed more clarification, as your description was relatively vague.

**Comment by aknuds1** [comment]
So, I found out that the Mimir team already has considered zstd support, but the zstd [implementation](https://github.com/mostynb/go-grpc-compression/blob/main/internal/zstd/zstd.go) we considered is apparently not very performant.

Is that the same zstd implementation as you're referring to?

**Comment by aallawala** [comment]
> So, I found out that the Mimir team already has considered zstd support, but the zstd [implementation](https://github.com/mostynb/go-grpc-compression/blob/main/internal/zstd/zstd.go) we considered is apparently not very performant.
> 
> 
> 
> Is that the same zstd implementation as you're referring to?


Thanks for checking in. I'm looking at https://github.com/klauspost/compress/tree/master/zstd as a possible zstd implementation.

**Comment by aallawala** [comment]
@aknuds1, checking in - are you able to share more on the reasons why that implementation was not performant?

**Comment by aknuds1** [comment]
I just know that @bboreham considered the aforementioned [zstd implementation](https://github.com/mostynb/go-grpc-compression/blob/main/internal/zstd/zstd.go), and found performance problems with it.

When we discussed trying another compression algorithm for cheaper A-Z traffic internally, the other point made was it wasn't worth all the testing that comes along with it.

**Comment by aknuds1** [comment]
I have some new context to share to shed hopefully enough light on why the Mimir team doesn't think the investment into a new compression algorithm for distributor -> ingester traffic is going to be worthwhile. I don't know if you're perhaps already familiar with this, but Mimir is moving towards a fundamentally revamped architecture, where distributors will no longer be writing directly to ingesters, but instead to a Kafka compatible back-end, which ingesters again read from. Please see _[FEATURE] Experimental Kafka-based ingest storage_ in the [changelog](https://github.com/grafana/mimir/blob/1eaffce140e6265d3c0b11a9e0563a7d653634bb/CHANGELOG.md) for reference.

**Comment by bboreham** [comment]
I remarked on the amount of memory allocations it does. 
Looks like this was improved recently, with the addition of a pool in https://github.com/mostynb/go-grpc-compression/commit/629c44d3acb9624993cc7de629f47d72109e2ce5.

Someone else commented https://github.com/mostynb/go-grpc-compression/issues/25

**Comment by deniszh** [comment]
@aallawala 
@aknuds1 
@bboreham 

I decided to experiment with zstd and s2 GRPC compression from https://github.com/mostynb/go-grpc-compression.
So, I created patched [dskit](https://github.com/deniszh/dskit/tree/dzhdanov/grpc-comp-7e83c3cb3b11), with zstd and s2 compression and then built [mimir 2.13.0 with that patched dskit](https://github.com/deniszh/mimir/tree/mimir-2.13.0-zstd)  - it's nothing fancy, just dskit pointed to patched version.

Then I ran this patched version in our test cluster, first with zstd compression, then s2. Please note, that before test test cluster already run Mimir 2.13.0 with Snappy GRPC compression enabled, so, comparison below is to snappy and NOT uncopressed:

Results:

Zstd results comparing to Snappy:
  - traffic dropped from 4MB/s per writer to 2.2MB/s per writer incoming, 3Mb/s outgoing to 1MB/s outgoing
    - i.e. 7MB to 3.2MB drop from snappy - 54% less traffic
  - cpu didn't change significantly
  - memory increased a lot - from 6.5G per writer to 15GB per writer - I think thats a show stopper
  - 99p write latency dropped from 90 to 50 ms.

![Image](https://github.com/user-attachments/assets/4f108daf-4a33-4472-9ea6-a683797607fe)

![Image](https://github.com/user-attachments/assets/a9e1888e-2e57-4e0b-aa84-dea513e7ce60)

So, results are good, but memory usage is tremendous. I checked heap, majority of memory consumed by `zstd.EnsureBlock`:

![Image](https://github.com/user-attachments/assets/40f7b61f-622e-4f9e-be5f-986777ef97b6)

But I also have a good news too, when I tried to switch to s2 compression, which is [better version of snappy](https://github.com/klauspost/compress/tree/master/s2#s2-compression).

S2 results comparing to Snappy:
 - traffic almost similar to zstd - receive 2.4MB/s per writer, send 1.4MB/s per writer
   - i.e 7MB to 3.8MB drop from snappy - 45% less traffic
   - cpu didn't change significantly
   - memory even dropped comparing to snappy - from 6.5G per writer to 5.8G per writer
   - 99p write latency dropped from 90 to 60 ms

![Image](https://github.com/user-attachments/assets/5d8636f9-1f1b-48da-ab8d-170b1a55e1ca)

(left is Snappy, middle - zstd, right part - S2)

So, after that I decided to drop zstd (first I wanted to test Datadog or another wrapper but then I realized that Mimir has no CGO enabled) and S2 looks really promising.

I know that Mimir architecture is revamped and will be migrated to Kafka, but it will take some time to implement that properly - and S2 patch can shave 50% of cross AZ data cost right now.

And I don't like run patched version and prefer to port my changes to upstream. I can clean up and submit PR for experimental S2 support in dskit. Should I or make no point?

**Comment by aallawala** [comment]
@deniszh, thanks so much for trying it out and posting your results. The memory increase seems to match up with what @bboreham said earlier in his findings too. 

Thanks for also trying out s2. The results seem much more favorable and it would be something I can also help drive in order to get this ported upstream. Do you have a PR available on the dskit side for s2?

**Comment by deniszh** [comment]
@aallawala : https://github.com/grafana/dskit/pull/582

But please take note that latest mimir is not ready to latest dskit. So, if you want to tesk you can build mimir from this branch https://github.com/deniszh/mimir/tree/2.13.0-grpc-s2

**Comment by deniszh** [comment]
Tried S2 on bigger cluster - it's less impressive but I see 70MB/s instead of 105MB/s - 30% decrease.

**Comment by aknuds1** [comment]
Thanks for your testing @deniszh! The results look very promising. I'm asking the Mimir team what they think.

**Comment by aknuds1** [comment]
@deniszh the Mimir team is positive to using S2 for gRPC compression in Mimir. I guess we should start out by reviewing your dskit PR.

**Comment by deniszh** [comment]
👍

**Comment by Rohlik** [comment]
Will be S2 better than gzip 🤔 compression?

**Comment by deniszh** [comment]
I didn't compare to gzip. Maybe by rate it is, but not by resources.

**Comment by mostynb** [comment]
FWIW I am considering a change to the zstd wrapper in https://github.com/mostynb/go-grpc-compression/pull/34

**Comment by deniszh** [comment]
Ok, I decided to tried it one more time. First, I applied @mostynb patch above, but for some reason I got panic somewhere in ztsd.go when calling close() in my tests.
So, I decided to simply take S2 compressor (which works perfectly) and change S2 readers and writers there with zstd reader and writer. I implemented that in https://github.com/deniszh/mimir/tree/2.14.2-grpc-s2-zstd branch (see [this](https://github.com/grafana/mimir/commit/aded4060a59c962db8097ffe0192ebfb7342d511) commit, rest is backports of 2.14.x  fixes).
After that I enabled zstd grpc compressor in the same cluster where I had S2 compressor before.
Results are below:

 - no changes in write latency, read latency, rule evaluation latency (comparing to S2)

 - very slight improve for write bandwith:
<img width="542" alt="Image" src="https://github.com/user-attachments/assets/f291844a-99d1-4f7c-9470-2b6ca3cb9c03" />
<img width="545" alt="Image" src="https://github.com/user-attachments/assets/1ad07fa4-fb2f-4ffd-855a-14e4506286f6" />

(65MB S2 vs 54MB ZSTD - 17% better)
(45MB S2 vs 35MB ZSTD - 22% better)

- no significant changes in read bandwith

- no significant changes in CPU for read and write components

- no significant changes in memory for mimir-write
<img width="1462" alt="Image" src="https://github.com/user-attachments/assets/78b99435-5c79-4135-ad3e-a0987c61ee48" />

- significant memory increase for mimir-read
<img width="1459" alt="Image" src="https://github.com/user-attachments/assets/ae912ad6-be16-47b0-a634-561c19d391af" />

(300% worse for ZSTD, similar effect is for mimir-backend)

Conclusion:
 - not sure if saving 15-20% of network bandwidth worth 3x increase of RAM for read components. OTOH, it's much better than previous implementation (now mimir-read RAM consumption is not increased)
 - We would stay on S2, though.

**Comment by deniszh** [comment]
PS: OTOH we need ZSTD compression between distributor and ingesters, would try that, using S2 for rest.

**Comment by deniszh** [comment]
OK, I applied [patch](https://github.com/grafana/mimir/compare/main...deniszh:mimir:2.15.0-grpc-zstd) on top of 2.15.0, then override ingester compression with "-ingester.client.grpc-compression=zstd", keeping s2 for the rest of clients.
Results:
  
 - 99p write latency is the same
  
 - cpu / memory of write component mostly the same (memory even improved a bit, but probably because of 2.15.0)
<img width="1474" alt="Image" src="https://github.com/user-attachments/assets/e3f760e3-3eea-40e3-9d4d-28dd39168c0f" />

 - write bandwith improved:

  RX - 63MB to 50MB 
  TX - 43MB to 32MB
  Total - 106 to 82 - 22% more (comparing to S2, which is kinda impressive):

<img width="1109" alt="Image" src="https://github.com/user-attachments/assets/d4b364de-928a-420b-9aae-a3d08d9d1bea" />

Will do more tests and give it some time for stability check and then introduce PR for zstd only in ingester client.

**Comment by deniszh** [comment]
OK, on bigger cluster I definitely see 22% of bandwith savings, but at the same time same 20% increase of CPU in distributors. Ingesters resources are the same, so, probably, still feasible in some use cases but generally speaking S2 can be probably still good compromise.

**Comment by deniszh** [comment]
Latest update - compared zstd with gzip. Compression ratio is the same as zstd (17% better than S2), but CPU-wise zstd is better than gzip for 15%, see graph of distributor CPU, normalized to S2 consumption:

![Image](https://github.com/user-attachments/assets/d7e6e410-5c16-454e-8307-37a5d4718de1)

Left is S2 (100), medium - ZSTD (140), right - gzip (165). So, maybe still worth to have it in ingester if anyone wants to save more traffic in exchange for CPU.

**Comment by deniszh** [comment]
So, for someone who curious/watching this topic I can add current state of things.
We still running [ZSTD patch](https://github.com/grafana/mimir/pull/10411) on our Mimir, I hope Grafana still considering it to merge.
I tried various optimizations and other things:

- I [tried](https://github.com/deniszh/mimir/tree/2.15.0-grpc-gozstd-dev) to replace purego zstd with C-linked version in [gozstd](https://github.com/valyala/gozstd). Good news - it works. Bad news - it's not working better than purego version!  Not in speed, not in resource consumption or ratio! So, kudos to @klauspost for such good optimization.

- I tried to implement [dictionary support](https://github.com/deniszh/mimir/tree/2.16.0-minlz-dict) in ZSTD but the problem here that ZSTD [do not support building dictionary from stream](https://github.com/facebook/zstd/issues/1239), so, I tried to mimic it. My idea was that majority of data in distributor-ingester traffic is [key-value tags](https://github.com/grafana/mimir/blob/main/pkg/mimirpb/mimir.proto#L80-L83), so, I collected subset of tags and train zstd on it. Result - some CPU increase, no significant compression ratio increase. Probably, we can try again with real GRPC dumps, not sure.

- I [tried](https://github.com/deniszh/mimir/tree/2.16.0-minlz-dict) [MinLZ](https://github.com/minio/minlz) compression (which is successor of S2). I didn't compare it with S2 but it looks similar - worse ratio, less CPU than ZSTD.

- I [tried](https://github.com/deniszh/mimir/tree/2.16.0-brotli-test) brotli compression. Good thing - it's indeed give you best compression ratio but CPU consumption is terrible. :(  Maybe, [purego brotli implementation](https://github.com/andybalholm/brotli) is not that optimized as zstd one.  Cpu difference was so bad, so, I decided not to try brotli with dictionaries. Maybe will try C-linked version, though.

So, conclusion - S2 is still the best option for generic GRPC compression, and ZSTD is still give you best compression ratio in exchange for some sane CPU amount.

**Comment by klauspost** [comment]
@deniszh Thanks for your insights!

MinLZ is written as a straight replacement for S2 (and based on the same code), with similar CPU for compression, less for decompression, but pretty much always better compression ratios. Direct improvements are most with regards to streams. The only exception is dictionary encodes, which we postponed past v1.

**Comment by frittentheke** [comment]
@aknuds1  @aallawala @bboreham with PR https://github.com/grafana/mimir/pull/10411 still open, it might make sense to keep / reopen this issue open as well?

Reading https://github.com/grafana/mimir/issues/8522#issuecomment-2826984792 by @deniszh it seems he still intends to pursue the PR adding zstd compression.

**Comment by deniszh** [comment]
Well, in Kafka architecture it doesn't make sense, so, that's maybe reason it's not merged.
Works perfectly in 3.x with old architecture though.
