### ISSUE TITLE
Distributor errors in mimir

### ISSUE THREAD

**Issue by RaviHari** [grafana/mimir#8629]
### Discussed in https://github.com/grafana/mimir/discussions/8628

<div type='discussions-op-text'>

<sup>Originally posted by **RaviHari** July  5, 2024</sup>
Hi I am seeing an unexpected issue on mimir distributor.. and I am running mimir 2.12.0 version:
```
ts=2024-07-04T17:33:53.373004163Z caller=push.go:171 level=error user=anonymous msg="push error" err="DoBatch: InstancesCount <= 0"
```
this is happening continuously inspite multiple restarts
any reasons why the would mimir  run into this state
I see all ingesters are up and running</div>

**Comment by narqo** [comment]
Before start delving into the details of this particular case, could you check if the existing discussion about similar errors (grafana/mimir/discussions/4662) could be helpful for your setup.

**Comment by 56quarters** [comment]
This is likely a configuration issue or something specific to your environment, not a bug.
