### ISSUE TITLE
Docs: ...https://github.com/grafana/mimir/releases/tag/mimir-2.13.0

### ISSUE THREAD

**Issue by stecullum** [grafana/mimir#8644]
#### Is your documentation request related to a feature? If so, which one?

See https://github.com/grafana/mimir/releases/tag/mimir-2.13.0

Helm chart improvements
The Grafana Mimir and Grafana Enterprise Metrics Helm charts are released independently.
Refer to the [Grafana Mimir Helm chart documentation](https://github.com/grafana/mimir/blob/mimir-2.13.0/docs/helm-charts/mimir-distributed/latest).

The link is invalid
#### Describe the solution that you’d like or the expected outcome

A valid link is provided

**Comment by dimitarvdimitrov** [comment]
thanks for reporting 🙂 should be fixed now
