### ISSUE TITLE
Unhealthy ingester pods are not recalibrating back to normal

### ISSUE THREAD

**Issue by sidkram** [grafana/mimir#8648]
#### Describe the bug
We have been facing an issue with mimir (after the update with MinIO) make use of dualstack URLs to access S3 as that increased costs excessively when used with private endpoints. But being able to use the following [PR](https://github.com/grafana/mimir/pull/8405#pullrequestreview-2129553296) we were able to get rid of that issue. But since then there had been a persistent issue with the ingesters that everytime one of the ingesters go unhealthy, they dont resolve back to healthy state unless manually 'forget'-ten from the ingester ring page. There used to be only a downtime of two or more mins earlier until the ingester comes back to healthy state as the replication factor can only handle one ingester pod going down.

Its clearly visible that the change from the PR and the observed behaviour is not related, but that appears to be the only start point of the behaviour 
#### To Reproduce
1. Start Mimir with [2.13.0-rc.0](https://hub.docker.com/layers/grafana/mimir/2.13.0-rc.0/images/sha256-9d57eb9e9cd0b9a5474577ee27d7185aaa420889d6b66d4f7c387eb78d55567d?context=explore) as the base image 
2. Perform Operations(Read/Write/Others)

#### Expected behavior
Anytime the ingester goes down because of excessive load, the unhealthy ingesters had to be manually forgotten to be able to remediate this issue.

#### Environment

- Infrastructure: Kubernetes - EKS
- Deployment tool: helm

#### Additional Context
I can probably attach a screenshot of a unhealthy ingester which had remained unhealthy for more than 12 hrs, when it used to never cross more than 8 mins earlier before the change

**Comment by dimitarvdimitrov** [comment]
Does the inger log anything in this period? Anything at the start of it?

**Comment by dimitarvdimitrov** [comment]
the pod should have details on it when it crashes. This is one example

```
   State:          Running
      Started:      Thu, 11 Jul 2024 18:04:25 +0200
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Thu, 11 Jul 2024 14:01:41 +0200
      Finished:     Thu, 11 Jul 2024 18:04:24 +0200
    Ready:          True
```

**Comment by dimitarvdimitrov** [comment]
can you share all the logs of the ingester before it enters the "frozen" state?

**Comment by atamsekar-tivo** [comment]
Same issue seen with 2.12
Ingesters did not log anything. However distributors were logging below,
`ts=2024-08-23T14:57:37.932213616Z caller=push.go:171 level=error user=mimir msg="push error" err="send data to ingesters: at least 2 live replicas required, could only find 1 - unhealthy instances: X.X.X.X:9095, X.X.X.X:9095"`

We had an event where the ingesters scaled up from 6 to 8 and during scale down they did not exit the ring gracefully. Had to "Forget" these unhealthy instances from Mimir admin UI. 

Any configuration to handle this correctly?

FYI. We configured HPA instead of using default KEDA.

**Comment by atamsekar-tivo** [comment]
Thank you @dimitarvdimitrov.

**Comment by 56quarters** [comment]
I'm going to close this because I don't think there's a bug here.
