### ISSUE TITLE
Docs: Write Grafana Mimir user guide

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#874]
Cherrypick experimental items from #870 and add them back in-line.

**Comment by jdbaldry** [comment]
To be honest, I can't understand from this or the related issue, what work needs to be done.

**Comment by osg-grafana** [comment]
To the best of my knowledge, this issue was intended to cover the content that is now listed under https://github.com/grafana/mimir/tree/main/docs/sources/operators-guide. We can always open a more actionable issue in the future.
