### ISSUE TITLE
Docs: use the new writers toolkit links in mimir and mimir helm chart docs

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#8744]
The writer's toolkit has a new implementation of linking between products: https://grafana.com/docs/writers-toolkit/write/links/

Also pick one of https://grafana.com/docs/writers-toolkit/write/links/#link-from-source-content-thats-used-in-multiple-projects and https://grafana.com/docs/writers-toolkit/write/links/#link-to-grafanacom-pages   reference methods and use that.

See comment here: https://github.com/grafana/mimir/pull/8489#issuecomment-2230254695

**Comment by tacole02** [comment]
Through discussions with @krajorama , we decided to backport these changes to the 2.13 release. This will include backporting of the updates from https://github.com/grafana/mimir/pull/8489.
