### ISSUE TITLE
Docs: Use sentence case within dashboards' JSON files

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#875]
- [ ] https://github.com/grafana/mimir/tree/main/operations/mimir-mixin-compiled/dashboards

**Comment by GrafanaWriter** [comment]
@osg-grafana - can you please reopen if this is still an issue and provide more context as to what work needs to be completed?

**Comment by osg-grafana** [comment]
The majority of the fix is in https://github.com/grafana/jsonnet-libs/pull/1038.
