### ISSUE TITLE
Bare requests to `/prometheus/api/v1/label/__name__/values` can cause all/most `store-gateway` pods to crash on large installations

### ISSUE THREAD

**Issue by HammoTime** [grafana/mimir#8816]
#### Describe the bug
We were performing load testing on our servers and one of those tests was an unparameterised query to `/prometheus/api/v1/label/__name__/values` in order to source some label values for our tests. After 30-60 seconds, the request will eventually return `422 UNPROCESSABLE ENTITY`, however the cluster will no longer respond to requests. On checking the nodes, all of the pods were `UNHEALTHY` and required recycling to restore service.

#### To Reproduce

Requires approximately:

 - 40MM active time series.
 - At least 2-3 months of historical data for those time series.

Steps to reproduce the behaviour:

1. Send the request `/prometheus/api/v1/label/__name__/values` to a tenant that meets the time series requirements.
2. Wait until the connection is ended or you receive a `422` response.

__Note: it could be more than one request, but I can safely say sending approx. 100 requests in quick succession will cause the behaviour to occur. This was seen in our production cluster and I don't have an easy interface to replicate the issue and determine test boundaries.__

#### Expected behavior

`422` seems a reasonable response given the circumstances as based on the architecture of Mimir and the amount of object store reads required to processed an unbounded request. On reflection, I think it's unreasonable to expect this call to work reliably on large installs.

A blanket stoppage on all bare requests to the endpoint would be problematic for smaller installs where it isn't an issue, however I think a config item could be appropriate to tune behaviour. This would be used in a production-hardening exercise and be kept in its default "unsafe" setting in lower environments. 

I think that something like `querier.max_time_range_for_prom_labels_endpoint` is the easiest and most appropriate config item that could be introduced. It would be a time period (in whatever format) that limits the range against which a query can be executed (e.g. `2d`). When set, it would necessarily require the user to specify a `start` and `end` in their query, otherwise the range would be infinity (and the check would fail). `422` would still be appropriate, as the request is valid against the Prometheus API and the cluster would be making a decision to just not serve it based on the request parameters.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: Helm

#### Additional Context

__Workaround__

Providing time boundaries for the query following the HTTP API works around this problem, however the bare endpoint is still susceptible to bad actors.

---

EDIT: Grammar and removed reference to `ingester` pods as I think I was mixing up some behaviours I was seeing due to a _different issue_.

**Comment by dimitarvdimitrov** [comment]
There is already a config to allow limiting label names and label values requests


```yaml
# Limit the time range (end - start time) of series, label names and values
# queries. This limit is enforced in the querier. If the requested time range is
# outside the allowed range, the request will not fail but will be manipulated
# to only query data within the allowed time range. 0 to disable.
# CLI flag: -store.max-labels-query-length
[max_labels_query_length: <duration> | default = 0s]
```

Can you also share which version of Mimir you are running?

**Comment by HammoTime** [comment]
Hey Team, you're spot on - it's already there. This was definitely a PEBKAC, thanks for pointing me in the direction of the flag.
