### ISSUE TITLE
MinIO pod memory consumption keeps increasing

### ISSUE THREAD

**Issue by vigneshvmohan** [grafana/mimir#8819]
#### Describe the bug
We've deployed the helm-chart version 5.4.0. We noticed that the memory usage of the MinIO pod running as dependency for mimir has been increasing steadily until it reaches it's limit.
Only an OOM kill or restart brings down the memory usage.
![image](https://github.com/user-attachments/assets/33d496fc-f2b7-464f-b864-08b03c553ea0)

#### To Reproduce
deploy mimir using helm chart 5.4.0
observe the memory usage increasing for the MinIO pod

#### Expected behavior
stable memory usage
#### Environment

- Infrastructure: AKS cluster
- Deployment tool: helm

**Comment by dimitarvdimitrov** [comment]
this looks like a problem with Minio. Consider opening an issue in minio/minio
