### ISSUE TITLE
Mimirtool - No option to output rules to file

### ISSUE THREAD

**Issue by kkerennnn** [grafana/mimir#8851]
Similar to how we can use the `--output-dir` flag when running `mimirtool alertmanager get`, it would be super helpful if I could run  `mimirtool rules print --output-dir`

**Comment by dimitarvdimitrov** [comment]
there is one for `mimirtool rules get` https://github.com/grafana/mimir/issues/7054. Doesn't this work for you?

**Comment by dimitarvdimitrov** [comment]
my bad, it is for both `mimritool rules print` and `mimirtool rules get`


> * [ENHANCEMENT] Add option `--output-dir` to `mimirtool rules get` and `mimirtool rules print` to allow persisting rule groups to a file for edit and re-upload. #7247
