### ISSUE TITLE
Allow to override cluster_name in mimir-distributed helm chart by using mimir.structuredConfig

### ISSUE THREAD

**Issue by maikel-09** [grafana/mimir#8866]
#### Is your feature request related to a problem? Please describe.

cluster_name is used for validating the GEM license, Right now the Release.Name value is used to set the cluster_name in the values.yaml. 

#### Describe the solution you'd like

```
    mimir:
      structuredConfig:
        cluster_name: "CLUSTERXYZ"
```

#### Describe alternatives you've considered

Alternatives are:
- Copying the whole mimir.config value and modifying the configuration as text (discouraged, unless you want to prevent upgrades of the chart from automatically updating the configuration)
- Setting extra CLI flags for components individually (discouraged, except for setting availability zone)

**Comment by benoitschipper** [comment]
Totally Agree, would make it more flexible :) +1

**Comment by narqo** [comment]
Please, reopen the issue and provide more details if this still doesn't work for you.
