### ISSUE TITLE
Removal of Liveness Probe in Loki 3.x for Query Frontend 

### ISSUE THREAD

**Issue by kashish1200** [grafana/mimir#9111]
I’ve been reviewing the Loki 3.x configuration, and I noticed that the liveness probe is no longer present for certain components, specifically the Query Frontend and Gateway. In previous versions, these components did have liveness probes configured.

Could you please provide some insight into why the liveness probes were removed for these components in Loki 3.x?

**Comment by dimitarvdimitrov** [comment]
This looks like a question for https://github.com/grafana/loki/issues, not for this repository. Can you please ask it there
