### ISSUE TITLE
Support LZ4 content encoding in the OTEL receiver once supported

### ISSUE THREAD

**Issue by irisgve** [grafana/mimir#9259]
#### Is your feature request related to a problem? Please describe.

This [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/11108/files#diff-ae510a297dd561956c65c1e375f12870c19e281c486b51017e3280e0d3de08f2) adds LZ4 encoding in the OTLP exporters. Once merged, it'll be great if we can support it in the distributor as well.

#### Describe the solution you'd like

Add LZ4 support [here](https://github.com/grafana/mimir/blob/402c6a8cf75b76e8497823a910c441e69c3a88d9/pkg/distributor/otel.go#L74)

Happy to submit a PR to support this.

**Comment by ying-jeanne** [comment]
It is a good idea @irisgve, PR is welcomed! (:

**Comment by santileira** [comment]
@irisgve / @ying-jeanne / @armandgrillet is this "issue" still opened? If so, I can get a PR ready to support LZ4 on the distributor.

**Comment by armandgrillet** [comment]
@santileira Yes the issue is still open, feel free to contribute with a PR.

**Comment by santileira** [comment]
@armandgrillet here is the PR: https://github.com/grafana/mimir/pull/9763 but for some reason the GitHub actions are not running. Do you know why?

**Comment by aknuds1** [comment]
@irisgve could you provide any context on why one would use LZ4 over e.g. Snappy (Mimir supports Snappy for gRPC compression, as a data point)?

**Comment by santileira** [comment]
@irisgve could you review the question from @aknuds1 and provide an answer? I would like to understand if we can move forward with the PR. Thanks

**Comment by irisgve** [comment]
Hey @aknuds1 @santileira internally we've found significant (data transfer costs) savings and performance improvements on implementing LZ4 compression in our metrics pipelines. It has slightly better compression ratios than snappy i.e. some benchmarks on https://github.com/inikep/lzbench/blob/master/lzbench18_sorted.md

**Comment by santileira** [comment]
Closed. We merged the PR. Thanks!

**Comment by pjastrzabek** [comment]
@irisgve  We switched to gzip due to data transfer costs (especially cross AZ). Have you possibly tested gzip? If yes, How did it compare with LZ4?

**Comment by irisgve** [comment]
Hi @pjastrzabek while gzip had better compression ratios (potentially lower data transfer costs) lz4 is ~10x faster than gzip and has lower CPU usage during compression/decompression which is more ideal for us.
