### ISSUE TITLE
Passing mimir endpont and auth details in keda autoscaling

### ISSUE THREAD

**Issue by snyaik** [grafana/mimir#9616]
Hi Everyone, 

I am trying to implement keda for miimir components. 
Keda is working fine when the prometheusAddress and customHeaders fields are left blank. 
I want to pass the mimir endpoint along with the auth details to kedaAutoscaling block. 

When I am passing the mimir endpoint in prometheus address it fails with 401 unauthorised error. 

There is not much info available on how to pass auth details in kedaAutoscaling block. 
Is there any specific format to be followed in passing auth details in customheaders. 
I have gone through keda documentation where I can see how to pass auth details but how to translate that into mimir values?

Expected behaviour: keda to work without metamonitoring block and by passing mimir endpoint in prometheus address.

**Comment by narqo** [comment]
Looking at the list of remaining work for stabilising autoscaling, this might not be supported yet. Refer to https://github.com/grafana/mimir/issues/7368:

> Currently basic auth and extra headers are ignored.

I suggest moving the issue there (or feel free to reopen this one providing more details for your particular scenario).
