### ISSUE TITLE
mimir helm chart 5.5.0 fails (ArgoCD outofsync or unknown field)

### ISSUE THREAD

**Issue by jkleinlercher** [grafana/mimir#9638]
#### Describe the bug

When installin mimir helm chart 5.5.0 with ArgoCD I recognized permanent outofsync in grafanaagent resource like documented in https://github.com/suxess-it/kubriX/pull/722#issuecomment-2412042498 ?

When deploying with „helm template …“| kubectl apply I get

Error from server (BadRequest): error when creating "STDIN": GrafanaAgent in version "v1alpha1" cannot be handled as a GrafanaAgent: strict decoding error: unknown field "spec.containers[1].topologySpreadConstraints"
and indeed topologySpreadConstraints is not a valid attribute inside containers attribute.

I believe the problem is that topologySpreadConstraints has an indent of 6 instead of 4:
https://github.com/grafana/mimir/blob/197314a28336088be9771624cc3f7dae767fd70b/operations/helm/charts/mimir-distributed/templates/metamonitoring/grafana-agent.yaml#L67

#### To Reproduce

Install mimir 5.5.0 helm chart with ArgoCD or simply apply rendered GrafanaAgent resource like in https://github.com/suxess-it/kubriX/pull/722#issuecomment-2412334694

#### Expected behavior

ArgoCD app should be synced and healthy or command explained above should run without error.

#### Environment

- Infrastructure:  Kubernetes
- Deployment tool: helm

**Comment by narqo** [comment]
Thank you for reporting this. It will be resolve in 5.5.1, that we're preparing in https://github.com/grafana/mimir/pull/9670
