### ISSUE TITLE
Docs: scrape_classic_histograms renamed to always_scrape_classic_histograms in Prometheus 3.0

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#9695]
#### Is your documentation request related to a feature? If so, which one?

Due to https://github.com/prometheus/prometheus/pull/15178 we'll have to update the documentation 
https://github.com/grafana/mimir/blob/b2c35f5e0d3b8ebe90a6a9fc5a8b5e6992c9c5c3/docs/sources/mimir/send/native-histograms/_index.md?plain=1#L114
https://github.com/grafana/mimir/blob/b2c35f5e0d3b8ebe90a6a9fc5a8b5e6992c9c5c3/docs/sources/mimir/send/native-histograms/_index.md?plain=1#L156
maybe other places as well?

#### Describe the solution that you’d like or the expected outcome

I think we should document the 3.0 way as primary and just mention 2.x way, wdyt?

**Comment by tacole02** [comment]
Thanks for creating this issue, @krajorama ! What timeline do you have in mind for completion?

**Comment by tacole02** [comment]
TImeline: ~ mid November, 2024
