### ISSUE TITLE
mimir-distributed has non-working Grafana dashboards

### ISSUE THREAD

**Issue by ripa1993** [grafana/mimir#9848]
#### Describe the bug
Grafana dashboards delivered with the Helm Chart use metrics that reference wrong pod names.
In the built mixins, the metrics assume pod names starting with `mimir-[component]` but in mimir-distributed chart the components are named `mimir-distributed-[component]`

#### To Reproduce

1. Deploy mimir-distributed with Grafana dashboards enabled
2. Observe Dashboards with "no data" in panels

#### Expected behavior

Dashboards panel should be able to fetch the correct data.

#### Environment

- Infrastructure: EKS
- Deployment tool: Helm mimir-distributed chart

**Comment by narqo** [comment]
>  In the built mixins, the metrics assume pod names starting with `mimir-[component]` but in mimir-distributed chart the components are named `mimir-distributed-[component]`

I think, with Helm chart this depends on the release name, user passes to the `helm install` command. That is, following Mimir Helm chart's [getting started][1] guide (note the "mimir" release name in the command above):

```
% helm install mimir grafana/mimir-distributed --namespace test-monitoring
```

This installs k8s resources with the `mimir-` prefix, i.e.

```
% kubectl -n test-monitoring get po
NAME                                        READY   STATUS      RESTARTS   AGE
mimir-compactor-0                           1/1     Running     0          8m27s
mimir-store-gateway-zone-c-0                1/1     Running     0          8m27s
mimir-store-gateway-zone-b-0                1/1     Running     0          8m26s
mimir-store-gateway-zone-a-0                1/1     Running     0          8m27s
mimir-ingester-zone-c-0                     1/1     Running     0          8m27s
mimir-ingester-zone-b-0                     1/1     Running     0          8m27s
mimir-ingester-zone-a-0                     1/1     Running     0          8m26s
···
```

The same is true for the `helm template` command, some users use to deploy Mimir. The dashboards expect "mimir" template name:

```
% helm template grafana/mimir-distributed --name-template mimir
```

If you chose to use another release name, for the moment, you need to rebuild the dashboards yourself, following [the guide][2].

[1]: https://grafana.com/docs/helm-charts/mimir-distributed/latest/get-started-helm-charts/
[2]: https://grafana.com/docs/mimir/v2.14.x/manage/monitor-grafana-mimir/installing-dashboards-and-alerts/#install-dashboards-from-jsonnet-mixin

**Comment by ripa1993** [comment]
Thanks @narqo
