### ISSUE TITLE
Q: how to unmark "no-compact" blocks?

### ISSUE THREAD

**Issue by deniszh** [grafana/mimir#9973]
Hello!
I marked some blocks as "no-compact" using markblocks by mistake. How can I revert that? I deleted "no-compact-mark.json" file from affected blocks but looks like that didn't help. Or should I clean some cache?

Thanks!

WBR,
   Denys

**Comment by 56quarters** [comment]
IIRC there's two places for markers: the "global" `markers/` directory in the bucket root and within each block directory.

**Comment by deniszh** [comment]
Thanks for answer! Yes, deleted from "marker" directory and it helps! Will ask such questions in forum next time, though, as far as I understand that's more appropriate . :)
